### ISSUE TITLE
can i get the path of two node?

### ISSUE THREAD

**Issue by caoxiaoyuan7242** [RedisGraph/RedisGraph#1009]
query :MATCH p=(a:user {user_index:'800002_u'})-[r*3]->(b:spu) RETURN p not work

**Comment by caoxiaoyuan7242** [comment]
is java api dont support path?

**Comment by DvirDukhan** [comment]
@caoxiaoyuan7242 
can you share:
1. RedisGraph version that you are using
2. which client and version are you using
3. the query and the method you are sending it (code sample)

**Comment by caoxiaoyuan7242** [comment]
@DvirDukhan 
hi!
1：redisgraph version :v2.0.5
2：java client ,version:2.0.0-rc3
3：code:
 RedisGraph graph = new RedisGraph();
 String query = "MATCH p = (a:user {user_index: 'index+_u'})-[:user2spu]->(:spu) RETURN p";
ResultSet resultSet =raph.query("SPU_GRAPH_2", query);
This code causes an ArrayIndexOutOfBoundsException

**Comment by springbarley** [comment]
i got the same problem when i do connection path retrieval, seems python api client does not have this problem

**Comment by springbarley** [comment]
print("path")
query = """MATCH p = (q:person {name:"John Doe"})-[*]->(m:economy {name:"high"}) RETURN p"""
result = redis_graph.query(query)
for record in result.result_set:
   path = record[0]
   # for node in path.nodes():
   #     print("node")
   # for relation in path.relationships():
   #     print(relation)

the path finding sample code with python version works well，but the same code with java doesn't work?

**Comment by DvirDukhan** [comment]
@caoxiaoyuan7242 
The API is not the same, you can't use the same code
In the README file you can find this example
```java
        resultSet = graph.query("social", "MATCH p = (:person)-[:knows]->(:person) RETURN p");
        while(resultSet.hasNext()) {
            Record record = resultSet.next();
            Path p = record.getValue("p");

            // More path API at Javadoc.
            System.out.println(p.nodeCount());
        }
```

**Comment by caoxiaoyuan7242** [comment]
@DvirDukhan 
so which java client version i can use this example ?

```
 resultSet = graph.query("social", "MATCH p = (:person)-[:knows]->(:person) RETURN p");
        while(resultSet.hasNext()) {
            Record record = resultSet.next();
            Path p = record.getValue("p");

            // More path API at Javadoc.
            System.out.println(p.nodeCount());
        }
```

**Comment by caoxiaoyuan7242** [comment]
@DvirDukhan 
when i add this to my pom,my project still can't get client 2.0.0-SNAPSHOT
```

  <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>com.redislabs</groupId>
      <artifactId>jredisgraph</artifactId>
      <version>2.0.0-SNAPSHOT</version>
    </dependency>
  </dependencies>
```

**Comment by caoxiaoyuan7242** [comment]
@DvirDukhan 
thanks , i use java client version:2.0.0 it works

**Comment by DvirDukhan** [comment]
@caoxiaoyuan7242 If everything is fine, can I close this issue?

**Comment by caoxiaoyuan7242** [comment]
@DvirDukhan ok,
