### ISSUE TITLE
In addition to the bulk API, are there other ways to quickly build a graph?

### ISSUE THREAD

**Issue by caoxiaoyuan7242** [RedisGraph/RedisGraph#1016]
We have tens of millions of nodes and tens of millions of sides of data. It takes an hour and a half to complete the graph building using the bulk API：[redisgraph-bulk-loader](https://github.com/RedisGraph/redisgraph-bulk-loader)

**Comment by swilly22** [comment]
Hi @caoxiaoyuan7242, apologise for the late response,
currently the bulk-loader utility is the fastest way we have to load data into RedisGraph, how often are you loading your data? is that a one time operation?

**Comment by caoxiaoyuan7242** [comment]
thank you，the graph data keeps updating，and the graph may be updated weekly, if bulk-loader is the fastest way, we can use it .

**Comment by caoxiaoyuan7242** [comment]
hi @swilly22 ,thank you，the graph may be updated weekly, if bulk-loader is the fastest way, we can use it .

**Comment by swilly22** [comment]
Currently this is your best option
