### ISSUE TITLE
Question: path variables and functions

### ISSUE THREAD

**Issue by dandago** [RedisGraph/RedisGraph#1045]
In #748, @DvirDukhan gave this example query:

```
graph.query FamilyTree "match p=(:Person)-[:childOf*0..]->(:Person {name:'John'})-[:childOf*0..]->(:Person) return nodes(p)"
```

I hadn't seen that kind of `p=` variable assignment syntax in RedisGraph before this, and although the `nodes()` function is in the [Commands](https://oss.redislabs.com/redisgraph/commands/) documentation, there aren't any associated examples.

So I wanted to ask what kind of features RedisGraph supports in this space, and what kind of queries they address. It would also be nice to have some examples in the documentation if possible.

**Comment by swilly22** [comment]
@DvirDukhan can you please add a few examples to the documentation?
