### ISSUE TITLE
support predicate functions like all()

### ISSUE THREAD

**Issue by skurfuerst** [RedisGraph/RedisGraph#1059]
Hey everybody,

I am really happy with RedisGraph so far - but now I've hit two roadblocks when doing variable-length queries:

- I want to only traverse relations based on a certain property, i.e. do something like `-[h:HIERARCHY*1..3 {property: 'foo'}]->`
 (which then says `RedisGraph does not currently support filters on variable-length paths.`).
- When doing these variable-length queries, I need to ensure all nodes on the path are having some properties. I tried with the following query:
  ```
  MATCH p = (parentNode1:Node {nodeAggregateIdentifier: 'r'}) -[h:HIERARCHY*1..3]->(n:Node)
    WHERE all(n IN nodes(p) WHERE n.dimensionSpacePointHash = 'd1')
    RETURN n
  ```
  However, it seems (by looking at the source) that the predicate functions from https://neo4j.com/docs/cypher-manual/current/functions/predicate/#functions-all are not supported - a short note on the docs would be nice.

As a workaround, I think I would be able to do this via Lua Scripting in Redis - this should work, right?

All the best and thanks for your work,
Sebastian

**Comment by DvirDukhan** [comment]
@skurfuerst 
First, thanks for using RedisGraph. 
Regarding the missing features, we are aware of them, and we need to discuss when to implement them, with respect to our higher prioritized tasks.
Regarding the Lua script, I think it is better if you share your thoughts on how to implement it so we can share our advice and opinions.
Cheers.

**Comment by skurfuerst** [comment]
Hey @DvirDukhan ,

thanks for your quick reply :) I'll get back here once I have a Lua script :) 

All the best,
Sebastian

**Comment by xujiaxj** [comment]
I ran into the same situation where I need to do a variable-length path match where all the edges on the path have a certain property value. Hope RedisGraph can support `all` predicate soon. 

My query is something like
```
match p=(c:Foo)<-[r*..10]-(n) where c.name='foo' and all(r in relationships(p) WHERE r.cardinality  = 'OneToMany') return p, distinct(n)
```
