### ISSUE TITLE
Segfaulting with a (admittedly bogus) query

### ISSUE THREAD

**Issue by itamarhaber** [RedisGraph/RedisGraph#1061]
I don't really expect `bar[1]` to be anything but a core dump is a nasty reply :)

Query:
```
127.0.0.1:6379> GRAPH.QUERY foo "CREATE (:person{name:bar[1]})"
Error: Server closed the connection

Reply:
```
redis-server: /redisgraph/src/value.c:145: SI_CloneValue: Assertion `false && "Encountered heap-allocated SIValue of unhandled type"' failed.

=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 12 Apr 2020 17:29:28.928 # Redis 5.0.8 crashed by signal: 11
1:M 12 Apr 2020 17:29:28.928 # Crashed running the instruction at: 0x7f52a0003611
1:M 12 Apr 2020 17:29:28.928 # Accessing address: (nil)
1:M 12 Apr 2020 17:29:28.928 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7f52a0003611]

Backtrace:
redis-server *:6379(logStackTrace+0x32)[0x561fd2776592]
redis-server *:6379(sigsegvHandler+0x9e)[0x561fd2776c6e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7f52a01b4730]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7f52a0003611]
/lib/x86_64-linux-gnu/libc.so.6(+0x2240f)[0x7f52a000340f]
/lib/x86_64-linux-gnu/libc.so.6(+0x30102)[0x7f52a0011102]
/usr/lib/redis/modules/redisgraph.so(+0x1aaaac)[0x7f529eee5aac]
/usr/lib/redis/modules/redisgraph.so(GraphEntity_AddProperty+0x69)[0x7f529ef140e9]
/usr/lib/redis/modules/redisgraph.so(CommitNewEntities+0x1be)[0x7f529ef088ee]
/usr/lib/redis/modules/redisgraph.so(+0x1c976f)[0x7f529ef0476f]
/usr/lib/redis/modules/redisgraph.so(ExecutionPlan_Execute+0x58)[0x7f529eefc178]
/usr/lib/redis/modules/redisgraph.so(Graph_Query+0x351)[0x7f529eef6691]
/usr/lib/redis/modules/redisgraph.so(+0x1ebd1d)[0x7f529ef26d1d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7f52a01a9fa3]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f52a00da4cf]

------ INFO OUTPUT ------
# Server
redis_version:5.0.8
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:ce75a617c591114f
redis_mode:standalone
os:Linux 4.19.76-linuxkit x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0
process_id:1
run_id:835a91d616d86628f2112882ae791310ab5e3299
tcp_port:6379
uptime_in_seconds:6
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:9654264
executable:/data/redis-server
config_file:

# Clients
connected_clients:1
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:1

# Memory
used_memory:2545744
used_memory_human:2.43M
used_memory_rss:8216576
used_memory_rss_human:7.84M
used_memory_peak:2545744
used_memory_peak_human:2.43M
used_memory_peak_perc:308.69%
used_memory_overhead:874470
used_memory_startup:824704
used_memory_dataset:1671274
used_memory_dataset_perc:97.11%
allocator_allocated:1042912
allocator_active:1220608
allocator_resident:3883008
total_system_memory:8350801920
total_system_memory_human:7.78G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.17
allocator_frag_bytes:177696
allocator_rss_ratio:3.18
allocator_rss_bytes:2662400
rss_overhead_ratio:2.12
rss_overhead_bytes:4333568
mem_fragmentation_ratio:9.96
mem_fragmentation_bytes:7391872
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:49694
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1586712562
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:1
total_commands_processed:1
instantaneous_ops_per_sec:0
total_net_input_bytes:67
total_net_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:1
keyspace_misses:1
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:4be7bc285512a71cd7a0204303a5581b271d17f6
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.059518
used_cpu_user:0.027937
used_cpu_sys_children:0.003291
used_cpu_user_children:0.000819

# Commandstats
cmdstat_graph.QUERY:calls=1,usec=131,usec_per_call=131.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=4 addr=172.17.0.1:45300 fd=8 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY

------ REGISTERS ------
1:M 12 Apr 2020 17:29:28.932 #
RAX:0000000000000000 RBX:0000000000000000
RCX:0000000000000000 RDX:0000000000000000
RDI:0000000000000002 RSI:00007f529ed38100
RBP:00007f52a0165ee0 RSP:00007f529ed38220
R8 :0000000000000000 R9 :00007f529ed38100
R10:0000000000000008 R11:0000000000000246
R12:00007f529f3ad000 R13:00007f529f3ad078
R14:0000000000000091 R15:0000000000000000
RIP:00007f52a0003611 EFL:0000000000010246
CSGSFS:002b000000000033
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed3822f) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed3822e) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed3822d) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed3822c) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed3822b) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed3822a) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed38229) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed38228) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed38227) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed38226) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed38225) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed38224) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed38223) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed38222) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed38221) -> 0000000000000000
1:M 12 Apr 2020 17:29:28.932 # (00007f529ed38220) -> 0000000000000020

------ FAST MEMORY TEST ------
1:M 12 Apr 2020 17:29:28.932 # Bio thread for job type #0 terminated
1:M 12 Apr 2020 17:29:28.933 # Bio thread for job type #1 terminated
1:M 12 Apr 2020 17:29:28.933 # Bio thread for job type #2 terminated
*** Preparing to test memory region 561fd28a4000 (2248704 bytes)
*** Preparing to test memory region 561fd3eb6000 (135168 bytes)
*** Preparing to test memory region 7f5294000000 (2109440 bytes)
*** Preparing to test memory region 7f5299e00000 (4194304 bytes)
*** Preparing to test memory region 7f529a2b2000 (2621440 bytes)
*** Preparing to test memory region 7f529a533000 (8388608 bytes)
*** Preparing to test memory region 7f529ad34000 (8388608 bytes)
*** Preparing to test memory region 7f529b535000 (8388608 bytes)
*** Preparing to test memory region 7f529bd36000 (8388608 bytes)
*** Preparing to test memory region 7f529c537000 (8388608 bytes)
*** Preparing to test memory region 7f529cd38000 (8388608 bytes)
*** Preparing to test memory region 7f529d539000 (8388608 bytes)
*** Preparing to test memory region 7f529dd3a000 (8388608 bytes)
*** Preparing to test memory region 7f529e53b000 (8388608 bytes)
*** Preparing to test memory region 7f529f5fd000 (12288 bytes)
*** Preparing to test memory region 7f529f600000 (8388608 bytes)
*** Preparing to test memory region 7f529ffdb000 (24576 bytes)
*** Preparing to test memory region 7f52a019e000 (16384 bytes)
*** Preparing to test memory region 7f52a01bf000 (16384 bytes)
*** Preparing to test memory region 7f52a0355000 (8192 bytes)
*** Preparing to test memory region 7f52a0358000 (4096 bytes)
*** Preparing to test memory region 7f52a0382000 (4096 bytes)
```

**Comment by DvirDukhan** [comment]
yeah
we will fix it soon
thanks
