### ISSUE TITLE
Query with out the Graph ID breaking the docker container

### ISSUE THREAD

**Issue by BhanuPrakash531** [RedisGraph/RedisGraph#1064]
Please find the query to replicate the scenario

```
localhost:6379> GRAPH.QUERY "MATCH (e) RETURN e"
Error: Connection reset by peer
(0.86s)
localhost:6379>
```

**Comment by DvirDukhan** [comment]
hi @BhanuPrakash531
which docker version are you using? we had a PR #1023  merged handling this.

**Comment by BhanuPrakash531** [comment]
Hi @DvirDukhan , version is redislabs/redisgraph:2.0.6

**Comment by DvirDukhan** [comment]
@BhanuPrakash531 
This a faulty version that #1023 fixed.
Sorry for this inconvinace.
I recommend that you use either `latest` tag which is now 2.0.10 or `edge` tag which is alligned to our `master` branch.

**Comment by BhanuPrakash531** [comment]
Thanks for the update @DvirDukhan

**Comment by DvirDukhan** [comment]
@BhanuPrakash531 can I close this issue?
