### ISSUE TITLE
Add support for READ ONLY query GRAPH.QUERY_RO 

### ISSUE THREAD

**Issue by gkorland** [RedisGraph/RedisGraph#1071]

**Comment by Sceat** [comment]
Hum so this will allow better usage of redis sentinel, i'd like to implement it in my redisgraph client but i would need a way to actually know if a cypher query is RO or not :thinking: 
#420

**Comment by gkorland** [comment]
You will get an error from the server if you'll call this API with none read-only operation.

**Comment by Sceat** [comment]
[Roy spoke](https://github.com/RedisGraph/RedisGraph/issues/343#issuecomment-481695452) about not extending the api but we don't have a way to correctly handle master/slave, if an error is returned that mean client libraries have to parse cypher ast to determine the read/write nature, or users have to refactor their codebase to manually use `QUERY` or `QUERY_RO`. The later seems better but lacks ergonomic.. yet i don't have any solution ideas :/

**Comment by Sceat** [comment]
Well actually just checking if the query string contains CREATE DELETE MERGE or SET should be enough, then i can choose to send a read only instead of a query 👌

**Comment by swilly22** [comment]
Use GRAPH.RO_QUERY #1364
