### ISSUE TITLE
Using parameters in redis-cli

### ISSUE THREAD

**Issue by dandago** [RedisGraph/RedisGraph#1078]
Hi,

I was reading from Neo4j training material that Cypher has a way to pass parameters to a query (reminds me of prepared statements when dealing with SQL).

The only mention of parameters in the RedisGraph docs is in the [Cypher coverage](https://oss.redislabs.com/redisgraph/cypher_support/) page which only refers to client libraries.

I'd like to know how parameters could be passed to a query via native commands when using `redis-cli`.

Thanks

**Comment by swilly22** [comment]
Hi @dandago,
You can use Redis `MONITOR` command to see the commands received by the server.

Regardless, this is how you would specify parameters:

```
GRAPH.QUERY g "CYPHER a=1; RETURN $a"
```

**Comment by dandago** [comment]
Thanks. I suppose these need to be specified for each query that is run.

What are the benefits of using parameters specifically in RedisGraph? Are there any performance/caching and security aspects for instance? Anything else worth mentioning?

**Comment by swilly22** [comment]
Well, for once, if you're query takes an input from users, introducing user input via parameters is much safer then injecting this data directly into the query (think SQL injection)

Moreover @DvirDukhan is almost done working on query caching which will benefit from parametrised queries.
