### ISSUE TITLE
Find Node via Alias Value

### ISSUE THREAD

**Issue by victorstewart** [RedisGraph/RedisGraph#1114]
Can you respond with a quick snippet of how to find a node if you have the label type and value of it? You don't have to iterate over every node in the label matrix I assume... that there's a map somewhere?

**Comment by swilly22** [comment]
What do you mean if you have the value of it?
Are you referring to an attribute value? e.g. `age = 33` ?

**Comment by victorstewart** [comment]
@swilly22 

Sorry for not being more clear. Maybe it called an alias?

So imagine I create a node: `CREATE (bob:Person)`

Then I'm here..
```
int nodeMatrixLabelID = GraphContext_GetSchema(g, "Person", SCHEMA_NODE)->id;
GrB_Matrix nodeMatrix = Graph_GetLabelMatrix(g, nodeMatrixLabelID);
```
How do I get back for the node for "bob"?

**Comment by swilly22** [comment]
The `nodeMatrix` matrix is a diagonal matrix, where `nodeMatrix[i,i] = 1` if node with ID i is labeled as Person. unless you know which ID was assign to Bob you gonna have to scan through the entire matrix, for each i such that nodeMatrix[i,i] = 1 you'll have to get node with ID i, `Graph_GetNode` and see if that node is Bob.

**Comment by victorstewart** [comment]
@swilly22 okay thanks for confirming what I suspected!

before I go back digging in the source code, is it possible to instruct CREATE to return me the `nodeID`? Then I can just store and use the IDs instead of aliases, to avoid all the cpu cycles searching for each node each time.

**Comment by swilly22** [comment]
You can return a created node:
```
CREATE (n) RETURN ID(n)
```
