### ISSUE TITLE
Unable to use Makefile to create redisgraph.so

### ISSUE THREAD

**Issue by sahassan013** [RedisGraph/RedisGraph#1119]
I've cloned the redisgraph repo and followed the steps in the readme to build the module 
(on a mac os)
but when running "make" in the directory where the Makefile exists,
I am unable to get the compiled binary redisgraph.so 

Getting the following error :

```
RedisGraph $ ls
Dockerfile		Dockerfile.centos	Makefile		demo			docs			mkdocs.yml		src
Dockerfile.alpine	LICENSE			README.md		deps			lgtm.yml		ramp.yml		tests

RedisGraph $ make
make[2]: *** No targets specified and no makefile found.  Stop.
make[1]: *** [../deps/rax/rax.o] Error 2
make: *** [all] Error 2```

**Comment by jeffreylovitz** [comment]
Hi @sahassan013,

RedisGraph should be cloned with its submodules like so:
`git clone --recurse-submodules https://github.com/RedisGraph/RedisGraph.git`

Submodules can be fetched in an already-cloned repository with the command:
`git submodule update --init --recursive`

**Comment by sahassan013** [comment]
@jeffreylovitz  Yeah, so I did exactly that. If you scroll to the right of my code snippet you'll see the src directory and others.... but when I run make inside of RedisGraph directory... it shows the error above.

**Comment by jeffreylovitz** [comment]
The error you've shared is one I've only seen when the project's submodules have not been pulled, though the directory structure will still be correct in this case.

When you run `ls deps/rax/`, is there any output? If not, the submodule update command should resolve the problem.

**Comment by sahassan013** [comment]
Alright yeah, so I started from scratch. Recloned the repo and running make works now. 

At the end it outputs a new error:
```
clang: error: unsupported option '-fopenmp'
make[1]: *** [redisgraph.so] Error 1
make: *** [all] Error 2
```
But this isn't redisgraph related

**Comment by jeffreylovitz** [comment]
Alright! The `fopenmp` complaint is an issue with the OSX toolchain version of Clang, and can be resolved by switching to a homebrew version of Clang or GCC (and some other ways). Some details about this can be found in https://oss.redislabs.com/redisgraph/#building.

**Comment by sahassan013** [comment]
I will check that out. Thanks!
