### ISSUE TITLE
Can I compile redis-graph on MS Windows 10 x64 ?

### ISSUE THREAD

**Issue by pimgeek** [RedisGraph/RedisGraph#114]
I've compiled redis-server on MS Windows 10 (using MSYS2 MinGW tools), but failed to compile redis-graph. The error message seems to show that redis-graph doesn't compile on MS Windows...

```
D:\hintsnet-wudi\develop\scaffold\hintsnet-redisgraph\redis-graph-master>make
make -C ./src all
make[1]: Entering directory '/d/hintsnet-wudi/develop/scaffold/hintsnet-redisgraph/redis-graph-master/src'
cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -D_GNU_SOURCE -std=gnu99 -I"/d/hintsnet-wudi/develop/scaffold/hintsnet-redisgraph/redis-graph-master/src" -DREDIS_MODULE_TARGET -g -ggdb -O3  -mmacosx-version-min=10.12 -c /d/hintsnet-wudi/develop/scaffold/hintsnet-redisgraph/redis-graph-master/src/delete_graph.c -o /d/hintsnet-wudi/develop/scaffold/hintsnet-redisgraph/redis-graph-master/src/delete_graph.o -MMD -MF /d/hintsnet-wudi/develop/scaffold/hintsnet-redisgraph/redis-graph-master/src/delete_graph.d
cc: error: unrecognized command line option '-mmacosx-version-min=10.12'
make[1]: *** [Makefile:71: /d/hintsnet-wudi/develop/scaffold/hintsnet-redisgraph/redis-graph-master/src/delete_graph.o] Error 1
make[1]: Leaving directory '/d/hintsnet-wudi/develop/scaffold/hintsnet-redisgraph/redis-graph-master/src'
make: *** [Makefile:2: all] Error 2
```

So, is it possible to compile redis-graph on MS Windows, when the cc options are probably set? 😅

**Comment by swilly22** [comment]
Hi @pimgeek,
I've never tried compiling RedisGraph on Window but the error we're seeing is easy to fix,
I'll try to get RedisGraph compiling and running on Windows probably sometime during the upcoming week, I'll update here.
Thank you.

**Comment by pimgeek** [comment]
Thanks for your quick reply 😊
I'm trying to develop a simple note card manager software based on DAG data structure, the opencypher syntax seems to simplify the data manipulation and query task.

**Comment by swilly22** [comment]
Sure, that's sounds cool, interested to see how it turns out.

**Comment by Code4SAFrankie** [comment]
So does it run on Windows 10 x64?

**Comment by pimgeek** [comment]
@Code4SAFrankie I didn't use RedisGraph on Windows after that compilation error.

**Comment by Code4SAFrankie** [comment]
I'm taking that as a no it doesn't run on MS Windows 10.

**Comment by jeffreylovitz** [comment]
Hi @Code4SAFrankie,

We haven't been targeting Windows development, and I find it unlikely that you could compile without modification on Windows! Sorry about that.

There are fairly few areas in which we use UNIX-specific tricks, so I feel like Windows support isn't an untenable goal, but it's not on our roadmap at this time!
