### ISSUE TITLE
!= (not equal) operation in WHERE clauses

### ISSUE THREAD

**Issue by jgillich** [RedisGraph/RedisGraph#1156]
https://github.com/RedisGraph/RedisGraph/issues/11 talks about this feature being added. And I think I've used it in 1.0 (although I'm not 100% sure). Was it removed in 2.0? I can't find much about that. The [docs](https://oss.redislabs.com/redisgraph/commands/#where) don't list it.

Example query:
```
MATCH (currency:currency) WHERE currency.iso_code != 'USD' RETURN currency
```
returns:
```
errMsg: Invalid input '!': expected '.', '(', AND, OR, XOR, NOT, '=~', '=', '<>', '+', '-', '*', '/', '%', '^', IN, CONTAINS, STARTS WITH, ENDS WITH, '<=', '>=', '<', '>', IS NULL, IS NOT NULL, '[', '{', a label, ';' or a clause line: 1, column: 51, offset: 50 errCtx: MATCH (currency:currency) WHERE currency.iso_code != 'USD' RETURN currency errCtxOffset: 50
```

with v2.0.12.

**Comment by sfroment** [comment]
You have to use ```<>```  which is the not operator.

**Comment by jgillich** [comment]
Ah cool, thank you!
