### ISSUE TITLE
RedisGraph does not currently support has labels

### ISSUE THREAD

**Issue by xujiaxj** [RedisGraph/RedisGraph#1167]
The following query doesn't work
```
match (n) where n:Foo return n
```
Saying "RedisGraph does not currently support has labels", but has label query is useful if I want to query for nodes of a few different label choices, like 
```
match (n) where n:Foo or n:Bar return n
```
This is a rather common use case, although one may argue the workaround is to combine the results of the following two queries
```
match (n:Foo) return n
match (n:Bar) return n
```
Doable? Yes. Efficient? Probably not.

**Comment by jeffreylovitz** [comment]
Adding support for the `where n:Foo` construction is on our roadmap, and we acknowledge its usefulness! Hopefully we will find time to introduce it soon.

In the meantime, the workaround I would recommend is:
`match (n) where LABELS(n) = 'Foo' OR LABELS(n) = 'Bar' return n`
Or if you prefer:
`match (n) where LABELS(n) IN ['Foo', 'Bar'] return n`

**Comment by xujiaxj** [comment]
@jeffreylovitz Thanks for the workaround tip. It works for me.
