### ISSUE TITLE
Secondary Match is loosing previous values

### ISSUE THREAD

**Issue by Sceat** [RedisGraph/RedisGraph#1230]
Not sure if it is expected behavior but i'm not able to retrieve values before a new `MATCH`

This create a node
```
CREATE (n { foo: 'bar'})
```

The node can be retrieved
```
MATCH (n { foo: 'bar'}) 
RETURN n
```

But here there is no results anymore
```
MATCH (n { foo: 'bar'})
WITH n
MATCH (a { foo: 'foo'})
RETURN n, a
```

**Comment by swilly22** [comment]
Hi @Sceat, 
You're not seeing any results because there's probably no node in the graph with attribute `foo` and value `foo`
You see for `n` to proceed `a` must exists, if you still want to project `n` while `a` might not exists use `OPTIONAL MATCH`

**Comment by Sceat** [comment]
Ok that's working thanks!
