### ISSUE TITLE
COLLECT(<empty result>) doesn't return empty array

### ISSUE THREAD

**Issue by kdojeteri** [RedisGraph/RedisGraph#1241]
Using CLI, this command:
```
127.0.0.1:6379> "GRAPH.QUERY" "portal-graph" "MATCH (n:ExampleNonsense) RETURN collect(id(n))"
```
currently gives this result:
```
1) 1) "collect(id(n))"
2) (empty array)
3) 1) "Query internal execution time: 0.397809 milliseconds"
```
which means this query returned 0 records in spite of an aggregate function being used.

I suspect the correct result should be 1 record with an empty array as a value:
```
1) 1) "collect(id(n))"
2) 1) (empty array)
3) 1) "Query internal execution time: 0.397809 milliseconds"
```

The behaviour in neo4j confirms my theory:
![image](https://user-images.githubusercontent.com/3697116/87479207-5c245600-c62b-11ea-8c4e-0e6efa16186c.png)

**Comment by swilly22** [comment]
Related #1234
