### ISSUE TITLE
Backslash did not work for full text search

### ISSUE THREAD

**Issue by renlei-bj** [RedisGraph/RedisGraph#1245]
Thank you in advance.

I wanted to do a full-text search on this exact word: `app=sre-ui`. I know WHERE clause with CONTAINS can work in this case. I am just wondering how to do it in the full-text search.

RediSearch will search `['app', 'sre']` and remove results contain`'ui'`. That is understandable, they said:
> All punctuation marks and whitespaces (besides underscores) separate the document and queries into tokens. e.g. any character of ,.<>{}[]"':;!@#$%^&*()-+=~ will break the text into terms. So the text foo-bar.baz...bag will be tokenized into [foo, bar, baz, bag] 

They also said a backslash should escape the special characters.
> Escaping separators in both queries and documents is done by prepending a backslash to any separator. e.g. the text hello\-world hello-world will be tokenized as [hello-world, hello, world] . NOTE that in most languages you will need an extra backslash when formatting the document or query, to signify an actual backslash, so the actual text in redis-cli for example, will be entered as hello\\-world . 

So I tested with this command, but I found the backslash did not work.
> graph.query test "call db.idx.fulltext.queryNodes('Pod', 'app\\=sre\\-ui') YIELD node RETURN node.name, node.label"

Is this a defect of RediSearch integration?

**Comment by gkorland** [comment]
notice when you escape a character it's included as part of the term.
e.g.
```
127.0.0.1:6379> ft.explain a 'app=sre-ui'
INTERSECT {
  UNION {
    app
    +app(expanded)
  }
  UNION {
    sre
    +sre(expanded)
  }
  NOT{
    ui
  }
}
```
vs 
```
127.0.0.1:6379> ft.explain a 'app\=sre\-ui'
UNION {
  app=sre-ui
  +app=sre-ui(expanded)
}
```

**Comment by renlei-bj** [comment]
@gkorland 
Thank you for your quick response.
The `a` in your example is an index, correct? How can I find it?
I read the RediSearch command reference but did not find how to list the full-text indexes I created.

**Comment by gkorland** [comment]
>  The a in your example is an index, correct? How can I find the available indexes in my environment?
You're right `a` in my example is the index but it's not directly exposed on RedisGraph, I was just using RediSearch to explain how the query is parsed.  

> I read the RediSearch command reference but did not find how to list the full-text indexes I created.
You're right current RediSearch 1.X doesn't expose it, should be added in RediSearch 2.X, anyway it's hidden in RedisGraph as RedisGraph is using these indexes and does not expose them directly.

**Comment by renlei-bj** [comment]
@gkorland Thank you!

**Comment by gkorland** [comment]
ref #1247
