### ISSUE TITLE
pkill on redis-server pid with RedisGraph (master branch) module loaded raises crash 

### ISSUE THREAD

**Issue by filipecosta90** [RedisGraph/RedisGraph#1259]
commit 67b33ef02258b7305b41e646f60c5b9e9398831a

issuing SIGTERM to redis-server  `pkill redis-server` raises a crash with the log available at the following link:  https://s3.amazonaws.com/benchmarks.redislabs/redisgraph/results/query-cache-filipe-dvir/67b33ef02258b7305b41e646f60c5b9e9398831a.redis-server.log

**Comment by swilly22** [comment]
#1298 resolves this
