### ISSUE TITLE
MATCH condition ignores Nodes with undefined property values

### ISSUE THREAD

**Issue by manoja1** [RedisGraph/RedisGraph#1261]
Steps to recreate 
```
CREATE (Manoj:Person {name: 'Manoj', country: 'USA'})
CREATE (Jim:Person { name: 'Jim'})
CREATE (CA:Location { name: 'CA', country: 'USA' })
CREATE (TX:Location { name: 'TX' })
```

Search with
```
MATCH (n:Person), (m:Location) WHERE n.country = m.country RETURN n, m; 
```

Expected: 2 Nodes `Manoj` and `CA`
Actual: All 4 Nodes !

Using latest version of redismod `docker run -p 6379:6379 -it --rm redislabs/redismod` v 6.0.1

**Comment by DvirDukhan** [comment]
@swilly22 @jeffreylovitz 
possible re-occurrence of https://github.com/RedisGraph/RedisGraph/issues/1124

**Comment by jeffreylovitz** [comment]
@manoja1 Thanks for the report! This is an error in NULL handling in the `ValueHashJoin` op, a fix will be out shortly.
