### ISSUE TITLE
Using a node twice in a WHERE statement return an error

### ISSUE THREAD

**Issue by Sceat** [RedisGraph/RedisGraph#1268]
```
CREATE (:Foo)-->(:Bar)
MATCH (b:Bar)
WHERE (a:Foo)-->(b)<--(a:Foo)
RETURN b
```

this give `a not defined`, i need that kind of pattern to ensure the a is the same as another node, it works in a MATCH but not in a WHERE

**Comment by jeffreylovitz** [comment]
@Sceat After doing some testing, it is actually invalid to introduce an identifier in a `WHERE` predicate in this way.

Can you provide a fuller version of this query, and we can try to workshop a viable solution?

**Comment by Sceat** [comment]
I have an user which is assigned on an apartment for a group, represented like this
```
(:User)-[:IS_ASSIGNED]->(a:Assignment)
(a)-[:ASSIGNED_ON]->(:Apartment)
(a)-[:ASSIGNED_FOR]->(:Group)
```
and in a query i'm matching an user in a group, and i also want to make sur he is assigned on an apartment for this group, thus i have (simplified)
```
MATCH (u:User)-->(g:Group)-->(n:Apartment)
WHERE (g)<--(a:Assign)<--(u)-->(a:Assign)-->(n)
```
The thing is i just need to make sur the `:Assign` node is the same left and right

**Comment by DvirDukhan** [comment]
1. `MATCH (u:User)-->(a:Assign)-->(g:Group)-->(n:Apartment)<--(a)<--(u)`
2. `MATCH (u:User)-->(a:Assign)-->(g:Group)-->(n:Apartment) WHERE (a)-->(n)`

**Comment by Sceat** [comment]
I forgot to say the :Assign is optional, if the user is owner of the group, it doesn't need the assignment
```
WHERE (u)-[:IS_OWNER]->(g) OR (g)<--(a:Assign)<--(u)-->(a:Assign)-->(p)
```

**Comment by Sceat** [comment]
The exact query is 

```
  MATCH (u:User)-->(g:Group)-->(p:Parcel)
  WHERE u.uuid = ${ bearer.uuid }
  AND g.uuid = ${ uuid } AND p.uuid = ${ parcel_id }
  AND (
    (u)-[:IS_OWNER]->(g) OR
    (g)<--(a:Assign)<--(u)-->(a:Assign)-->(p)
  )
  WITH DISTINCT u, g, p
  MATCH (tenant:User)-[rel:IS_TENANT]->(p)
  RETURN DISTINCT rel AS is_in, tenant, p AS parcel
```

**Comment by Sceat** [comment]
I tried something like this but redis crashed

```
  MATCH (u:User)-->(g:Group)-->(p:Parcel)
  WHERE u.uuid = ${ bearer.uuid }
  AND g.uuid = ${ uuid } AND p.uuid = ${ parcel_id }
  WITH u, g, p
  OPTIONAL MATCH (g)<--(a:Assign)
  WITH DISTINCT u, g, p, a
  MATCH (tenant:User)-[rel:IS_TENANT]->(p)
  WHERE tenant.uuid = ${ tenant_id }
  AND ( (u)-->(a)-->(p) OR (u)-[:IS_OWNER]->(g) )
  RETURN DISTINCT rel AS is_in, tenant AS the_tenant, p AS parcel
```

<details>
<summary>crash logs</summary>
<pre>
redis-graph_1     | 
redis-graph_1     | 
redis-graph_1     | === REDIS BUG REPORT START: Cut & paste starting from here ===
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.131 # Redis 6.0.5 crashed by signal: 11
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.131 # Crashed running the instruction at: 0x7fd670cf0f54
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.131 # Accessing address: (nil)
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.131 # Failed assertion: <no assertion failed> (<no file>:0)
redis-graph_1     | 
redis-graph_1     | ------ STACK TRACE ------
redis-graph_1     | EIP:
redis-graph_1     | /usr/lib/redis/modules/redisgraph.so(ExecutionPlan_LocateOpMatchingType+0x4)[0x7fd670cf0f54]
redis-graph_1     | 
redis-graph_1     | Backtrace:
redis-graph_1     | redis-server *:6379(logStackTrace+0x32)[0x55db3789ce02]
redis-graph_1     | redis-server *:6379(sigsegvHandler+0x9e)[0x55db3789d4de]
redis-graph_1     | /lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7fd671ed2730]
redis-graph_1     | /usr/lib/redis/modules/redisgraph.so(ExecutionPlan_LocateOpMatchingType+0x4)[0x7fd670cf0f54]
redis-graph_1     | /usr/lib/redis/modules/redisgraph.so(ExecutionPlan_Clone+0x30d)[0x7fd670cefc3d]
redis-graph_1     | /usr/lib/redis/modules/redisgraph.so(ExecutionCtx_FromQuery+0x199)[0x7fd670ced389]
redis-graph_1     | /usr/lib/redis/modules/redisgraph.so(Graph_Query+0x40)[0x7fd670ced460]
redis-graph_1     | /usr/lib/redis/modules/redisgraph.so(+0x1f4d2d)[0x7fd670d20d2d]
redis-graph_1     | /lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7fd671ec7fa3]
redis-graph_1     | /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fd671df64cf]
redis-graph_1     | 
redis-graph_1     | ------ INFO OUTPUT ------
redis-graph_1     | # Server
redis-graph_1     | redis_version:6.0.5
redis-graph_1     | redis_git_sha1:00000000
redis-graph_1     | redis_git_dirty:0
redis-graph_1     | redis_build_id:7c345cef74f59a8c
redis-graph_1     | redis_mode:standalone
redis-graph_1     | os:Linux 5.4.52-1-MANJARO x86_64
redis-graph_1     | arch_bits:64
redis-graph_1     | multiplexing_api:epoll
redis-graph_1     | atomicvar_api:atomic-builtin
redis-graph_1     | gcc_version:8.3.0
redis-graph_1     | process_id:1
redis-graph_1     | run_id:f192cab3148c923aa92d3fec743353f3c82e8367
redis-graph_1     | tcp_port:6379
redis-graph_1     | uptime_in_seconds:23
redis-graph_1     | uptime_in_days:0
redis-graph_1     | hz:10
redis-graph_1     | configured_hz:10
redis-graph_1     | lru_clock:2348999
redis-graph_1     | executable:/data/redis-server
redis-graph_1     | config_file:
redis-graph_1     | 
redis-graph_1     | # Clients
redis-graph_1     | connected_clients:3
redis-graph_1     | client_recent_max_input_buffer:2
redis-graph_1     | client_recent_max_output_buffer:0
redis-graph_1     | blocked_clients:1
redis-graph_1     | tracking_clients:0
redis-graph_1     | clients_in_timeout_table:0
redis-graph_1     | 
redis-graph_1     | # Memory
redis-graph_1     | used_memory:2316928
redis-graph_1     | used_memory_human:2.21M
redis-graph_1     | used_memory_rss:15704064
redis-graph_1     | used_memory_rss_human:14.98M
redis-graph_1     | used_memory_peak:2454184
redis-graph_1     | used_memory_peak_human:2.34M
redis-graph_1     | used_memory_peak_perc:94.41%
redis-graph_1     | used_memory_overhead:887974
redis-graph_1     | used_memory_startup:836944
redis-graph_1     | used_memory_dataset:1428954
redis-graph_1     | used_memory_dataset_perc:96.55%
redis-graph_1     | allocator_allocated:4218584
redis-graph_1     | allocator_active:5472256
redis-graph_1     | allocator_resident:10727424
redis-graph_1     | total_system_memory:16675385344
redis-graph_1     | total_system_memory_human:15.53G
redis-graph_1     | used_memory_lua:37888
redis-graph_1     | used_memory_lua_human:37.00K
redis-graph_1     | used_memory_scripts:0
redis-graph_1     | used_memory_scripts_human:0B
redis-graph_1     | number_of_cached_scripts:0
redis-graph_1     | maxmemory:0
redis-graph_1     | maxmemory_human:0B
redis-graph_1     | maxmemory_policy:noeviction
redis-graph_1     | allocator_frag_ratio:1.30
redis-graph_1     | allocator_frag_bytes:1253672
redis-graph_1     | allocator_rss_ratio:1.96
redis-graph_1     | allocator_rss_bytes:5255168
redis-graph_1     | rss_overhead_ratio:1.46
redis-graph_1     | rss_overhead_bytes:4976640
redis-graph_1     | mem_fragmentation_ratio:6.42
redis-graph_1     | mem_fragmentation_bytes:13258384
redis-graph_1     | mem_not_counted_for_evict:0
redis-graph_1     | mem_replication_backlog:0
redis-graph_1     | mem_clients_slaves:0
redis-graph_1     | mem_clients_normal:50958
redis-graph_1     | mem_aof_buffer:0
redis-graph_1     | mem_allocator:jemalloc-5.1.0
redis-graph_1     | active_defrag_running:0
redis-graph_1     | lazyfree_pending_objects:0
redis-graph_1     | 
redis-graph_1     | # Persistence
redis-graph_1     | loading:0
redis-graph_1     | rdb_changes_since_last_save:21
redis-graph_1     | rdb_bgsave_in_progress:0
redis-graph_1     | rdb_last_save_time:1596184496
redis-graph_1     | rdb_last_bgsave_status:ok
redis-graph_1     | rdb_last_bgsave_time_sec:-1
redis-graph_1     | rdb_current_bgsave_time_sec:-1
redis-graph_1     | rdb_last_cow_size:0
redis-graph_1     | aof_enabled:0
redis-graph_1     | aof_rewrite_in_progress:0
redis-graph_1     | aof_rewrite_scheduled:0
redis-graph_1     | aof_last_rewrite_time_sec:-1
redis-graph_1     | aof_current_rewrite_time_sec:-1
redis-graph_1     | aof_last_bgrewrite_status:ok
redis-graph_1     | aof_last_write_status:ok
redis-graph_1     | aof_last_cow_size:0
redis-graph_1     | module_fork_in_progress:0
redis-graph_1     | module_fork_last_cow_size:0
redis-graph_1     | 
redis-graph_1     | # Stats
redis-graph_1     | total_connections_received:3
redis-graph_1     | total_commands_processed:129
redis-graph_1     | instantaneous_ops_per_sec:69
redis-graph_1     | total_net_input_bytes:22249
redis-graph_1     | total_net_output_bytes:37177
redis-graph_1     | instantaneous_input_kbps:11.37
redis-graph_1     | instantaneous_output_kbps:19.65
redis-graph_1     | rejected_connections:0
redis-graph_1     | sync_full:0
redis-graph_1     | sync_partial_ok:0
redis-graph_1     | sync_partial_err:0
redis-graph_1     | expired_keys:0
redis-graph_1     | expired_stale_perc:0.00
redis-graph_1     | expired_time_cap_reached_count:0
redis-graph_1     | expire_cycle_cpu_milliseconds:0
redis-graph_1     | evicted_keys:0
redis-graph_1     | keyspace_hits:125
redis-graph_1     | keyspace_misses:3
redis-graph_1     | pubsub_channels:1
redis-graph_1     | pubsub_patterns:0
redis-graph_1     | latest_fork_usec:0
redis-graph_1     | migrate_cached_sockets:0
redis-graph_1     | slave_expires_tracked_keys:0
redis-graph_1     | active_defrag_hits:0
redis-graph_1     | active_defrag_misses:0
redis-graph_1     | active_defrag_key_hits:0
redis-graph_1     | active_defrag_key_misses:0
redis-graph_1     | tracking_total_keys:0
redis-graph_1     | tracking_total_items:0
redis-graph_1     | tracking_total_prefixes:0
redis-graph_1     | unexpected_error_replies:0
redis-graph_1     | 
redis-graph_1     | # Replication
redis-graph_1     | role:master
redis-graph_1     | connected_slaves:0
redis-graph_1     | master_replid:45e7c4d334dc26de37a6f28579da7d6cccfec2c0
redis-graph_1     | master_replid2:0000000000000000000000000000000000000000
redis-graph_1     | master_repl_offset:0
redis-graph_1     | second_repl_offset:-1
redis-graph_1     | repl_backlog_active:0
redis-graph_1     | repl_backlog_size:1048576
redis-graph_1     | repl_backlog_first_byte_offset:0
redis-graph_1     | repl_backlog_histlen:0
redis-graph_1     | 
redis-graph_1     | # CPU
redis-graph_1     | used_cpu_sys:0.042632
redis-graph_1     | used_cpu_user:0.273329
redis-graph_1     | used_cpu_sys_children:0.000000
redis-graph_1     | used_cpu_user_children:0.001932
redis-graph_1     | 
redis-graph_1     | # Modules
redis-graph_1     | module:name=graph,ver=999999,api=1,filters=0,usedby=[],using=[],options=[]
redis-graph_1     | 
redis-graph_1     | # Commandstats
redis-graph_1     | cmdstat_info:calls=3,usec=104,usec_per_call=34.67
redis-graph_1     | cmdstat_graph.QUERY:calls=109,usec=1941,usec_per_call=17.81
redis-graph_1     | cmdstat_publish:calls=14,usec=49,usec_per_call=3.50
redis-graph_1     | cmdstat_subscribe:calls=1,usec=3,usec_per_call=3.00
redis-graph_1     | cmdstat_graph.DELETE:calls=2,usec=115,usec_per_call=57.50
redis-graph_1     | 
redis-graph_1     | # Cluster
redis-graph_1     | cluster_enabled:0
redis-graph_1     | 
redis-graph_1     | # Keyspace
redis-graph_1     | db0:keys=1,expires=0,avg_ttl=0
redis-graph_1     | 
redis-graph_1     | ------ CLIENT LIST OUTPUT ------
redis-graph_1     | id=6 addr=127.0.0.1:40192 fd=8 name= age=1 idle=1 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=info user=default
redis-graph_1     | id=7 addr=127.0.0.1:40194 fd=9 name= age=1 idle=0 flags=P db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe user=default
redis-graph_1     | id=8 addr=[::1]:43866 fd=10 name= age=1 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY user=default
redis-graph_1     | 
redis-graph_1     | ------ REGISTERS ------
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # 
redis-graph_1     | RAX:0000000000000002 RBX:0000000000000008
redis-graph_1     | RCX:0000000000000004 RDX:0000000000000002
redis-graph_1     | RDI:0000000000000000 RSI:00007fd6711ad868
redis-graph_1     | RBP:00007fd66a0157a0 RSP:00007fd66f326458
redis-graph_1     | R8 :0000000000000026 R9 :0000000000000060
redis-graph_1     | R10:00007fd66f327070 R11:0000000000000130
redis-graph_1     | R12:00007fd66a015840 R13:00007fd66a05a280
redis-graph_1     | R14:00007fd6711ad868 R15:0000000000000020
redis-graph_1     | RIP:00007fd670cf0f54 EFL:0000000000010202
redis-graph_1     | CSGSFS:002b000000000033
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f326467) -> 000055db39c1bd18
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f326466) -> 000055db39c1bcc0
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f326465) -> 000055db39c1bcb0
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f326464) -> 00007fd6718358c0
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f326463) -> 00007fd67181cdf8
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f326462) -> 00007fd654217208
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f326461) -> 00007fd67181cdf8
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f326460) -> 00007fd670ced389
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f32645f) -> 00007fd6713fee10
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f32645e) -> 00007fd671928b30
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f32645d) -> 00007fd66a0154d0
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f32645c) -> 00007fd654217180
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f32645b) -> 00007fd66a015750
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f32645a) -> 00007fd66f326510
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f326459) -> 00007fd6713fee10
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # (00007fd66f326458) -> 00007fd670cefc3d
redis-graph_1     | 
redis-graph_1     | ------ MODULES INFO OUTPUT ------
redis-graph_1     | 
redis-graph_1     | ------ FAST MEMORY TEST ------
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # Bio thread for job type #0 terminated
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # Bio thread for job type #1 terminated
redis-graph_1     | 1:M 31 Jul 2020 08:35:19.132 # Bio thread for job type #2 terminated
redis-graph_1     | *** Preparing to test memory region 55db379e8000 (2277376 bytes)
redis-graph_1     | *** Preparing to test memory region 55db39beb000 (270336 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd654000000 (2281472 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd658000000 (2232320 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd65c000000 (2224128 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd660000000 (2232320 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd664000000 (135168 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd669200000 (4194304 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd669800000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66a000000 (4194304 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66a600000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66ae00000 (4194304 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66b400000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66bc00000 (4194304 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66c0a3000 (2621440 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66c324000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66cb25000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66d326000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66db27000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66e328000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66eb29000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66f32a000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd66fb2b000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd67032c000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd6713fc000 (16384 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd671400000 (8388608 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd671cf9000 (16384 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd671eba000 (24576 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd671edd000 (16384 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd6721c6000 (16384 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd6723ee000 (8192 bytes)
redis-graph_1     | *** Preparing to test memory region 7fd67241b000 (4096 bytes)
redis-graph_1     | .O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.files_redis-graph_1 exited with code 139
</code>

</details>

**Comment by jeffreylovitz** [comment]
Thanks for the extra info! I just opened a new issue to track the bug you encountered.

The first approach I thought of to your problem is to combine OPTIONAL MATCH with null checks like so:
```
  MATCH (u:User)-->(g:Group)-->(p:Parcel)
  WHERE u.uuid = ${ bearer.uuid }
  AND g.uuid = ${ uuid } AND p.uuid = ${ parcel_id }
  OPTIONAL MATCH (u)-[edge_1:IS_OWNER]->(g)
  OPTIONAL MATCH (g)<--(edge_2:Assign)<--(u)-->(edge_2:Assign)-->(p)
  WHERE edge_1 IS NOT NULL OR edge_2 IS NOT NULL
  WITH DISTINCT u, g, p
  MATCH (tenant:User)-[rel:IS_TENANT]->(p)
  WHERE tenant.uuid = ${ tenant_id }
  RETURN DISTINCT rel AS is_in, tenant AS the_tenant, p AS parcel
```
This query does not crash, but I did not try generating sample data to validate it against. What do you think?

**Comment by Sceat** [comment]
Oh damn i didn't know optional match worked like that you can actually ensure one of them is correct 😯
