### ISSUE TITLE
CyphSem crashes RedisGraph

### ISSUE THREAD

**Issue by DvirDukhan** [RedisGraph/RedisGraph#1285]
1. `MATCH y1=(x3) WITH “c” AS `“c”`, x3 AS u3 WHERE [[x3.while,false,[1],true,x4]] RETURN *` 
1. `MATCH () MATCH u2=()-[:likes]-(v4 :tall)-[*0]-(y2 :human:tall) RETURN *`

**Comment by swilly22** [comment]
@jeffreylovitz  see if this issue has been resolved already,
Referencing #1328 here
