### ISSUE TITLE
UNWIND - Tempalted queries

### ISSUE THREAD

**Issue by flpgrz** [RedisGraph/RedisGraph#1293]
_Redis v6.0.6
RedisGraph v2.0.15_

Hi all,

A question concerning templated queries. 

```
{batch: [
{id:"alice@example.com",properties:{name:"Alice",age:32}},{id:"bob@example.com",properties:{name:"Bob",age:42}}]}
UNWIND $batch as row
MERGE (n:Label {id: row.id})
(ON CREATE) SET n += row.properties
```

Can this be done with RedisGraph? I cannot define the `batch` parameter in any way, I always get an error. I tried both in this way and with :param batch => (as currently supported by Neo4J).

Also, concerning the Python API: 

```
cypher_query = 'UNWIND $batch as row ' \
                       'MATCH (node:Node) WHERE node.id = row.id ' \
                       'SET node.description = row.description'
        redis_graph.query(cypher_query, batch)  # ERROR: I cannot pass  a list of dictionaries (batch) at the moment 
```
Is there a way to use UNWIND, as of now? 
Thanks

**Comment by DvirDukhan** [comment]
Hi @flpgrz 
This query is using the `map` data type, that we currently not support. Your `batch` parameter is an array that contains an anonymous `map` (key-value data structure). 

regarding the python API, can you elaborate more? We do support `UNWIND` on 2.0.15 so if you can send the complete code snippet (with the definition of you `batch` parameter) as well as the error you receive. 

Thanks

**Comment by flpgrz** [comment]
Hello @DvirDukhan ,

Thanks for your reply.

Concerning the Python API, my idea was to pass a list of dictionaries (`batch`), which would then be UNWINDed (I'm migrating a script from Neo4J to ReidGraph). So this would be something like:

```
batch = [{'node_name': 'Glucose', 'node_type': 'molecule'}, {'node_name': 'Gluten', 'node_type': 'molecule'}]  # example of batch
cypher_query = 'UNWIND $batch as row ' \
                       'CREATE (n:Node) ' \
                       'SET n += row'
redis_graph.query(cypher_query, batch)  # Error!
```

The thrown error is of course, as you expect a dictionary: 
```
File "...\lib\site-packages\redisgraph\graph.py", line 125, in query
    q = self.build_params_header(params) + q
  File "...\lib\site-packages\redisgraph\graph.py", line 107, in build_params_header
    assert type(params) == dict
AssertionError
```

**Comment by DvirDukhan** [comment]
First, in your query, `batch` is a parameter representing an array of maps. In short, a query with an `UNWIND` clause executes the query logic for each entry in the array, in your case, for each entry in the `batch` array the query creates a new node and sets the properties map of the newly created node to be the current entry value.

The python API expects a query and optional `map` (python's `dict`) of parameters.
In the future, when we support map as data type, your python code should look like
```
batch = [{'node_name': 'Glucose', 'node_type': 'molecule'}, {'node_name': 'Gluten', 'node_type': 'molecule'}]  # example of batch
params = {'batch':batch}
cypher_query = 'UNWIND $batch as row ' \
                       'CREATE (n:Node) ' \
                       'SET n += row'
redis_graph.query(cypher_query, params)
```

The `UNWIND` clause logic is implemented on the RedisGraph server itself. The python client sends the prepared query string and parses the answer.

**Comment by flpgrz** [comment]
Ok, thanks.

I think I can close the issue. UNWINDing a list of dictionaries is not currently possible, but will be supported in the future.

**Comment by flpgrz** [comment]
@DvirDukhan 
In sake of curiosity: as of now, since UNWIND does not support `map`, how would you implement with UNWIND in the Python API a query like:

```
cypher_query = 'UNWIND $batch as row ' \
                               'MATCH (head:Node) WHERE head.id = row.head_id ' \
                               'MATCH (tail:Node) WHERE tail.id = row.tail_id ' \
                               'CREATE (head)-[rel:RELATIONSHIP]->(tail) ' \
                               'SET rel += row.properties'
                tx.run(cypher_query, batch=batch)
```
?

**Comment by DvirDukhan** [comment]
First, let's be more accurate. `map` datatype is not supported in RedisGraph, regardless to the clause (`MATCH`, `UNWIND` etc..)
you can send an array of arrays such as
```
batch = [['Glucose', 'molecule'], ['Gluten', 'molecule']]  # example of batch
params = {'batch':batch}
cypher_query = 'UNWIND $batch as row ' \
                       'CREATE (n:Node {node_name:row[0], node_type:row[1]) ' 
redis_graph.query(cypher_query, params)
```
