### ISSUE TITLE
Support multiple labels

### ISSUE THREAD

**Issue by swilly22** [RedisGraph/RedisGraph#13]
Allow entities to have multiple labels attached to them.

**Comment by gkorland** [comment]
Should also support labels() function e.g.

```
match (r) return distinct labels(r)
```

**Comment by abevoelker** [comment]
I was trying out RedisGraph today and ran into this. Glad to see it's already on a todo list and looking forward to it being implemented at some point.

**Comment by adityaarun** [comment]
Is there any ETA on this feature?

**Comment by swilly22** [comment]
@adityaarun it will be part of the next upcoming version 2.4, it is scheduled to April 2021

**Comment by lorenzovalente** [comment]
any updates on this?

**Comment by swilly22** [comment]
In review
https://github.com/RedisGraph/RedisGraph/pull/1561
