### ISSUE TITLE
[The tip of building on Mac10.15]

### ISSUE THREAD

**Issue by loveJasmine** [RedisGraph/RedisGraph#1307]
if we run make , we can see the error 

clang: error: unsupported option '-fopenmp'

that is on Mac, clang is alias of gcc,

so we use CC=gcc-10 make  //check the right version

but it failed on linking: 

ld: 40991 duplicate symbols for architecture x86_64

so, the workaround is:
run make first, 
DO NOT clean
run CC=gcc-10 make 

it will OK

**Comment by vinyll** [comment]
To rephrase in shorter, copy paste the following:

```sh
make
CC=gcc-10 make
```
