### ISSUE TITLE
Add support for pattern comprehension

### ISSUE THREAD

**Issue by Sceat** [RedisGraph/RedisGraph#1308]
Pattern comprehension is a way to populate a list with the results of an expansion.

```cypher
MATCH (movie:Movie {title:'The Matrix'})
WITH movie, [(movie)<-[:DIRECTED]-(director) | director] as directors
MATCH (movie)<-[:ACTED_IN]-(actor:Person)-[:ACTED_IN]->(other)
...
```

**Comment by FallingSnow** [comment]
This still gonna make 2.4?

**Comment by jeffreylovitz** [comment]
@FallingSnow This is one of the soonest items on our roadmap, so I am hoping so!

**Comment by swilly22** [comment]
pattern comprehension been merged to our `master` branch.
