### ISSUE TITLE
Module fails to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by ntwrkguru** [RedisGraph/RedisGraph#1321]
Environment:
- Ubuntu 18.04 docker container with all stated dependencies installed
- gcc version: `gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`

What happens:
- Build fails with several errors like the one below.

```text
/RedisGraph/src/util/range/unsigned_range.c:127:44: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'uint64_t {aka const long unsigned int}' [-Wformat=]
  else offset += sprintf(buff + offset, "%llu", range->max);
                                         ~~~^   ~~~~~~~~~~
                                         %lu
```

What should happen:
- Module should build. :-)

Full `make` output is in this [gist](https://gist.github.com/ntwrkguru/e4eb57d6d1697d86a440ce3e964ac295).

**Comment by jeffreylovitz** [comment]
hi @ntwrkguru,

Did this compilation actually fail? Those 2 warnings are not errors and shouldn't break the build (though we should fix them, granted).

It looks like your build successfully generated the `redisgraph.so` file.

**Comment by ntwrkguru** [comment]
Hmm... I thought it bailed before it published the lib, but I will check and revert. Thanks for the super-fast reply!

**Comment by ntwrkguru** [comment]
You are correct. It does, in fact, build. Sorry for the false alarm, and thanks again for the fast response.
