### ISSUE TITLE
alternative to set all properties

### ISSUE THREAD

**Issue by odanoburu** [RedisGraph/RedisGraph#1335]
what would be the best alternative to the query below? if I know all properties I can simply break down the SET clause into several (even though this is not very robust), of course.

```
> GRAPH.QUERY g "MATCH (n), (m) SET n = m RETURN n"
(error) RedisGraph does not currently support set all properties
```

is there a timeline for this to be implemented?

**Comment by swilly22** [comment]
Currently I don't see an alternative of performing this operation, on the next version (2.4) the map data-type will be added, this is a first step in that direction.

**Comment by jeffreylovitz** [comment]
To simplify tracking, I'm closing this issue in favor of #943 .
