### ISSUE TITLE
CASE behavior is different between `<>` and `IS NOT NULL`

### ISSUE THREAD

**Issue by Sceat** [RedisGraph/RedisGraph#1343]
Not sure if this behavior is expected in cypher, but doing

```
MATCH (i:Intervention)
  WHERE i.uuid = 'x'
  OPTIONAL MATCH (i)-[:ON]->(on_property:Property)
  OPTIONAL MATCH (i)-[:ON]->(:Parcel)<--(parent_property:Property)
  RETURN CASE
    WHEN on_property IS NOT NULL 
    THEN on_property
    ELSE parent_property 
    END AS property
```

returns nothing, while doing

```
MATCH (i:Intervention)
  WHERE i.uuid = 'x'
  OPTIONAL MATCH (i)-[:ON]->(on_property:Property)
  OPTIONAL MATCH (i)-[:ON]->(:Parcel)<--(parent_property:Property)
  RETURN CASE
    WHEN on_property <> NULL 
    THEN on_property
    ELSE parent_property 
    END AS property
```

returns the node correctly.

So using `IS NOT NULL` doesn't work while using `<> NULL` correctly works

**Comment by swilly22** [comment]
```
OPTIONAL MATCH (a) RETURN a is not NULL
```
If `a` exists `true` is returned, otherwise `false` is returned.

```
OPTIONAL MATCH (a) RETURN a <> NULL
```
In this case comparing NULL to anything will always return NULL.

**Comment by Sceat** [comment]
in my case `on_property` is `NULL` so
```
  RETURN CASE
    WHEN on_property IS NOT NULL 
    THEN on_property
    ELSE parent_property 
    END AS property
```
should return the `parent_property` node but instead i get no result, while on the second query i get the node. Does the case statement use `false` as a valid value ?

**Comment by swilly22** [comment]
Indeed `false` seems like a valid value, although Neo4J is behaving differently, from Neo's doc:

> The predicates are evaluated in order until a true value is found,

We would have to fix this, thank you!
