### ISSUE TITLE
`WHERE` after a `WITH` clause doesn't filter execution [question]

### ISSUE THREAD

**Issue by Sceat** [RedisGraph/RedisGraph#1346]
I though using a `WITH` could allow me to filter executions but it does not

```
CREATE (:Foo)
```

```
MATCH (a)
WITH a
OPTIONAL MATCH (b)
WITH a, b
WHERE b.bar = true
RETURN a, b
```

I expected nothing to be returned as the `WHERE` should never be valid

**Comment by swilly22** [comment]
We would have to check the semantics here, see how early the filter can be applied, as currently it is positioned right after matching `b` see execution plan:
```
127.0.0.1:6379> GRAPH.EXPLAIN g "MATCH (a) WITH a OPTIONAL MATCH (b) WITH a,b WHERE b.bar = true RETURN a,b"
 1) "Results"
 2) "    Project"
 3) "        Project"
 4) "            Apply"
 5) "                Project"
 6) "                    All Node Scan | (a)"
 7) "                Optional"
 8) "                    Filter"
 9) "                        All Node Scan | (b)"
10) "                            Argument"
```

**Comment by Sceat** [comment]
Is there some alternative ways to force the filtering ?

**Comment by jeffreylovitz** [comment]
Hi @Sceat,

We've written a fix for this that should be merged in the next few days!

To force the filtering right now, you can use this really silly workaround:
```
MATCH (a)
WITH a
OPTIONAL MATCH (b)
WITH a, b AS x
WHERE x.bar = true
RETURN a, x
```

**Comment by Sceat** [comment]
after pulling latest `edge` i get this error on multiple queries, currently tring to find which one is causing it but seems to happen on many

```
ReplyError: Received 3 arguments to function 'path_filter', expected at most 0
```

**Comment by swilly22** [comment]
@Sceat probably filters such as: `...WHERE (a)-[]->()...`

**Comment by Sceat** [comment]
managed to reproduce

```
MATCH (u)
WITH u
OPTIONAL MATCH ()--()
WHERE (u)--()
RETURN true
```

now i'll try to setup some datas and create an issue
