### ISSUE TITLE
[`edge`] Invalid filter statement 

### ISSUE THREAD

**Issue by Sceat** [RedisGraph/RedisGraph#1350]
I sometimes get an `Invalid filter statement` when using this query, yet it is not always failing

### Query

```
MATCH (i:Intervention)-[:HAS_PROVIDER]->(pro:Group)
WHERE pro.uuid = 'Group:6c70e352-362f-4a84-8b4a-1f79efd01445'
AND (pro)-[:STARTED]->(i)
AND NOT (:Group { type: 'MANAGER' })-[:CANCELED]->(i)
AND NOT (pro)-[:CANCELED]->(i)
WITH DISTINCT i, pro
OPTIONAL MATCH (pro)-[:PATCHED]->(quote:InterventionPatch {_type:'quote'})-->(i)
WITH DISTINCT i, quote
WHERE NOT ()-[:PAYED_BILL]->(quote) AND
OR NOT ()-[:DECLINED_QUOTE]->(quote)
WITH i
OPTIONAL MATCH (i)-[:ON]->(on_property:Property)
OPTIONAL MATCH (i)-[:ON]->(on_parcel:Parcel)<--(parent_property:Property)
WITH DISTINCT i, on_property, parent_property
WHERE on_property.uuid = 'Property:e34b3851-8fb2-4ec4-b47e-af76b2d57f64'
OR parent_property.uuid = 'Property:e34b3851-8fb2-4ec4-b47e-af76b2d57f64'
RETURN DISTINCT i AS intervention
```

### Dump
https://redisgraph-dump-invalid-filter.s3.eu-central-1.amazonaws.com/dump.rdb

### Profile

<details>
<summary>trace</summary>

<pre>
>> graph.profile default "MATCH (i:Intervention)-[:HAS_PROVIDER]->(pro:Group) WHERE pro.uuid = 'Group:6c70e352-362f-4a84-8b4a-1f79efd01445' AND (pro)-[:STARTED]->(i) AND NOT (:Group { type: 'MANAGER' })-[:CANCELED]->(i) AND NOT (pro)-[:CANCELED]->(i) WITH DISTINCT i, pro OPTIONAL MATCH (pro)-[:PATCHED]->(quote:InterventionPatch {_type:'quote'})-->(i) WITH DISTINCT i, quote WHERE NOT ()-[:PAYED_BILL]->(quote) AND OR NOT ()-[:DECLINED_QUOTE]->(quote) WITH i OPTIONAL MATCH (i)-[:ON]->(on_property:Property) OPTIONAL MATCH (i)-[:ON]->(on_parcel:Parcel)<--(parent_property:Property) WITH DISTINCT i, on_property, parent_property WHERE on_property.uuid = 'Property:e34b3851-8fb2-4ec4-b47e-af76b2d57f64' OR parent_property.uuid = 'Property:e34b3851-8fb2-4ec4-b47e-af76b2d57f64' RETURN DISTINCT i AS intervention"
(error) Invalid filter statement.

>> graph.profile default "MATCH (i:Intervention)-[:HAS_PROVIDER]->(pro:Group) WHERE pro.uuid = 'Group:6c70e352-362f-4a84-8b4a-1f79efd01445' AND (pro)-[:STARTED]->(i) AND NOT (:Group { type: 'MANAGER' })-[:CANCELED]->(i) AND NOT (pro)-[:CANCELED]->(i) WITH DISTINCT i, pro OPTIONAL MATCH (pro)-[:PATCHED]->(quote:InterventionPatch {_type:'quote'})-->(i) WITH DISTINCT i, quote WHERE NOT ()-[:PAYED_BILL]->(quote) AND OR NOT ()-[:DECLINED_QUOTE]->(quote) WITH i OPTIONAL MATCH (i)-[:ON]->(on_property:Property) OPTIONAL MATCH (i)-[:ON]->(on_parcel:Parcel)<--(parent_property:Property) WITH DISTINCT i, on_property, parent_property WHERE on_property.uuid = 'Property:e34b3851-8fb2-4ec4-b47e-af76b2d57f64' OR parent_property.uuid = 'Property:e34b3851-8fb2-4ec4-b47e-af76b2d57f64' RETURN DISTINCT i AS intervention"
 1) "Results | Records produced: 1, Execution time: 0.000743 ms"
 2) "    Distinct | Records produced: 1, Execution time: 0.000613 ms"
 3) "        Project | Records produced: 1, Execution time: 0.000643 ms"
 4) "            Distinct | Records produced: 1, Execution time: 0.001354 ms"
 5) "                Project | Records produced: 1, Execution time: 0.001307 ms"
 6) "                    Filter | Records produced: 1, Execution time: 0.002033 ms"
 7) "                        Apply | Records produced: 1, Execution time: 0.001360 ms"
 8) "                            Apply | Records produced: 1, Execution time: 0.003748 ms"
 9) "                                Project | Records produced: 1, Execution time: 0.000589 ms"
10) "                                    Distinct | Records produced: 1, Execution time: 0.001229 ms"
11) "                                        Project | Records produced: 1, Execution time: 0.001250 ms"
12) "                                            Apply | Records produced: 1, Execution time: 0.002058 ms"
13) "                                                Distinct | Records produced: 1, Execution time: 0.009513 ms"
14) "                                                    Project | Records produced: 1, Execution time: 0.001199 ms"
15) "                                                        Filter | Records produced: 1, Execution time: 0.001513 ms"
16) "                                                            Semi Apply | Records produced: 1, Execution time: 0.005494 ms"
17) "                                                                Anti Semi Apply | Records produced: 2, Execution time: 0.002228 ms"
18) "                                                                    Conditional Traverse | (i:Intervention)->(pro:Group) | Records produced: 4, Execution time: 0.036546 ms"
19) "                                                                        Anti Semi Apply | Records produced: 4, Execution time: 0.006814 ms"
20) "                                                                            Node By Label Scan | (i:Intervention) | Records produced: 9, Execution time: 0.002976 ms"
21) "                                                                            Filter | Records produced: 5, Execution time: 0.006127 ms"
22) "                                                                                Conditional Traverse | (anon_2:Group)->(anon_2:Group) | Records produced: 7, Execution time: 0.317514 ms"
23) "                                                                                    Argument | Records produced: 9, Execution time: 0.000974 ms"
24) "                                                                    Expand Into | (pro:Group)->(i:Intervention) | Records produced: 2, Execution time: 0.075401 ms"
25) "                                                                        Argument | Records produced: 4, Execution time: 0.000469 ms"
26) "                                                                Expand Into | (pro:Group)->(i:Intervention) | Records produced: 1, Execution time: 0.040439 ms"
27) "                                                                    Argument | Records produced: 2, Execution time: 0.000185 ms"
28) "                                                Optional | Records produced: 1, Execution time: 0.000321 ms"
29) "                                                    Expand Into | (quote:InterventionPatch)->(i) | Records produced: 1, Execution time: 0.169499 ms"
30) "                                                        Filter | Records produced: 1, Execution time: 0.002554 ms"
31) "                                                            Conditional Traverse | (pro)->(quote:InterventionPatch) | Records produced: 5, Execution time: 0.035080 ms"
32) "                                                                Argument | Records produced: 1, Execution time: 0.000169 ms"
33) "                                Optional | Records produced: 1, Execution time: 0.000252 ms"
34) "                                    Conditional Traverse | (i)->(on_property:Property) | Records produced: 1, Execution time: 0.034432 ms"
35) "                                        Argument | Records produced: 1, Execution time: 0.000106 ms"
36) "                            Optional | Records produced: 1, Execution time: 0.000483 ms"
37) "                                Conditional Traverse | (i)->(parent_property:Property) | Records produced: 0, Execution time: 0.091170 ms"
38) "                                    Argument | Records produced: 1, Execution time: 0.000212 ms"
</pre>

</details>

**Comment by jeffreylovitz** [comment]
Hi @Sceat,

There's an error in your query at:
```
WHERE NOT ()-[:PAYED_BILL]->(quote) AND
OR NOT ()-[:DECLINED_QUOTE]->(quote)
```
You should use either AND or OR, but not both.

This should resolve the problem! Incidentally, if the condition you want is AND, you can collapse these conditions into:
```
WHERE NOT ()-[:PAYED_BILL|DECLINED_QUOTE]->(quote)
```

**Comment by Sceat** [comment]
oh damn, missed this one thx
