### ISSUE TITLE
MERGE edge after DELETE slower than DELETE and then MERGE

### ISSUE THREAD

**Issue by haljin** [RedisGraph/RedisGraph#1353]
Hi,

Given the graph here: https://gist.github.com/haljin/534410db6a72a53c2f551c60d0b0c546/

I am trying to make a query that deletes all `[:at]` relationships of the node and then inserts a set of new ones in an atomic query.

When I query 

```
MATCH (d:sometype {id: 'd5047'}) 
  OPTIONAL MATCH (d)-[a:at]->(:location) DELETE a 
  MERGE (dst:location {id: 'l60'}) 
  MERGE (d)-[:at]->(dst)
```

I get the following profile
```
Merge | Records produced: 1, Execution time: 0.167515 ms,
      Merge | Records produced: 1, Execution time: 8.712046 ms,
          Delete | Records produced: 1, Execution time: 0.003676 ms,
              Apply | Records produced: 1, Execution time: 0.011584 ms,
                  Index Scan | (d:sometype) | Records produced: 1, Execution time: 0.027212 ms,
                  Optional | Records produced: 1, Execution time: 0.001177 ms,
                      Conditional Traverse | Records produced: 1, Execution time: 0.486727 ms,
                          Argument | Records produced: 1, Execution time: 0.000653 ms,
          Index Scan | (dst:location) | Records produced: 1, Execution time: 0.013433 ms,
              Argument | Records produced: 1, Execution time: 0.000431 ms,
          MergeCreate | Records produced: 0, Execution time: 0.000000 ms,
              Argument | Records produced: 0, Execution time: 0.000000 ms,
      Expand Into | Records produced: 0, Execution time: 0.082230 ms,
          Argument | Records produced: 1, Execution time: 0.000472 ms,
      MergeCreate | Records produced: 1, Execution time: 0.007713 ms,
          Argument | Records produced: 1, Execution time: 0.000162 ms
```

But if I do the DELETE and MERGE in opposite order:

```
MATCH (d:sometype {id: 'd5047'}) 
 MERGE (dst:location {id: 'l65'}) MERGE (d)-[a:at]->(dst) 
 WITH d, a
 OPTIONAL MATCH (d)-[r:at]->() WHERE r <> a DELETE r
```
I get
```
Delete | Records produced: 1, Execution time: 0.001434 ms,
      Apply | Records produced: 1, Execution time: 0.011356 ms,
          Project | Records produced: 1, Execution time: 0.006478 ms,
              Merge | Records produced: 1, Execution time: 0.220162 ms,
                  Merge | Records produced: 1, Execution time: 0.014363 ms,
                      Index Scan | (d:sometype) | Records produced: 1, Execution time: 0.024270 ms,
                      Index Scan | (dst:location) | Records produced: 1, Execution time: 0.009633 ms,
                          Argument | Records produced: 1, Execution time: 0.000383 ms,
                      MergeCreate | Records produced: 0, Execution time: 0.000000 ms,
                          Argument | Records produced: 0, Execution time: 0.000000 ms,
                  Expand Into | Records produced: 0, Execution time: 0.362474 ms,
                      Argument | Records produced: 1, Execution time: 0.000752 ms,
                  MergeCreate | Records produced: 1, Execution time: 0.006642 ms,
                      Argument | Records produced: 1, Execution time: 0.000167 ms,
          Optional | Records produced: 1, Execution time: 0.001070 ms,
              Filter | Records produced: 1, Execution time: 0.004522 ms,
                  Conditional Traverse | (d)-[r:at]->(anon_0) | Records produced: 2, Execution time: 0.155673 ms,
                      Argument | Records produced: 1, Execution time: 0.000526 ms
```

This seems to be much more efficient and does not have any single step that takes >1ms. The Merge is a _lot_ faster. The first query however is much more concise and easier to write. For the second one to work if there's more than one `:at` I'd like to create I have to add it to the `WHERE` with an `AND`. e.g.:

```
Redix.command(c, ["GRAPH.PROFILE", "test_graph", 
"MATCH (d:sometype {id: 'd5047'}) 
 MERGE (dst:location {id: 'l81'}) MERGE (d)-[a:at]->(dst) 
 MERGE (dst2:location {id: 'l82'}) MERGE (d)-[b:at]->(dst2) 
 WITH d, a, b
 OPTIONAL MATCH (d)-[r:at]->() WHERE r <> a AND r <> b DELETE r
"])
```

 Is this an expected behavior and my query is wrong or is that a bug somewhere?

**Comment by swilly22** [comment]
Hi @haljin,
I believe the bottleneck you're experiencing is coming from our requirement of synchronising our internal data-structures (matrices)

In your first query there's a sync right after the deletion during the first merge,
If you were to run the second query twice you'll see a similar delay in the first `Filter` operation, as a result of the previous deletion.

As such I would recommend sticking with the first query as it is much more readable, we're currently working on a solution which will reduce the total sync time.

**Comment by haljin** [comment]
Ah, that explains it. When I moved `DELETE` to a separate query ran beforehand the total execution of both queries didn't really change and I was wondering what was up with that. Still, it seems in our particular use case the second query seems to have improved things in general, maybe due to the particular sequence of queries that we run, but I'll benchmark a bit more under load to make sure. Thanks for the answer!

Do you have another issue to track the solution? I'd like to subscribe to it to know when something changes and I should pull the new version. :)

**Comment by swilly22** [comment]
We can leave this issue open and you can track it.
May I ask what is your use case?

**Comment by haljin** [comment]
We synchronize an external data source with RedisGraph, running the above query (and some others) at a rate of about 150/sec. Sometimes there is no graph in Redis, and the upload of the data is very quick, however if it happens when the graph already exists it becomes much slower, since now the `DELETE` clause actually deletes something as the `OPTIONAL MATCH` hits. I

However after reloading the new query it seems the speed is always the same, no matter if the graph is there or not. I suppose it could be because each execution of the query pertains to a different node/edge? 

Here's a graph, the query we're talking about is illustrated in orange. The first bar comes from synchronizing an empty graph. The second one is an existing graph. At 16:10 I have reloaded our codeto use the DELETE-after-MERGE query instead and it instantly dropped in execution time. 

![image](https://user-images.githubusercontent.com/2393962/94364815-5be51400-00cc-11eb-916f-d3614e7a0cf5.png)

But looking at your answer I need to make sure no other query then shot up due the synchronization, I'll have to run some more tests tomorrow.

**Comment by swilly22** [comment]
should be resolved now by delta matrix
