### ISSUE TITLE
Several tests fail with "Unhandled exception: No support for nested multi bulk replies with depth > 7"

### ISSUE THREAD

**Issue by SteffenBauer** [RedisGraph/RedisGraph#1370]
Trying to compile RedisGraph on a Jetson Nano board. (`ARMv8 Processor rev 1 (v8l)` as of `/proc/cpuinfo`)

Compilation of `redisgraph.so` works flawlessly, but some tests fail.

Occurs with both RedisGraph version tags `2.2.6` and `2.0.21`.

Environment:

`redis 6.0.8` (also locally compiled, with all tests running successfully)
`Python 2.7.17`
`Python 3.6.9`

Installed python packages indicated in `tests/requirements.txt` (installed for both Python2 and Python3 with pip2 / pip3)
- `redis == 3.5.3`
- `redisgraph == 2.1.5`
- `click == 7.1.2`
- `behave == 1.2.6`

`requirements.txt` in RedisGraph `2.0.21` demands python package `redis==2.10.5`, but tests fail the same way when installing this package.

I build RedisGraph with these commands in a freshly updated local git repository:
```
> git checkout tags/v2.2.6
> git submodule sync --recursive 
> git submodule update --init --recursive 
> make
> make test
```

The first tests in `make test` run successfully, until I get an exception in `test_path:testPath`:
```
test_path:testPath
	test_path:testPath.test_bi_directional_path
	[ERROR]
	Unhandled exception: No support for nested multi bulk replies with depth > 7
Traceback (most recent call last):
  File "/home/steffen/.local/lib/python2.7/site-packages/RLTest/__main__.py", line 511, in _runTest
    fn()
  File "/home/steffen/Workspace/Buildspace/RedisGraph/tests/flow/test_path.py", line 111, in test_bi_directional_path
    self._assert_resultset_and_expected_mutually_included(redis_graph.query(query), query_info)
  File "/home/steffen/.local/lib/python2.7/site-packages/redisgraph/graph.py", line 132, in query
    response = self.redis_con.execute_command(*command)
  File "/home/steffen/.local/lib/python2.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/steffen/.local/lib/python2.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/steffen/.local/lib/python2.7/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/steffen/.local/lib/python2.7/site-packages/redis/connection.py", line 471, in read_response
    response = self._reader.gets()
InvalidResponse: No support for nested multi bulk replies with depth > 7
```

In total 9 tests fail, all with the same "No support for nested multi bulk replies with depth > 7":

```
Failed Tests Summary:
	test_path:testPath.test_bi_directional_path
		Exception raised during test execution. See logs
	test_path:testPath.test_bi_directional_path_functions
		Exception raised during test execution. See logs
	test_path:testPath.test_path_comparison
		Exception raised during test execution. See logs
	test_path:testPath.test_simple_path
		Exception raised during test execution. See logs
	test_path:testPath.test_variable_length_path
		Exception raised during test execution. See logs
	test_path:testPath.test_zero_length_path
		Exception raised during test execution. See logs
	test_comprehension_functions:testComprehensionFunctions.test06_list_comprehension_on_graph_entities
		Exception raised during test execution. See logs
	test_distinct:testDistinct.test_distinct_path
		Exception raised during test execution. See logs
	test_prev_rdb_decode:test_prev_rdb_decode.test_v6_decode
		Exception raised during test execution. See logs
Makefile:6: recipe for target 'test' failed
```

**Comment by jeffreylovitz** [comment]
Hi @SteffenBauer,

That exception was hard-coded into earlier versions of [Hiredis](https://github.com/redis/hiredis). That restriction has since been lifted and nested array depth is now unlimited, but most libraries that depend on Hiredis (like the Python `redis` package) have not updated their internal version.

The consequence is that deeply-nested result sets (particularly returning full paths) can trigger this issue at times, though it is not a common issue.

I assume that its appearance in the test suite is due to some difference in ARM compilation, but am not sure why! I do not believe this should affect your user experience, however.

**Comment by swilly22** [comment]
Please see:
https://github.com/RedisGraph/redisgraph-py/issues/86
