### ISSUE TITLE
[question] Are cellTypes still used in `edge` redisgraph ?

### ISSUE THREAD

**Issue by Sceat** [RedisGraph/RedisGraph#1387]
My coverage on [hydre/rgraph](https://github.com/HydreIO/rgraph) is not passing anymore as it is unable to get a result different from `1` for the cell type

In redisgraph.js here :point_down: there is still 4 values :thinking: 

https://github.com/RedisGraph/redisgraph.js/blob/c2b429fdffb7d8faa032e2c7ecf38c072a2a926d/src/resultSet.js#L9

```js
const ResultSetColumnTypes = {
	COLUMN_UNKNOWN: 0,
	COLUMN_SCALAR: 1,
	COLUMN_NODE: 2,
	COLUMN_RELATION: 3,
};
```

### i logged each sequence return cell type
![image](https://user-images.githubusercontent.com/11330271/96586962-feff0700-12e1-11eb-9faf-66ee37e4fc5e.png)

**Comment by swilly22** [comment]
Hi @Sceat,
To support returning full entities (node/edge) under a "multi-type" column (one which might change its type from one row to another)
we have to extend `COLUMN_SCALAR` to describe both scalar primitives e.g. numbers, strings, etc` but to also represent nodes and edges, see [redisgraph-py result-set parser](https://github.com/RedisGraph/redisgraph-py/blob/master/redisgraph/query_result.py)
specifically [parse_scalar](https://github.com/RedisGraph/redisgraph-py/blob/5680907ab67ba010f86f5c99342635cd052ce66a/redisgraph/query_result.py#L138)

**Comment by Sceat** [comment]
ok i see so i can safely delete them in the lib.

`# Unused as of RedisGraph v2.1.0, retained for backwards compatibility.`
