### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mofywong** [RedisGraph/RedisGraph#1390]
test below:
restart redis-server
pid:13380
cat /proc/13380/status| grep RSS
VmRSS:      7868 kB

run redis-cli
create node:      GRAPH.QUERY rules "CREATE (d:Dev{name:'node'}) return d"
set value:            GRAPH.QUERY rules "MATCH (d:Dev {name:'node'}) set d.v1=1,d.v2=2,d.v3=3,d.v4=4"
query node:        GRAPH.QUERY rules "MATCH (d:Dev {name:'node'}) return d"

current VmRss is 8980 kB
manual set value by command "GRAPH.QUERY rules "MATCH (d:Dev {name:'node'}) set d.v1=1,d.v2=2,d.v3=3,d.v4=4"" in redis-cli with 100 times.
after 100 times the VmRss is 8992kB

next I use python script test 10000 times，the VmRss increase to 12672 kB。
python result
![image](https://user-images.githubusercontent.com/32129866/96686892-b878dd80-13b1-11eb-8ba6-72983da3656d.png)

query node info
![image](https://user-images.githubusercontent.com/32129866/96686987-d9d9c980-13b1-11eb-8021-62ae61a9a194.png)

memory
![image](https://user-images.githubusercontent.com/32129866/96687030-e8c07c00-13b1-11eb-9c28-902551adafea.png)
![image](https://user-images.githubusercontent.com/32129866/96687077-f6760180-13b1-11eb-92a5-c49238d0d2c2.png)
![image](https://user-images.githubusercontent.com/32129866/96687119-068de100-13b2-11eb-978c-fa9f62458872.png)

**Comment by jeffreylovitz** [comment]
hi @mofywong,

RedisGraph maintains some internal buffers that may result in initial RSS growth, as does Redis itself (in its jemalloc allocator pools). Over time, memory usage will remain stable, and there are no leaks in your sample query.

I reproduced your test on Redis 6.0.7 and the current HEAD of RedisGraph's master, running 1 million MATCH...SET queries with the command:
```
redis-benchmark -c 1 -n 1000000 GRAPH.QUERY "rules" "MATCH (d:Dev {name:'node'}) set d.v1=rand(),d.v2=rand(),d.v3=rand(),d.v4=rand()"
```
Prior to starting this command, the state of the server is:
```
$ cat /proc/67533/status
Name:   redis-server
[...]
VmPeak:   151804 kB
VmSize:   151804 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:      9936 kB
VmRSS:      9936 kB
RssAnon:            1940 kB
RssFile:            7996 kB
RssShmem:              0 kB
VmData:   128228 kB
VmStk:       136 kB
VmExe:      1500 kB
VmLib:      9064 kB
VmPTE:       152 kB
VmSwap:        0 kB
```
After 1 million updates:
```
[...]
VmPeak:   903448 kB
VmSize:   837912 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:     11916 kB
VmRSS:     11916 kB
RssAnon:            2504 kB
RssFile:            9412 kB
RssShmem:              0 kB
VmData:   241224 kB
VmStk:       136 kB
VmExe:      1500 kB
VmLib:      9064 kB
VmPTE:       328 kB
VmSwap:        0 kB
```
I graphed the VmRSS usage over time as follows:
![Screenshot from 2020-10-23 13-02-20](https://user-images.githubusercontent.com/6090852/97033353-36172780-1531-11eb-8f9d-fa979468a08a.png)

**Comment by gkorland** [comment]
@mofywong do you need anymore help?

**Comment by mofywong** [comment]
> @mofywong do you need anymore help?

Sorry, I have nothing need you help now, but I busy in work this time, so have no time to verify. I guess it's the version issue. 
I close this first and reply you after verify this issue.
Thank you for you help!
