### ISSUE TITLE
Received 2 arguments to function 'path_filter', expected at most 0

### ISSUE THREAD

**Issue by Sceat** [RedisGraph/RedisGraph#1391]
After the recent merge of #1361 i came accross this problem

```
CREATE (u)
```

```
MATCH (u)
WITH u
OPTIONAL MATCH ()--()
WHERE (u)--()
RETURN true
```
`Received 2 arguments to function 'path_filter', expected at most 0`

_Originally posted by @Sceat in https://github.com/RedisGraph/RedisGraph/issues/1346#issuecomment-713550801_

**Comment by swilly22** [comment]
Thanks @Sceat, we'll look into it ASAP.

**Comment by swilly22** [comment]
@Sceat fix just merged to the `master` branch, should be available on the `edge` docker image shortly ~1h, could you please confirm?

**Comment by Sceat** [comment]
Seems fine on my end, thx well done :+1:
