### ISSUE TITLE
(error) node alias error when using full text search

### ISSUE THREAD

**Issue by avisangray** [RedisGraph/RedisGraph#1405]
hi
i'm using full text search on the recommended docker container however a query as mentioned in quick start as
CALL db.idx.fulltext.queryNodes('Movie', 'Book') YIELD node AS m
WHERE m.genre = 'Adventure'
RETURN m ORDER BY m.rating
returns
(error) node not defined 

while same query as
CALL db.idx.fulltext.queryNodes('Movie', 'Book') YIELD node AS m
RETURN m.rating works fine

**Comment by swilly22** [comment]
Hi @avisangray thank you for reporting!
As a temporary workaround, you can omit `"AS"` and address `node`

```
CALL db.idx.fulltext.queryNodes('Movie', 'Book') YIELD node WHERE node.genre = 'Adventure' RETURN node ORDER BY node.rating
```
