### ISSUE TITLE
Sidy enterprise testimonial

### ISSUE THREAD

**Issue by Sceat** [RedisGraph/RedisGraph#1411]
@swilly22 

We run Redisgraph since some months now and here is our short testimonial at [Sidy.fr](https://sidy.fr)

> The most powerful query language combined with the fastest in memory database, Redisgraph is now fully integrated as the one and only database at Sidy. Our complex dataset is constantly evolving and we need this incredible flexibility to stay ahead on the market. The representation of real estate data takes many forms, the only limitation is now our creativity.
--
Cyril Morlet - CTO Sidy

*(issue can be closed when read)*

**Comment by gkorland** [comment]
@Sceat thanks for the kind word!!!
