### ISSUE TITLE
Change asserts to RedisModule_Assert

### ISSUE THREAD

**Issue by MeirShpilraien** [RedisGraph/RedisGraph#1422]
The reason for this is that an assert exists without a crash report using sigabrt (and prints the assert failure message to stdout which is not always available). Using RedisModule_Assert, the entire crash report will be printed to the log file. Notice that this fix https://github.com/redis/redis/commit/f210e197f3b9d0b4a81c6c354296da8f1ddad513 will make sure the crash report will be output even on sigabrt but it will on be available on future Redis versions.

**Comment by swilly22** [comment]
Switch from #define ASSERT assert to #define ASSERT RedisModule_Assert

**Comment by MeirShpilraien** [comment]
RedisModule_Assert is available since Redis 6.0.0, if you do not intend to support an older version then this so yes, otherwise you will need to check if RedisModule_Assert is not NULL, if its NULL I would suggest to print the failure manually to the log and exists with segfault to get a full crash report.
