### ISSUE TITLE
Size of a graph

### ISSUE THREAD

**Issue by banuAndrei99** [RedisGraph/RedisGraph#1423]
I am running benchmarks in order to decide what database to use in a production environment and I came across redisgraph which I really like so far, but I can't seem to find the size of my graph after I added a few millions of nodes and edges.
I am doing:
1. `docker run -p 6379:6379 -it --rm redislabs/redisgraph`
2. connect to this redis, create a graph, add a few million nodes and edges
3. run some queries
And then I want to see how much storage does it need(the size in bytes or any human readable format of my whole graph) and I can't seem to find how to do this.
I don't really wanna do the size estimation calculator because my data is extremely variable.

**Comment by swilly22** [comment]
Hi, try running [Redis `info memory` command](https://redis.io/commands/info), see `used_memory_human`.

**Comment by banuAndrei99** [comment]
Thanks, that solves the issue :D
