### ISSUE TITLE
Matching both nodes and edges with a single query

### ISSUE THREAD

**Issue by banuAndrei99** [RedisGraph/RedisGraph#1433]
In my use case, the edges have quite a lot of properties and hold important information about some relationships.
I want to fetch all the nodes and edges which have a specific property. Currently I do this in the following way:
Query for nodes: ```MATCH (obj) WHERE obj.type = 'requested_type' RETURN obj```
Query for edges: ```MATCH ()-[obj]->() WHERE obj.type = 'requested_type' RETURN obj```
My WHERE clause is way more complex than this and it gets built from user input, but the one above illustrates the idea pretty well.
Then I just merge the result from both the queries and return it, which worked fine for a while, but my database has gotten bigger and pagination should be supported, which seems quite complicated to do on 2 queries on the same time.
Is there any way to query for both nodes and edges within a single query? I want to get all the object from my graph(nodes and edges) which have the property type set to "requested_type" for example.

**Comment by swilly22** [comment]
There might be several ways to combine your results:

Using the WITH clause
```
MATCH (n) WHERE n.type = 'requested_type' WITH n AS node
MATCH ()-[edge]->() WHERE edge.type = 'requested_type' RETURN node, edge
```

Using the UNION clause
```
MATCH (obj)
WHERE obj.type = 'requested_type'
RETURN obj
UNION 
MATCH ()-[obj]->()
WHERE obj.type = 'requested_type'
RETURN obj
```

**Comment by swilly22** [comment]
May I ask what is your use case?

**Comment by banuAndrei99** [comment]
> May I ask what is your use case?

We are working on an exchange protocol, can't really say more than that regarding our data itself... but I can say the following:

I will use the word `object` to describe a database element, either node or edge.
User goes: "I want all the objects from your database with type "xyz"
Then the users analyses those objects and may do some additional queries like: "objects O1, O2, O3 seemed weird, give me all the nodes directly connected to them"
Regarding the solution you proposed, under the hood, both of them 2 the same thing? Or is one faster/recommended?
I'd personally go for the first one due to the ease of pagination on a single return, but I'd like to ask:
If my query matches 1k nodes and 500 edges and I use  `LIMIT 100` on it will i get 100 nodes or mixed objects?

**Comment by swilly22** [comment]
Sorry I've just realised something, in the first suggested version, because there's no connection between the matched node and the matched edge, the query will return the same set of edges for each found node. (probably not what you want)

As such I'll recommend using the `UNION` version, you can specify different `SKIP` and `LIMIT` on each of the RETURN clauses
`MATCH (n) RETURN n SKIP 1 LIMIT 1 UNION MATCH (n) RETURN n SKIP 4 LIMIT 2`

**Comment by banuAndrei99** [comment]
Thanks for fast responses :D, that works for me; even if implementing pagination on that won't be the easiest thing, it is doable and does the job
