### ISSUE TITLE
Local persistence 

### ISSUE THREAD

**Issue by banuAndrei99** [RedisGraph/RedisGraph#1438]
Sorry if this question is dumb, but I'm quite new to redisgraph and redis in general: I want to assure database persistence and don't know how to do that.
Right now I'm running redisgraph in a docker so clearly there is no persistence there, but there might be the case that I will take it to production eventually and I'm not sure how I am supposed to do that. I've seen that there exists Redis Enterprise which let you configure clusters in the cloud, but that might not be possible for me(the data I'm working with is quite sensitive and should not leave our infrastructure). Ideally I would want to deploy the database myself in my organization's infrastructure. Is this possible?

**Comment by swilly22** [comment]
Defiantly possible, see [here](https://redis.io/topics/persistence)

**Comment by banuAndrei99** [comment]
As always, thanks for a fast response Roi
Have a nice one
