### ISSUE TITLE
Crash on self-referential property assignment

### ISSUE THREAD

**Issue by jeffreylovitz** [RedisGraph/RedisGraph#1443]
The following query causes a server crash:
```
CREATE (node_0:label4{prop5:node_0.prop2}) SET node_0.prop2 = 5
```
Ideally, we would emit an error on the CREATE-internal access to `node_0`, but at bare minimum this should not crash.

**Comment by swilly22** [comment]
```
GRAPH.QUERY g "CREATE (node_0:label4{prop5:node_0.prop2}) SET node_0.prop2 = 5"
(error) Attempted to access undefined property
```

**Comment by swilly22** [comment]
@jeffreylovitz do you know which PR resolved this issue?
Do we have a test(s) covering this "usecase" ?

**Comment by jeffreylovitz** [comment]
This was resolved by https://github.com/RedisGraph/RedisGraph/pull/1495.
This PR introduced a test on:
```
CREATE (a:L {v: a.v})
```
Which I believe is the same case as the initial issue depicts.
