### ISSUE TITLE
Remove GraphBlas gcc 7 hard requirement

### ISSUE THREAD

**Issue by jobs-git** [RedisGraph/RedisGraph#1445]

**Comment by jeffreylovitz** [comment]
@jobs-git If I recall correctly, GCC 7 _is_ a hard requirement for GraphBLAS compilation. Do you have reason to think that's incorrect?

**Comment by jobs-git** [comment]
The requirement reduces the compatibility of RedisGraph on older linuxes. For example, CentOS 7 is on gcc 4.9 while debian 9 is on gcc 6.3.

Unless GraphBLAS uses syscalls that are ONLY available on 4.x-up else it should not require advance GCC versions.

**Comment by jeffreylovitz** [comment]
GraphBLAS makes use of Generic and RedisGraph uses atomics, both of which I believe require newer GCC versions. This condition of the CMake target was not modified by the RedisGraph team, so I'm inclined to defer to the default requirement.

**Comment by swilly22** [comment]
From GraphBLAS CMakeLists.txt file:

```CMake
if ( CMAKE_C_COMPILER_VERSION VERSION_LESS 4.9 )
    message ( FATAL_ERROR "gcc version must be at least 4.9" )
```
