### ISSUE TITLE
Can't use `all` predicate in conjunction with other conditions?

### ISSUE THREAD

**Issue by skieffer** [RedisGraph/RedisGraph#1447]
Hi, and thanks for your work! I'm loving RedisGraph as a lightweight alternative to Neo4j.

I'm having a very weird error where the `all()` predicate just seems to stop working as soon as I `AND` it with any other condition. I consulted [the docs](https://oss.redislabs.com/redisgraph/commands/#existential-comprehension-functions) on `all()` but didn't find anything about this.

I'm using the `redislabs/redisgraph:2.2.8` Docker image.

Here's an example of the problem:

We build this graph with weighted edges:

                 1        2
             /------>()------>(name: A, color: red)
            /
           /     1        2
    (start)--------->()------>(name: B, color: blue)
           \
            \
             \------>()------>(name: C, color: blue)
                 1        3

as follows:

    GRAPH.QUERY foo 'CREATE ({name: "start"})'
    GRAPH.QUERY foo 'MATCH (s {name: "start"}) MERGE (s)-[:LINK {weight: 1}]->()-[:LINK {weight: 2}]->({name: "A", color: "red"})'
    GRAPH.QUERY foo 'MATCH (s {name: "start"}) MERGE (s)-[:LINK {weight: 1}]->()-[:LINK {weight: 2}]->({name: "B", color: "blue"})'
    GRAPH.QUERY foo 'MATCH (s {name: "start"}) MERGE (s)-[:LINK {weight: 1}]->()-[:LINK {weight: 3}]->({name: "C", color: "blue"})'

Now, I'm going to ask which nodes we can reach along paths of length at least 2, and where all edge weights are less than 3. RedisGraph correctly reports that we can reach nodes `A` and `B`:

    127.0.0.1:6379> GRAPH.QUERY foo 'MATCH p = ({name: "start"})-[:LINK*2..]->(e) WHERE all(r IN relationships(p) WHERE r.weight < 3) RETURN e.name'
    1) 1) "e.name"
    2) 1) 1) "B"
       2) 1) "A"
    3) 1) "Cached execution: 0"
       2) "Query internal execution time: 1.340900 milliseconds"

That's great. But now I make the same query, except I add `AND e.color = "blue"`. Now we _should_ only be able to reach node `B`, but RedisGraph says we can reach nodes `B` and `C`? It's as if it forgot about the condition on edge weights:

    127.0.0.1:6379> GRAPH.QUERY foo 'MATCH p = ({name: "start"})-[:LINK*2..]->(e) WHERE all(r IN relationships(p) WHERE r.weight < 3) AND e.color = "blue" RETURN e.name'
    1) 1) "e.name"
    2) 1) 1) "C"
       2) 1) "B"
    3) 1) "Cached execution: 0"
       2) "Query internal execution time: 1.629100 milliseconds"

Strange!

I also tried putting the color condition first, like this:

    MATCH p = ({name: "start"})-[:LINK*2..]->(e) WHERE e.color = "blue" AND all(r IN relationships(p) WHERE r.weight < 3) RETURN e.name

but that still produces the same wrong results: `B` and `C`.

I have tried the exact same setup and queries in Neo4j, and there I do get the correct results: when color must be "blue", then only `B` can be reached.

Hopefully I have just made some blunder, but I cannot find it.

**Comment by jeffreylovitz** [comment]
Hi @skieffer,

Thanks for the detailed report! It was really helpful.

There are no blunders in your logic (which is actually a very cool approach to traversing weighted graphs); this was a bug. It was actually fixed by the recent PR https://github.com/RedisGraph/RedisGraph/pull/1429, though!

We haven't released a numbered version since this PR, but if you switch to the Docker tag `edge` you should get the correct behavior, with only `B` being returned in your example.

**Comment by skieffer** [comment]
Thanks! I appreciate the quick reply!

Okay, I have tried it in the `edge` image, and indeed it now works. : )
