### ISSUE TITLE
Trim leading, trailing white space from query

### ISSUE THREAD

**Issue by swilly22** [RedisGraph/RedisGraph#1452]
`GRAPH.QUERY g "   Create () "` Should become: `GRAPH.QUERY g "Create ()"`
This has the potential of improving cache utilisation.

**Comment by nafraf** [comment]
I'm working on this issue and I'd like to validate if I'm in the right way.

My idea is to modify the function 
```
int CommandDispatch(RedisModuleCtx *ctx, RedisModuleString **argv, int argc) 
```
The current query is taken from argv[2], then that string should be extracted from argv[2], trimmed, and assigned to query.
Is that correct? Thanks.

**Comment by swilly22** [comment]
Honestly I don't think it is worth spending time addressing this issue, there are probably other more urgent tasks...
Also I think that for the majority of the cases we won't be encountering this type of queries, the "overhead" of checking for leading/trailing spaces for queries that don't have them is just a waste of time
