### ISSUE TITLE
count() returns zero rows but should return one row with value 0

### ISSUE THREAD

**Issue by jonaskello** [RedisGraph/RedisGraph#1455]
Running this query in neo4j playground and RedisInsight gives diffrent results:

```
MATCH (a) WHERE a.nonExistentProperty = 123 RETURN count(a)
```

neo4j playground:
```
count(a)
--
1 | 0

```

RedisInsight:

```
INFO
No records and no modifications
```

According to this post I think a row with a value of zero should be returned for this query: 
https://neo4j.com/developer/kb/understanding-aggregations-on-zero-rows/

> Operators in Cypher produce rows, and they also execute per row. When there are no more rows (due to MATCH not finding matches, or WHERE clause filtering), then there is nothing left to execute upon, and remaining operations become no-op.
> One big exception to this are aggregation functions, most often count() and collect().

So I guess this could be  a bug in RedisGraph?

**Comment by jeffreylovitz** [comment]
@jonaskello You're right, this is a RedisGraph misbehavior! Thanks for opening this issue, I will add it to our roadmap.

**Comment by jonaskello** [comment]
Did this make it into 2.4 or is it planned in an new release?

**Comment by pzac** [comment]
Chiming in to add some information: this seems to happen when matching properties, but it behaves correctly with labels:

```
127.0.0.1:6379[3]> GRAPH.QUERY zoo "MATCH (n:animal {foo:'bar'}) RETURN COUNT(n)"
1) 1) "COUNT(n)"
2) (empty array)
3) 1) "Cached execution: 1"
   2) "Query internal execution time: 0.171000 milliseconds"
127.0.0.1:6379[3]> GRAPH.QUERY zoo "MATCH (n:foobar) RETURN COUNT(n)"
1) 1) "COUNT(n)"
2) 1) 1) (integer) 0
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 0.564000 milliseconds"
```

**Comment by jonaskello** [comment]
@jeffreylovitz Any ETA on this one?

**Comment by jeffreylovitz** [comment]
Hi @jonaskello,

Sorry for the late reply! I'm not sure when this will be delivered; it's not a high priority right now.

I expect we'll reach it in the next few months, but cannot make any guarantees.

**Comment by jonaskello** [comment]
@jeffreylovitz Thanks for the update! We're doing validation queries for graphs that would be really easy to do with correct behavior of `count()`. For now we need to resort to rather complex workarounds. So here's hoping that correct cypher behavior will soon become a priority again :-).
