### ISSUE TITLE
Lua + redis-graph

### ISSUE THREAD

**Issue by jeanbaptiste-brasselet** [RedisGraph/RedisGraph#146]
I would like to do an atomic operation read / update using redis-graph ! I am missing the with statement to do it. I tried to run a LUA script with some redis graph query in it but I got an error saying it's a blocking operation.

I would like to know if there is a way to make it not blocking ? Is there some configuration ? Or it's not possible ?

**Comment by jeffreylovitz** [comment]
Hi @jeanbaptiste-brasselet ,

All RedisGraph commands are defined as blocking, and as such cannot be run from Lua scripts or as part of a MULTI/EXEC group.

What type of read/update operation are you trying to perform? So long as no clients are trying to write to the graph during this sequence, serial queries ought to be a safe approach.

**Comment by swilly22** [comment]
the WITH clause should be supported within a week or two, I'll update here once it is supported.

**Comment by K-Jo** [comment]
@jeanbaptiste-brasselet can we replace this issue with https://github.com/RedisLabsModules/RedisGraph/issues/254 and close this one?

**Comment by swilly22** [comment]
WITH clause partially supported, LUA is enabled.

**Comment by mayureshkumbhar** [comment]
@swilly22 @jeanbaptiste-brasselet 
I am looking atomic operation to execute read/update on RedisGraph, tried with WATCH/MULTI/EXEC but its work as pipeline rather transaction (https://github.com/RedisGraph/RedisGraph/issues/333#issuecomment-612487478 )

I am not good at LUA but tried to execute below code, but facing errors:

> String script = "return {GRAPH.QUERY social \"CREATE (:person{name:'roi',age:32})\";GRAPH.QUERY social \"CREATE (:person{name:'mk',age:30})\";GRAPH.QUERY social \"CREATE (:person{name:ARGV[1],age:ARGV[2]})\";GRAPH.QUERY social \"MATCH (a:person), (b:person) WHERE (a.name = 'roi' AND b.name='mk') CREATE (a)-[:knows]->(b)\";GRAPH.QUERY social \"MATCH (a:person), (b:person) WHERE (a.name = 'amit' AND b.name='mk') CREATE (a)-[:fof]->(b)\";}";
Jedis jedis = new Jedis("localhost", 6379);
Object o = jedis.eval(script, Arrays.asList("name","age"), Arrays.asList("amt","55"));
System.out.println(o);

Getting below error:

> Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: ERR Error compiling script (new function): user_script:1: '}' expected near 'social' 

Looking for sample LUA + REDISGRAPH Queries example

**Comment by itamarhaber** [comment]
Hello @mayureshkumbhar 

I "fixed" your script so it now works if you send the below:

```lua
redis.call("GRAPH.QUERY", KEYS[1], "CREATE (:person{name:'roi',age:32})")
redis.call("GRAPH.QUERY", KEYS[1], "CREATE (:person{name:'mk',age:30})")
redis.call("GRAPH.QUERY", KEYS[1], "CREATE (:person{name:"..ARGV[1]..",age:"..ARGV[2].."})")
redis.call("GRAPH.QUERY", KEYS[1], "MATCH (a:person), (b:person) WHERE (a.name = 'roi' AND b.name='mk') CREATE (a)-[:knows]->(b)")
redis.call("GRAPH.QUERY", KEYS[1], "MATCH (a:person), (b:person) WHERE (a.name = 'amit' AND b.name='mk') CREATE (a)-[:fof]->(b)")
```
