### ISSUE TITLE
Crash when attempting to drop an index

### ISSUE THREAD

**Issue by pierrelambert** [RedisGraph/RedisGraph#1472]
Hi, 

I got Redis with Redisgraph 2.2.8 crashed when attempting to drop an index.

Please find logs attached
[dropinndexbug.log](https://github.com/RedisGraph/RedisGraph/files/5631391/dropinndexbug.log)

**Comment by swilly22** [comment]
@pierrelambert, can you please include steps to re-create this crash?

**Comment by pierrelambert** [comment]
I executed the command : GRAPH.QUERY "graph" "DROP INDEX ON :NODE(prop1,prop2,prop3)"
