### ISSUE TITLE
not support that queryNodes with multiple nodes with same keywords

### ISSUE THREAD

**Issue by dwgeneral** [RedisGraph/RedisGraph#1479]
hi, I wanna query 'someKeyWords' on all inserted nodes in redisgraph rather than single node, such as 

`CALL db.idx.fulltext.queryNodes('*', 'someKeywords')`

but it's not supported.

**Comment by jeffreylovitz** [comment]
hi @dwgeneral,

An index is strictly built for one specific label at present, and there is no way to utilize the index without specifying the label. At present, we have no plans to modify that behavior, as it's preferable for most use cases.

If your main intent is to query graphs this way, you can create all nodes with the same label, but this would limit your data modeling options.
