### ISSUE TITLE
Traverse same relationship from parent to child and child to parent is it possible?

### ISSUE THREAD

**Issue by hiteshbal91** [RedisGraph/RedisGraph#1488]
Hi Team,

I am having a problem statement where nodes have the same relationship but I want to traverse in both ways. Consider the following example.

`GRAPH.QUERY family 'CREATE (gp:Person {name: "GrandParent", gender: "male"})-[r1:parent {relation: "parent"}]->(p: Person  {name: "Parent", gender: "male"})'`
`GRAPH.QUERY family 'CREATE (p1:Person {name: "Parent", gender: "male"})-[:parent {relation: "parent"}]->(c: Person  {name: "Child", gender: "male"})'`

Consider above will create the 3 nodes GrandParent, Parent and Child, and 2 relationships. 

GrandParent -> Parent -> Child

Now the issue is that How do I identify the "GrandParent" of the "Child", Currently I can do the following query and identify from "GrandParent" to "Child".

`GRAPH.QUERY family  'MATCH (p1:Person)-[:parent*1..]->(c:Person)' RETURN p1.name, collect(c.name)`

Please can someone help with the above problem?

**Comment by jeffreylovitz** [comment]
Hi @hiteshbal91,

Your create queries are going to create 4 nodes, with the `Parent` node duplicated and no path between `GrandParent` and `Child`. To get the correct structure, you can use 1 create query or use a `MATCH...CREATE` construct on the second query.

To get the grandparent node of a child, you can use a query like:
`'MATCH (p1:Person {name: "Child"})<-[:parent*2]-(c:Person)' RETURN p1.name, c.name`

**Comment by hiteshbal91** [comment]
Ok @jeffreylovitz For create my bad need match and create, I will try the above solution. 

If you can help me with another query as well if possible https://github.com/RedisGraph/RedisGraph/issues/633#issuecomment-739140895.

**Comment by hiteshbal91** [comment]
thanks @jeffreylovitz it worked 👍
