### ISSUE TITLE
Assertion `QueryGraph_GetEdgeByAlias(qg, alias) == NULL' failed

### ISSUE THREAD

**Issue by SevereOverfl0w** [RedisGraph/RedisGraph#1505]
* Redis started with `podman run  -p 6379:6379 --rm docker.io/redislabs/redismod`.
* Query was `"MATCH (a:expr) WHERE a.id = 7 CREATE (a)-[r:LIST_HEAD]->(b:expr{col:13,line:15,text:\"assoc\"}),(b)-[r:NEXT]->(c{col:19,line:15,text:\":key\"})"` using the Java RedisGraph library.
* Log at https://gist.github.com/SevereOverfl0w/2c3dacb4d1950250e28a18535bcc6f66

My query is probably invalid :), but crashing redis is no fun either.

**Comment by jeffreylovitz** [comment]
Hi @SevereOverfl0w,

The `redismod` image is using an outdated RedisGraph version; this issue does not occur on RedisGraph version 2.2. Can you use the image `redislabs/redisgraph:latest` or `redislabs/redisgraph:edge`?
