### ISSUE TITLE
Any hope for geo/spatial support?

### ISSUE THREAD

**Issue by ian** [RedisGraph/RedisGraph#1513]
Really looking for some sort of spatial index support and basic geo functions (distance, etc).

Just wondering if this is on the radar at all?

**Comment by swilly22** [comment]
Hi @ian, can you please provide additional details on your use-case?
It seems like we'll be able to support 2D geo spatial (lat, long) coordinates

**Comment by ian** [comment]
2D lat+lng would totally acceptable for my use case. Just need nodes to be able to be spatial and represented on a map,  without elevation.

Neo4j goes a bit overboard IMO with their support for so many coord systems.  I think you can cover 90% of the cases for spatial with just 2D.

Happy to chat more if it helps move the project forward.

**Comment by swilly22** [comment]
Thanks @ian I'll update here on our progress.

**Comment by swilly22** [comment]
@ian the data-point data structure had just been merged to our `master` branch, it should be available on `dockerhub` `edge` image in a few hours, may I ask which client library are you using to query RedisGraph?

**Comment by ian** [comment]
@swilly22 This is great news! 

Currently I am on "redisgraph.js": "^2.2.1"

Does the above PR add access to geospatial functions (distance, nearby) as well as the point type?

**Comment by ian** [comment]
@swilly22 I just saw the documentation for distance().

**Comment by ian** [comment]
@swilly22 ok will follow along when that's ready. I've got a PR against our code to swap neo4j for redis-graph, so I can test if you need anything.

**Comment by ian** [comment]
@swilly22 is there a PR open for the bindings in redisgraph.js?

**Comment by swilly22** [comment]
@ian the point data structure had made its way to RedisGraph `edge` docker image:
```
docker run -p 6379:6379 -it --rm redislabs/redisgraph:edge
```
in addition [`redisgraph.js`](https://www.npmjs.com/package/redisgraph.js) version 2.2.2 support that data type.

**Comment by ian** [comment]
Awesome, thanks for the update. And this will support distance() calculation as well?

**Comment by swilly22** [comment]
it is.
