### ISSUE TITLE
Is RLTest platform independent

### ISSUE THREAD

**Issue by PSK-oss** [RedisGraph/RedisGraph#1520]
i have a redis instance(Big endian) and working on RedisGraph/RediSearch, Observed a statement in the test scripts "from RLTest import Env" and commands in the scripts are based on the imported env. But getting many assertion failures while testing. 

I have installed RLTest from Github using pip install and I'm not sure whether it is platform independent or not, please advise.

**Comment by swilly22** [comment]
@rafie, can you please advise?

**Comment by gkorland** [comment]
@PSK-oss can you please add the errors you get?

**Comment by PSK-oss** [comment]
Tried executing one of the pytest(test_ext.py)

* Module 'ft' loaded from /home/RediSearch/src/redisearch.so
* Ready to accept connections
:signal-handler (1609927390) Received SIGTERM scheduling shutdown...
:M 06 Jan 2021 02:03:11.026 # User requested shutdown...
:M 06 Jan 2021 02:03:11.026 # Redis is now ready to exit, bye bye...
['cc', '-shared', '-fPIC', '-o', '/home/RediSearch/src/pytest/libexample_extension.so', '/home/RediSearch/src/pytest/../tests/ext-example/example.c', '-I/home/RediSearch/src/pytest/../']
0
^[[36mtest_ext:testExt^[[0m
        ^[[31;1m❌  (FAIL):     ^[[0m^[[33m100 == 1L^[[0m       ^[[30;1mtest_ext.py:47^[[0m
        ^[[31;1m[FAIL]^[[0m
^[[1mTest Took: 0 sec^[[0m
^[[1mTotal Tests Run: 1, Total Tests Failed: 1, Total Tests Passed: 0^[[0m
^[[1mFailed Tests Summary:^[[0m
        ^[[1mtest_ext:testExt^[[0m
                ^[[31;1m❌  (FAIL):     ^[[0m^[[33m100 == 1L^[[0m       ^[[30;1mtest_ext.py:47^[[0m
Makefile:141: recipe for target 'pytest' failed

**Comment by rafie** [comment]
`RLTest` is Python-based, therefore theoretically platform independent. However, one of the Python dependencies (`psutil`) is platform-sensitive. The 'Env' part in `RLTest` is basically a mechanism for starting up and shutting down `redis-server`.
I suggest the following:
1. Using Python 2 with `virtualenv` to install `RLTest`
2. Installing `RLTest` using `bin/getrmpytools` from https://github.com/RedisLabsModules/readies
3. Focus on specific test failures (you can run RediSearch tests using `make test TEST=test_ext:testExt` to get all the interesting outputs) and analyzing them.

**Comment by PSK-oss** [comment]
I have installed RLTest using the same method(above mentioned step 2)

python -m pip install git+https://github.com/Grokzen/redis-py-cluster.git@master
python -m pip install git+https://github.com/RedisLabsModules/RLTest.git@master
python -m pip install git+https://github.com/RedisLabs/RAMP@master

Can you suggest me how to install RLTest using Python2-virtualenv(Step 1).

**Comment by rafie** [comment]
```
git clone https://github.com/RedisLabsModules/readies.git
VENV=venv ./readies/bin/getpy2
. ./venv/bin/activate
./readies/bin/getrmpytools
```

**Comment by PSK-oss** [comment]
Tried installing using venv, but testcase failing with same error.

Failed Tests Summary:
        test_ext:testExt
                ❌  (FAIL):     100 == 1L       test_ext.py:47
Makefile:141: recipe for target 'pytest' failed

Can you pls. confirm is the issue realte

**Comment by PSK-oss** [comment]
Can you please check & let me know whether these errors(assertion failures & index related issues) are due to the python-dependency psutil? 
Because for installing RLTest i tried all the ways, but getting same issues.

**Comment by rafie** [comment]
Please check if your psutil version is 5.8.0.
Most distributions don't currently have a native `python2-psutil` package and pip in able to install psutil without building it, and it should work just fine.
We'll check the specific test, but on the face of it, it works well in our CI, so we'll probably need to dig a little bit deeper on your side.

**Comment by PSK-oss** [comment]
Thanks for the update, i have verified the psutil version and it is 5.8.0 only.
