### ISSUE TITLE
query `IN` list not working after creating index in 2.2.12

### ISSUE THREAD

**Issue by SherinV** [RedisGraph/RedisGraph#1526]
On an indexed node, we have a list property `aliases`. Querying the list used to work in 2.2.8, but not in 2.2.12

> graph.query test "CREATE (:Person {name:'Peter', aliases:['Pete','Mike']})"
> graph.query test "CREATE (:Person {name:'Dave'})"
> 
> graph.query test "MATCH (p:Person) WHERE 'Mike' IN p.aliases RETURN p"

returns results.

But, if I create an index on `Person`, the above query doesn't work anymore.

> graph.query test "CREATE INDEX ON :Person(name)"

> graph.query test "MATCH (p:Person) WHERE 'Mike' IN p.aliases RETURN p"
> 1) 1) "p"
> 2) (empty list or set)
> 3) (error) Type mismatch: expected List but was String

throws error `Type mismatch: expected List but was String`. It works if I drop the index. 

Thanks.

**Comment by swilly22** [comment]
@SherinV thank you for reporting, we'll look into it

In addition, consider the following:
```
CREATE ( {v:['a','b']}), ({v:'ab'})
```

```
MATCH (n) WHERE 'a' IN n.v RETURN n
```

In which case, one `n` node will have its `v` attribute as an array while in the other it will be a string, in which case RedisGraph should ignore the error and skip that node.
