### ISSUE TITLE
[Question] Debugging intermediate returns

### ISSUE THREAD

**Issue by fabianmurariu** [RedisGraph/RedisGraph#1542]
Not sure if this is the right place to post this but here it goes.

Is there a way to obtain an exact execution plan for the matrix algebra multiplications? Especially how you combine expressions for results in the middle of the path? Explicit debug information with every matrix would be splendid.

I'm trying to understand the approach RedisGraph takes with intermediate returns, this is described [here](http://wiki.ldbcouncil.org/pages/viewpage.action?pageId=106233859&preview=/106233859/111706128/LDBC-July-2019.pdf)

Are there any unit tests that show how you combine the intermediate expressions?

I've been following GraphBLAS for a while and I maintain the [Rust](https://github.com/fabianmurariu/rustgraphblas) and [Java](https://github.com/fabianmurariu/graphblas-java-native) bindings.

**Comment by swilly22** [comment]
HI @fabianmurariu,
Please see `test_algebraic_expression.cpp`
In addition if you're interested in compiling the source you can call `AlgebraicExpression_PrintTree` or `AlgebraicExpression_Print`
on each constructed algebraic expression, for example in `op_conditional_traverse.c` and `op_expand_into.c`

**Comment by fabianmurariu** [comment]
Thanks for that, I was just printing some stuff

```
774730:M 23 Jan 2021 16:50:05.358 * Module 'graph' loaded from /opt/RedisGraph/src/redisgraph.so


a * X * BAlg_Eval_Mul
  16x4 GraphBLAS bool matrix, sparse by row:
  res, 2 entries

    (0,1)   1
    (0,3)   1
b * Y * CAlg_Eval_Mul
  16x4 GraphBLAS bool matrix, sparse by row:
  res, 1 entry

    (0,2)   1
774730:M 23 Jan 2021 17:49:57.012 * 1 changes in 3600 seconds. Saving...
```

my simple query is (a:A)-[:X]->(b:B)-[:Y]-(c:C) return c
aXB and bYC are the 2 parts I'm very confused about how you mix them together and how you perform the scan but I can print stuff out now so I'm getting there

**Comment by fabianmurariu** [comment]
Graph (the usual diamond kind):
`GRAPH.QUERY MotoGP "create (a1:A)-[:X]->(b1:B)-[:Y]->(c1:C),(a1)-[:X]->(b2:B)-[:W]->(c1);" `
Query (take the top path)
`GRAPH.QUERY MotoGP "match (a:A)-[:X]->(b:B)-[:Y]->(c:C) return b;"`

where does the leftmost matrix of the 2nd expression come from? (b * Y * C)

```
b * Y * C
LEFT1 ( wait what? )
  16x4 GraphBLAS bool matrix, sparse by row:
  A, 2 entries

    (0,1)   1
    (1,3)   1
```

the full output?
expr1 easy A*X*B you get b1 and b2 over at row 0 in A
```
a * X * B
LEFT1 ( this is A)
  16x4 GraphBLAS bool matrix, sparse by row:
  A, 1 entry

    (0,0)   1

RIGHT1 (this is X)
  4x4 GraphBLAS uint64_t matrix, sparse by row:
  B, 2 entries

    (0,1)   9223372036854775808
    (0,3)   9223372036854775810

LEFT2 (this is A*X)
  16x4 GraphBLAS bool matrix, sparse by row:
  res, 2 entries

    (0,1)   1
    (0,3)   1

RIGHT2 (this is B)
  4x4 GraphBLAS bool matrix, sparse by row:
  B, 2 entries

    (1,1)   1
    (3,3)   1

Alg_Eval_Mul (this is AXB)

  16x4 GraphBLAS bool matrix, sparse by row:
  res, 2 entries

    (0,1)   1
    (0,3)   1

```

expr 2 (what is the left most Matrix of this expression ?)

```
b * Y * C
LEFT1 ( wait what? )
  16x4 GraphBLAS bool matrix, sparse by row:
  A, 2 entries

    (0,1)   1
    (1,3)   1

RIGHT1 (this is Y)
  4x4 GraphBLAS uint64_t matrix, sparse by row:
  B, 1 entry

    (1,2)   9223372036854775809

LEFT2 (this is the output before we check it's in C)
  16x4 GraphBLAS bool matrix, sparse by row:
  res, 1 entry

    (0,2)   1

RIGHT2 (this is C)
  4x4 GraphBLAS bool matrix, sparse by row:
  B, 1 entry

    (2,2)   1

Alg_Eval_Mul (result)

  16x4 GraphBLAS bool matrix, sparse by row:
  res, 1 entry

    (0,2)   1

```

**Comment by fabianmurariu** [comment]
@swilly22 I'm still a bit confused as to how you do your filtering, in my head I would expect some operation to transform the result of the  expansion a*X*b into a diagonal selection matrix where all the outputs in b are relocated onto the diagonal and the next expansion uses that as a filter. So instead of (0, 1) and (1, 3) I was expecting (1, 1) and (3, 3).

I raised this issue on the GraphBLAS forum and there seem to be some consensus on a GxB_diag method that sets the values of a sparse vector onto the k-th diagonal of a matrix without needing to extract the values out of GRB.
