### ISSUE TITLE
Add all-properties selector to map projection

### ISSUE THREAD

**Issue by nirelbaz** [RedisGraph/RedisGraph#1547]
Hey, I'm Using docker-image with the edge tag. And I come across the following error while trying to use the `.*` selector:
`(error) RedisGraph does not currently support all properties projection`

My query looks something like this:
```
MATCH (a:a)-[:e]->(b:b)
WHERE b.id='****'
WITH a { .*, b: b } AS a
RETURN a
```

Will be great if we could have it supported.

**Comment by mattb-af** [comment]
+1
