### ISSUE TITLE
Query does not support backtics

### ISSUE THREAD

**Issue by Wajihulhassan** [RedisGraph/RedisGraph#155]
I have some special character (colon) in my query and to escape that cypher language suggests to use backtics as mentioned [here](https://stackoverflow.com/questions/20048882/cant-query-properties-with-colon). Howerver, using redisgraph I get following error:
```
127.0.0.1:6379>  GRAPH.QUERY provenance "MATCH (n:`C:\USERS\TARGET0\JAVA.EXE`)-[:write]->(d) RETURN n,d"
(error) Syntax error at offset 13 near ':'
```

**Comment by swilly22** [comment]
Hi @Wajihulhassan 
Thanks for posting, I was not aware you could escape using backtics, I'll have to look into our parser to see how we can support this feature, although I must say we've got a number of tasks in the pipeline and so this might take awhile, appreciate your patient.

**Comment by swilly22** [comment]
```
GRAPH.EXPLAIN provenance "MATCH (n:`C:\USERS\TARGET0\JAVA.EXE`)-[:write]->(d) RETURN n,d"
1) "Results"
2) "    Project"
3) "        Conditional Traverse | (n:C:USERSTARGET0JAVA.EXE)->(d)"
4) "            Node By Label Scan | (n:C:USERSTARGET0JAVA.EXE)"
```
