### ISSUE TITLE
Different Results Between Neo4j and RedisGraph with the Same Data and Queries - Friend Recommendations

### ISSUE THREAD

**Issue by EbuOgden** [RedisGraph/RedisGraph#1559]
Hello, we were looking for graph database solutions and came across with neo4j and redisgraph. Based on the benchmark performance differences we were planning to go with RedisGraph but unfortunately we cannot get this use case work for us.

We have users and we recommend friends to our users based on their relation with others. (Friends of friend)

We tried one directional and bi-directional relation between nodes but unfortunately neither of them gave an expected output. I was wondering if our queries or data structure is the problem or this method isn't supported by RedisGraph.

**One Directional Relation**

_Users_

```
CREATE (:person{name:'ebu',age:27})
CREATE (:person{name:'gokhan',age:30})
CREATE (:person{name:'azmi',age:55})
CREATE (:person{name:'cansu',age:72})
CREATE (:person{name:'mehmetali',age:28})
CREATE (:person{name:'erhan',age:28})
```

_One Directional Relations_

```
MATCH (a:person), (b:person) WHERE (a.name = 'ebu' AND b.name='gokhan') CREATE (a)-[:connected]->(b)
MATCH (a:person), (b:person) WHERE (a.name = 'azmi' AND b.name='gokhan') CREATE (a)-[:connected]->(b)
MATCH (a:person), (b:person) WHERE (a.name = 'mehmetali' AND b.name='ebu') CREATE (a)-[:connected]->(b)
MATCH (a:person), (b:person) WHERE (a.name = 'azmi' AND b.name='cansu') CREATE (a)-[:connected]->(b)
MATCH (a:person), (b:person) WHERE (a.name = 'erhan' AND b.name='azmi') CREATE (a)-[:connected]->(b)
```

**Recommend 2nd Level Friends to Gokhan**

```
MATCH  
    (me:person)-[:connected*2]-(friendOfFriend:person) 
WHERE NOT 
    (me)-[:connected]-(friendOfFriend:person) 
    AND me.name = 'gokhan' 
RETURN 
    count(friendOfFriend) as friendsInCommon, friendOfFriend.name as suggestedFriend 
ORDER BY 
    friendsInCommon DESC
```

_The relations between users_

<img width="1824" alt="relations" src="https://user-images.githubusercontent.com/12768835/106503065-2e9ddd80-6493-11eb-8413-e9889ceb08aa.png">

_Expected Results (Got it from Neo4j)_

<img width="1833" alt="Screen Shot 2021-02-01 at 12 28 26 AM" src="https://user-images.githubusercontent.com/12768835/106503270-6c026b00-6493-11eb-86ce-40eed3cceda0.png">

_What we got from RedisGraph_

![2nd-level-got](https://user-images.githubusercontent.com/12768835/106502300-33ae5d00-6492-11eb-9754-bdaadd1330f0.png)

and if we add one more person to the scenario,

`CREATE (:person{name:'sevda',age:28})`

create a relation with a person who is 2nd level to 'Gokhan'

`MATCH (a:person), (b:person) WHERE (a.name = 'sevda' AND b.name='cansu') CREATE (a)-[:connected]->(b)`

When we query to get the 3rd level recommendation for Gokhan, we expect to only get 'sevda' but with RedisGraph we are not able to do that:

_Expected Results for 3rd Level (Got it from Neo4j - friendsInCommon can be ignored here)_

<img width="1816" alt="Screen Shot 2021-02-01 at 12 28 07 AM" src="https://user-images.githubusercontent.com/12768835/106503620-e29f6880-6493-11eb-9520-cf1610139744.png">

_What we got from RedisGraph (3rd Level - friendsInCommon can be ignored here)_

![Screen Shot 2021-02-01 at 12 31 31 AM](https://user-images.githubusercontent.com/12768835/106503666-f0ed8480-6493-11eb-9612-cb32c6a81c70.png)

Without giving the directions in the query, neo4j is able to produce the results. Can we use RedisGraph to get the same outputs?

Thanks!

**Comment by swilly22** [comment]
Hi @EbuOgden, when performing traversals RedisGraph can revisit visited nodes, this is why `gokhan` is showing up in your first result-set, to avoid it simply require that `me <> friendOfFriend`

```
MATCH (me:person {name:'gokhan'})-[:connected*2]-(friendOfFriend:person)
WHERE NOT (me)-[:connected]-(friendOfFriend) AND me <> friendOfFriend
RETURN friendOfFriend.name as suggestedFriend, count(friendOfFriend) as friendsInCommon
ORDER BY friendsInCommon DESC
```

**Comment by CatalinAdlerDF** [comment]
I wonder what's the perf impact of node revisiting in redis; in neo4j it was night and day for us, but unfortunately we had to use graph algos to avoid it, cypher lacked this.

@EbuOgden what has been your experience with regards to perf between the two engines?
My team is also researching the matter.

**Comment by swilly22** [comment]
I believe it's a trade off between keeping track after visited nodes and the overhead of traversing through a node you've already visited,
Depending on the query and the graph topology one can be "cheaper" than the other.

**Comment by EbuOgden** [comment]
Thanks for the reply and answer @swilly22, highly appreciate it! 

@CatalinAdlerDF For now we went with Neo4j. Unfortunately I cannot say too much about performance differences based on the current dataset we have. But on the other hand, by knowing the performance of Redis, I can easily say that it would be incredibly fast and their benchmark results show that. Would it be a robust solution in the long run based on RAM usage? Again, haven't had enough experience to say something about that topic, I believe the time will show?

A couple reasons of our choice of Neo4j over RedisGraph:
- Community
- Been around longer, believing they might have more robust solutions and already dealt with bugs that we can/might encounter in the future
- And the result differences based on the same dataset and queries (Kind of what we were looking for mainly)

Overall RedisGraph is a great tool, but it wasn't for us for now. Maybe later :)

**Comment by CatalinAdlerDF** [comment]
Thanks for the feedback @EbuOgden !
We're also looking into graph engine selection and we've narrowed it down to tiger/neo and redis.
My hopes are that redisgraph is mature enough for prod usage and cherry on the cake to be GPU support.

Having the ability to get significant more perf by just using a GPU is priceless; but I am not clear if this works with the current version or if I have to do anything to benefit from it.

Hope this project does not go down the drain in few years :(
