### ISSUE TITLE
The 'graphdata' datastructure

### ISSUE THREAD

**Issue by MohamedRagabAnas** [RedisGraph/RedisGraph#1563]
Hi there, 
I'm interested in the project and wanna understand more about the internals of RedisGraph, and looks for the feasibility of the interoperability between Redis-Streams  and Redis-Graph modules.

Thus, I'm wondering on what native data structures of Redis you have built your own data structure of the 'graphdata' that is shown up when we run ```TYPE myGraph``` command. 
- Is the graph inside the RedisGraph module (or its sub-components, nodes, edges, paths), are built on the known data structures of Redis, e.g SETS, LISTS,...etc. 
- or RedisGraph is using a native new data structure inside its module.

Thanks in advance for your answer, and support!

**Comment by swilly22** [comment]
Hi @MohamedRagabAnas,
Thank you for showing interest in the project,
RedisGraph uses its own data structures to represent a graph, node and edge objects. start exploring [here](https://github.com/RedisGraph/RedisGraph/blob/master/src/graph/graph.h) 

For additional information see [redisgraph-internals](https://www.slideshare.net/RedisLabs/redisgraph-internals-roi-lipman) and [Deep Dive into RedisGraph
](https://www.youtube.com/watch?v=4KS2MRccQX4)

We are interested in integrating Graph with Streams but have yet to really look into such integration.

**Comment by MohamedRagabAnas** [comment]
Thanks!
