### ISSUE TITLE
Manipulating array property values

### ISSUE THREAD

**Issue by PradeepKumar1994** [RedisGraph/RedisGraph#1571]
Hi,

Help wanted.

I was experimenting with arrays as property value. I have been doing the following:

`  graph.query Test "MATCH (u:Person) Create (:Person {address:['something1', 'something2']})" `

To able to do this:

>1) 1) "x"`
>2) 1) 1) 1) 1) "id"`
>            2) (integer) 0
>        2) 1) "labels"
>            2) 1) "Person"
>         3) 1) "properties"
>            2) 1) 1) "address"
>                  2) "[something1, something2]"

What I am looking for is able to ### append or add more to elements to the [array operations](https://oss.redislabs.com/redisgraph/commands/#list-functions). For instance I wanted to do add elements such as ['something3', 'something4'] to address, and able to see result such as the following:

>1) 1) "x"
>2) 1) 1) 1) 1) "id"
>            2) (integer) 0
>        2) 1) "labels"
>            2) 1) "Person"
>         3) 1) "properties"
>            2) 1) 1) "address"
>                  2) "[something1, something2, something3, something4]"

And also able to delete if I have to part of the array.
Thank you in advance

**Comment by swilly22** [comment]
To add elements to an array simply use addition e.g. `RETURN 1 + [2,3]` or `RETURN [2,3] + 4`
Removing an element from an isn't supported, you'll have to reconstruct the array.

**Comment by PradeepKumar1994** [comment]
Thank you. :) 

After experimenting I've realized return with the addition would just return but not make changes to value in the redisgraph, for instance, a redis list when you do  `rpush mylist helllo` which will reflect the changes to the list.

Perhaps, I've miscommunicated the first time. Similarly, like to redis list what I am looking more of where I can update the list for a particular property

> from {key: ['something1', 'something2']}     to           {key: ['something1', 'something2', 'something3', 'something4']}

**Comment by laurentdroin** [comment]
Pradeep, would the following work for you?

`graph.query Test "MATCH (u:Person) set u.address = u.address + ['something3', 'something4']"`

It gives:

`graph.query Test "match (n) return n"
1) 1) "n"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "address"
                  2) "[something1, something2, something3, something4]"`

**Comment by PradeepKumar1994** [comment]
Thank you, Laurent. :)
