### ISSUE TITLE
Support for OPTIONAL and DETACH keyword

### ISSUE THREAD

**Issue by esokullu** [RedisGraph/RedisGraph#158]
Any plans to support "OPTIONAL" and "DETACH" keywords soon?

For example;
```MATCH (n {udid: {udid}}) OPTIONAL MATCH (n)-[e]-()  DELETE e, n```
or
```MATCH (n {udid: {udid}}) DETACH  DELETE  n```

are both legit Cypher queries.

Thanks by the way. I've been following the project for a while, for our open source project https://github.com/phonetworks and I can see the great progress you've made over the past few months. Once the [PHP client ](https://github.com/RedisLabsModules/redis-graph/issues/157)and complex queries are supported, we'll drop Neo4J in favor of RedisGraph.

**Comment by swilly22** [comment]
Hi @esokullu,
Thank you for showing interest in this project, we defiantly appreciate the kind words.

Let me start with DETACH, RedisGraph doesn't require the DETACH keyword when trying to delete a node with incoming/outgoing edges, when issuing `MATCH (n {udid: {udid}}) DETACH DELETE n`
all incoming/outgoing edges of `n` will be removed in addition to `n`

Regarding `OPTIONAL` I'll have to estimate and see when we can add support for this keyword, probably not before end of November.

**Comment by davisford** [comment]
@swilly22 , may want to consider adding that concise, helpful example on how to `DELETE` a node...I was also wondering why there was no support to remove a node or edge, and was looking here in issues for an answer.  

Even if its understood that's how to delete, it's still good to document the fact that it does the equivalent of a `CASCADE DELETE` for 1-hop edges.

**Comment by MichaelHirn** [comment]
Kind of abusing this PR to check on the status of `OPTIONAL`. Any news here? Any temporary workarounds?

**Comment by renewooller** [comment]
+1 for OPTIONAL, I would find this really useful

**Comment by swilly22** [comment]
@MichaelHirn unfortunately not at the moment, `OPTIONAL` will not be part of 2.0

**Comment by renewooller** [comment]
> @MichaelHirn unfortunately not at the moment, `OPTIONAL` will not be part of 2.0

What's the rough timeframe on OPTIONAL support? It's quite difficult to work around it adequately at the moment, requiring either multiple lookups that will slow down the search, or adding in an extra 13 GB of relationships.

**Comment by swilly22** [comment]
@renewooller, it is hard to tell, it is on our post 2.0 roadmap but I can't tell exactly when we'll start working on this feature.

**Comment by MichaelHirn** [comment]
> @MichaelHirn unfortunately not at the moment, `OPTIONAL` will not be part of 2.0

Thanks for the reply - we actually refactored our queries and don't need `OPTIONAL` anymore. We did it by using pattern comprehension as described [here](https://medium.com/neo4j/loading-graph-data-for-an-object-graph-mapper-or-graphql-5103b1a8b66e). That being said, we have it running on Neo4J, so not sure if something like pattern comprehension is an actual replacement that works on RedisGraph yet.

Hope to get to it soon though.

**Comment by renewooller** [comment]
As a work around missing optional, I'm trying to refactor this query, however it's timing out.  Any ideas on how to work around the missing optional other than multiple queries?

`MATCH (sys:system) WHERE sys.system_id = 'WOOL03' WITH sys 
MATCH (songs:song)-[songs_in_list:SONG_IN_LIST]->(list1:list)-[list_on_system:LIST_ON_SYSTEM]->(sys:system)
WHERE ((songs.song_title_sortkey CONTAINS 'b' AND songs.song_title_sortkey CONTAINS 'r' ) OR (songs.song_artist_sortkey CONTAINS 'b' AND songs.song_artist_sortkey CONTAINS 'r' )) AND songs.category IN ['','ALTERNATIVE','ASIAN','BALLADS','BLUES','BLUESnROOTS','BREAKS','CAFE','CLASSICAL','CLUB','COUNTRY','CUBAN','DANCE','DANCE`','DISCO','DJ_TOOLS','ELECTRONIC','ELETRONIC','FRENCH','FUNKnSOUL','GERMAN','HIPHOPnRAP','HOUSE','IRISH','ITALIAN','JAZZ','KIDS','LATIN','LYRICVIDEO','OCCASIONS','ORIENTAL','PARTY','POP','PROMO','RADIO','REGGAE','RELAXATION','ROCK','ROCKnROLL','SWING','TECHNO','URBAN','WORLD','XMAS']
WITH songs, sys
MATCH (sz:system_zone)-[:SYSTEM_ZONE_ON_SYSTEM]->(sys:system) WHERE sz.zone = 1
WITH sz, songs, sys
MATCH (sz)<-[soz:SONG_ON_ZONE]-(songs_to_remove:song)-[songs_in_list:SONG_IN_LIST]->(list1:list)-[list_on_system:LIST_ON_SYSTEM]->(sys)
WHERE soz.removed = 1 OR soz.hidden = 1
WITH sz, COLLECT(songs_to_remove.song_id) AS song_ids_to_remove, songs, sys
WHERE NOT songs.song_id IN song_ids_to_remove
RETURN songs LIMIT 30`

`graph.EXPLAIN "nl-tune-yards:default:graph" "MATCH (sys:system) WHERE sys.system_id = 'WOOL03' WITH sys  MATCH (songs:song)-[songs_in_list:SONG_IN_LIST]->(list1:list)-[list_on_system:LIST_ON_SYSTEM]->(sys:system) WHERE ((songs.song_title_sortkey CONTAINS 'b' AND songs.song_title_sortkey CONTAINS 'r' ) OR (songs.song_artist_sortkey CONTAINS 'b' AND songs.song_artist_sortkey CONTAINS 'r' )) AND songs.category IN ['','ALTERNATIVE','ASIAN','BALLADS','BLUES','BLUESnROOTS','BREAKS','CAFE','CLASSICAL','CLUB','COUNTRY','CUBAN','DANCE','DANCE`','DISCO','DJ_TOOLS','ELECTRONIC','ELETRONIC','FRENCH','FUNKnSOUL','GERMAN','HIPHOPnRAP','HOUSE','IRISH','ITALIAN','JAZZ','KIDS','LATIN','LYRICVIDEO','OCCASIONS','ORIENTAL','PARTY','POP','PROMO','RADIO','REGGAE','RELAXATION','ROCK','ROCKnROLL','SWING','TECHNO','URBAN','WORLD','XMAS'] WITH songs, sys MATCH (sz:system_zone)-[:SYSTEM_ZONE_ON_SYSTEM]->(sys:system) WHERE sz.zone = 1 WITH sz, songs, sys MATCH (sz)<-[soz:SONG_ON_ZONE]-(songs_to_remove:song)-[songs_in_list:SONG_IN_LIST]->(list1:list)-[list_on_system:LIST_ON_SYSTEM]->(sys) WHERE soz.removed = 1 OR soz.hidden = 1 WITH sz, COLLECT(songs_to_remove.song_id) AS song_ids_to_remove, songs, sys WHERE NOT songs.song_id IN song_ids_to_remove RETURN songs LIMIT 30"`

1) "Results"
 2) "    Limit"
 3) "        Project"
 4) "            Filter"
 5) "                Aggregate"
 6) "                    Filter"
 7) "                        Expand Into | (songs_to_remove:song)-[soz:SONG_ON_ZONE]->(sz)"
 8) "                            Conditional Traverse | (sys)->(songs_to_remove:song)"
 9) "                                Project"
10) "                                    Filter"
11) "                                        Conditional Traverse | (sys:system)->(sz:system_zone)"
12) "                                            Project"
13) "                                                Filter"
14) "                                                    Conditional Traverse | (sys:system)->(songs:song)"
15) "                                                        Project"
16) "                                                            Index Scan | (sys:system)"

**Comment by swilly22** [comment]
Support for OPTIONAL MATCH has been merged to the master branch.
#1043
