### ISSUE TITLE
Questions on Full Text Search/Documentation Improvements/Possible Bugs

### ISSUE THREAD

**Issue by kornha** [RedisGraph/RedisGraph#1584]
Hello,

Great work and I appreciate your efforts on this. We are exploring RedisGraph's search capabilities.
I have found this [page](https://oss.redislabs.com/redisgraph/commands/#full-text-indexes) which appears to be the sole source of documentation on full text search of Redis Graph.

1: Say I do, 

`GRAPH.QUERY DEMO_GRAPH "CALL db.idx.fulltext.createNodeIndex('Movie', 'title')"
`
But I don't just have 'Movie', I also have Series. And I want the same indexes on both. ALSO, say I don't just want title, I want title + 'description', for both movie and series.

Logically I might be able to do:

`GRAPH.QUERY DEMO_GRAPH "CALL db.idx.fulltext.createNodeIndex('Movie Series', 'title description')"
`
But this does not work. Cannot find any reference on this anywhere, other than the mention of:

`(More properties can be added to this index by adding their names to the above set of arguments, or using this syntax again with the additional names.)
`
How to?

2: Now let us assume I have created these two indexes on both 'Movie' and 'Series'.

How do I agnostically search in both?
Logically it might be:
`GRAPH.QUERY DEMO_GRAPH "CALL db.idx.fulltext.queryNodes('Movie|Series', 'Book') YIELD node RETURN node.title"`
But this does not work. Once again, I cannot find any documentation on this topic.
How to?

3: As another item, say I have a title, "The Power". When I search 
```
GRAPH.QUERY DEMO_GRAPH
"CALL db.idx.fulltext.queryNodes('Movie', 'Power') YIELD node RETURN node.title"
```
This works. However, if I do 
```
GRAPH.QUERY DEMO_GRAPH
"CALL db.idx.fulltext.queryNodes('Movie', 'the') YIELD node RETURN node.title"
```
This does not return the title(!) 
Maybe words like "The" are not indexed?
Furthermore, if I do:
```
GRAPH.QUERY DEMO_GRAPH
"CALL db.idx.fulltext.queryNodes('Movie', 'Powe') YIELD node RETURN node.title"
```
No such luck. I must use Powe*, which then makes me wonder exactly how fulltext is working. It appears to match exact words case insensitive. Say I want full text, partial word, with Levenstein variation, a common search need, how might I do that?

4: Finally, if I want to add a full text index on, say, an Array property of my node (eg., Actors), how might I do that?
Appreciate your time!

**Comment by swilly22** [comment]
Hi @kornha,
Each index is associated with a single node label, in-order to index both `Movie` and `Series` you'll have to create two indices:
 ```
GRAPH.QUERY DEMO_GRAPH "CALL db.idx.fulltext.createNodeIndex('Movie', 'title', 'description')"
GRAPH.QUERY DEMO_GRAPH "CALL db.idx.fulltext.createNodeIndex('Series', 'title', 'description')"
```

To query both agnostically let me suggest:
```
GRAPH.QUERY DEMO_GRAPH "CALL db.idx.fulltext.queryNodes('Movie', 'Book') YIELD node RETURN node.title
UNION
CALL db.idx.fulltext.queryNodes('Series', 'Book') YIELD node RETURN node.title"
```

As far as I'm aware the word `the` is considered a stop word which isn't indexed.

> No such luck. I must use Powe*, which then makes me wonder exactly how fulltext is working. It appears to match exact words case insensitive. Say I want full text, partial word, with Levenstein variation, a common search need, how might I do that?

@MeirShpilraien can you please help answering this question?

Lastly RedisGraph can only index strings when using full-text index, for exact-match indices we can index both numerics, boolean and strings (soon to be supported Geo)

**Comment by kornha** [comment]
Thank you so much, this is incredibly useful.
On the subject of Arrays, do you have a recommendation for how we might search in them (ie., combine them into a string?) or is that not possible yet?

**Comment by MeirShpilraien** [comment]
@kornha the full-text search is done by RediSearch, you can see the full query syntax here: https://oss.redislabs.com/redisearch/Query_Syntax/
Specifically for LD you can use `#Powe#`

**Comment by swilly22** [comment]
@kornha depending on rather or not you intend to search these arrays via an index, if so you'll have to concatenate them into strings, otherwise (not using an index) you can use the `IN` operator to search for elements within arrays, e.g. `...WHERE 1 IN [1,2,3]...`

**Comment by kornha** [comment]
Ok great makes sense.
Might be a nice feature to include in the roadmap -- indexing arrays of strings, but I can workaround it in the meanwhile.
One last question, I promise. Let's say I want a different weight for 'title' and 'description' fields.. 

1-Eg., If I have an exact match I want to rank it first, followed by prefix match, followed by fuzzy match. Is there a way to do this?

2-Furthermore, I want to order Titles ahead of Description. Seems like I would just combine queries for this, no?

**Comment by swilly22** [comment]
RediSearch do allows to set weights on indexed fields, but we don't expose that via the Graph interface, I'm not sure if Cypher defines means to specify weights.

Not sure I understand your second question regarding ordering, can you please elaborate?

**Comment by kornha** [comment]
OK, will look into working in my own weighting. Appreciate your responses!

**Comment by kornha** [comment]
One more question :) let's say I have 2 movies, one titled 'The Lord of the Rings' and another titled 'ABC' but has, in its description, the word 'ring'.

So if I create an index like this:
`GRAPH.QUERY DEMO_GRAPH "CALL db.idx.fulltext.createNodeIndex('Movie', 'title', 'description')"`
And search the word ring:
`CALL db.idx.fulltext.queryNodes('Movie', 'ring') YIELD node RETURN node.title"`
Is there a way I can prioritize that the title match comes before the description match?
