### ISSUE TITLE
Drop RediSearch index command is not working

### ISSUE THREAD

**Issue by rajanim** [RedisGraph/RedisGraph#1611]
Command : graph.query trxs_graph "call db.idx.fulltext.drop('Transaction')"

```
127.0.0.1:6379> graph.query trxs_graph "call db.idx.fulltext.drop('Transaction')"
Error: Server closed the connection

```

`=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 04 Mar 2021 20:15:25.551 # Redis 6.0.5 crashed by signal: 11
1:M 04 Mar 2021 20:15:25.551 # Crashed running the instruction at: 0x7f7d39351181
1:M 04 Mar 2021 20:15:25.551 # Accessing address: (nil)
1:M 04 Mar 2021 20:15:25.551 # Failed assertion: <no assertion failed> (<no file>:0)
------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(+0x15c181)[0x7f7d39351181]
Backtrace:
redis-server *:6379(logStackTrace+0x32)[0x55a024b6fe02]
redis-server *:6379(sigsegvHandler+0x9e)[0x55a024b704de]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7f7d393ca730]
/lib/x86_64-linux-gnu/libc.so.6(+0x15c181)[0x7f7d39351181]
/usr/lib/redis/modules/redisgraph.so(GraphContext_GetAttributeID+0x1e)[0x7f7d3812e74e]
/usr/lib/redis/modules/redisgraph.so(Schema_RemoveIndex+0x20)[0x7f7d38143950]
/usr/lib/redis/modules/redisgraph.so(Proc_FulltextDropIndexInvoke+0x48)[0x7f7d381441b8]
/usr/lib/redis/modules/redisgraph.so(Proc_Invoke+0xe)[0x7f7d381453ee]
/usr/lib/redis/modules/redisgraph.so(+0x1d08c2)[0x7f7d3811f8c2]
/usr/lib/redis/modules/redisgraph.so(+0x1d552e)[0x7f7d3812452e]
/usr/lib/redis/modules/redisgraph.so(ExecutionPlan_Execute+0x48)[0x7f7d38119018]
/usr/lib/redis/modules/redisgraph.so(+0x1c6428)[0x7f7d38115428]
/usr/lib/redis/modules/redisgraph.so(+0x1fb20d)[0x7f7d3814a20d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7f7d393bffa3]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f7d392ee4cf]
------ INFO OUTPUT ------
# Server
redis_version:6.0.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:a552bef8bac6cf1c
redis_mode:standalone
os:Linux 4.19.121-linuxkit x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0
process_id:1
run_id:cb221a1e3eaaf03d974f56350f8c33665f59ccec
tcp_port:6379
uptime_in_seconds:314
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:4276189
executable:/data/redis-server
config_file:
# Clients
connected_clients:1
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:1
tracking_clients:0
clients_in_timeout_table:0
# Memory
used_memory:68744984
used_memory_human:65.56M
used_memory_rss:91897856
used_memory_rss_human:87.64M
used_memory_peak:70197552
used_memory_peak_human:66.95M
used_memory_peak_perc:97.93%
used_memory_overhead:859314
used_memory_startup:842256
used_memory_dataset:67885670
used_memory_dataset_perc:99.97%
allocator_allocated:69523832
allocator_active:78716928
allocator_resident:82604032
total_system_memory:2086899712
total_system_memory_human:1.94G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.13
allocator_frag_bytes:9193096
allocator_rss_ratio:1.05
allocator_rss_bytes:3887104
rss_overhead_ratio:1.11
rss_overhead_bytes:9293824
mem_fragmentation_ratio:1.34
mem_fragmentation_bytes:23210776
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:16986
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
# Persistence
loading:0
rdb_changes_since_last_save:2000
rdb_bgsave_in_progress:0
rdb_last_save_time:1614888611
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0
# Stats
total_connections_received:2
total_commands_processed:6014
instantaneous_ops_per_sec:0
total_net_input_bytes:11683307
total_net_output_bytes:334296
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:55
evicted_keys:0
keyspace_hits:4021
keyspace_misses:1
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
# Replication
role:master
connected_slaves:0
master_replid:4eb1e146e97ddc17e779cb5b241c8d7abc1985f1
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU
used_cpu_sys:2.154256
used_cpu_user:6.249685
used_cpu_sys_children:0.002469
used_cpu_user_children:0.001333
# Modules
module:name=graph,ver=20214,api=1,filters=0,usedby=[],using=[],options=[]
# Commandstats
cmdstat_command:calls=1,usec=579,usec_per_call=579.00
cmdstat_ping:calls=4000,usec=39930,usec_per_call=9.98
cmdstat_graph.QUERY:calls=2013,usec=538019,usec_per_call=267.27
# Cluster
cluster_enabled:0
# Keyspace
db0:keys=1,expires=0,avg_ttl=0
------ CLIENT LIST OUTPUT ------
id=6 addr=172.17.0.1:63758 fd=8 name= age=302 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY user=default
------ REGISTERS ------
1:M 04 Mar 2021 20:15:25.553 #
RAX:0000000000000000 RBX:0000000000000000
RCX:0000000000000000 RDX:0000000000000000
RDI:0000000000000000 RSI:0000000000000000
RBP:00007f7d38c351f8 RSP:00007f7d34f463d8
R8 :00007f7d38144170 R9 :0000000000000024
R10:0000000000000003 R11:0000000000000001
R12:00007f7d38c351e0 R13:0000000000000001
R14:00007f7d0f6455ec R15:0000000000000000
RIP:00007f7d39351181 EFL:0000000000010283
CSGSFS:002b000000000033
1:M 04 Mar 2021 20:15:25.553 # (00007f7d34f463e7) -> 00007f7d20215b08
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463e6) -> 00007f7d3811f8c2
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463e5) -> 00007f7d21b2f0e0
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463e4) -> 00007f7d381453ee
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463e3) -> 00007f7d321b8a00
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463e2) -> 00007f7d381441b8
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463e1) -> 0000000000000000
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463e0) -> 0000000000000000
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463df) -> 00007f7d2c27f328
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463de) -> 00007f7d3812e3c0
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463dd) -> 0000000000000001
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463dc) -> 00007f7d38143950
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463db) -> 00007f7d30415040
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463da) -> 0000000000000000
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463d9) -> 0000000000000002
1:M 04 Mar 2021 20:15:25.554 # (00007f7d34f463d8) -> 00007f7d3812e74e
------ MODULES INFO OUTPUT ------
# graph_executing commands
graph_command:graph.query call db.idx.fulltext.drop('Transaction')
------ FAST MEMORY TEST ------
1:M 04 Mar 2021 20:15:25.555 # Bio thread for job type #0 terminated
1:M 04 Mar 2021 20:15:25.555 # Bio thread for job type #1 terminated
1:M 04 Mar 2021 20:15:25.555 # Bio thread for job type #2 terminated
*** Preparing to test memory region 55a024cbb000 (2277376 bytes)
*** Preparing to test memory region 55a026b4d000 (270336 bytes)
*** Preparing to test memory region 7f7d0c1fd000 (12582912 bytes)
*** Preparing to test memory region 7f7d0cdfe000 (8388608 bytes)
*** Preparing to test memory region 7f7d0d5ff000 (8388608 bytes)
*** Preparing to test memory region 7f7d0de00000 (8388608 bytes)
*** Preparing to test memory region 7f7d0e600000 (30351360 bytes)
*** Preparing to test memory region 7f7d14000000 (135168 bytes)
*** Preparing to test memory region 7f7d18000000 (135168 bytes)
*** Preparing to test memory region 7f7d1c000000 (3088384 bytes)
*** Preparing to test memory region 7f7d20100000 (55574528 bytes)
*** Preparing to test memory region 7f7d23800000 (8388608 bytes)
*** Preparing to test memory region 7f7d24000000 (135168 bytes)
*** Preparing to test memory region 7f7d28000000 (3080192 bytes)
*** Preparing to test memory region 7f7d2c000000 (3092480 bytes)
*** Preparing to test memory region 7f7d30000000 (8388608 bytes)
*** Preparing to test memory region 7f7d30a00000 (8388608 bytes)
*** Preparing to test memory region 7f7d31200000 (4194304 bytes)
*** Preparing to test memory region 7f7d316ff000 (8388608 bytes)
*** Preparing to test memory region 7f7d32000000 (4194304 bytes)
*** Preparing to test memory region 7f7d324c4000 (2621440 bytes)
*** Preparing to test memory region 7f7d32745000 (8388608 bytes)
*** Preparing to test memory region 7f7d32f46000 (8388608 bytes)
*** Preparing to test memory region 7f7d33747000 (8388608 bytes)
*** Preparing to test memory region 7f7d33f48000 (8388608 bytes)
*** Preparing to test memory region 7f7d34749000 (8388608 bytes)
*** Preparing to test memory region 7f7d34f4a000 (8388608 bytes)
*** Preparing to test memory region 7f7d3574b000 (8388608 bytes)
*** Preparing to test memory region 7f7d35f4c000 (8388608 bytes)
*** Preparing to test memory region 7f7d3674d000 (8388608 bytes)
*** Preparing to test memory region 7f7d36f4e000 (8388608 bytes)
*** Preparing to test memory region 7f7d3774f000 (8388608 bytes)
*** Preparing to test memory region 7f7d387fd000 (12288 bytes)
*** Preparing to test memory region 7f7d38800000 (8388608 bytes)
*** Preparing to test memory region 7f7d391f1000 (16384 bytes)
*** Preparing to test memory region 7f7d393b2000 (24576 bytes)
*** Preparing to test memory region 7f7d393d5000 (16384 bytes)
*** Preparing to test memory region 7f7d396be000 (16384 bytes)
*** Preparing to test memory region 7f7d398e6000 (8192 bytes)
*** Preparing to test memory region 7f7d39913000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.%`

**Comment by swilly22** [comment]
issue fixed, please upgrade.
