### ISSUE TITLE
Issues with multiple or in the edge label filter

### ISSUE THREAD

**Issue by eruffaldi** [RedisGraph/RedisGraph#1612]
With 3 or conditions in an edge label the outcome is not correct and depends on the order:

  a-[:X|:Y|:Z]-b differs from a-[:Z|:Y|:X]-b

While UNION a-[:X|:Y]-b and a-[:Z]-b provides the correct answer.

**Comment by jeffreylovitz** [comment]
Thanks for the report, @eruffaldi.

Can you provide some sample queries to reproduce this problem?

**Comment by eruffaldi** [comment]
MATCH (a) DELETE  (a)
CREATE(a:A {name:"a"})  
CREATE(b:B {name:"b"})  
CREATE(c:C {name:"c"}) 
CREATE(c:D {name:"d"}) 
MATCH (a:A), (b:B)  CREATE (a)-[:X]->(b) RETURN a
MATCH (a:A), (b:C)  CREATE (a)-[:Y]->(b) RETURN a
MATCH (a:A), (b:D)  CREATE (a)-[:Z]->(b) RETURN a
MATCH (a)-[:X|:Y|:Z]->(b) RETURN a,b 
MATCH (a)-[:Y|:Z|:X]->(b) RETURN a,b

**Comment by swilly22** [comment]
Fixed #1618
