### ISSUE TITLE
Full text search how to know which field is matched

### ISSUE THREAD

**Issue by kornha** [RedisGraph/RedisGraph#1619]
Hey,

I just want to say I really appreciate your timely responses and understand this is a huge burden, answering all these questions.

We have a common and considerable use-cause question here;
if I make an index, eg., 
`CALL db.idx.fulltext.createNodeIndex('Movie', 'title', 'description')`
And then, to search I call;
`CALL db.idx.fulltext.queryNodes('Movie', 'book') YIELD node RETURN node`
When I do a full text search on the above, I want to order **the title matches above the description matches**, as for a title we are more concerned with matching that text directly.
Is there a way to accomplish this?

For example, in Neo4j I can do it this way:

`CALL db.index.fulltext.createNodeIndex("titlesAndDescriptions", ["Movie", "Book"], ["title", "description"])`

**Comment by swilly22** [comment]
@kornha I don't see how `CALL db.index.fulltext.createNodeIndex("titlesAndDescriptions", ["Movie", "Book"], ["title", "description"])` would order the title matches above the description,
the mentioned call would simply create a fulltext index over both `Movie` and `Book` indexing properties: `title` and `description`

**Comment by kornha** [comment]
Because in this case, I can simply make a node index just for title, and search that without searching the description one. I do not see how to do the same in the RedisGraph implementation (if I want to **still** have an index on description for searching that separately).
