### ISSUE TITLE
Redisgraph alpine / ubuntu images? 

### ISSUE THREAD

**Issue by lppier** [RedisGraph/RedisGraph#1624]
Hi, I'm using redisgraph in production, and we have vulnerability scans on the containers. 
Would you consider building a alpine docker image like what redis does? 
Or at the very least, using ubuntu 20.04, as they seem to resolve vulnerabilities more promptly? 

Thanks!

**Comment by swilly22** [comment]
Hi @lppier, please see our [Alpine docker file](https://github.com/RedisGraph/RedisGraph/blob/master/Dockerfile.alpine)

**Comment by lppier** [comment]
Thanks for this @swilly22 , we'll give it a try.
