### ISSUE TITLE
Indexes not utilized on constant array inputs

### ISSUE THREAD

**Issue by jeffreylovitz** [RedisGraph/RedisGraph#1635]
The current logic to determine whether a label scan can be replaced by an index scan checks the `FilterTree` for filters where one side is an indexed property and the other side is a constant value.

However, it is possible to have a side that resolves to a constant value at run-time but not when the index scan is created, as in:
```
WITH [1, 2, 3] AS ids UNWIND ids AS id MATCH (a:L {id: id}) RETURN a
```
or
```
WITH [1, 2, 3] AS arr MATCH (a:L {id: arr[0]}) RETURN a
```
In these cases, the index will be unused and we will instead have a LabelScan operation followed by a filter.

To solve this problem, the `utilizeIndices` logic in the optimization phase should simply determine whether the filter expression will resolve to a constant value instead of building the `RSQNode` that forms the RediSearch query. The IndexScan operation itself will then build the query once for each input record, using the constant values provided by the input record.

**Comment by OfirMos** [comment]
Solved in the following commit:
commit 247d747e4abd3996aac1da718d2c609d22df0279
Author: Roi Lipman <swilly22@users.noreply.github.com>
Date:   Sun Apr 25 13:26:09 2021 +0300

    Runtime index utilisation (#1641)

    * WIP migrate search query composition from utilize_indices to a utility file

    * [WIP] runtime index query construction

    * resolve compile-time unknowns

    * entity functions are reduceable if the entity is known

    * test index runtime query construction

    * normalize filter, make sure filtered entity is on the left hand side

    * free index scan filter tree

    * return none converted filters

    * WIP

    * WIP

    * index none indexed field names

    * pull from index until unresolved filter pass or iterator deplete

    * test index scan over none indexable values

    * remove include of deleted file

    * rebase conflicts resolved

    * address PR comments

    * change index separator
