### ISSUE TITLE
RedisSearch Stop Words Not Working

### ISSUE THREAD

**Issue by sidenAlex** [RedisGraph/RedisGraph#1638]
Hello,

I have noticed a change in behavior from RedisSearch stop words.
Stop words should be ignored and not considered when searching and indexing per this documentation: https://oss.redislabs.com/redisearch/Stopwords/

However, I noticed for RedisGraph this only works on indexing, but not on search.

For example:
`CALL db.idx.fulltext.createNodeIndex('movie', 'title')`
`CALL db.idx.fulltext.queryNodes('movie', 'big short') YIELD node return node.title`
This returns: The Big Short.
Now if I call:
`CALL db.idx.fulltext.queryNodes('movie', 'the big short') YIELD node return node.title`
This returns nothing matched. According to the above link the stop word 'the' should not be searched. 

Might I also ask if there will be a way to remove stop words?
Please guide me if this is a user error.

**Comment by swilly22** [comment]
Hi @sidenAlex, thank you for brining this up, we're investigating.

**Comment by tnp0** [comment]
I'm seeing the same problem. When searching, I'm having to remove stop words prior to passing to redisgraph as a workaround, but this is very limiting and has it's own major drawbacks.

`men in black` -> no results
`"men in black"` -> no results
`men black` -> found `men in black` and `men driving a black car`

**Comment by ashtul** [comment]
BTW, [this is the default stopword list](https://oss.redislabs.com/redisearch/Stopwords/#default_stop-word_list).

**Comment by sidenAlex** [comment]
Hello @swilly22 , I was hoping to circle back on this and related "token characters" eg,:

```
//stopwords
	"a": true, "is": true, "the": true, "an": true, "and": true, "are": true, "as": true, "at": true, "be": true, "but": true,
	"by": true, "for": true, "if": true, "in": true, "into": true, "it": true, "no": true, "not": true, "of": true, "on": true,
	"or": true, "such": true, "that": true, "their": true, "then": true, "there": true, "these": true, "they": true, "this": true,
	"to": true, "was": true, "will": true, "with": true,
//token chars
	",": true, ".": true, "<": true, ">": true, "{": true,
	"}": true, "[": true, "]": true, "\"": true, "'": true,
	":": true, ";": true, "!": true, "@": true, "#": true,
	"$": true, "%": true, "^": true, "&": true, "*": true,
	"(": true, ")": true, "-": true, "+": true, "=": true, "~": true,
```

The stopwords and token characters have made it difficult for our usage of RedisSearch on RedisGraph. I am wondering if treating each of these items like normal words/letters is on the roadmap, and if so, the expected timeline for them?

Thank you all so much, you do excellent work.
