### ISSUE TITLE
List all graph names in RedisGraph

### ISSUE THREAD

**Issue by movingname** [RedisGraph/RedisGraph#1642]
Would it be possible to add a function that lists all graph names in RedisGraph? We hope to support a user case in which a user can select one specific graph, and then see a visualization of it.

Thanks!

Related discussion: https://forum.redislabs.com/t/list-all-graph-names/1237

**Comment by movingname** [comment]
Many many thanks! It really helps our product.

**Comment by swilly22** [comment]
@movingname, can you please share some details on your use-case?

**Comment by movingname** [comment]
Hi @swilly22, so we are developing a product to show a knowledge graph. The knowledge graph has several versions, one for productions and multiple for research & test. For developers and researchers we hope to let them select which version then want to see. Each version is stored as a separate graph inside a RedisGraph instance. That's why I requested this feature:)
