### ISSUE TITLE
Any plans to support more math functions in cypher queries?

### ISSUE THREAD

**Issue by micahscopes** [RedisGraph/RedisGraph#1652]
So first off, I really love redisgraph, it's amazing.

My question: are there any plans to support additional math functions in cypher queries?  I'm currently in need of `sqrt`, but I'm sure at some point others would be handy too.

**Comment by swilly22** [comment]
Hi @micahscopes, thank you for the kind words,
`sqrt` should be fairly easy to add, I'll close this ticket once it is.
May I ask what's your use case ?

**Comment by micahscopes** [comment]
Hey @swilly22!
Well, in my specific case I am computing a loss function over various paths, and for each path in order to get the optimal value of the loss function I need to take a `sqrt` of the product of some edge weights.  Currently I have to do this in the application after the query, but I was thinking about just how nice it'd be if I could do it in the query itself, like to do aggregate queries over optimal values of the loss function for each path in a given set of paths.

More generally though I just love to play with graphs and math, so having a bigger set of math functions to throw at problems never hurts!  I could see exponential and trig functions being nice to have.  I was also surprised that the neo4j cypher spec doesn't mention a `pow` function.  But I think that one would be great to have too.  I'm currently manually computing powers of edge weights by repeating them e.g. `(...)*(...)*(...)` and that makes my queries a little tougher to read and write.
