### ISSUE TITLE
add power function

### ISSUE THREAD

**Issue by swilly22** [RedisGraph/RedisGraph#1654]
`RETURN pow(x, y)` 
The pow() functions compute x raised to the power y.

#1652

- [ ] tests: TCK ?
- [ ] tests: tests/unit/test_arithmetic_expression.cpp
- [ ] docs: docs/commands.md

**Comment by jeffreylovitz** [comment]
Note that Cypher supports exponentiation with the `^` operator, as in:
`RETURN 2 ^ 3`
