### ISSUE TITLE
`redis-cli --csv` creates files without newlines

### ISSUE THREAD

**Issue by abevoelker** [RedisGraph/RedisGraph#1658]
I've been doing my RedisGraph queries like this to produce some kind of machine-readable output:

```
$ redis-cli --csv GRAPH.QUERY Donations "MATCH (d:Person)-[:contributesTo*0..1]-(d2:Person)-[:contributesTo]->(r:Person) WHERE r.special = 'T' AND d2.party IS NULL AND d.party IS NULL AND d.id <> d2.id RETURN DISTINCT d.id, d2.id, r.id" > foo.csv
```

It's generating large CSV files, but they have no newlines:

```
$ du -sh foo.csv
948M    foo.csv

$ wc -l foo.csv
1 foo.csv

$ head -c 100 foo.csv
"d.id","d2.id","r.id","X00390641","X00370056","X00661868","X00390641","X00370056","X00661868","X0072
```

I can do [a little cleanup](https://unix.stackexchange.com/a/446401/17420) to fix the file:

```
$ tr ',' '\n' <foo.csv |paste -sd',,\n' > bar.csv

$ head -c 100 bar.csv
"d.id","d2.id","r.id"
"X00390641","X00370056","X00661868"
"X00390641","X00370056","X00661868"
```

However then I noticed at the end of these files is some debug output I need to trim:

```
$ tail -n 2 bar.csv
"X00084871","X00412791","X00412304"
"Cached execution: 0","Query internal execution time: 37812.206287 milliseconds"
```

I also noticed if I make a mistake in my query, it gets output to my file/stdout instead of stderr:

```
$ redis-cli --csv GRAPH.QUERY Donations "MATCH asdflkj" > baz.csv

$ cat baz.csv
ERROR,"errMsg: Invalid input at end of input: expected '=' line: 1, column: 14, offset: 13 errCtx: MATCH asdflkj errCtxOffset: 13"
```

Is there a better way to get machine-readable output from ad-hoc RedisGraph queries? Curious how other people are doing it or what I could do differently

**Comment by swilly22** [comment]
Hi @abevoelker, I'm not familiar with the `--csv` flag but, it seems like it treats array replies as if they were a single row in a CSV file, which seems reasonable to me, a reply from redis-server is a row in the csv file and each element in the reply is mapped to its own column,

```
SET a "A"
SET a "A"

**Comment by abevoelker** [comment]
Thanks for the clarification. I see what you mean. I now see this seems to be [an old complaint](https://groups.google.com/g/redis-db/c/l0Z_XrsHpmI/m/WF1HJstrwq8J) with redis-cli, although apparently pretty low traffic.

I suppose most people are probably using a higher level language binding like Python, Ruby, etc. so they don't use this option. Going to close this and just use Ruby or Python when I get a better handle on my queries. Thanks!
