### ISSUE TITLE
RedisGraph + RediSearch fails to search for strings with special symbols

### ISSUE THREAD

**Issue by kumskov** [RedisGraph/RedisGraph#1674]
I'm running redisgraph:2.4.2 docker image with redisearch 2.0.0 module loaded. I run queries from Redis-cli.

I want to query fields that contain special chars (@ in my example), but I fail to do so.

I've created an example graph demonstrating my issue. 

```
GRAPH.QUERY gr "CREATE (:Person {name:'John Doe', handle:'@jdoe', email:'john@mail.server})"
GRAPH.QUERY gr "CREATE (:Person {name:'Adam Smith', handle:'@asmith', email:'adam@mail.server'})"
GRAPH.QUERY gr "CALL db.idx.fulltext.createNodeIndex('Person', 'handle', 'email')"
```

Querying handles kinda works if you strip leading @ in the query:

```
127.0.0.1:6379> GRAPH.QUERY gr "CALL db.idx.fulltext.queryNodes('Person', 'asmith')"
1) 1) "node"
   2) "score"
2) 1) 1) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Adam Smith"
               2) 1) "handle"
                  2) "@asmith"
               3) 1) "email"
                  2) "adam@mail.server"
      2) "2"
3) 1) "Cached execution: 1"
   2) "Query internal execution time: 1.621800 milliseconds"
```

But if I run my query with escaped @ I get nothing

```
127.0.0.1:6379> GRAPH.QUERY gr "CALL db.idx.fulltext.queryNodes('Person', '\\@asmith')"
1) 1) "node"
   2) "score"
2) (empty array)
3) 1) "Cached execution: 1"
   2) "Query internal execution time: 0.464500 milliseconds"
```

I can't seem to get any results from email querying no matter how I try. My first guess was to escape @, but it doesn't work.

```
127.0.0.1:6379> GRAPH.QUERY gr "CALL db.idx.fulltext.queryNodes('Person', 'adam\\@mail.server')"
1) 1) "node"
   2) "score"
2) (empty array)
3) 1) "Cached execution: 1"
   2) "Query internal execution time: 1.447000 milliseconds"
```

Completely stripping special characters from query string doesn't seem to work either.

Is there any way I can query those fields?

**Comment by emmanuelkeller** [comment]
As the full-text tokenization includes both ```@``` and ```.```, the email address ```adam@mail.server``` is stored in the full-text index as three words: ```adam```, ```mail``` and ```server```.

On the query part, escaping the ```@``` means that the full-text engine is going to search for the words ```adam@mail``` and ``` server```, which does not match.

The workaround to this is escaping the email address in the node (at indexing time):

```
GRAPH.QUERY gr "CREATE (:Person {name:'Adam Smith', handle:'\\@asmith', email:'adam\\@mail\\.server'})"
```

And in the query:

``` 
GRAPH.QUERY gr "CALL db.idx.fulltext.queryNodes('Person', 'adam\\@mail\\.server')"
```

You may also use a dedicated for the full-text part, to avoid escaping everything:

```
GRAPH.QUERY gr "CREATE (:Person {name:'Adam Smith', handle:'@asmith', email:'adam@mail.server', fulltext:'\\@asmith adam\\@mail\\.server'})"
```

**Comment by kumskov** [comment]
Thanks @emmanuelkeller , your reply helped a lot!
