### ISSUE TITLE
multiple algo.BFS call crash redis

### ISSUE THREAD

**Issue by bingo-ctrl** [RedisGraph/RedisGraph#1676]
Hello @swilly22 . redisgraph is amazing 👋.we are starting to using redisgraph,but we got some problems,which crash redis ,it will be very appreciate if you could take a look at this.

simple reproduce steps:

1. docker run -p 6379:6379 -it --rm redislabs/redisgraph
2. GRAPH.QUERY MotoGP "CREATE (:Rider {name:'Valentino Rossi'})-[:rides]->(:Team {name:'Yamaha'}), (:Rider {name:'Dani Pedrosa'})-[:rides]->(:Team {name:'Honda'}), (:Rider {name:'Andrea Dovizioso'})-[:rides]->(:Team {name:'Ducati'})"
3. GRAPH.QUERY "MotoGP" "MATCH (n0:Rider {name: 'Valentino Rossi'}) CALL algo.BFS(n0, 3, NULL) YIELD nodes as ns1 MATCH (n1:Rider {name: 'Andrea Dovizioso'})  CALL algo.BFS(n0, 3, NULL)  YIELD  nodes  as ns2  return ns1"

**Comment by swilly22** [comment]
@bingo-ctrl, thank you for reporting, a fix has just been merged to our master branch and will be available soon on our `edge` docker image.

**Comment by bingo-ctrl** [comment]
@swilly22 , Awesome,guys! thanks for your quick action and effort,💓.

**Comment by bingo-ctrl** [comment]
@swilly22 , I noticed a new version 2.4.4 has been released,which contains a fix for this issue,many thanks for all your efforts,but the crash still exists when we do test on the lastest redisgraph,it will be grateful if you could take look at the issue #1701

**Comment by swilly22** [comment]
@bingo-ctrl sorry for the mess, we'll look into it,
I'll continue reporting on the other issue.
