### ISSUE TITLE
algo.BFS only support outgoing relationships

### ISSUE THREAD

**Issue by bingo-ctrl** [RedisGraph/RedisGraph#1689]
Hi, we want to ensure whether the algo.BFS only support outgoing relationship,thanks in adance.
1. GRAPH.QUERY DEMO_BFS "CREATE  (:element{name:'act'})-[:IsElementOf]->(:fact{name:'act may be a civil wrong'})<-[:IsElementOf]-(:element{name:'civil wrong'})"
2. GRAPH.QUERY "DEMO_BFS" "MATCH (n0:fact{name: 'act may be a civil wrong'}) CALL algo.BFS(n0, 3, NULL) YIELD nodes as ns0 RETURN ns0"

step 2 return empty set, Is that ok?

**Comment by jeffreylovitz** [comment]
Hi @bingo-ctrl,

You are correct, `algo.BFS` only traverses outgoing relationships from each node. The results you're retrieving are expected.

**Comment by bingo-ctrl** [comment]
@jeffreylovitz thanks for your clarification.
