### ISSUE TITLE
shortestPath crash redis

### ISSUE THREAD

**Issue by bingo-ctrl** [RedisGraph/RedisGraph#1695]
Hi, please take a look at the tricky issue,you could use our masking data to reproduce the issue.

this is the data:[shortestPathCrash.zip](https://github.com/RedisGraph/RedisGraph/files/6465101/shortestPathCrash.zip)

1.docker run -p 6379:6379 -it --rm redislabs/redisgraph:latest

2. redisgraph-bulk-loader GRAPH_DEMO  --enforce-schema  -n /tmp/nodes/element.csv -n /tmp/nodes/fact.csv -r /tmp/rel/FormOf.csv -r /tmp/rel/IsA.csv -r /tmp/rel/IsElementOf.csv -r /tmp/rel/RelatedTo.csv -r /tmp/rel/RootOf.csv -r /tmp/rel/Synonym.csv

3. GRAPH.QUERY "GRAPH_DEMO" "MATCH (n0:element{name: 'summons'}),(n1:element {name: 'heaving'}) with shortestPath((n0)<-[*]-(n1)) as p return p"
![image](https://user-images.githubusercontent.com/30015767/117952216-875cfc00-b347-11eb-9182-5833a09ca0c0.png)

4. GRAPH.QUERY "GRAPH_DEMO" "MATCH (n0:element{name: 'summons'}),(n1:element {name: 'heaving'}) with shortestPath((n0)-[*]->(n1)) as p return p"

As we could see, step 3 give us right result,BUT redis will be crashed,even we only reverse the direction between n0 and n1 in the step 4.

**Comment by jeffreylovitz** [comment]
Hi @bingo-ctrl,

Thanks for the report! This crash is occurring because the `(n0)-[*]->(n1)` traversal is erroneously reporting a zero-length path, and subsequently trying to read an invalid node.

I'm not immediately sure why this is the case, but will make time to look into it soon!
