### ISSUE TITLE
Design question about IDs

### ISSUE THREAD

**Issue by patelsan** [RedisGraph/RedisGraph#1697]
I have a quick question about a comment about ids - `Internal IDs are returned with nodes and relations, but these IDs are not immutable. After entities have been deleted, higher IDs may be migrated to the vacated lower IDs.` on page https://oss.redislabs.com/redisgraph/result_structure/. Would you say it's better to avoid using the system assigned Ids and instead assign and use custom GUID/ UUID as part of `Properties` of nodes or edges? If yes, any performance implications/ considerations to keep in mind? Thanks for all the work on RedisGraph!

**Comment by jeffreylovitz** [comment]
Hi @patelsan,

To a degree, this depends on your workflow. If you don't have a delete-heavy design and are okay with IDs that aren't monotonically increasing, it's safe to rely on internal IDs.

The benefit of this, though, is only a small amount of space saved. In the general case, I would say it's safer to create an `id` property that you assign! This property should definitely be indexed on node labels, but other than that, no considerations spring to mind.

**Comment by patelsan** [comment]
Thanks for the inputs @jeffreylovitz !
