### ISSUE TITLE
Appendonly disabled redisgraph module

### ISSUE THREAD

**Issue by mdazartash** [RedisGraph/RedisGraph#1704]
i am using redisgraph for a while now.i want to add AOF persistency. the appendonly command disables redisgraph module. redisinsight will also tell u that.
if be removed command will work correctly. 
this works
docker run -p 6379:6379 --volume=D:\docker\data:/data --name redisg  -it --rm redislabs/redisgraph:edge
but in this one graph is off
docker run -p 6379:6379 --volume=D:\docker\data:/data --name redisg  -it --rm redislabs/redisgraph:edge --appendonly yes

**Comment by jeffreylovitz** [comment]
Hi @mdazartash,

This is a Docker CMD/ENTRYPOINT issue - your `appendonly` directive causes the module to not get loaded because it overwrite the default command. You can resolve this by adding the load directive explicitly:
```
 docker run -p 6379:6379 --volume=D:\docker\data:/data --name redisg -it --rm redislabs/redisgraph:edge --appendonly yes --loadmodule src/redisgraph.so
```

**Comment by GnaneshKunal** [comment]
@mdazartash 

For redisgraph container, this one does it:

`docker run -p 6379:6379 --volume=D:\docker\data:/data --name redisg -it --rm redislabs/redisgraph:edge --appendonly yes --loadmodule /usr/lib/redis/modules/redisgraph.so`

**Comment by mdazartash** [comment]
Thank u guys, it worked.
