### ISSUE TITLE
BGSAVE waits for synchronisation lock forever

### ISSUE THREAD

**Issue by OfirMos** [RedisGraph/RedisGraph#1706]
When BGSAVE forks while a graph's matrix synchronisation locks is taken, the synchronisation lock in the child never gets freee so the process blocks forever.

One solution is to not synchronise the Matrix under lock (using Nope synchronisation policy) so the synchrinization will take place on the iterator creation without a lock.

This still leaves us with other problem that rose hile investigating the bug:
When the BGSAVE fork took place while matrix synchronisation took place, the child process gets a matrix which is in an invalid state.

The suggested solution is to get the write lock before the call for fork() and releasing it afte the call finishes.
This will also resolve the original bug, so the synchronisation policy shouldn't be changed.
This solution have been implemented once and was reverted for some reason:
[https://github.com/RedisGraph/RedisGraph/commit/72daf27c368e29dce5d3404a349d7581ddf4684a](url)
Need to resubmit this change.

(RED-56424)

**Comment by swilly22** [comment]
Solved by #1709
