### ISSUE TITLE
Flatten (similar to neo4j reduce(output = [], ...))

### ISSUE THREAD

**Issue by Rambatino** [RedisGraph/RedisGraph#1713]
We have a slightly complex query and we're struggling to flatten the results without doing multiple UNWINDs that lead to cartesian products.

The query at the moment is this:

``` js
MATCH p1 = (main_m:Measure {value: "gender"})-[cap1:CAPTURES]->(m:Measurement)-[d1:MEASURES {dimension: "gender"}]->(c1:Constant {value:"Female"})
OPTIONAL MATCH p2 = (:Measure)-[cap:CAPTURES]->(m)-[:EQUALS*1..]->(n:Measurement)-[d2:MEASURES]->(c2:Constant)
WITH collect(distinct c1)+collect(distinct c2) as c, main_m, collect(distinct p2) as p2
RETURN reduce(output = [], [path in p2 | [r in relationships(path) WHERE type(r) = "CAPTURES" | output + r.storage_key]] )
```

The last part doesn't return with the correct shape, it's of the form: `[[''], [''], ['']]` and ideally we'd flatten that somehow. Is it possible? There is a reduce in the neo4j docs but it doesn't look like it's implemented here.

In fact, it may be useful to rewind and tell you the actual problem we're dealing with.

``` js
MATCH p1 = (main_m:Measure {value: "gender"})-[cap1:CAPTURES]->(m:Measurement)-[d1:MEASURES {dimension: "gender"}]->(c1:Constant {value:"Female"})
OPTIONAL MATCH p2 = (:Measure)-[cap2:CAPTURES]->(m)-[:EQUALS*1..]->(n:Measurement)-[d2:MEASURES]->(c2:Constant)
WITH collect(distinct c1)+collect(distinct c2) as c, main_m, collect(m) + collect(n) as m
OPTIONAL MATCH p3 = (main_m)-[:EQUALS*0..]->(:Measure)-[d3:MEASURES]->(m3:Measurement)-[:CAPTURES]->(c)
UNWIND c AS c
RETURN [elem IN collect(m3) + m | elem.storage_key]
```
So we find the unique set of constants and unwind that and pass that into p3 path and use that to do the lookups. 

The return has to be a single row. Now you can use collect to do that, but we're struggling to:

* RETURN m + collect(m3) i.e. append the lists together
* Pass the cap1 and cap2 through, as performance drops substantially when more variables are passed through with WITH (even if you do a `collect(distinct cap1) + collect(distinct cap2) as cap` to reduce the dimensionality

So _ I think _ flatten would solve some of the issues here alongside the list comprehension.

**Comment by AviAvni** [comment]
@Rambatino sorry it took a lot of time to response
this is a very complex query and I think it can be simplified to achieve the results, have better performance and be more readable
can you please share what is the purpose of your query?

**Comment by Rambatino** [comment]
Gosh i can't even remember now! Sorry :D
