### ISSUE TITLE
UNWIND -> MATCH Does not Maintain Order Integrity

### ISSUE THREAD

**Issue by sidenAlex** [RedisGraph/RedisGraph#1752]
Example:

`UNWIND ['ID|1', 'ID|2', 'ID|3'] AS id MATCH q=(m:movie {ID:id})-[*0..1]->(n) RETURN m, COLLECT(NODES(q)), COLLECT(RELATIONSHIPS(q))`

Expected output; if matched, object(ID|1) , object(ID|2) , object(ID|3). 
Actual Output; random order integrity

Also tried to manually enforce the ordering with an index;

`WITH ['ID|1', 'ID|2', 'ID|3'] AS num UNWIND range(0, size(num) - 1) as index MATCH q=(m:movie {ID:num[index]})-[*0..1]->(n) with index, m, q ORDER BY index ASC RETURN m, COLLECT(NODES(q)), COLLECT(RELATIONSHIPS(q))`

Is there a way where I can fix the order based on an input array?

**Comment by jeffreylovitz** [comment]
Using a trivial data set, I could not reproduce this problem, but it might occur with more complex data.

I think you're applying your `ORDER BY` clause prematurely, try running the following:
```
WITH ['ID|1', 'ID|2', 'ID|3'] AS num UNWIND range(0, size(num) - 1) as index MATCH q=(m:movie {ID:num[index]})-[*0..1]->(n) RETURN m, COLLECT(NODES(q)), COLLECT(RELATIONSHIPS(q)) ORDER BY index ASC
```

**Comment by sidenAlex** [comment]
Hey this worked for us, thank you!
