### ISSUE TITLE
Add alternative delete routines for nodes and implicit edges

### ISSUE THREAD

**Issue by jeffreylovitz** [RedisGraph/RedisGraph#1786]
The optimization #1783 dramatically improves performance of deleting explicitly named edges, as in:
`MATCH ()-[e]->() DELETE e`
This optimization is applied when at most 4 edges are being deleted, and improves performance in testing from 670ms to 2ms.

We should replicate this optimization for the deletion of nodes and the implicit deletion of edges that have deleted nodes as an endpoint.

Additionally, the bulk delete routine should be investigated to determine whether we can improve performance in the case of deleting larger numbers of entities.

**Comment by swilly22** [comment]
@jeffreylovitz please validate if this issue is still relavent now that we have Delta-Matrices
