### ISSUE TITLE
Does redisGraph support Index seek ?

### ISSUE THREAD

**Issue by Mon0Man** [RedisGraph/RedisGraph#1805]
neo4j doc: https://neo4j.com/docs/cypher-manual/current/execution-plans/operators/#query-plan-node-index-seek

![cypher-execution-plan-operators](https://user-images.githubusercontent.com/86112502/123977733-41a6d200-d98d-11eb-9923-c88c89d60600.png)

I created an Index on actor id: `GRAPH.QUERY test "CREATE INDEX ON :Actor(id)"`

```
GRAPH.EXPLAIN test "MATCH (a:Actor {id: 'XOr41oi6ZTw1'}) RETURN a"

1) "Results"
2) "    Project"
3) "        Index Scan | (a:Actor)"
```

Does this mean it has to scan though the entire index ? what if id is unique ?

Thanks.

**Comment by jeffreylovitz** [comment]
Hi @Mon0Man,

RedisGraph has one `Index Scan` operation that performs the equivalent work of `Index Seek` and `Index Scan`. It's my understanding that the latter of these is used when a range of the index must be iterated over, and the former is

**Comment by Mon0Man** [comment]
@jeffreylovitz, why the reopen ?
