### ISSUE TITLE
MATCH .. CREATE works, but MATCH .. MERGE has syntax error?

### ISSUE THREAD

**Issue by davisford** [RedisGraph/RedisGraph#181]
```
127.0.0.1:6379> GRAPH.QUERY authz "MATCH(o1:org {id: 1}) CREATE (p:posusers)-[:member]->(o1)"
1) (empty list or set)
2) 1) Labels added: 1
   2) Nodes created: 1
   3) Relationships created: 1
   4) "Query internal execution time: 0.236034 milliseconds"
```

```
127.0.0.1:6379> GRAPH.QUERY authz "MATCH(o1:org {id: 1}) MERGE (p:posusers)-[:member]->(o1)"
(error) Syntax error at offset 28 near 'MERGE'
```

**Comment by swilly22** [comment]
Hey @davisford,
Currently RedisGraph does not supports mixing MATCH and MERGE.
This is something we should defiantly support soon.

**Comment by ediphy-azorab** [comment]
`GRAPH.QUERY authz "MERGE (o1:org {id: 1}) MERGE (p:posusers)-[:member]->(o1)"` doesn't seem to work either, unfortunately

**Comment by swilly22** [comment]
@ediphy-azorab correct, we do not support multiple occurrences of clauses for the time being, I suggest combining these two together into a single MERGE clause, or issue multiple queries.

**Comment by ediphy-azorab** [comment]
@swilly22 I think that would have different behaviour to that query? The double merge should first get or create the `org` and then create a relationship between all `posusers` and that `org`. My reading of "When using MERGE on full patterns, either the whole pattern matches, or the whole pattern is created" suggests that doing the whole query in one line will create a new `org` vertex even if one with the right `id` already exists.

For now I guess I'm going to be doing a lot of `MATCH ... CREATE` :)

**Comment by swilly22** [comment]
You're correct! sorry for misleading.
I'll update once we'll support multiple clauses of the same type within a single query.

**Comment by wuyanxing** [comment]
Now， support mixing MATCH and MERGE?

**Comment by swilly22** [comment]
@wuyanxing, yet, we're working on replacing our current parser, once that work is done we'll be able to mix MATCH and MERGE, I'll update here once that's done.

**Comment by wuyanxing** [comment]
Will it be fully supported with cypher syntax? just like neo4j

**Comment by swilly22** [comment]
@wuyanxing as far as the parsing goes, yes.
I'll have to see what are the implications on our execution plan.

**Comment by hobofan** [comment]
@jeffreylovitz Any update on this? :)

I'm currently adding support for RedisGraph to a project of mine which was previously only targeting Neo4J, and ran into this limitation. I think I've managed to work around it by splitting it up into individual statements, but in the future it would be great to be able to use a more expressive syntax and use the same queries across both databases.

**Comment by jeffreylovitz** [comment]
Sorry, I forgot to update on this issue!

We've moved robust MERGE support up on our roadmap, but the safe ETA is end of 2019. Hopefully we'll manage to implement this sooner, but it can't be guaranteed!

**Comment by hobofan** [comment]
Thanks, for the update. That's great to hear! Overall very impressed with the recent changes (indexing via RedisSearch and improved Cypher coverage)!

**Comment by MichaelHirn** [comment]
@jeffreylovitz Are there any news on `MATCH ... MERGE` support?

We decided that we want to go full in on RedisGraph (instead of Neo4J) and ported everything successfully over to work with RedisGraph ... except for `MATCH ... MERGE` which is mission-critical for us and we weren't able to find a work-around for it. It's the only missing part and we would love to move forward with RedisGraph, but EOY is too far out for us to wait for it.

Hoping for good news 🤞🤞🤞

**Comment by MichaelHirn** [comment]
Oh wow, that's fantastic. We can't wait to try it out!

**Comment by swilly22** [comment]
Support for the MERGE clause (and mixing different clauses with merge) has just been merged :D into the master branch, documentation been updated.

Please report any issue encountered. thanks!
