### ISSUE TITLE
[CRASH] redisgraph crashed

### ISSUE THREAD

**Issue by hector690** [RedisGraph/RedisGraph#1914]
redisgraph is crashed while executing the following command and crash report is attached

GRAPH.QUERY "roster" "CYPHER contacts=[RosterUser(msisdn=901, domain=d1, nick=n1, isBip=false), RosterUser(msisdn=902, domain=d2, nick=n2, isBip=true), RosterUser(msisdn=903, domain=d3, nick=n3, isBip=false), RosterUser(msisdn=904, domain=d4, nick=n4, isBip=true)] UNWIND $contacts AS c MERGE (u:user{msisdn:'906333101331'}) ON CREATE SET u.domain = 'alcar.ihgzt.com.tr', u.isBip = true ON MATCH SET u.domain = 'alcar.ihgzt.com.tr', u.isBip = true MERGE (:user{msisdn:c.msisdn}) MERGE (u)-[r:knows{nick:c.nick}]->(c)"
[redisgraph_crash.txt](https://github.com/RedisGraph/RedisGraph/files/7105726/redisgraph_crash.txt)

**Comment by swilly22** [comment]
Hi @hector690, thank you for reporting this,
Please note you're using an undefined function: `RosterUser` in your `contacts` parameter.
Obviously this shouldn't crash the server...
