### ISSUE TITLE
UNWIND  returns only subset of the list from the array 

### ISSUE THREAD

**Issue by techpanga** [RedisGraph/RedisGraph#1920]
This query returns only 16 records where i have about 800. unwind is having unexpected behavior

MATCH (n:OrderDetails) unwind n.keywords as kw return kw,count(n)

**Comment by jeffreylovitz** [comment]
Hi @techpanga,

Can you provide sample data to reproduce this issue?

**Comment by techpanga** [comment]
Hi @jeffreylovitz ,

Thanks for quick response. The issue seems to be related to with data loading, 

I reloaded data with out newline characters in description attribute in the CREATE command and now it is able to present all. I am not sure about how the newline characters in the create command affected this.

Thanks again.
