### ISSUE TITLE
How close the cypher implementation to the Neo4J

### ISSUE THREAD

**Issue by techpanga** [RedisGraph/RedisGraph#1921]
Hi All,

This is amazing concept and looking forward for the stable version of the RedisGraph for production ready.

I see good performance benefits by running in memory and persisting to disk using redis capabilities.

Could someone advise the production readiness of this module? How close the cypher implementation is towards the Neo4J?

I could not find the memory implementation of Neo4J and our project is implemented using neo4j and would like to migrate to redisgraph for best query performance.

Many keywords are yet to be supported. what would be the timeline of these additional keywords of cypher implementation.

**Comment by LiorKogan** [comment]
> Could someone advise the production readiness of this module?

RedisGraph is production-ready and used in production by many companies and organizations. Many are using RedisGraph in high-availability configurations (using [Redis Sentinel](https://redis.io/topics/sentinel) or [other configurations](https://docs.redis.com/latest/rs/concepts/high-availability/) on Redis Enterprise).

> How close the cypher implementation is towards the Neo4J?

RedisGraph follows the Cypher query language reference, but the coverage, while continuously being extended, is not complete.
