### ISSUE TITLE
Question: How to get paths of two vertex(node)?

### ISSUE THREAD

**Issue by Mrliu8023** [RedisGraph/RedisGraph#1956]
A path like `A -IS_PART_OF->B-LOCATION_TO->C`, give vertex `A` and `C`, are there any way to find this path?

**Comment by jeffreylovitz** [comment]
Hi @Mrliu8023,

The general syntax you want is:
`MATCH p=(A)-[*]->(B) RETURN p`
This will find all paths of any length between vertices `A` and `C` and return them. (If using one of the [client libraries](https://oss.redis.com/redisgraph/clients/#currently-available-libraries) they will be returned with full node and edge details, `redis-cli` will only print IDs).

If you know that you want to match the exact pattern you provided, the syntax is:
`MATCH p=(A)-[:IS_PART_OF]->(B)-[:LOCATION_TO]->(C) RETURN p`

**Comment by Mrliu8023** [comment]
> Hi @Mrliu8023,
> 
> The general syntax you want is:
> `MATCH p=(A)-[*]->(B) RETURN p`
> This will find all paths of any length between vertices `A` and `C` and return them. (If using one of the [client libraries](https://oss.redis.com/redisgraph/clients/#currently-available-libraries) they will be returned with full node and edge details, `redis-cli` will only print IDs).
> 
> If you know that you want to match the exact pattern you provided, the syntax is:
> `MATCH p=(A)-[:IS_PART_OF]->(B)-[:LOCATION_TO]->(C) RETURN p`

Thanks~
