### ISSUE TITLE
String function replace

### ISSUE THREAD

**Issue by nehz** [RedisGraph/RedisGraph#1965]
Any plans to support the replace() function for strings?
Thanks!

**Comment by swilly22** [comment]
@nehz, yeah, this shouldn't take too long,
May I ask what are you using RedisGraph for?

**Comment by nehz** [comment]
Building a calculation engine of sorts which uses Nodes as dependencies for calculations - fully versioned and immutable. One of the issues was that Node IDs won't be available in self-referential scenarios and I it needed to all happen in that one "commit"/version - so was thinking of using placeholders and replace with ID(node) during query execution.

Would like to take opportunity to thank you guys for RedisGraph, it is a wonderful product that fits certain needs!

**Comment by swilly22** [comment]
Thanks for sharing,
graph entity ID is available as soon as the entity is created, e.g.
`CREATE (a) WITH a MATCH (b) WHERE b.v = ID(a)`

**Comment by nehz** [comment]
Yup so I have a string "formula" which uses IDs as references e.g
`Node.formula = "[1] + [2]", e.g something like this:
`CREATE (a) SET a.formula = replace({formula}, {placeholder}, ID(a)) RETURN ID(a)`

**Comment by swilly22** [comment]
I see, yeah this should work once we introduce the replace function, but you can also use string concatenation:
`CREATE (a) SET a.formula = "1 + " +  tostring(ID(a))" RETURN ID(a)`

**Comment by swilly22** [comment]
`Replace` been introduced, should be available on the `edge` docker image shortly.
`docker run -p 6379:6379 -it --rm redislabs/redisgraph:edge`
