### ISSUE TITLE
Is internal ids stable with AOF restore?

### ISSUE THREAD

**Issue by nehz** [RedisGraph/RedisGraph#1967]
It is mentioned that IDs are not immutable with deletes: https://oss.redis.com/redisgraph/result_structure/
But does restoring from AOF have the potential for moving IDs around, assuming no deletes have occurred? 
I would assume yes as the ID allocation is deterministic and should be replicated with the exact same order, however, would be great to get some clarification.

Thanks!

**Comment by swilly22** [comment]
Generally speaking I wouldn't recommend relying on internal IDs as the guarantees currently in-place might be subject to change
that said loading from AOF should maintain the original entity IDs, unless a random parameter was added to a query, e.g.
`UNWIND [0.3, 0.6] AS X WHERE X < random() CREATE ()`

**Comment by nehz** [comment]
Thanks, that makes sense. Would there be a small performance penalty with using your own IDs vs internal IDs? And are there any helpers to make it easier (e.g AUTO INCREMENT in SQL) ?

**Comment by swilly22** [comment]
Can you please provide an example query ?

**Comment by nehz** [comment]
This would be standard ID lookups, e.g:

`MATCH (n) WHERE ID(n) = {value} RETURN n`

Also I believe there is no way to enforce "unique" indexes ?

**Comment by swilly22** [comment]
At the moment the index doesn't enforce uniqueness.
`MATCH (n) WHERE ID(n) = {value} RETURN n` should be extremely fast, the second option, using an index is the next best thing.

**Comment by nehz** [comment]
What kind of performance penalty, very roughly, will be taken with `ID(n)` vs indexed `n.uid` ? Thanks!

**Comment by swilly22** [comment]
roughly going from `O(1)` to `Log(n)`
