### ISSUE TITLE
RedisGraph-2.4.11 build from source failed

### ISSUE THREAD

**Issue by darionyaphet** [RedisGraph/RedisGraph#1977]
Hi experts When I build from `RedisGraph-2.4.11` source code, seems report a error

```
No rule to make target `rax.h', needed by `rax-test.o'.  Stop.
```

Are there any third-party libraries missing? thanks a lot

**Comment by jeffreylovitz** [comment]
Hi @darionyaphet,

It looks like you need to pull the submodules:
```
git submodule update --init --recursive 
```

**Comment by darionyaphet** [comment]
ok it work well thanks ~
