### ISSUE TITLE
Question about testing LDCB-SNB

### ISSUE THREAD

**Issue by randomJoe211** [RedisGraph/RedisGraph#2019]
I tested RedisGraph on https://github.com/ldbc/ldbc_snb_interactive/blob/0.3.3/cypher/queries/interactive-complex-14.cypher, but RedisGraph does not support extract(). May I know how you wrote interactive-complex-14 to pass this test?

Interactive-complex-14 v0.3.4 changed a little bit, but RedisGraph still does not support reduce().

Redis version: 6.2.5
RedisGraph commit ID: 69973de
Dataset: LDBC-SNB v0.3.3 sf1

**Comment by jeffreylovitz** [comment]
Hi @randomJoe211,

We haven't attempted to rewrite interactive-complex-14, so at this time RedisGraph does not support that particular test.

**Comment by randomJoe211** [comment]
Got it. Thank you for the reply, Jeff!
