### ISSUE TITLE
Why delete node is very slowly, Can it be optimized？

### ISSUE THREAD

**Issue by p0xiao** [RedisGraph/RedisGraph#2021]
Hi @swilly22  @jeffreylovitz  @gkorland @DvirDukhan  , I found in the process of using, delete node is very slowly, and cpu load is very high (cpu can reach 2000%).

Server: 32c64g
Redis version: 6.0.9

Node total: 258805
Edge total: 248353

Xxx node total: 162
Xxx node id has created an index.

```
# Xxx node total
127.0.0.1:16779> graph.query asset "match (n:Xxx) return count(n)"
1) 1) "count(n)"
2) 1) 1) (integer) 162
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 0.873307 milliseconds"

# query one node
127.0.0.1:16779> graph.query asset "match (n:Xxx) where n.id='618785bbe4b06488e6aae609' return n.id"
1) 1) "n.id"
2) 1) 1) "618785bbe4b06488e6aae609"
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 1.741537 milliseconds"

# query one node profile
127.0.0.1:16779> graph.profile asset "match (n:Xxx) where n.id='618785bbe4b06488e6aae609' return n.id"

1) "Results | Records produced: 1, Execution time: 0.000871 ms"
2) "    Project | Records produced: 1, Execution time: 0.006753 ms"
3) "        Index Scan | (n:Xxx) | Records produced: 1, Execution time: 0.031692 ms"

# delete one node profile (cpu is 1367%)
127.0.0.1:16779> graph.profile asset "match (n:Xxx) where n.id='618785bbe4b06488e6aae609' delete n"
1) "Delete | Records produced: 1, Execution time: 0.003763 ms"
2) "    Index Scan | (n:Xxx) | Records produced: 1, Execution time: 0.040701 ms"
(2.77s)


# delete another node 
127.0.0.1:16779> graph.query asset "match (n:Xxx) where n.id='618785abe4b06488e6aae606' delete n"
1) 1) "Nodes deleted: 1"
   2) "Cached execution: 0"
   3) "Query internal execution time: 2960.552654 milliseconds"
(2.96s)
```

Is this normal? can it be optimized?

**Comment by gkorland** [comment]
Which version of RedisGraph are you using?

**Comment by p0xiao** [comment]
> Which version of RedisGraph are you using? Notice 2.8.4+ includes major improvements in the area.

We using redisgraph v2.2.13.

**Comment by p0xiao** [comment]
Another question, `order by` clause is slowly too(eg: `order by updatedTime`, even if the index is added, the optimization effect is not achieved

**Comment by jeffreylovitz** [comment]
@p0xiao Are you able to upgrade to RedisGraph 2.8.4?

**Comment by p0xiao** [comment]
ok, i will try upgrade to 2.8.4+ for verify.


> @p0xiao Are you able to upgrade to RedisGraph 2.8.4?

**Comment by ntreq** [comment]
@jeffreylovitz Does the upgrade from 2.2.12 to 2.8.4+ also speed up relationships deletion? I'm facing the same issue with slow deletion when trying to restructure graph matching 800k nodes to delete one relation on each of them.

**Comment by gkorland** [comment]
@ntreq yes it should help reduce the overhead of deleting an edge too.
