### ISSUE TITLE
toJSON breaks json string

### ISSUE THREAD

**Issue by Mon0Man** [RedisGraph/RedisGraph#2030]
Hey!, I am storing json string on node property and have run into a problem; toJSON() modify the json string into invalid json. 

Regular `RETURN` output: `"{\"twitter\":\"javed_twi\",\"instagram\":\"javed_ig\"}"`
`RETURN toJSON()` output: `\"{\"twitter\":\"javed_twi\",\"instagram\":\"javed_ig\"}\"`

As you can see it escape the beginning and ending double quotes. Maybe toJSON can check if `{` come after `"` and replace `"` with `'` ?

of course there is no need to use toJSON for this as the value is stored in json format. But saying I want to returns all the node properties in json format.

example: 
```
 GRAPH.QUERY "testGraph" "MATCH (a:Actor) WHERE a.slug = \"javed-joe\" RETURN toJSON(a)"

returns invalid json: 
"{\"type\": \"node\", \"id\": 2671, \"labels\": [\"Actor\"], \"properties\": {\"id\": \"firt15c1GmP\", \"slug\": \"javed-joe\", \"name\": \"javed joe\", \"image\": false, \"avatar\": false, \"type\": \"movie-star\", \"gender\": \"f\", \"social\": \"{\"twitter\":\"javed_twi\",\"instagram\":\"javed_ig\"}\"}}"
```

**Comment by gkorland** [comment]
How do you store the JSON in as an attribute?

**Comment by Mon0Man** [comment]
@gkorland 
this is how I create:
`GRAPH.QUERY "grph" "CREATE (a:Actor {id: 100, social: '{\"twitter\":\"javed_twi\",\"instagram\":\"javed_ig\"}'})"`

if I try without the surrounding `'`: 
`GRAPH.QUERY "grph" "CREATE (a:Actor {id: 100, social: {\"twitter\":\"javed_twi\",\"instagram\":\"javed_ig\"}})"` 

it throw error: 
```
errMsg: Invalid input '"': expected a parameter, a property name or '}' line: 1, column: 36, offset: 35 errCtx: CREATE (a:Actor {id: 100, social: {"twitter":"javed_twi","instagram":"javed_i... errCtxOffset: 35
```

**Comment by AviAvni** [comment]
toJSON is not converting json string to json object so when you run toJSON on object that contains string it surround it with quotes

**Comment by Mon0Man** [comment]
maybe I think toJSON should have a check case for `"{` and not escape and replace `"` with `'`
maybe @jeffreylovitz can comment ?

Thanks.

**Comment by jeffreylovitz** [comment]
I have some qualms about checking if an input is valid JSON, as it would double the amount of work performed by this function - we can't assume that every input beginning with `{` is JSON. I don't view this function as performing casting, but instead producing a new output.

If in your case you are willing to assume that all strings enclosed with curly braces shouldn't be modified, you can do something like:
```
MATCH (a:Actor)
RETURN CASE WHEN left(a.social, 1) = '{' AND right(a.social, 1) = '}'
THEN input
ELSE
toJson(input)
END
```

**Comment by Mon0Man** [comment]
@jeffreylovitz Thanks for the input, I completely understand the reasoning.
I am storing the data in an array now `[["twitter","javed_twi"],["instagram","javed_ig"]]`.

Thanks.
