### ISSUE TITLE
Replicating All Properties by Matched Alias in CREATE

### ISSUE THREAD

**Issue by TropicalPenguin** [RedisGraph/RedisGraph#2045]
If I try creating a simple new test graph with the following command:

`GRAPH.QUERY test "CREATE (a)-[b:foo {x:1, y: 2}]->(c) RETURN a,b,c"`

I get back the following:
```
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) (empty array)
         3) 1) "properties"
            2) (empty array)
      2) 1) 1) "id"
            2) (integer) 0
         2) 1) "type"
            2) "foo"
         3) 1) "src_node"
            2) (integer) 0
         4) 1) "dest_node"
            2) (integer) 1
         5) 1) "properties"
            2) 1) 1) "x"
                  2) (integer) 1
               2) 1) "y"
                  2) (integer) 2
      3) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) (empty array)
         3) 1) "properties"
            2) (empty array)
3) 1) "Nodes created: 2"
   2) "Properties set: 2"
   3) "Relationships created: 1"
   4) "Cached execution: 0"
   5) "Query internal execution time: 1.158369 milliseconds"
```

What if I then want to effectively rename the relation `foo` without explicitly naming its properties?

 I first tried the following, since I've seen this Cypher syntax elsewhere:
`GRAPH.QUERY test "MATCH (a)-[b]->(c) WHERE ID(b)=0 CREATE (a)-[d:bar]->(c) SET d=b DELETE b RETURN d"`

That yields: `(error) Property values can only be of primitive types or arrays of primitive types`

I then tried:
`GRAPH.QUERY test "MATCH (a)-[b]->(c) WHERE ID(b)=0 CREATE (a)-[d:bar b]->(c) DELETE b RETURN d"`

Neither work. I hope such a feature can be planned for the future? This seems to overlap significantly with https://github.com/RedisGraph/RedisGraph/issues/428 and https://github.com/RedisGraph/RedisGraph/issues/943.

**Comment by jeffreylovitz** [comment]
Hi @TropicalPenguin,

RedisGraph does not have support for this functionality right now, but it is a useful feature and should be trivial to add. I will attempt to resolve this in the next few days!

**Comment by swilly22** [comment]
@TropicalPenguin
Support for entity assignment just been merged into our `master` branch
e.g. `MATCH (a:A), (b:B) SET a=b`, `MATCH (a:A), (b:B) SET a += b`

**Comment by TropicalPenguin** [comment]
This is awesome; thanks for the rapid implementation! :1st_place_medal:
