### ISSUE TITLE
Unable to unload graph module

### ISSUE THREAD

**Issue by Amitgb14** [RedisGraph/RedisGraph#2058]
We load graph module by updating redis.conf but after comment, this line or run unload it failed,

```
$ redis-cli module  list
1) 1) "name"
   2) "graph"
   3) "ver"
   4) (integer) 20411
```

1) stop redis service
2) comment line in redis.conf
```# loadmodule /etc/redis/redisgraph-2.4.11.so```
3) start redis service and failed
redis.log
```# The RDB file contains AUX module data I can't load: no matching module 'graphdata'```

OR 
```
$ redis-cli GRAPH.LIST
(empty array)
$ redis-cli  module unload graph
(error) ERR Error unloading module: the module exports one or more module-side data types, can't unload
```

**Comment by swilly22** [comment]
`# The RDB file contains AUX module data I can't load: no matching module 'graphdata'`
The RDB file (persistency) contains graph key(s), in case Redis is started without the Graph module and tries to load from RDB upon hitting an encoded graph key or AUX field related to Graph, it wouldn't know how to handle that and will fail.

`(error) ERR Error unloading module: the module exports one or more module-side data types, can't unload`
in case redis keyspace contains graph keys you can't unload the graph module as redis wouldn't know how to handle these keys.
