### ISSUE TITLE
Protocol Error with CRLF in Property Contents

### ISSUE THREAD

**Issue by TropicalPenguin** [RedisGraph/RedisGraph#2072]
In the course of trying to find a workaround for https://github.com/gomodule/redigo/issues/587 (after updating redisgraph from a457762e to 7d550c74, though this may be coincidental), I found that redis-cli would reliably fail with the following:

```
> GRAPH.QUERY foo "CREATE (n {text:'Foo\r\nBar'})"
1) 1) "Nodes created: 1"
   2) "Properties set: 1"
   3) "Cached execution: 0"
   4) "Query internal execution time: 0.909102 milliseconds"
127.0.0.1:6379> GRAPH.QUERY foo "MATCH (n) RETURN n"
Error: Protocol error, got "B" as reply type byte
```

There's no protocol error (with redis-cli, at least) when using a plain LF. It's just with CRLF.

This also seems to be peculiar to graph data. Redis HGET, for example, tolerates the same data just fine.

```
> redis-server --version
Redis server v=6.0.15 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=4610f4c3acf7fb25
```

**Comment by jeffreylovitz** [comment]
Thanks for the report, @TropicalPenguin!

I'm looking into this issue, and will report on my findings soon.

**Comment by TropicalPenguin** [comment]
Superb; this seems to automatically resolve https://github.com/gomodule/redigo/issues/587; thanks!

Though it seems - unsurprisingly, I suppose - I must be careful with changes on master; some commit(s) - I'd guess 84df9359ab5e45a67dfb1aa305b44a8901902036 - introduced _after_ this PR cause redis startup to abort loading existing graph data :sweat_smile:, just FYI.

```
 642830:M 23 Dec 2021 06:12:18.523 # ------------------------------------------------
 642830:M 23 Dec 2021 06:12:18.523 # !!! Software Failure. Press left mouse button to continue
 642830:M 23 Dec 2021 06:12:18.523 # Guru Meditation: Error loading data from RDB (short read or EOF). Read performed by module 'graph' about type 'graphdata' after reading '0' bytes of a value for key    named: 'G:1'. #module.c:3798
 642830:M 23 Dec 2021 06:12:18.523 # (forcing SIGSEGV in order to print the stack trace)
 642830:M 23 Dec 2021 06:12:18.523 # ------------------------------------------------
 642830:M 23 Dec 2021 06:12:18.523 # Redis 6.0.15 crashed by signal: 11, si_code: 1
 642830:M 23 Dec 2021 06:12:18.523 # Crashed running the instruction at: 0x55c2913adc4d
 642830:M 23 Dec 2021 06:12:18.523 # Accessing address: 0xffffffffffffffff
 642830:M 23 Dec 2021 06:12:18.523 # Failed assertion: <no assertion failed> (<no file>:0)
 
 ------ STACK TRACE ------
 EIP:
 /usr/bin/redis-server 127.0.0.1:6379(_serverPanic+0x14d)[0x55c2913adc4d]
 
 Backtrace:
 /usr/bin/redis-server 127.0.0.1:6379(logStackTrace+0x5d)[0x55c2913ab66d]
 /usr/bin/redis-server 127.0.0.1:6379(sigsegvHandler+0xd0)[0x55c2913b0370]
 /lib/x86_64-linux-gnu/libc.so.6(+0x46520)[0x7f0757cd5520]
 /usr/bin/redis-server 127.0.0.1:6379(_serverPanic+0x14d)[0x55c2913adc4d]
 /usr/bin/redis-server 127.0.0.1:6379(moduleRDBLoadError+0x59)[0x55c2913e6389]
 /usr/bin/redis-server 127.0.0.1:6379(RM_LoadStringBuffer+0x8a)[0x55c2913eee4a]
 /usr/lib/redis/redisgraph.so(RdbLoadGraphSchema_v10+0x44)[0x7f0754995ee4]
 /usr/lib/redis/redisgraph.so(RdbLoadGraphContext_v10+0x154)[0x7f07549951b4]
 /usr/lib/redis/redisgraph.so(+0x21ff4a)[0x7f0754991f4a]
 /usr/bin/redis-server 127.0.0.1:6379(+0x7a740)[0x55c29138a740]
 /usr/bin/redis-server 127.0.0.1:6379(rdbLoadRio+0x2ca)[0x55c291380dfa]
 /usr/bin/redis-server 127.0.0.1:6379(rdbLoad+0xb0)[0x55c291381a30]
 /usr/bin/redis-server 127.0.0.1:6379(loadDataFromDisk+0xab)[0x55c29135cb3b]
 /usr/bin/redis-server 127.0.0.1:6379(main+0x3e6)[0x55c291342546]
 /lib/x86_64-linux-gnu/libc.so.6(+0x2dfd0)[0x7f0757cbcfd0]
 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d)[0x7f0757cbd07d]
 /usr/bin/redis-server 127.0.0.1:6379(_start+0x2e)[0x55c2913429ae]
```

**Comment by jeffreylovitz** [comment]
Oh, that definitely shouldn't happen! Would you be able to share the RDB (and the version/commit it was built from) with us?

We should be able to resolve this.

**Comment by TropicalPenguin** [comment]
Hmmm; if I backup my current /var/lib/redis/dump.rdb somewhere, reload redis, and scrub some of the personally-identifying information from the live db, and can still reproduce this on one of those commits, would the resulting .rdb be sufficient?

Not sure I've a clear record of which redisgraph commit was used to build it, but the server log at least says:
```
Loading RDB produced by version 6.0.15
```

**Comment by jeffreylovitz** [comment]
That would definitely be sufficient. The backtrace says that the failure occurred while loading the graph schema, so it may even be reproducible if you delete all nodes and edges from your graph.

**Comment by TropicalPenguin** [comment]
Thanks @jeffreylovitz; scrubbed and uploaded in the above.
