### ISSUE TITLE
Why doesn't RedisGraph support sharding

### ISSUE THREAD

**Issue by ChenDan29** [RedisGraph/RedisGraph#2083]
Why doesn't RedisGraph support sharding

**Comment by LiorKogan** [comment]
RedisGraph aims to be the fastest memory-first Property Graph database.
RedisGraph is also very memory efficient (it used compressed sparse matrices to store the graph adjacency) so larger graphs can fit the available memory. 
Shard-based communication introduces network latency. When superfast performance is a major consideration, sharding is something you would prefer to avoid.
