### ISSUE TITLE
size() Type mismatch for getting string length 

### ISSUE THREAD

**Issue by Mon0Man** [RedisGraph/RedisGraph#2086]
Hey! I notice in the docs there is size() function for both String functions and List functions, however size( ) only works for list.
I run `RETURN size('hello world')` and get `Type mismatch: expected List but was String`.

using the latest update.

**Comment by swilly22** [comment]
Hi @Mon0Man,
Which version of RedisGraph are you using?

Running against RedisGraph 2.8.6
`docker run -p 6379:6379 -it --rm redislabs/redisgraph:2.8.6`

```sh
127.0.0.1:6379> GRAPH.QUERY g "return size('a')"
1) 1) "size('a')"
2) 1) 1) (integer) 1
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 0.748000 milliseconds"
127.0.0.1:6379> GRAPH.QUERY g "return size([1,2,3])"
1) 1) "size([1,2,3])"
2) 1) 1) (integer) 3
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 0.440000 milliseconds"
```

**Comment by Mon0Man** [comment]
I am using redislabs/redismod:edge docker image, I have rebuilt with new image and its working. Sorry for that.
Thanks!
