### ISSUE TITLE
Redis server crashes when `MATCH`ing a node engages an index to search for a value that is a RediSearch stop word

### ISSUE THREAD

**Issue by jgaskins** [RedisGraph/RedisGraph#2090]
I'm using the current RedisGraph `master` branch built from source on macOS Monterey 12.1 loaded into the latest Redis server release via Homebrew and it crashes reliably, regardless of whether the DB is fully populated or brand new. I also tested when RedisGraph is the only module loaded as well as with RediSearch, RedisTimeSeries, and RedisJSON also loaded. 

I can also reproduce it using the `redislabs/redisgraph:edge` Docker image, so I assume it happens on Linux, as well. It does not crash when using the `latest` tag, though, if that helps narrow down when the bug was introduced.

Simplified reproduction:

```
graph.query test "create index on :User(id)"
graph.query test "match (u:User { id: 'not' }) return u"
```

I'm suspect it's due to RediSearch stop words — the reproduction above uses `"not"` in the indexed field but it also crashed on a user with  `id: 'an'` (testing with data from a production app and those are actual usernames). It's notable that this happens specifically with stop words despite the index not having any stop words defined:

```
127.0.0.1:6379> graph.query test "call db.indexes"
1) 1) "type"
   2) "label"
   3) "properties"
   4) "language"
   5) "stopwords"
   6) "entitytype"
2) 1) 1) "exact-match"
      2) "User"
      3) "[id]"
      4) "english"
      5) "[]"
      6) "NODE"
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 0.232000 milliseconds"
```

Oddly, if you run the query _before_ creating the index, you can run it after creating it, even if you create a node in between:

```
graph.query test "match (u:User { id: 'not' }) return u"
graph.query test "create index on :User(id)"
graph.query test "match (u:User { id: 'not' }) return u"
graph.query test "create (u:User { id: 'not' })"
graph.query test "match (u:User { id: 'not' }) return u"
```

---

_EDIT_: It just occurred to me that that last point is likely due to query-plan caching.

**Comment by swilly22** [comment]
Hi @jgaskins, we've identified the issue and should have a fix within the next couple of days,
I'll update here once it is available.
Thank you!

**Comment by swilly22** [comment]
@jgaskins sorry for the late response, issue had been resolved and a fix been merged into our `master` branch

**Comment by jgaskins** [comment]
@swilly22 Thank you! 💯
