### ISSUE TITLE
return result is empty when count Node/Relationship with where 

### ISSUE THREAD

**Issue by ChandlerBent** [RedisGraph/RedisGraph#2091]
RedisGraph version: 2.8.7

```
GRAPH.QUERY graph "MATCH (a)-[r:TEST]-() return count(r)"
```

```python
[[b'count(_)'],
 [[0]],
 [b'Cached execution: 0',
  b'Query internal execution time: 0.325100 milliseconds']]
```
This is OK.

```
GRAPH.QUERY graph "MATCH (a)-[r:TEST]-() where id(a)=100 return count(r)"
```

```python
[[b'count(_)'],
 [[]],
 [b'Cached execution: 0',
  b'Query internal execution time: 0.325100 milliseconds']]
```
Wrong. It should be return [[0]]

If the relationship is exists, it can return [[1]]. 
The example is count relationship. Node also has this problem.

**Comment by swilly22** [comment]
Hi @ChandlerBent, thank you for brining this to our attention, this is a known issue which we hope to address within the next couple of days.

**Comment by ChandlerBent** [comment]
Hi. Will redisgraph fix this bug and release in recently?

Do you have a release plan on this month?
@swilly22 

Redisgraph is so good, I can't wait use redisgraph on this month.
