### ISSUE TITLE
create or merge conditionally in case clause or other alternative

### ISSUE THREAD

**Issue by ebrahimtorabi** [RedisGraph/RedisGraph#2120]
i need create or merge conditionally
for example:
FOREACH(ignoreMe IN CASE WHEN 'y' THEN [1] ELSE [] END |
MERGE (u)-[r2:STAGE {startdate:20141225, enddate:'99999999', status:'InProgress'}]->(b2 {fork:'fail'})
)
FOREACH(ignoreMe IN CASE WHEN NOT 'y' THEN [1] ELSE [] END |
MERGE (u)-[r2:STAGE {startdate:20141225, enddate:'99999999', status:'InProgress'}]->(b2)
)

**Comment by swilly22** [comment]
Can you please explain your use case here in high level?

**Comment by AviAvni** [comment]
foreach added in https://github.com/RedisGraph/RedisGraph/pull/2825
