### ISSUE TITLE
Does redisgraph works with redis virtual memory enabled?

### ISSUE THREAD

**Issue by lucasbmiguel** [RedisGraph/RedisGraph#2137]
I was wondering that for cases when the graph holds enormous amounts of data, if I enable Redis Virtual Memory it will work seamlessly.

Redis VM is a feature added on Redis 2.0. More info at: https://redis.io/topics/virtual-memory

**Comment by jeffreylovitz** [comment]
Hi @lucasbmiguel,

The entire graph is stored in a single key, so Redis VM won't confer any advantages - it is not capable of swapping partial value segments to disk.

**Comment by LiorKogan** [comment]
@lucasbmiguel 

Note that Redis VM was deprecated a long time ago.
