### ISSUE TITLE
Different results returned when executing the same queries on Redisgraph and Neo4j, respectively

### ISSUE THREAD

**Issue by abc123000111** [RedisGraph/RedisGraph#2138]
**Redisgraph version**
2.4.11 Docker

**Environment**
Windows 11
Java API / Cypher

**Describe the bug**
I discovered that when I executed the following queries on Redisgraph and Neo4j, respectively, different results were returned:
```
CREATE (n0 :L2);
CREATE (n1 :L0{k4:-1032527763, k5:true, k6:false});
CREATE (n2 :L1{k11:-770665201});
CREATE (n3 :L0{k0:'8qVg', k1:false, k3:1190292536});
CREATE (n4 :L4);
CREATE (n5 :L1{k8:false});
CREATE (n6 :L0{k2:916495906, k3:-1032527763});
CREATE (n7 :L3{k21:'Caf'});
CREATE (n8 :L0);
CREATE (n9 :L2{k12:false});
CREATE (n10 :L2{k12:true, k13:1190292536, k17:-1327867491});
CREATE (n11 :L1{k8:true, k10:1733814312});
CREATE (n12 :L2{k14:1190292536});
CREATE (n13 :L1{k9:2017419622});
CREATE (n14 :L1{k8:false});
CREATE (n15 :L3);
CREATE (n16 :L2{k12:true, k17:-820517567});
MATCH (n10 :L2{k12:true, k13:1190292536, k17:-1327867491}), (n16 :L2{k12:true, k17:-820517567}) MERGE (n10)-[r0 :T3{k53:1677628897}]->(n16);
MATCH (n0)-[r0 :T1 *1..]->(n1 :L2) WITH stDev(0) AS a0 OPTIONAL MATCH (n3) RETURN DISTINCT a0;
```

**To Reproduce**
1. Start Redisgraph 2.4.11 and Neo4j 4.4.3, respectively.
2. Execute the mentioned queries on each graph database.
3. Compare the result sets.

**Expected behavior**
The result sets are the same. But the actual behavior is:
Redisgraph returns 0 record.
Neo4j returns 1 record.

**Comment by abc123000111** [comment]
In the Cypher Query Language Reference (Version 9), it says "stDev(null) returns 0":
![微信图片_20220204141014](https://user-images.githubusercontent.com/34190313/152481350-d3fb5af8-9b65-44dc-99d2-950a118a6a16.png)

Here is the query plan of Neo4j：
![plan](https://user-images.githubusercontent.com/34190313/152481355-ba69b393-acc8-462e-89f6-8904b1980be0.png)

Is it necessary to be consistent with the description in the official documentation of openCypher9?

**Comment by swilly22** [comment]
Hi @abc123000111 thank you for reporting,
This issue is similar to: `MATCH (a:NoneExisting) RETURN count(a)`
where RedisGraph wouldn't return any data and Neo will return a single row with the value `0`

We hope to address this issue soon.
