### ISSUE TITLE
db.idx.fulltext.queryNodes does not support Chinese language.

### ISSUE THREAD

**Issue by garyhai** [RedisGraph/RedisGraph#2148]
Full-text index is created with language by `"CALL db.idx.fulltext.createNodeIndex({ label: 'Text', language: 'chinese' }, 'v')"`.

Invoke "CALL db.idx.fulltext.queryNodes('Text', '世界') YIELD node RETURN node.v" return empty result.

But invoke English query "CALL db.idx.fulltext.queryNodes('Text', 'world') YIELD node RETURN node.v" return expected result.

So RediSearch as RedisGraph dependence may not configured for Chinese full-text search yet.

Has RedisGraph plan to support commands of RediSearch? e.g. "FT.SEARCH idx "数据" LANGUAGE chinese HIGHLIGHT SUMMARIZE"

**Comment by AviAvni** [comment]
thanks for using the new feature
on my machine using the master branch I get
```
127.0.0.1:6379> GRAPH.QUERY x "CALL db.idx.fulltext.createNodeIndex({ label: 'Text', language: 'chinese' }, 'v')"
1) 1) "Indices created: 1"
   2) "Cached execution: 0"
   3) "Query internal execution time: 0.908000 milliseconds"
127.0.0.1:6379> GRAPH.QUERY x "CREATE (:Text {v: '世界'})"
1) 1) "Nodes created: 1"
   2) "Properties set: 1"
   3) "Cached execution: 0"
   4) "Query internal execution time: 110.297000 milliseconds"
127.0.0.1:6379> GRAPH.QUERY x "CALL db.idx.fulltext.queryNodes('Text', '世界') YIELD node RETURN node.v"
1) 1) "node.v"
2) 1) 1) "\xe4\xb8\x96\xe7\x95\x8c"
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 0.407000 milliseconds"
```

which version of of redisgraph you are using?

**Comment by garyhai** [comment]
Thanks a lot. I found my issue caused by Chinese tokenization module [Friso](https://github.com/lionsoul2014/friso). 

```
127.0.0.1:6379> GRAPH.QUERY x "CREATE (:Text {v: '双减政策'})"
1) 1) "Labels added: 1"
   2) "Nodes created: 1"
   3) "Properties set: 1"
   4) "Cached execution: 0"
127.0.0.1:6379> GRAPH.QUERY x "CALL db.idx.fulltext.queryNodes('Text', '政策') YIELD node RETURN node.v"
1) 1) "node.v"
2) 1) 1) "\xe5\x8f\x8c\xe5\x87\x8f\xe6\x94\xbf\xe7\xad\x96"
127.0.0.1:6379> GRAPH.QUERY x "CALL db.idx.fulltext.queryNodes('Text', '双减') YIELD node RETURN node.v"
1) 1) "node.v"
2) (empty array)
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 0.159000 milliseconds"

```

Friso cannot tokenize the new word '双减'. After replaced by [cppjieba](https://github.com/yanyiwu/cppjieba), it worked.

In my opinion, it is enough to use the simplest sliding-window comparison algorithm for Chinese full-text query. Chinese tokenization algorithm brings too much ambiguity, which makes full-text searching buggy and unstable.
