### ISSUE TITLE
Question: Betweenness centrality

### ISSUE THREAD

**Issue by dandago** [RedisGraph/RedisGraph#2166]
Hi,

I was just wondering whether RedisGraph supports any algorithm for betweenness centrality, or has any plans to do so in the future.

For instance, [Neo4j has a betweenness centrality algorithm](https://neo4j.com/docs/graph-data-science/current/algorithms/betweenness-centrality/) based on Brandes' approximate algorithm.

**Comment by swilly22** [comment]
Hi @dandago,
Adding additional graph algorithms is planed, I can't commit on the timeline but the idea is to have every algorithm from [LAGraph](github.com/GraphBLAS/LAGraph) imported into RedisGraph, including [betweenness centrality](https://github.com/GraphBLAS/LAGraph/blob/reorg/src/algorithm/LAGr_Betweenness.c)

**Comment by dandago** [comment]
Thanks @swilly22
