### ISSUE TITLE
2.8.8GA toJSON() major bug, missing/corrupted data returned on simple query

### ISSUE THREAD

**Issue by milanbgd011** [RedisGraph/RedisGraph#2171]
Just simple 2 tables (ie. Producers and Models) with "ri,rc,ru,rd,rr" timestamps and "rd" as string. 
Created relation between single Producer and multiple Models.
Then used toJSON() to return data.

Used exactly same .AOF file, just booted different redisgraph version over that file.

## v2.8.8 NOT USING toJSON(), only direct data - all OK

![Screenshot 2022-02-18 at 23 22 40](https://user-images.githubusercontent.com/20988958/154770126-41c1ed2d-514d-41f3-8444-11f1213011d8.png)
![Screenshot 2022-02-18 at 23 22 35](https://user-images.githubusercontent.com/20988958/154770124-0d8a6ef8-0ee6-4187-8e84-c6790666216c.png)

## v2.8.8 using toJSON() - 2 fields OK, 4 fields totally corrupted/missing

![Screenshot 2022-02-18 at 23 14 26](https://user-images.githubusercontent.com/20988958/154770827-f1148d68-e156-4c05-b617-1864da3b2726.png)

## v2.8.7 using toJSON() - all OK

![Screenshot 2022-02-18 at 23 04 44](https://user-images.githubusercontent.com/20988958/154770111-e0e60eea-e459-4135-ba57-0b2c86da6b8c.png)

## v2.8.8 docker-compose.yml
```
version: "3.7"
services:
  redisgraph100:
    container_name: "redisgraph100"
    image: "redislabs/redisgraph:2.8.8"
    ports:
      - "6379:6379"
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--loadmodule",
        "/usr/lib/redis/modules/redisgraph.so",
      ]
```

## v2.8.7 docker-compose.yml
```
version: "3.7"
services:
  redisgraph100:
    container_name: "redisgraph100"
    image: "redislabs/redisgraph:2.8.7"
    ports:
      - "6379:6379"
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--loadmodule",
        "/usr/lib/redis/modules/redisgraph.so",
      ]
```

**Comment by jeffreylovitz** [comment]
Hi @milanbgd011,

Thanks for the report, and sorry for the late reply!

I've just opened a PR that should resolve this problem.

**Comment by milanbgd011** [comment]
Hi @jeffreylovitz

I am forever greatful that now I will be able to use newest 2.8 GA now :) Will wait for the next release which includes it, of course. Have a great day! Thank you very much! Highly appreciated! ❤️
