### ISSUE TITLE
chinese characters can't use on property key

### ISSUE THREAD

**Issue by ChandlerBent** [RedisGraph/RedisGraph#2198]
RedisGraph Version: 2.8.7

```
GRAPH.QUERY "graph" "create (n:person {名字: '小明'}) return n"
```

error msg:
```
errMsg: Invalid input '�': expected a property name, '}' or a parameter line: 1, column: 19, offset: 18 errCtx: create (n:person {名字: '小明'}) return n errCtxOffset: 18
```

neo4j is support.

**Comment by jeffreylovitz** [comment]
Hi @ChandlerBent,

This is a problem that can occur when Chinese characters are used outside of quoted strings.

The solution is to use backticks to escape the Chinese string:
```
$ redis-cli --raw
127.0.0.1:6379> GRAPH.QUERY "graph" "create (n:person {`名字`: '小明'}) return n"
n
id
0
labels
person
properties
名字
小明
Labels added: 1
Nodes created: 1
Properties set: 1
Cached execution: 0
Query internal execution time: 0.289488 milliseconds
```
(Without the `--raw` argument, redis-cli will print the Chinese characters as Unicode sequences.)

**Comment by ChandlerBent** [comment]
> Hi @ChandlerBent,
> 
> This is a problem that can occur when Chinese characters are used outside of quoted strings.
> 
> The solution is to use backticks to escape the Chinese string:
> 
> ```
> $ redis-cli --raw
> 127.0.0.1:6379> GRAPH.QUERY "graph" "create (n:person {`名字`: '小明'}) return n"
> n
> id
> 0
> labels
> person
> properties
> 名字
> 小明
> Labels added: 1
> Nodes created: 1
> Properties set: 1
> Cached execution: 0
> Query internal execution time: 0.289488 milliseconds
> ```
> 
> (Without the `--raw` argument, redis-cli will print the Chinese characters as Unicode sequences.)

Thank you for reply.
:)
