### ISSUE TITLE
undefined variable in MERGE/CREATE doesn't throw error

### ISSUE THREAD

**Issue by Mon0Man** [RedisGraph/RedisGraph#2202]
Hey!, given the command below `v` isn't defined in but the command doesn't return error.
shouldn't this throw error ?
```
MATCH (n:Video), (a:Actor) 
WHERE n.id = '27sus79' AND a.id = '910od8' 
MERGE (a)-[:ACTED_IN]->(v)
```
command return: 
```
1) 1) "Cached execution: 1"
   2) "Query internal execution time: 0.815157 milliseconds"
```
- redisgraph 2.8.8

**Comment by swilly22** [comment]
Hi @Mon0Man there's no `v` entity in the query you've specified,
the only defined aliases are: `n` and `a`

**Comment by Mon0Man** [comment]
@swilly22 oh sorry, I updated the post: `MERGE (a)-[:PERFORMED_IN]->(v)`

**Comment by jeffreylovitz** [comment]
Hi @Mon0Man,

In your example it looks unintuitive, but this is in fact valid Cypher, as `MERGE` is allowed to introduce new variables.

`v` will be created as a new unlabeled node with no properties, but there are other cases which demonstrate more sensible usage that require undefined aliases to be allowed in `MERGE`:
```
MERGE (n:Video {id: '27sus79'}) RETURN n
MATCH (n) MERGE (n)-[:PARENT_OF]->(c:Child {created_at: timestamp()}) RETURN n, c
```
```
