### ISSUE TITLE
Some mathematic expressions are not evaluated as expected

### ISSUE THREAD

**Issue by LiorKogan** [RedisGraph/RedisGraph#2212]
RedisGraph 2.8.9

Some mathematic expressions are not evaluated as expected:

`GRAPH.QUERY t "return -0"`
-0

`GRAPH.QUERY t "return --3"`
--3

`GRAPH.QUERY t "return --003"`
--003

**Comment by nafraf** [comment]
`return --3` is now valid on Neo4j 4.4.10 

Maybe these validations should be done by libcypher-parser
