### ISSUE TITLE
`WITH *` erases path variables

### ISSUE THREAD

**Issue by LiorKogan** [RedisGraph/RedisGraph#2223]
RedisGraph 2.4.14, 2.8.9

The following query 
```
GRAPH.QUERY test "MATCH p = (x1)<-[*]-(x2) WITH * RETURN p"

```
returns 
```
(error) p not defined
```

In Neo4j, `MATCH p = (x1)<-[*]-(x2) WITH * RETURN p` is a valid query.

According to https://neo4j.com/docs/cypher-manual/current/clauses/with/
You can use the wildcard * to carry over all variables that are in scope.

**Comment by jeffreylovitz** [comment]
This issue was resolved by #2233.
