### ISSUE TITLE
If Node Exists, Do Nothing

### ISSUE THREAD

**Issue by jdgamble555** [RedisGraph/RedisGraph#2286]
I am looking for a way to NOT create OR update a node if a it already exists.

For example:

```graphql
CREATE (u:User { email: 'me@you.com', ... })
RETURN u
```
This creates a new node, but I want to do something simple like this:

```graphql
MATCH (u:User { email: 'me@you.com' })
IF NOT u
CREATE (u:User { email: 'me@you.com', name: 'Jon Smith' })
RETURN u
```

This seems like pretty basic behavior, as it would be the default behavior in other databases.

Surely there is a way to do this in Cypher (or rather, redisgraph cypher) ?

J

**Comment by LiorKogan** [comment]
`MERGE` either matches existing nodes and binds them, or it creates new data and binds that. It’s like a combination of `MATCH` and `CREATE` that additionally allows you to specify what happens if the data was matched or created.

**Comment by jdgamble555** [comment]
Right, but I *don’t* want to `MERGE`, I don’t want to do anything if it exists. Merging could change data.

J

**Comment by swilly22** [comment]
Please see: [MERGE ON CREATE / ON MATCH](https://redis.io/commands/graph.query/#merge)

consider the following:
```graphql
MERGE (u:User { email: 'me@you.com' })
ON CREATE SET u.name: 'Jon Smith'
```

**Comment by swilly22** [comment]
Another option:
```graphql
OPTIONAL MATCH (u:User { email: 'me@you.com' })
WHERE u is not NULL
RETURN u LIMIT 1
```

**Comment by jdgamble555** [comment]
Thanks!  I had to modify both of them to work like so:

```graphql
MERGE (u:User { email: 'me@you.com' })
ON CREATE SET u.name='Jon Smith'
RETURN u
```
and
```graphql
OPTIONAL MATCH (u:User { email: 'me@you.com' })
WHERE u IS NULL
SET u.name='Jon Smith'
RETURN u
```
J

**Comment by jdgamble555** [comment]
So this doesn't work as expected.

@swilly22 - Is this what you meant?

```graphql
OPTIONAL MATCH (u:User { email: 'me@you.com' })
WHERE u IS NULL
SET u.name='Jon Smith'
RETURN u
```

I think this doesn't work because `u` is just null.

I need a way to do this with two unique keys `email, username`, so MERGE won't work (it would use the combination and not the individual keys).

Thanks,

J

**Comment by swilly22** [comment]
Please consider the following query:

```
GRAPH.QUERY g "cypher email='a' username='b'
OPTIONAL MATCH (n)
WHERE n.email = $email OR n.username = $username
WITH n is null as missing
WHERE missing = true
CREATE ({email:$email, username:$username})"
```

Given an empty graph:

```
GRAPH.QUERY g "cypher email='a' username='b' OPTIONAL MATCH (n) WHERE n.email = $email OR n.username = $username  WITH n is null as missing WHERE missing = true CREATE (n {email:$email, username:$username})"
1) 1) "Nodes created: 1"
   2) "Properties set: 2"
   3) "Cached execution: 0"
   4) "Query internal execution time: 1.469000 milliseconds"

GRAPH.QUERY g "cypher email='a' username='b' OPTIONAL MATCH (n) WHERE n.email = $email OR n.username = $username  WITH n is null as missing WHERE missing = true CREATE (n {email:$email, username:$username})"
    1) 1) "Cached execution: 1"
       2) "Query internal execution time: 0.614000 milliseconds"
```

Running the exact same query twice, the first execution created the missing node the second one didn't modified the graph.

**Comment by jdgamble555** [comment]
Sweet! Thanks!

This is important, as RedisGraph does not have a Unique Constraint!

```graphql
OPTIONAL MATCH (u:User)
WHERE u.email = 'me@you.com'
OR u.username = 'bill'
WITH u IS NULL AS missing
WHERE missing = true
CREATE (u2:User { email: 'me@you.com', username: 'bill' })
```

J
