### ISSUE TITLE
Implement functions returning maps

### ISSUE THREAD

**Issue by odanoburu** [RedisGraph/RedisGraph#2297]
e.g., the `properties` function.

I know maps as a data type were implemented relatively recently, so only now this is possible. Are there any hurdles to implement this? I can try my hand at it.

**Comment by LiorKogan** [comment]
RedisGraph follows the Cypher query language reference, but the coverage, while continuously being extended, is not complete.

Currently, we don't have any concrete timeline for `properties` support.
