### ISSUE TITLE
Bulk not working with over 16384 nodes in 2.8

### ISSUE THREAD

**Issue by jaceenet** [RedisGraph/RedisGraph#2305]
When I try to import more than 16384 nodes the rest are imported without any label on the node. This was working fine before 2.8 (tested on 2.4 everything ok).

https://gist.github.com/jaceenet/9ed3a96cd18b816ad9500565ed177bd1

![image](https://user-images.githubusercontent.com/333529/163228032-268a95cb-97e3-4fc0-a320-13e6626b6ffe.png)

**Comment by AviAvni** [comment]
thanks for using RedisGraph
can you provide the RedisBinaryWriter code I can't run this code

**Comment by jaceenet** [comment]
Of course! 

I have updated the gist so everything is there.

**Comment by AviAvni** [comment]
can you try to run
```
MATCH (n:testnode) RETURN count(n)
```
I wasn't able to reproduce it and it look like a visualization issue

**Comment by jaceenet** [comment]
I am running 
`docker run -p 6379:6379 -it --rm redislabs/redisgraph:2.8.11`

and the results:
```
Pinging Redis server on 127.0.0.1:6378...
Connected.
Ready to execute commands.
>> GRAPH.QUERY "--bulk-impl-test3" "match (n) return labels(n), count(n)"

1) 1) "labels(n)"
   2) "count(n)"
2) 1) 1) "[]"
      2) (integer) 10
   2) 1) "[testnode]"
      2) (integer) 16384
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 12.691863 milliseconds"
```

**Comment by LiorKogan** [comment]
@jaceenet Thank you for reporting. Most of our team are on vacation this week. We will look at this next week.

**Comment by AviAvni** [comment]
https://gist.github.com/jaceenet/9ed3a96cd18b816ad9500565ed177bd1#file-program-cs-L35
this line is the problematic line
GRAPH.BULK command expect the # of nodes and # of edges if you change 1 to 16394 it will be ok

**Comment by jaceenet** [comment]
Fixing 1 to 16394 make the nodes correct and the queries are fixed in 2.8 - so far so good. But this only works for bulk import of nodes only without relations. There must be something I misunderstand in the bulk documentation what the arguments are for.

The docs explain the following arguments: `graph name`, `BEGIN`, `node count`, `edge count`, `binary blob`...

this cause redis to crash (both 2.4 and 2.8), so I asked around (in redis chats) and was proposed:
`graph name`, `BEGIN`, `node count`, `node total`, `edge count`, `edge total`, `binary blob`...
(but I cannot find any documentation explaining why this works)

So my final question, is there something missing in the documentation, because running it with relations fails adding any relations. My big confusion comes from all this working in 2.4 where I never specified node count or edge count but instead blob count.

I have updated the sample to simulate adding 4 nodes and 3 relations to keep it simple. How should the arguments be?
`BEGIN`, `node count`, `???`, `???`, `???`, `blob node`, `blob rel`

I have tried, followed by blobs [node, rel]:
BEGIN 4, 3, 1, 1
BEGIN 4, 1, 3, 1
BEGIN 4, 4, 3, 3
BEGIN 4, 3, 2 (assuming node count, edge count, blob count)
(none of the options works)

(I have updated the gist with this sample)
https://gist.github.com/jaceenet/9ed3a96cd18b816ad9500565ed177bd1

it produce 4 nodes and 16 nodes of the relation name (or garbage). I cannot make the bulk operation work with your correction **and** add relations at the same time...

**Comment by AviAvni** [comment]
here is the documentation 

and here is the code that work on my machine

```
using StackExchange.Redis;

var conn = ConnectionMultiplexer.Connect("localhost:6379");
var dbname = "--bulk-impl-test3";
var db = conn.GetDatabase();
await db.KeyDeleteAsync(dbname);

var nodecount = 4;//16384 + 10;
byte[] data = Helper.WriteBatch("testnode", nodecount);
byte[] rel = Helper.WriteRelation();

var cmdargs = new List<object>();
cmdargs.Add("--bulk-impl-test3");
cmdargs.Add("BEGIN");
// node count
cmdargs.Add(nodecount);
// edge count
cmdargs.Add(3);
// node tokens count
cmdargs.Add(1);
// edge tokens count
cmdargs.Add(1);

cmdargs.Add(data);
cmdargs.Add(rel);

await db.KeyDeleteAsync(cmdargs[0].ToString());
await db.ExecuteAsync("GRAPH.BULK", cmdargs);

Console.WriteLine("Completed");


public static class RedisBinaryWriter
{
    public static void WriteString(this BinaryWriter writer, string s)
    {
        byte[] buffer = System.Text.Encoding.Default.GetBytes(s);
        writer.Write(buffer);
        writer.Write((byte) 0);
    }

    public static void WritePropertyCount(this BinaryWriter writer, int c)
    {
        writer.Write((uint) c);
    }

    public static void WriteNodeId(this BinaryWriter writer, long index)
    {
        writer.Write(index);
    }
    
    public static void WriteValue(this BinaryWriter writer, object v)
    {
        if (v is Guid g)
        {
            writer.WriteValue(g.ToString());
            return;
        }

        if (v is DateTime dt)
        {
            long ticks = new DateTimeOffset(dt.Ticks, TimeSpan.Zero).ToUnixTimeSeconds();
            writer.WriteValue(ticks);
            return;
        }

        if (v is string s)
        {
            writer.Write((byte)3);
            writer.WriteString(s);
            return;
        }

        if (v is int i)
        {
            writer.WriteValue((long) i);
            return;
        }

        if (v is bool b)
        {
            writer.Write((byte) 1);
            writer.Write(b);
            return;
        }

        if (v is double d)
        {
            writer.Write((byte) 2);
            writer.Write(d);
            return;
        }

        if (v is long l)
        {
            writer.Write((byte) 4);
            writer.Write(l);
            return;
        }

        if (v is Enum @enum)
        {
            writer.WriteValue(@enum.ToString());
            return;
        }

        writer.Write((byte) 0);
    }
}

public class Helper
{
    public static byte[] WriteRelation()
    {
        using var mem = new MemoryStream();
        var relationWriter = new BinaryWriter(mem);
        
        //rel header
        relationWriter.WriteString("rel");
        relationWriter.WritePropertyCount(2);
        relationWriter.WriteString("kind");
        relationWriter.WriteString("kind2");

        // rel 1
        relationWriter.WriteNodeId(0);
        relationWriter.WriteNodeId(1);
        relationWriter.WriteValue("my rel prop");
        relationWriter.WriteValue("my rel prop1");

        // rel 2
        relationWriter.WriteNodeId(1);
        relationWriter.WriteNodeId(2);
        relationWriter.WriteValue("my rel prop");
        relationWriter.WriteValue("my rel prop2");

        // rel 3
        relationWriter.WriteNodeId(2);
        relationWriter.WriteNodeId(3);
        relationWriter.WriteValue("my rel prop");
        relationWriter.WriteValue("my rel prop3");
        
        return mem.ToArray();
    }
    
    public static byte[] WriteBatch(string node, int count)
    {
        using (var mem = new MemoryStream())
        {
            var bulkwriter = new BinaryWriter(mem);

            bulkwriter.WriteString(node);
            bulkwriter.WritePropertyCount(5);

            bulkwriter.WriteString("prop1_dt");
            bulkwriter.WriteString("prop2_int");
            bulkwriter.WriteString("prop3_long");
            bulkwriter.WriteString("prop4_bool");
            bulkwriter.WriteString("prop5_str");

            for (int i = 0; i < count; i++)
            {
                bulkwriter.WriteValue(DateTime.UtcNow.AddSeconds(i));
                bulkwriter.WriteValue(i + 4022 % 20);
                bulkwriter.WriteValue(i);
                bulkwriter.WriteValue(true);
                bulkwriter.WriteValue("some text " + i);
            }

            return mem.ToArray();
        }
    }
}
```

**Comment by jaceenet** [comment]
Yes ended up with the same, but it should be mentioned here: https://github.com/RedisGraph/RedisGraph/blob/master/docs/docs/design/bulk_spec.md for others.

**Comment by AviAvni** [comment]
thanks we will update the documentation soon
