### ISSUE TITLE
How to remove label?

### ISSUE THREAD

**Issue by odanoburu** [RedisGraph/RedisGraph#2308]
Redisgraph 2.8.11, Redis 6.2.6

The documentation at https://redis.io/docs/stack/graph/cypher_support/#writing-clauses says REMOVE is not supported to modify properties, but says nothing about labels. 

```
> GRAPH.QUERY test "MATCH (n1:Node1) REMOVE n1:Node1 RETURN n1"
(error) RedisGraph does not currently support REMOVE
```

Doesn't work. Is there an alternative way to remove labels as there is to remove properties?

**Comment by LiorKogan** [comment]
**Todo:**
Add support for the following:
GRAPH.QUERY g "MATCH (n {key:123}) REMOVE n:oldLabel"
GRAPH.QUERY g "MATCH (n {key:123}) SET n:newLabel"

**Comment by LiorKogan** [comment]
@odanoburu 
In the meanwhile you can do:

```
graph.query g "MATCH (m:curLabel {key:123}) CREATE (n) SET n = m DELETE m"
```
