### ISSUE TITLE
Support toBoolean, toFloat, toXXXOrNull, split

### ISSUE THREAD

**Issue by LiorKogan** [RedisGraph/RedisGraph#2313]
Currently, RedisGraph does not support the following functions:

```
toBoolean()
toFloat()

toBooleanOrNull()
toFloatOrNull()
toIntegerOrNull()
toStringOrNull()

split()
```

**Comment by DvirDukhan** [comment]
@LiorKogan 
`toFloat` is supported https://github.com/RedisGraph/RedisGraph/blob/e5dc9c864ddf5e546fe01d156075100cc343564e/src/arithmetic/numeric_funcs/numeric_funcs.c#L132

we left with `toXXXOrNull` to support
