### ISSUE TITLE
Assertion failed on NULL root in filter tree

### ISSUE THREAD

**Issue by jeffreylovitz** [RedisGraph/RedisGraph#2323]
The query:
```
OPTIONAL MATCH (:Person)  RETURN [(:Company) <-[*1{edge_id:2}]- () WHERE NOT 2 AND ((FALSE)) | TRUE]
```
Produces the crash:
```
src/filter_tree/filter_tree.c:530 'root && func && node' is not true
```

**Comment by OfirMos** [comment]
@LiorKogan @AviAvni @swilly22 Neo4j returns error when doing no on number literal:
`OPTIONAL MATCH (:Person) RETURN [(:Company) <-[*1{edge_id:2}]- () WHERE NOT 2 AND ((FALSE)) | TRUE]



Neo.ClientError.Statement.SyntaxError
Type mismatch: expected Boolean but was Integer (line 1, column 78 (offset: 77))
"OPTIONAL MATCH (:Person)  RETURN [(:Company) <-[*1{edge_id:2}]- () WHERE NOT 2 AND ((FALSE)) | TRUE]"
                                                                              ^`
