### ISSUE TITLE
make gives errors

### ISSUE THREAD

**Issue by saurabhkumar** [RedisGraph/RedisGraph#2352]
OS: Ubuntu 18.04

Installed packages as mentioned in documentation:

> apt-get install build-essential cmake m4 automake peg libtool autoconf

Then executed make from the project folder

The following errors are shown:

> make[1]: Entering directory '/path_to_src/RedisGraph-2.4/src'
> make[2]: Entering directory '/path_to_src/RedisGraph-2.4/deps/rax'
> make[2]: *** No rule to make target 'rax.h', needed by 'rax-test.o'.  Stop.
> make[2]: Leaving directory '/path_to_src/RedisGraph-2.4/deps/rax'
> Makefile:210: recipe for target '/path_to_src/RedisGraph-2.4/deps/rax/rax.o' failed
> make[1]: *** [path_to_src/RedisGraph-2.4/deps/rax/rax.o] Error 2
> make[1]: Leaving directory '/path_to_src/RedisGraph-2.4/src'
> Makefile:25: recipe for target 'all' failed
> make: *** [all] Error 2

Is there any additional package / compiler / compiler version to be installed?

**Comment by swilly22** [comment]
This is just a temporary workaround, obviously this needs to be fixed but in the meanwhile can you try navigating to `/path_to_src/RedisGraph-2.4/deps/rax` run `make` then run `make` again from `/path_to_src/RedisGraph-2.4/`

**Comment by saurabhkumar** [comment]
When I clone the repository, and checkout 2.4 or if I download and extract the zip file, the /path_to_src/deps/rax folder is empty.

**Comment by swilly22** [comment]
Please use `git clone --recurse-submodules -j8 https://github.com/RedisGraph/RedisGraph.git` to clone sub modules this should include the rax directory

**Comment by saurabhkumar** [comment]
Sorry, my mistake with that.

Now I cloned using `git clone --recurse-submodules -j8 https://github.com/RedisGraph/RedisGraph.git`
Then I did `git checkout 2.4`

Now make gives the following error:

> /path_to_src/src/commands/execution_ctx.c: In function
> _GetExecutionTypeFromAST’:
> /path_to_src/src/commands/execution_ctx.c:17:18: error:
> ‘CYPHER_AST_DROP_NODE_PROPS_INDEX’ undeclared (first use in this function); did you mean ‘CYPHER_AST_DROP_PROPS_INDEX’?
>    17 |  if(root_type == CYPHER_AST_DROP_NODE_PROPS_INDEX) return EXECUTION_TYPE_INDEX_DROP;
>       |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                  CYPHER_AST_DROP_PROPS_INDEX
> /home/devops/redissgraph_github/RedisGraph/src/commands/execution_ctx.c:17:18: note: each undeclared identifier is reported only once for each function it appears in
> make[1]: *** [Makefile:200: /path_to_src/src/commands/execution_ctx.o] Error 1
> make[1]: Leaving directory '/path_to_src/src'
> make: *** [Makefile:25: all] Error 2

I tried to checkout 2.6 and build.
I get the same error

What am I doing wrong now?

**Comment by saurabhkumar** [comment]
Sorry, my mistake with that.
Now I cloned using `git clone --recurse-submodules -j8 https://github.com/RedisGraph/RedisGraph.git`
Then I did `git checkout 2.4`

Now `make ` gives the following error:

> /path_to_src/src/commands/execution_ctx.c: In function
> _GetExecutionTypeFromAST’:
> /path_to_src/src/commands/execution_ctx.c:17:18: error:
> ‘CYPHER_AST_DROP_NODE_PROPS_INDEX’ undeclared (first use in this function); did you mean ‘CYPHER_AST_DROP_PROPS_INDEX’?
>    17 |  if(root_type == CYPHER_AST_DROP_NODE_PROPS_INDEX) return EXECUTION_TYPE_INDEX_DROP;
>       |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                  CYPHER_AST_DROP_PROPS_INDEX
> /home/devops/redissgraph_github/RedisGraph/src/commands/execution_ctx.c:17:18: note: each undeclared identifier is reported only once for each function it appears in
> make[1]: *** [Makefile:200: /path_to_src/src/commands/execution_ctx.o] Error 1
> make[1]: Leaving directory '/path_to_src/src'
> make: *** [Makefile:25: all] Error 2
> 

I tried to use 2.6.
But I get the same error.

Am I still missing something?

**Comment by saurabhkumar** [comment]
Sorry, my mistake with that.
Now I cloned using git clone --recurse-submodules -j8 https://github.com/RedisGraph/RedisGraph.git
Then I did git checkout 2.4

Now make gives the following error:

/path_to_src/src/commands/execution_ctx.c: In function
_GetExecutionTypeFromAST’:
/path_to_src/src/commands/execution_ctx.c:17:18: error:
‘CYPHER_AST_DROP_NODE_PROPS_INDEX’ undeclared (first use in this function); did you mean ‘CYPHER_AST_DROP_PROPS_INDEX’?
17 | if(root_type == CYPHER_AST_DROP_NODE_PROPS_INDEX) return EXECUTION_TYPE_INDEX_DROP;
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| CYPHER_AST_DROP_PROPS_INDEX
/path_to_src/src/commands/execution_ctx.c:17:18: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:200: /path_to_src/src/commands/execution_ctx.o] Error 1
make[1]: Leaving directory '/path_to_src/src'
make: *** [Makefile:25: all] Error 2

I tried to use 2.6.
But I get the same error.

Am I still missing something?

**Comment by swilly22** [comment]
Switching from `master` to `2.4` requires refetch of submodules via:
`git submodule update --init --recursive`

**Comment by saurabhkumar** [comment]
Thanks. This solved my build issue.
