### ISSUE TITLE
Redisgraph installation error

### ISSUE THREAD

**Issue by milanchheda** [RedisGraph/RedisGraph#2353]
I am trying to install redisgraph on fresh Ubuntu 20.04 server. After following the steps, I am getting the following error upon executing `make` command:

```
make -C /home/ubuntu/RedisGraph/deps/RediSearch STATIC=1 BINROOT=/home/ubuntu/RedisGraph/bin/linux-x64-release
deps/readies/mk/main:45: *** Cannot find python2 interpreter.
Use can install one by running 'make setup'..  Stop.
make[1]: *** [Makefile:292: /home/ubuntu/RedisGraph/bin/linux-x64-release/search-static/libredisearch.a] Error 2
make: *** [Makefile:45: all] Error 2
```

I have installed `python2` but it still gives the same error. Any direction to resolve this issue would be of great help.

**Comment by rafie** [comment]
Hello @milanchheda,
I apologize for the lack of proper documentation of the build process - we're fixing it now.
Basically, to build RedisGraph you need to invoke the following:
```
./deps/readies/bin/getpy3
./sbin/system-setup.py
```
And then: `bash -l` followed by `make` (that is, invoke a logic shell to activate profile.d scripts).
It is highly recommended to perform installation and build experiments in a protected environment, e.g. inside a docker container (often used with `-v` to access local files system via a volume mount).

**Comment by milanchheda** [comment]
Thanks that has helped. I forgot to close three issue.
