### ISSUE TITLE
Getting the following error “Attempted to access undefined property” while adding an index to an EDGE property

### ISSUE THREAD

**Issue by blockchain-art** [RedisGraph/RedisGraph#2370]
We're running into a weird RedisGraph problem when adding indexes to an `EDGE` property.

Syntax we're using is: `CREATE INDEX FOR ()-[mea:MEASURES]-() ON (mea.dimension)`, and the error message we get back is: **“Attempted to access undefined property”**. Under what circumstances is this error returned?

To note;
- we're able to add indexes to other EDGEs
- the EDGE `:MEASURES` with property `dimension` both exist, and when we query it using: `MATCH ()-[m:MEASURES]-() RETURN DISTINCT(m.dimension)` we get `224` values
- version of RedisGraph we're running is `2.8.13`, via a docker image: `redislabs/redisgraph:2.8.13`

**Comment by swilly22** [comment]
Hi @blockchain-art,
Would it be possible to get steps to reproduce this issue ?

**Comment by blockchain-art** [comment]
@swilly22 we're only able to reproduce the issue once we load all of our data into the graph, whose size is then around 12GB. If we write dummy data to the graph then we're unable to reproduce the issue

**Comment by swilly22** [comment]
thanks, are you able to test this outside of a docker container ?

**Comment by AviAvni** [comment]
@blockchain-art how did you load the data?

**Comment by blockchain-art** [comment]
@AviAvni we write the data using regular cypher queries

@swilly22 sorry for the delay in getting back, haven't had the time to explore this option yet will update once I do

**Comment by AviAvni** [comment]
@blockchain-art I was able to reproduce the issue and proposed a fix https://github.com/RedisGraph/RedisGraph/pull/2471
