### ISSUE TITLE
Unable to raise MAX_QUEUED_QUERIES error

### ISSUE THREAD

**Issue by DavidS-B** [RedisGraph/RedisGraph#2405]
I'm investigating the MAX_QUEUED_QUERIES configuration parameter and I'm trying to trigger its error "Max pending queries exceeded" but with no success.

I have set the MAX_QUEUED_QUERIES parameter to 1 and then tried a lot of things:
* parallelizing the processing of thousands of queries.
* with redis-cli using the MULTI command to add a lot of queries to the queue.
* with redis-benchmark  using various GRAPH.QUERY entries and configurations.

I found nothing online to help me on the subject, and I don't know if there is something that I don't understand or if it's a bug.
Any help would be greatly appreciated!

**Comment by AviAvni** [comment]
@DavidS-B thanks for using query graph
MAX_QUEUED_QUERIES is the number of queries that is waiting to be processed when all threads in the thread pool is fully busy with queries

can you share the script you tried of the first point?

in the second point multi command don't use the thread pool so MAX_QUEUED_QUERIES has no effects

you will see an error "Max pending queries exceeded" returned from query

you need to make sure the query is slow enough and you can also decrease the amount of threads in thread pool

**Comment by DavidS-B** [comment]
@AviAvni @LiorKogan Thank you for your help

First of all, the result of "GRAPH.CONFIG GET *":
```text
 1) 1) "TIMEOUT"
    2) (integer) 0
 2) 1) "CACHE_SIZE"
    2) (integer) 25
 3) 1) "ASYNC_DELETE"
    2) (integer) 1
 4) 1) "OMP_THREAD_COUNT"
    2) (integer) 4
 5) 1) "THREAD_COUNT"
    2) (integer) 4
 6) 1) "RESULTSET_SIZE"
    2) (integer) -1
 7) 1) "VKEY_MAX_ENTITY_COUNT"
    2) (integer) 100000
 8) 1) "MAX_QUEUED_QUERIES"
    2) (integer) 1
 9) 1) "QUERY_MEM_CAPACITY"
    2) (integer) 0
10) 1) "DELTA_MAX_PENDING_CHANGES"
    2) (integer) 10000
11) 1) "NODE_CREATION_BUFFER"
    2) (integer) 16384
```

**Comment by AviAvni** [comment]
@DavidS-B I'm not sure about the implementation of the elixir client but probably sync client so you not parallelize try to open new connection on each task

**Comment by DavidS-B** [comment]
@AviAvni Thank you for your help! I can raise the error now
