### ISSUE TITLE
toJson() error or outdated documentation

### ISSUE THREAD

**Issue by stakez** [RedisGraph/RedisGraph#2429]
According to https://redis.io/commands/graph.query/#list-functions, toJson() invocation on relationship objects should appear like the following image

<img width="725" alt="Screen Shot 2022-06-25 at 12 52 03 AM" src="https://user-images.githubusercontent.com/99569934/175762213-3c7e5a3d-341b-4733-b93c-c8886a3a3303.png">
 
However, I get the following map structure using test data on my local machine against remote RedisGraph  running V2.8.13

`{
  type: 'relationship',
  id: 0,
  relationship: 'worksFor',
  properties: { name: 'water plc', b: true },
  start: { id: 1, labels: [ 'Stuff1' ], properties: { name: 'jon' } },
  end: {
    id: 0,
    labels: [ 'Stuff' ],
    properties: { name: 'bill', fol: [ 'bold', true ] }
  }
}`

The main issue being that the documentation has the `label` key while my local machine queries are getting the `relationship` key instead. Is the documentation outdated or this is an error?

**Comment by LiorKogan** [comment]
@stakez Thank you for reporting. 

This is indeed a documentation issue. Will be fixed soon.

**Comment by stakez** [comment]
Thanks for the clarification @LiorKogan .
