### ISSUE TITLE
T_NULL in SI_VALID_PROPERTY_VALUE

### ISSUE THREAD

**Issue by MikkelSnitker** [RedisGraph/RedisGraph#2439]
Hi. 
Just a quick question:
Shouldn't T_NULL be included in SI_VALID_PROPERTY_VALUE ?(https://github.com/RedisGraph/RedisGraph/blob/master/src/value.h)

/mikkel

**Comment by MikkelSnitker** [comment]
> no because we don't store null also neo4j not store null in node/edges attributes

Ok. is there a way do avoid this returning 'Property values can only be of primitive types or arrays of primitive types'

`CYPHER test = [{id: 1, aField: "withValue",andOneWithout: null}] UNWIND $test as item MERGE (n:foobar{id: item.id}) ON CREATE SET n += item ON MATCH SET n += item`

**Comment by swilly22** [comment]
As @AviAvni said we don't allow `NULL` values to be stored as attributes
Let me suggest a simple rewrite (I've removed the `andOneWithout` key as its value is `NULL`):
```
CYPHER test = [{id: 1, aField: "withValue"}]
UNWIND $test as item
MERGE (n:foobar{id: item.id})
SET n += item 
```

**Comment by MikkelSnitker** [comment]
In [src/execution_plan/ops/op_merge.c](https://github.com/RedisGraph/RedisGraph/blob/b0ecf0c8d980e6d1be9d4d17671516c68a48b6f9/src/execution_plan/ops/op_merge.c) _UpdateProperties call's EvalEntityUpdates with allow_null false, but in [src/execution_plan/ops/op_update.c](https://github.com/RedisGraph/RedisGraph/blob/b0ecf0c8d980e6d1be9d4d17671516c68a48b6f9/src/execution_plan/ops/op_update.c) it's called with allow_null true. What's the reason for that?

**Comment by swilly22** [comment]
@MikkelSnitker that's a good point, @AviAvni do you recall why we differentiate in this case, I believe it has to do something with compatibility with other graph vendors...

**Comment by AviAvni** [comment]
yes the difference is that in update we also to set null to remove a property instead of using remove that will be introduced in 2.10.0
in merge we don't allow because it is like create we don't allow to add property with value null

**Comment by MikkelSnitker** [comment]
wouldn't it be possible to allow null in merge, and then just ignore null properties if it matches ON CREATE ?

**Comment by AviAvni** [comment]
would you like have a zoom meeting with about this?

**Comment by MikkelSnitker** [comment]
I'm not sure that will be needed. If you can accept the "solution" I proposed I'll be happy to make a PR. Otherwise I'll just use my fork of the repo.
