### ISSUE TITLE
GRAPH.CONFIG docs link wrong SET command

### ISSUE THREAD

**Issue by sazzad16** [RedisGraph/RedisGraph#2445]
Command documentation pages of both [GRAPH.CONFIG SET](https://redis.io/commands/graph.config-set/) and [GRAPH.CONFIG GET](https://redis.io/commands/graph.config-get/) commands wrongfully links [regular SET](https://redis.io/commands/set) command.

**Comment by LiorKogan** [comment]
Both docs updated. Thanks.
