### ISSUE TITLE
Wrong result query in creating edges

### ISSUE THREAD

**Issue by ddaa2000** [RedisGraph/RedisGraph#2487]
RedisGraph 2.8.15
After executing following queries in an empty database:
CREATE (n0) RETURN *;
CREATE (n1 :L1 :L3 :L4{k7:-648503374, k25:'FA'}) RETURN *;
CREATE (n2 :L0 :L1 :L4{k26:-740728607}) RETURN *;
CREATE (n3 :L3{k19:'el'}) RETURN *;
CREATE (n4 :L1 :L2{k9:'K', k13:-648503374, k14:false}) RETURN *;
CREATE (n5) RETURN *;
CREATE (n6 :L2 :L4 :L5 :L6{k12:false, k15:-20004647, k17:'MvLR', k26:929398578, k29:'N7L6zJ', k31:'3XqhsYezV', k35:929398578}) RETURN *;
CREATE (n7 :L3 :L5{k20:'', k24:'MPhU8XD'}) RETURN *;
CREATE (n8 :L0{k0:false}) RETURN *;
CREATE (n9 :L0 :L3 :L6{k1:true, k2:'', k20:'7', k21:'p'}) RETURN *;
CREATE (n10) RETURN *;
CREATE (n11 :L4{k26:1802376245}) RETURN *;
CREATE (n12 :L2 :L4{k11:true, k13:615778134, k28:-740728607}) RETURN *;
CREATE (n13 :L1{k8:'F8CuXn', k10:-345621334}) RETURN *;
CREATE (n14 :L3{k18:true, k19:'ofy', k23:'TW', k24:''}) RETURN *;
CREATE (n15) RETURN *;
CREATE (n16) RETURN *;
CREATE (n17 :L1 :L5{k6:false, k8:'D', k34:'m5', k36:true, k37:true}) RETURN *;
CREATE (n18 :L3 :L6{k24:'6L0X', k39:false, k41:'sk'}) RETURN *;
MATCH (n6 :L2 :L4 :L5 :L6{k12:false, k15:-20004647, k17:'MvLR', k26:929398578, k29:'N7L6zJ', k31:'3XqhsYezV', k35:929398578}), (n15) MERGE (n6)-[r0 :T4]->(n15) RETURN *;
MATCH (n7 :L3 :L5{k20:'', k24:'MPhU8XD'}), (n10) MERGE (n7)<-[r1 :T3{k62:899521365}]-(n10) RETURN *;

Then execute:
MATCH (n0)-[r]->(n1) RETURN 2

The result should contain 38 lines since their should be 38 relationships in the database (just as neo4j do). However, I got 37 lines instead:

127.0.0.1:6379> GRAPH.QUERY TEST "MATCH (n0)-[r]->(n1) RETURN 2"
1) 1) "2"
2)  1) 1) (integer) 2
    2) 1) (integer) 2
    3) 1) (integer) 2
    4) 1) (integer) 2
    5) 1) (integer) 2
    6) 1) (integer) 2
    7) 1) (integer) 2
    8) 1) (integer) 2
    9) 1) (integer) 2
   10) 1) (integer) 2
   11) 1) (integer) 2
   12) 1) (integer) 2
   13) 1) (integer) 2
   14) 1) (integer) 2
   15) 1) (integer) 2
   16) 1) (integer) 2
   17) 1) (integer) 2
   18) 1) (integer) 2
   19) 1) (integer) 2
   20) 1) (integer) 2
   21) 1) (integer) 2
   22) 1) (integer) 2
   23) 1) (integer) 2
   24) 1) (integer) 2
   25) 1) (integer) 2
   26) 1) (integer) 2
   27) 1) (integer) 2
   28) 1) (integer) 2
   29) 1) (integer) 2
   30) 1) (integer) 2
   31) 1) (integer) 2
   32) 1) (integer) 2
   33) 1) (integer) 2
   34) 1) (integer) 2
   35) 1) (integer) 2
   36) 1) (integer) 2
   37) 1) (integer) 2

**Comment by LiorKogan** [comment]
Duplicate of #2208
