### ISSUE TITLE
Query taking too much time

### ISSUE THREAD

**Issue by ddaa2000** [RedisGraph/RedisGraph#2538]
RedisGraph 2.8.14
After using following statements to create the graph:
[graph.txt](https://github.com/RedisGraph/RedisGraph/files/9335684/graph.txt)

Then execute the following two queries：
MATCH (n0) WHERE (true IS NOT NULL) OPTIONAL MATCH (n0)<-[r0 :T0 *3..]-(n1) WHERE ('' > 'e') WITH r0 RETURN DISTINCT 1

RedisGraph version 2.10.1 took more than 60s while memgraph only used 2s.

**Comment by AviAvni** [comment]
duplicate https://github.com/RedisGraph/RedisGraph/issues/2488
did you noticed the on both queries the where contains an expression that can be evaluated to false which is common to happen in real queries
