### ISSUE TITLE
redisgraph-bulk-loader is not loading all relationships

### ISSUE THREAD

**Issue by zanek** [RedisGraph/RedisGraph#255]
I have a huge 60mb nodes file with some relationship files containing about 800000 edges. Everything loads correctly in the bulk loader, but when I query for  nodes that I have verified have IDs in the nodes & relationships files, I get no results.

Is there anyway to see all the relationships coming out from a particular node ?

Has anyone experienced this before ? This is making me think Redisgraph is unstable and to alpha to be used

**Comment by swilly22** [comment]
Can you please share the query which you suspect produce incorrect results?
To retrieve all outgoing relationships of a particular node with ID: K use this query:
GRAPH.QUERY "MATCH (n)-[e]->() WHERE ID(n) = K RETURN e"

**Comment by zanek** [comment]
If I do:

GRAPH.QUERY CONS "MATCH (d:nodes {id:986089})-[e]->(p:nodes) RETURN d,e,p LIMIT 5 "

I get back:

127.0.0.1:6379> GRAPH.QUERY CONS "MATCH (d:nodes {id:986089})-[e]->(p:nodes) RETURN d,e,p LIMIT 5 "
1) 1) 1) "d.uri"
      2) "d.id"
      3) "d.label"
      4) "e"
      5) "p.uri"
      6) "p.id"
      7) "p.label"
2) 1) "Query internal execution time: 229.697000 milliseconds"

However, if I just do:

127.0.0.1:6379> GRAPH.QUERY CONS "MATCH (d:nodes {id:986089}) RETURN d LIMIT 5 "
1) 1) 1) "d.uri"
      2) "d.id"
      3) "d.label"
   2) 1) "/conductor/nin"
      2) "986089.000000"
      3) "conductor"
2) 1) "Query internal execution time: 130.122000 milliseconds"

If I look in my relationships file, I can see a lines with  
85546 , 986089
986089,1009750
986089,981074

If I do this query, I get results:

127.0.0.1:6379> GRAPH.QUERY CONS "MATCH (d:nodes {id:1009750}) RETURN d LIMIT 5 "
1) 1) 1) "d.uri"
      2) "d.id"
      3) "d.label"
   2) 1) "/medium/n"
      2) "1009750.000000"
      3) "medium"
2) 1) "Query internal execution time: 128.798000 milliseconds"


Results from my bulk insert are:

5035264 relations created in 10 queries.
Successfully constructed 1524817 nodes and 688881 edges in graph 'CONS'

**Comment by swilly22** [comment]
Hey @zanek,
Let me elaborate on how bulk-insert works, suppose you've got one CSV file representing your nodes, let's call it nodes.csv, in it there are 100 nodes, header row of nodes.csv would contain:
`ID, Name`
and so this is an example of a single row within nodes.csv:
`986089,Alex`

The property `ID`, you've specified, is treated simply as an attribute, similar to the Name attribute.

When RedisGraph process nodes.csv it would create a new graph, with 100 nodes, and it will assign an **internal** `ID` starting from 0 increasing linearly, and so those 100 nodes will be assigned internal IDs starting with 0 for the first node presented corresponding to the first row in nodes.csv and 99 to the last row.

These **internal** IDs are the ones you should use when creating your relationships csv file(s)
you can't refer to the ID property you've specified,
for example if you want to connect the first node in nodes.csv with the last node in nodes.csv then you would have to create relationships.csv and include the row: `0,99`

I know this is a bit messy and unclear, it's our intention to make bulk-insert simpler to use.
For the time-being I suggest you refer to [redisgraph-bulk-loader](https://github.com/RedisLabsModules/redisgraph-bulk-loader#determining-node-ids)
for complete documentation.

**Comment by swilly22** [comment]
Would you mind sharing your CSV files?

**Comment by swilly22** [comment]
One more thing I would like to verify, could you please run:
`GRAPH.QUERY "MATCH  (d:nodes {id:986089}) RETURN d, ID(d)"`
this will show **internal** `ID` assigned to node with "id" attribute with value 986089
if you want to use id 986089 within your relationship csv files ID(d) needs to be 986089.

Also I'm interested to see how many outgoing edges are there for that particular node
GRAPH.QUERY "MATCH  (d:nodes {id:986089})-[e]->() RETURN ID(d) COUNT(e)"
The return count should be the same as the number of rows in your relationship csv file(s)
starting with "986089"

**Comment by swilly22** [comment]
@zanek I don't think the file extension matters.

The current version of the Bulk-Insert python script doesn't support specifying attributes to relations, as such `e` will return empty as it doesn't have any attributes attached to it.

**Comment by zanek** [comment]
Alright, I'm still stumped as to the missing relationships then.

I was expecting "e" to show me the name of the file that the relationship  was imported from

I will try to send my import files shortly

**Comment by swilly22** [comment]
@zanek we've updated our bulk-insert python script to support relationship attribute,
please use the latest version of RedisGraph with the latest version of the script,
see [bulk-loader](https://github.com/RedisLabsModules/redisgraph-bulk-loader) updated doc

**Comment by swilly22** [comment]
Would you mind sharing the CSV files?
