### ISSUE TITLE
Slow execution seems optimizable

### ISSUE THREAD

**Issue by ddaa2000** [RedisGraph/RedisGraph#2557]
In RedisGraph2.10.1
1. Use following queries to create the graph:
[graph.txt](https://github.com/RedisGraph/RedisGraph/files/9418073/graph.txt)
2. Then execute:
```
MATCH (n0), (n1) WHERE (1850831210 > -1979128613) MATCH (n1)-[r0 *3..]-(n2) WHERE false RETURN 1
```

The query takes more than 1 minute to execute. However, as the last where clause is always false, the last MATCH clause is not necessary to be executed. Actually, in memgraph this query only takes a few mini seconds.

**Comment by AviAvni** [comment]
duplicate https://github.com/RedisGraph/RedisGraph/issues/2488
