### ISSUE TITLE
error while saving / encoding graph 

### ISSUE THREAD

**Issue by jer-0** [RedisGraph/RedisGraph#2594]
Hey I am seeing this error before redis crashing, (crash logs: https://github.com/RedisJSON/RedisJSON/issues/823)

```
* 100 changes in 300 seconds. Saving...
* Background saving started by pid 322
* <graph> Created 0 virtual keys for graph graphkey
thread '<unnamed>' panicked at 'byte index 24 is not a char boundary; it is inside '\0' (bytes 23..24) of `0�׭  ���֭         �       /�sE�|wle": "post title", "createdAt": 1657453992, "duration": 3671, "views": 3042, "pi%̭  ��׭                 ��$̭  spectRatio": 1.77777777777778, "actors": [{"id": "_tRJBw`[...]', library/core/src/str/mod.rs:127:5
run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Seems like the data gets corrupted, I don't know what it could be.

I am using: Linux Ubuntu 21, docker. redis/redis-stack-server:7.0.2-RC2

**Comment by gkorland** [comment]
Do you use RedisJSON commands or only Graph commands?

**Comment by Mon0Man** [comment]
I use both json and graph. I query data from redisgraph and then add to redisjson. I use both redisjson and redisgraph commands throughout my application.

**Comment by Mon0Man** [comment]
I believe this problem seems to occur when running both redisjson and redisgraph commands on the same redis instance. 
I now separate json and graph to two different redis instance and run each queries separately and didn't crash.

related: 
https://github.com/RedisGraph/RedisGraph/issues/2095 
https://github.com/RedisJSON/RedisJSON/issues/823

**Comment by ZhenNan2016** [comment]
Hi @gkorland 
I'm so sorry to bother you. 
I have some questions about redisgraph that I need to consult with you, and I don't know how to contact you. 
Can I consult here?
After confirming the contact information in a moment, you can delete this reply content.
Thank you very much.
