### ISSUE TITLE
Single backslash '\' cannot be set in the database

### ISSUE THREAD

**Issue by BhanuPrakash531** [RedisGraph/RedisGraph#2646]
We cannot set single backslash ‘\’ in the database. If I add one ‘\’ it is ignoring it and if I add 2 ‘\\’ it is creating two backslashes in the database.

Please find steps to replicate.

```
127.0.0.1:6379> "graph.QUERY" "Test" "CREATE (n:Test{name:'Test'}) RETURN n"
1) 1) "n"
2) 1) 1) 1) 1) "id"
            2) (integer) 1611769
         2) 1) "labels"
            2) 1) "Test"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Test"
3) 1) "Labels added: 1"
   2) "Nodes created: 1"
   3) "Properties set: 1"
   4) "Cached execution: 0"
   5) "Query internal execution time: 29.001000 milliseconds"
127.0.0.1:6379>
127.0.0.1:6379>
127.0.0.1:6379> "graph.QUERY" "Test" "MATCH (n:Test{name:'Test'}) SET n.address = '123 \\4 cross street' RETURN n"
1) 1) "n"
2) 1) 1) 1) 1) "id"
            2) (integer) 1611769
         2) 1) "labels"
            2) 1) "Test"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Test"
               2) 1) "address"
                  2) "123 \\4 cross street"
3) 1) "Properties set: 1"
   2) "Cached execution: 0"
   3) "Query internal execution time: 19.276600 milliseconds"
127.0.0.1:6379> "graph.QUERY" "Test" "MATCH (n:Test{name:'Test'}) SET n.address = '123 \4 cross street' RETURN n"
1) 1) "n"
2) 1) 1) 1) 1) "id"
            2) (integer) 1611769
         2) 1) "labels"
            2) 1) "Test"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Test"
               2) 1) "address"
                  2) "123 4 cross street"
3) 1) "Properties set: 1"
   2) "Cached execution: 0"
   3) "Query internal execution time: 11.315800 milliseconds"
```

**Comment by OfirMos** [comment]
This is not a problem in the module, but a problem in Redis RESP2
@LiorKogan
Opened a ticket for it:
https://redislabs.atlassian.net/browse/RED-88078

**Comment by OfirMos** [comment]
Hi @[BhanuPrakash531](https://github.com/BhanuPrakash531)
BhanuPrakash531 ,
This an intentional behaviour of the redis client to return the string with the escaping backslash.
For instance:
`127.0.0.1:6379> set a "\\"
OK
127.0.0.1:6379> strlen a
(integer) 1
127.0.0.1:6379> get a
"\\"`

So you can run redis-cli --raw to get one backslash:
`ofir:RedisGraph ofir.moskovich$ redis-cli --raw
127.0.0.1:6379> set t "a \\ bla"
OK
127.0.0.1:6379> get t
a \ bla`

**Comment by LiorKogan** [comment]
@BhanuPrakash531 
there is no issue in setting a single backslash.
A single backslash is printed as a double backslash in redis-cli, but you can try the following:

```
graph.QUERY Test "CREATE (n:Test{name:'Test'}) RETURN n"
graph.QUERY Test "MATCH (n:Test{name:'Test'}) SET n.address = '123 \\4 cross street' RETURN substring(n.address, 4, 1)"
1) 1) "substring(n.address, 4, 1)"
2) 1) 1) "\\"
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 3.437600 milliseconds"
```

The `substring` function above returns a single character at zero-based offset 4, which is the single backslash.
You can see that it is printed as a double backslash, but again - this is a single character.
