### ISSUE TITLE
 Bug Report

### ISSUE THREAD

**Issue by hpapaxen** [RedisGraph/RedisGraph#2694]
8:M 04 Nov 2022 10:14:25.204 # Redis 6.2.7 crashed by signal: 11, si_code: 1
8:M 04 Nov 2022 10:14:25.204 # Accessing address: 0x20
8:M 04 Nov 2022 10:14:25.204 # Crashed running the instruction at: 0x7fd2a516bbf2

------ STACK TRACE ------
EIP:
/opt/redis-stack/lib/redisgraph.so(Query_EvalNode+0x22)[0x7fd2a516bbf2]

Backtrace:
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7fd2a75a5420]
/opt/redis-stack/lib/redisgraph.so(Query_EvalNode+0x22)[0x7fd2a516bbf2]
/opt/redis-stack/lib/redisgraph.so(QAST_Iterate+0x52)[0x7fd2a516c622]
/opt/redis-stack/lib/redisgraph.so(+0x12881cd)[0x7fd2a51731cd]
/opt/redis-stack/lib/redisgraph.so(RediSearch_GetResultsIterator+0x45)[0x7fd2a51733b5]
/opt/redis-stack/lib/redisgraph.so(+0x2023d9)[0x7fd2a40ed3d9]
/opt/redis-stack/lib/redisgraph.so(+0x2013bc)[0x7fd2a40ec3bc]
/opt/redis-stack/lib/redisgraph.so(+0x201094)[0x7fd2a40ec094]
/opt/redis-stack/lib/redisgraph.so(ExecutionPlan_Execute+0x50)[0x7fd2a40e15d0]
/opt/redis-stack/lib/redisgraph.so(+0x1f0f03)[0x7fd2a40dbf03]
/opt/redis-stack/lib/redisgraph.so(+0x236acf)[0x7fd2a4121acf]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609)[0x7fd2a7599609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7fd2a74be133]

------ REGISTERS ------
8:M 04 Nov 2022 10:14:25.210 #
RAX:0000000000000000 RBX:00007fd2a1ee43c0
RCX:0000000000000000 RDX:00007fd2a1ee42c0
RDI:00007fd2a1ee4250 RSI:0000000000000000
RBP:00007fd2a1ee42f0 RSP:00007fd2a1ee41b0
R8 :00007fd2a1ee42b0 R9 :00007fd29b045460
R10:00007fd2a1ee42c0 R11:00007fd2a7000900
R12:00007fd28e2241e0 R13:00007fd2a6e5f180
R14:00007fd28e224250 R15:00007fd2a1ee42b0
RIP:00007fd2a516bbf2 EFL:0000000000010246
CSGSFS:002b000000000033
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41bf) -> 00007fd28e2241e0
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41be) -> 00007fd2a1ee42f0
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41bd) -> 00007fd2a1ee43c0
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41bc) -> 00007fd2a6e5f180
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41bb) -> e599bbfb814d4100
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41ba) -> 0000000000000010
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41b9) -> 00005630ff84b954
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41b8) -> 00007fd2a1ee42c0
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41b7) -> e599bbfb814d4100
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41b6) -> 0000000000000001
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41b5) -> 00007fd2a1ee42bf
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41b4) -> 00007fd2a1ee4327
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41b3) -> 000000000000002a
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41b2) -> 0000000000000000
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41b1) -> 0000000000000040
8:M 04 Nov 2022 10:14:25.210 # (00007fd2a1ee41b0) -> 0000000000001000

------ INFO OUTPUT ------
Server

redis_version:6.2.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:adcdff4a0d295794
redis_mode:standalone
os:Linux 5.15.57-0-virt x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:9.4.0
process_id:8
process_supervised:no
run_id:6a091ef5ceec7b2ad9b07b697109cad878e1c037
tcp_port:6379
server_time_usec:1667556865203167
uptime_in_seconds:29
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:6612481
executable:/opt/redis-stack/bin/redis-server
config_file:
io_threads_active:0
Clients

connected_clients:1
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:32
client_recent_max_output_buffer:0
blocked_clients:1
tracking_clients:0
clients_in_timeout_table:0
Memory

used_memory:143781736
used_memory_human:137.12M
used_memory_rss:156348416
used_memory_rss_human:149.11M
used_memory_peak:164527624
used_memory_peak_human:156.91M
used_memory_peak_perc:87.39%
used_memory_overhead:1026960
used_memory_startup:1006312
used_memory_dataset:142754776
used_memory_dataset_perc:99.99%
allocator_allocated:144018344
allocator_active:145039360
allocator_resident:149073920
total_system_memory:8350715904
total_system_memory_human:7.78G
used_memory_lua:32768
used_memory_lua_human:32.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.01
allocator_frag_bytes:1021016
allocator_rss_ratio:1.03
allocator_rss_bytes:4034560
rss_overhead_ratio:1.05
rss_overhead_bytes:7274496
mem_fragmentation_ratio:1.09
mem_fragmentation_bytes:13015200
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:20512
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0
Persistence

loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1667556836
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0
Stats

total_connections_received:1
total_commands_processed:10
instantaneous_ops_per_sec:0
total_net_input_bytes:503
total_net_output_bytes:34303
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:3
evicted_keys:0
keyspace_hits:21
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:8
total_writes_processed:7
io_threaded_reads_processed:0
io_threaded_writes_processed:0
Replication

role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:c9846ede05fef391a02668a2c63c2c7c8e003007
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
CPU

used_cpu_sys:0.102682
used_cpu_user:3.331731
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
used_cpu_sys_main_thread:0.000000
used_cpu_user_main_thread:0.005545
Modules

module:name=graph,ver=20819,api=1,filters=0,usedby=[],using=[ReJSON],options=[]
module:name=ReJSON,ver=20200,api=1,filters=0,usedby=[search|graph],using=[],options=[handle-io-errors]
module:name=search,ver=20414,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=timeseries,ver=10617,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
module:name=bf,ver=20218,api=1,filters=0,usedby=[],using=[],options=[]
Commandstats

cmdstat_acl:calls=2,usec=76,usec_per_call=38.00,rejected_calls=0,failed_calls=0
cmdstat_graph.QUERY:calls=2,usec=2039,usec_per_call=1019.50,rejected_calls=0,failed_calls=0
cmdstat_info:calls=3,usec=341,usec_per_call=113.67,rejected_calls=0,failed_calls=0
cmdstat_graph.RO_QUERY:calls=1,usec=367349,usec_per_call=367349.00,rejected_calls=0,failed_calls=0
cmdstat_command:calls=1,usec=465,usec_per_call=465.00,rejected_calls=0,failed_calls=0
cmdstat_client:calls=1,usec=12,usec_per_call=12.00,rejected_calls=0,failed_calls=0
Errorstats
Cluster

cluster_enabled:0
Keyspace

db0:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=16 addr=127.0.0.1:35194 laddr=127.0.0.1:6379 fd=12 name=redisinsight-workbench-7771aeea age=11 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=40954 argv-mem=69 obl=0 oll=0 omem=0 tot-mem=61533 events=r cmd=graph.QUERY user=default redir=-1

------ MODULES INFO OUTPUT ------
graph_executing commands

graph_command:GRAPH.QUERY match (m:Methods) where id(m) in [99929] return m
ReJSON_trace

ReJSON_trace: 0: redis_module::base_info_func
1: rejson::__info_func
2: modulesCollectInfo
at /__w/redis-stack/redis-stack/redis/src/module.c:7100:9
3: logModulesInfo
at /__w/redis-stack/redis-stack/redis/src/debug.c:1598:22
4: printCrashReport
at /__w/redis-stack/redis-stack/redis/src/debug.c:1849:5
5: sigsegvHandler
at /__w/redis-stack/redis-stack/redis/src/debug.c:1831:5
6:
7: Query_EvalNode
8: QAST_Iterate
9: handleIterCommon
10: RediSearch_GetResultsIterator
11: IndexScanConsume
12: ProjectConsume
13: ResultsConsume
14: ExecutionPlan_Execute
15: _ExecuteQuery
16: thread_do
17: start_thread
18: clone
search_version

search_RedisSearch_version:6.2.7
search_index

search_number_of_indexes:0
search_fields_statistics
search_runtime_configurations

search_concurrent_mode:OFF
search_enableGC:ON
search_minimal_term_prefix:2
search_maximal_prefix_expansions:200
search_query_timeout_ms:500
search_timeout_policy:return
search_cursor_read_size:1000
search_cursor_max_idle_time:300000
search_max_doc_table_size:1000000
search_max_search_results:10000
search_max_aggregate_results:10000
search_search_pool_size:20
search_index_pool_size:8
search_gc_scan_size:100
search_min_phonetic_term_length:3

------ FAST MEMORY TEST ------
8:M 04 Nov 2022 10:14:25.229 # main thread terminated
8:M 04 Nov 2022 10:14:25.230 # Bio thread for job type #0 terminated
8:M 04 Nov 2022 10:14:25.230 # Bio thread for job type https://github.com/redis/redis/issues/1 terminated
8:M 04 Nov 2022 10:14:25.231 # Bio thread for job type https://github.com/redis/redis/issues/2 terminated

Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.
------ DUMPING CODE AROUND EIP ------
Symbol: Query_EvalNode (base: 0x7fd2a516bbd0)
Module: /opt/redis-stack/lib/redisgraph.so (base 0x7fd2a3eeb000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x7fd2a516bbd0 -D -b binary -m i386:x86-64 /tmp/dump.bin

8:M 04 Nov 2022 10:14:25.231 # dump of function (hexdump of 162 bytes):
f30f1efa415741564155415455534883ec6864488b042528000000488944245831c0837e200e0f87f40200008b4620488d15a6c910004989fc4889f5486304824801d03effe0662e0f1f840000000000e80b8307004989c50f1f840000000000488b4424586448330425280000000f85650800004883c4684c89e85b5d415c415d415e415fc3662e0f1f840000000000e89bfeffff4989c5ebc6660f1f440000488b
Function at 0x7fd2a51e3f30 is NewEmptyIterator
Function at 0x7fd2a516bb00 is Query_EvalTokenNode

**Comment by LiorKogan** [comment]
Thank you for reporting.
This is identical to #2591 and was fixed already in #2592.
The fix is available in RedisGraph 2.8.20 and 2.10.2 (which are available in the latest Redis Stack release candidates, soon to be released).
