### ISSUE TITLE
GRAPH.QUERY

### ISSUE THREAD

**Issue by DanielNinchev** [RedisGraph/RedisGraph#2738]
Functions toBoolean() and properties() do not work for me. Am I doing something wrong? I receive error message "Unknown function 'toBoolean'" or "Unknown function 'properties'". Any suggestions?

GRAPH.QUERY "test" "MATCH (hw:hardware)-[:OWNS]->(c:cameras)
RETURN toBoolean(c{.enabled})"

**Comment by LiorKogan** [comment]
These functions were introduced in v2.10. Which version are you using?
