### ISSUE TITLE
GRAPH.PROFILE timeout

### ISSUE THREAD

**Issue by swilly22** [RedisGraph/RedisGraph#2740]
In case `GRAPH.PROFILE` experience an error e.g. timeout. we should reply with an error and skip reporting profiling information.
One issue I see with this change is users experiencing timeouts on queries will want to analyze them using `GRAPH.PROFILE` 
They will not be able to investigate unless they increase / disable timeout.

**Comment by LiorKogan** [comment]
>  we should reply with an error and skip reporting profiling information.

I agree

> users experiencing timeouts on queries will want to analyze them using GRAPH.PROFILE. They will not be able to investigate unless they increase / disable timeout.

When users can't increase or disable timeout (e.g., RC) - indeed, they will have to resort to GRAPH.EXPLAIN or change the scope of the query.

**Comment by swilly22** [comment]
@raz-mon @AviAvni Please indicate this is fix on Jira as well.
