### ISSUE TITLE
Multi-dimensional queries with more than 2 linked node types

### ISSUE THREAD

**Issue by schwab** [RedisGraph/RedisGraph#278]
What is the correct approach to querying for entities with relationships to multiple other nodes?  I see how it's possible to specify up to 2 relationships by binding the target node between of two sets of arrows.  In this case return the count of dates were we have facts relating to  surgeons...
```

GRAPH.QUERY graph:surgeries "MATCH (s:surgeon)<-[:in]-(f:fact_periop)-[:in]->(d:date)  RETURN count(d)"
1) 1) 1) "count(d)"
   2) 1) "2145.000000"


```
How should this be expanded beyond just 2 dimensions?  For instance what if we wanted the dates where we have a facts about surgeons and the facility?
Some approaches I've tried:
```
GRAPH.QUERY graph:periop "MATCH (s:surgeon)<-[:in]-(f:fact)-[:in]->(d:date) MATCH (f)-[:in]->(:facility)  RETURN count(d)"
(error) Alias 'f' reused. Entities with the same alias may not be referenced in multiple patterns.

```
```
GRAPH.QUERY graph:periop "MATCH (s:surgeon)<-[:in]-(f:fact)-[:in]->(d:date), (f)-[:in]->(:facility)  RETURN count(d)"
(error) Alias 'f' reused. Entities with the same alias may not be referenced in multiple patterns.

```
``GRAPH.QUERY graph:periop "MATCH (s:surgeon)<-[:in]-(f:fact)-[:in]->(d:date) and (f)-[:in]->(:facility)  RETURN count(d)"
(error) Syntax error at offset 54 near 'and'

``
Surely there must be a way to express multiple joins in the same query.  Are there other options for querying against star or snowflake like schemas, or are we limited to just 2 relationships per entity?

**Comment by schwab** [comment]
Looks Cypher generally supports these kinds of queries using the WITH statement.
from the SO question : .../questions/33564859/using-where-clause-in-multiple-relationships-in-neo4j
`MATCH (d:Department)<-[:WorksAt]-(t:Tutor)
WHERE d.name = 'Science' AND t.name = 'Maria Smith'
WITH t
MATCH (t)-[r:ResponsibleFor]->(c:Courses)
RETURN t.name, r, c`

Which allows for arbitrary numbers of MATCH statements to be combined into the same result (UNION)?

**Comment by K-Jo** [comment]
https://github.com/RedisLabsModules/RedisGraph/issues/254

**Comment by schwab** [comment]
Thanks for the feedback. It's great news that WITH and MATCH patterns will soon be supported.  

While working through potential work-arounds it occurred to me that an IN clause which could point at a standard redis cache SET would be an extremely useful filter.  IT should also be very fast (assuming redis graph can access standard SETs by key name in process.  

For instance  a query like:
``` (a:label1)-[:linkedto]->(b:label2) WHERE a.key IN {some:redis:set}``` would allow for leveraging sets that are created by other processes or based on information not in the current graph db.  Just a thought.

**Comment by swilly22** [comment]
@schwab the WITH clause has been available for while now, can you please verify that you can use it to perform multi dimensional queries?

**Comment by swilly22** [comment]
#474
