### ISSUE TITLE
Optimize-label-scan mistreating OPTIONAL MATCH leading to crash

### ISSUE THREAD

**Issue by raz-mon** [RedisGraph/RedisGraph#2784]
RedisGraph crashes after the following queries:

`CREATE (n:N)`

`MATCH (n:N) OPTIONAL MATCH (n:M)`

as a result of not treating the OPTIONAL MATCH in optimize-label-scan appropriately (need to neglect it).

**Comment by LiorKogan** [comment]
Duplicate of #2631

**Comment by LiorKogan** [comment]
See also #2631

**Comment by LiorKogan** [comment]
Duplicate of #2631
