### ISSUE TITLE
right(), left() - wrong reply when length is null

### ISSUE THREAD

**Issue by LiorKogan** [RedisGraph/RedisGraph#2798]
RedisGraph 2.10.4

```
GRAPH.QUERY g "RETURN right('abc', null)"
1) 1) "right('abc', null)"
2) 1) 1) "" 

GRAPH.QUERY g "RETURN left('abc', null)"
1) 1) "left('abc', null)"
2) 1) 1) (nil)
```

Note the difference between `left` and `right`, anyway, in both cases - the reply should be an error when the second argument is not a non-negative integer.

Note that when both arguments are null - the reply should not be an error - as it is:

```
GRAPH.QUERY g "RETURN left(null, null)"
1) 1) "left(null, null)"
2) 1) 1) (nil)
```

---

In addition, the error messages should be fixed:

```
GRAPH.QUERY g "RETURN left('abc', -1)"
(error) length must be positive integer

GRAPH.QUERY g "RETURN right('abc', -1)"
(error) length must be positive integer
```

"length must be positive integer" should be replaced with "length must be a non-negative integer".

**Comment by gkorland** [comment]
@LiorKogan it should be marked as a breaking change
