### ISSUE TITLE
How to update property on multiple relationships in specified path?

### ISSUE THREAD

**Issue by martinstepanek** [RedisGraph/RedisGraph#2834]
Update of one relationship is easy:
```
MATCH (u:UserNode {userId: 'a1fabd33-981f-4f21-aba0-21cf8619cea7'})<-[r:PARENT_OF*1]-(p:UserNode) 
SET r.numberPropery = r.numberPropery + 10
```

When updating multiple relationships, query doesn't throw error, but it updates nothing:
```
MATCH (u:UserNode {userId: 'a1fabd33-981f-4f21-aba0-21cf8619cea7'})<-[r:PARENT_OF*10]-(p:UserNode) 
SET r.numberPropery = r.numberPropery + 10
```

For this use-case, I am used to use `FOREACH` in Neo4j (that is not supported in RedisGraph) or `UNWIND`:
```
MATCH (u:UserNode {userId: 'a1fabd33-981f-4f21-aba0-21cf8619cea7'})<-[r:PARENT_OF*10]-(p:UserNode) 
UNWIND r as rel
SET rel.numberPropery = rel.numberPropery + 10
```
this also doesn't throw error, but doesn't update anything.

Any idea how to update property on n number of relationships in specified path?

**Comment by LiorKogan** [comment]
Thank you @martinstepanek 

I created #2835 based on your report here.

`FOREACH` is currently under development.

**Comment by LiorKogan** [comment]
@martinstepanek

For now, you can do:

`MATCH (a:A)-[r:R*1..10]->(b:B) UNWIND relationships(r) as rel set rel.x = 7`

See also #2774 which is relevant to your example and will be fixed soon.
