### ISSUE TITLE
exists() function returns empty array instead of false

### ISSUE THREAD

**Issue by martinstepanek** [RedisGraph/RedisGraph#2837]
```
match (n) RETURN exists(n)"
```

When node exists, query returns:
```
1) 1) "exists(u)"
2) 1) 1) "true"
```

When node doesn't exist:
```
1) 1) "exists(n)"
2) (empty array)
```

I would presume that correct consistent result would be: 
```
1) 1) "exists(u)"
2) 1) 1) "false"
```

**Comment by LiorKogan** [comment]
@martinstepanek thank you.
`exists` should accept a pattern, not a node, so this query should return an error.

This is a known issue (#2555), so I'm closing this as a duplicate.
