### ISSUE TITLE
The [:EDGE*] syntax is not working

### ISSUE THREAD

**Issue by DanielNinchev** [RedisGraph/RedisGraph#2848]
Hello, I have an issue with the following syntax:

MATCH (s:Site)-[:HAS_HARDWARE*]->(h:Hardware)
RETURN count(h)

Apparently, this query does not work today, although it worked all the times I have tried it before, including yesterday. It returns 0 and it should return 62. My graph database has the following relationships from (:Site) to (:Hardware):

(:Site)-[:HAS_RECORDINGSERVER]->(:RecordingServer)-[:HAS_HARDWARE]->(:Hardware)

I am trying to reach all hardwares with the relationship :HAS_HARDWARE starting from site. The following query however works fine:

MATCH (s:Site)-[:HAS_RECORDINGSERVER]->(rs:RecordingServer)-[:HAS_HARDWARE]->(h:Hardware)
RETURN count(h) 

Can somebody tell me where might be the problem? Is this some new bug or am I doing something wrong (if so, do you have any suggestions what might be the cause)? My version of RedisGraph today is v. 2.10.4

Thank you!

**Comment by LiorKogan** [comment]
> Apparently, this query does not work today

What changed between yesterday and today? Did you upgrade RedisGraph? What was the previous version?

**Comment by DanielNinchev** [comment]
My version yesterday was the same as today (2.10.4). Forgive me, now I have the impression that I may have misunderstood the current syntax. Could you please explain to me, is the MATCH (:X)-[:Y*]->(:Z) clause matching the Z nodes only when there are relationships Y in the entire path and no other relationships? I am very confused because yesterday the current syntax was working for a path that had many relationships with different names on it and it returned the count of a component under a site with a given site id that are several hops away. Literally yesterday the same query was returning 62 as a count and today it returns 0. Obviously something has changed today and I am trying to figure out where. The edges and nodes are the same in the database.

**Comment by LiorKogan** [comment]
>  I may have misunderstood the current syntax. Could you please explain to me

Please see the [Cypher Query Language Reference](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf) pages 11-12, or the `Variable length relationships` section in the [GRAPH.QUERY documentation](https://redis.io/commands/graph.query/).

>  yesterday the current syntax was working

I can only assume that either the query or the graph changed...

**Comment by polygonhell** [comment]
I think this is the same issue as I just filed
https://github.com/RedisGraph/RedisGraph/issues/2849

**Comment by polygonhell** [comment]
Note I just verified this is recently broken, the 2.10.5 container behaves correctly, the :latest version is broken

**Comment by polygonhell** [comment]
One final note it looks like this was broken on some versions of latest, For my test case at least 2.10.5 does not exhibit the behavior and as far as I can see neither does latest after I manually pulled the image.

**Comment by DanielNinchev** [comment]
> I think this is the same issue as I just filed #2849 The query works as expected unless you specify a Label on the RHS of the pattern, so I think it's a bug. Looks very much to me like it's treating the [:Y*] as just [:Y] if the Lael is specified on the right.
> 
> See my other example but It looks it's not as simple as * is applying to both the specified relationship label and the node type to it's right. In my example those are always consistent, it's just ignoring the * altogether

It did treat the [:Y*] as [:Y] in my case. But when the path contains only :Y edges, it works. However that was not the case when I tried this query before. Consider the following path:

(a)-[:X]->(b)-[:Y]->(c)-[:Z]->(d)

In this case I would be able to write the following query:
 MATCH (a)-[:Z*]->(d) RETURN count(d)
 and it would work.
 
 Now in order to get a valid result, the path needs to have only :Z edges:  (a)-[:Z]->(b)-[:Z]->(c)-[:Z]->(d)
 It didn't behave that way before. It would work even if there was no (a)-[:Z]->(d) in the graph.
 
 

> One final note it looks like this was broken on some versions of latest, For my test case at least 2.10.5 does not exhibit the behavior and as far as I can see neither does latest after I manually pulled the image.

We will try this on 2.10.5. and see if there is any difference.

**Comment by DanielNinchev** [comment]
Update: I probably misunderstood the way that syntax should work. I am closing the issue.
