### ISSUE TITLE
FOREACH crash

### ISSUE THREAD

**Issue by dtthuog755** [RedisGraph/RedisGraph#2874]
```
MATCH path=(u:Actor), (g:Actor { id: 'Marketing' })
WHERE u.id IN ['vietld', 'phuongdd']
UNWIND nodes(path) as nodePath
FOREACH (n IN (nodePath) | CREATE (n)-[:belong]->(g))
```
========OR=======
```
MATCH (u:Actor), (g:Actor { name: 'Marketing' })
WHERE u.id = 'vietld' OR u.id = 'phuongdd'
FOREACH (n IN CASE WHEN u.id = 'vietld' THEN [u] ELSE [] END | CREATE (n)-[:belong]->(g))
```

**Comment by raz-mon** [comment]
Hi @dtthuog755,

With no data there are no crashes for both queries, care to share some demo data with which the crash can be reproduced?

**Comment by dtthuog755** [comment]
@raz-mon  create (:Actor{id:'Marketing'}), (:Actor{id:'vietld'}), (:Actor{id:'phuongdd'})

**Comment by dtthuog755** [comment]
I also want use this query but it get error "_AR_EXP_UpdateEntityIdx: Unable to locate a value with alias path within the record"
MATCH path=(u:Actor), (g:Actor { id: 'Marketing' })
WHERE u.id IN ['vietld', 'phuongdd']
FOREACH (n in nodes(path) | create (n)-[:belong]->(g))

**Comment by raz-mon** [comment]
Notice that the first query is not valid, as nodePath is a node, and not a list (and the `()` brackets should be removed as well). This is due to the UNWIND of-course.
Regarding the other queries, we will investigate and update, thanks for bringing this up.
