### ISSUE TITLE
Hello, is there a tool similar to mysqldump?

### ISSUE THREAD

**Issue by zhangliang-zl** [RedisGraph/RedisGraph#2889]
rdb is unreadable, do you plan to provide other backup methods?

**Comment by zhangliang-zl** [comment]
A month ago, we encountered a lot of data loss due to rdb file corruption. Now hope to find a more reliable way of data backup.

**Comment by LiorKogan** [comment]
@zhangliang-zl we are not going to introduce such method.

Consider a high-availability solution: Setting up a Redis cluster or switching to Redis Enterprise or Redis Enterprise Cloud.

**Comment by LiorKogan** [comment]
@zhangliang-zl I also suggest that you take a look the [RedisGraph license](https://github.com/RedisGraph/RedisGraph/blob/master/LICENSE.txt).
