### ISSUE TITLE
MATCH query failure in RO_QUERY

### ISSUE THREAD

**Issue by SamWolfs** [RedisGraph/RedisGraph#2915]
**Redis version**: 7.0.8
**RedisGraph version**: 2.10.8

When upgrading from Redis 7.0.5 and RedisGraph 2.8.20, we started seeing a different behaviour when running a `MATCH` query as either `GRAPH.QUERY` or `GRAPH.RO_QUERY`. Unfortunately, I'm having a hard time finding documentation for this change in behaviour, so I am wondering whether it's intended.

### Redis (7.0.8), RedisGraph (2.10.8)

```
127.0.0.1:6379> GRAPH.RO_QUERY Bob "MATCH (node:person) RETURN node.id"
(error) ERR Invalid graph operation on empty key
127.0.0.1:6379> GRAPH.QUERY Fred "MATCH (node:person) RETURN node.id"
1) 1) "node.id"
2) (empty array)
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 1.074308 milliseconds"
127.0.0.1:6379> GRAPH.RO_QUERY Fred "MATCH (node:person) RETURN node.id"
1) 1) "node.id"
2) (empty array)
3) 1) "Cached execution: 1"
   2) "Query internal execution time: 0.104056 milliseconds"
```

### Redis (7.0.5), RedisGraph (2.8.20)

```
127.0.0.1:6379> GRAPH.RO_QUERY Bob "MATCH (node:person) RETURN node.id"
1) 1) "node.id"
2) (empty array)
3) 1) "Cached execution: 0"
   2) "Query internal execution time: 0.234448 milliseconds"
```

**Comment by raz-mon** [comment]
Hi @SamWolfs,
Yes, now must first create the graph key before performing read queries on it, via a write query.
You can also create the graph key by running `GRAPH.QUERY bob "RETURN 1"` if you wish to have an empty graph.

**Comment by SamWolfs** [comment]
Thanks @raz-mon!
We'll keep that in mind moving forward :)
