### ISSUE TITLE
Does redisgraph currently support its own extension algorithm?

### ISSUE THREAD

**Issue by 980849920** [RedisGraph/RedisGraph#292]
In addition to the basic graph algorithms that are currently supported, can I extend the graph's algorithm myself, how can I implement it?

**Comment by swilly22** [comment]
@980849920 as RedisGraph is written purely in C, it's not easily extendable.
One way of going about this, is for RedisGraph to expose C API, with some useful operations, e.g. `getNode` and `extendNode` which will be consumed by the algorithm writer.

For now there's no such support.
You can always clone RedisGraph and add your additions but I wouldn't recommend doing so.
