### ISSUE TITLE
Problem about building RedisGraph

### ISSUE THREAD

**Issue by ljhhuxiaoba** [RedisGraph/RedisGraph#2982]
An error occurred when I executed the "make" command in the project directory and I don't know why it can't find readies.

![image](https://user-images.githubusercontent.com/67541048/227116106-a3491d29-e84b-4246-94a6-75e33d57c918.png)

**Comment by AviAvni** [comment]
you didn't clone the submodules see readme how to clone the repository
```
git clone --recurse-submodules -j8 https://github.com/RedisGraph/RedisGraph.git
```
