### ISSUE TITLE
Unexpected syntax error about substring() function

### ISSUE THREAD

**Issue by ljhhuxiaoba** [RedisGraph/RedisGraph#3016]
I execute a query on my RedisGraph database,and an error occurred.

Redis version:6.2.10
RedisGraph version: v2.10.9
operating system: windows 10
API：Cypher version 9
query:return substring("a", 0, 1)
error message:"Invalid argument(s): Closing quote must be followed by a space or nothing at all."
expected output:a

**Comment by LiorKogan** [comment]
I can't reproduce it from redis-cli.

You may be mixing the parameter's double quote symbol with the query's double quote symbol. Try replacing it with a single quote.

**Comment by ljhhuxiaoba** [comment]
Problem solved, and thank you very much
