### ISSUE TITLE
Attempted to access undefined attribute

### ISSUE THREAD

**Issue by ljhhuxiaoba** [RedisGraph/RedisGraph#3020]
I execute a query on my RedisGraph ,and an error occurs.

Redis version:6.2.10
RedisGraph version: v2.10.9
operating system: windows 10
API：Cypher version 9
query:create (n{age:1}),({age:n.age}) return 1
error message:"Attempted to access undefined attribute"

_Expected behavior_:
The query should run successfully and two nodes are created.

**Comment by swilly22** [comment]
RedisGraph can't refer to newly created entities within the same CREATE clause, The assumption that `n` is created first and only then the second anonymous node `({age:n.age})` is created is wrong.
To the best of my understanding there's no order obligations within a CREATE clause.

Let me suggest:
```
CREATE (n{age:1}) WITH n CREATE ({age:n.age})
```

**Comment by ljhhuxiaoba** [comment]
Thanks for your explanation!
