### ISSUE TITLE
The data stored in certain fields is actually part of a cypher statement.

### ISSUE THREAD

**Issue by zhangliang-zl** [RedisGraph/RedisGraph#3026]
I found that the data stored in some fields in redisgraph is actually part of the cypher statement.

This looks like some other thread is executing part of the statement.

Is it because the data contains special characters that lead to data acquisition errors?

```sql
GRAPH.QUERY "asset" "MATCH (n)  WHERE  size(n.id)<>24 return n.id"


 69) 1) "ce375e'] AND  n1.invalid=0 RETURN n0.id,n1 ORDER BY n1.createdTime ASC"
   70) 1) "rty(n1,createdTime,26)"
   71) 1) "N ['6434f755e4b0b815c7ce3090'] AND  n1.invalid=0 RETURN n0.id,n1 ORDER BY n1.createdTime ASC"
   72) 1) "\x98"
   73) 1) "6434f737\x11"
   74) 1) "Pr \xc0$\x7f"
   75) 1) "\x06"
   76) 1) "`f \xc0$\x7f"
   77) 1) "\x98"
   78) 1) "\xa0k!\xc0$\x7f"
   79) 1) "\x02"
   80) 1) "x"
   81) 1) "\x01"
   82) 1) "pk \xa0$\x7f"
   83) 1) "$"
   84) 1) "P) \x1c%\x7f"
   85) 1) "\x8a"
   86) 1) "\x98"
   87) 1) "p\x9f\x88H(\x7f"
   88) 1) "x"
   89) 1) "\xf0\xbe \xb4$\x7f"
   90) 1) "!"
   91) 1) "\a"
   92) 1) "\x02"
   93) 1) "\x01"
   94) 1) "x"
   95) 1) ""
   96) 1) "6"
   97) 1) "\x10\n"
   98) 1) ""
   99) 1) "\b"
   100) 1) "x"
   101) 1) "\x01"
   102) 1) "P9\x11\x0c%\x7f"
   103) 1) "q"
   104) 1) "\xb0? \xd4$\x7f"
   105) 1) " 7"
   106) 1) "rty(n1,createdTime,26)"
   107) 1) "6434f37ee4b0b815c7ce0bc5p"
   108) 1) ""
   109) 1) "x"
   110) 1) ""
   111) 1) ""
   112) 1) ""
   113) 1) "ation) where n0.id IN ['6434f2c8e4b0b815c7ce056b'] AND  n1.invalid=0 RETURN n0.id,n1 ORDER BY n1.createdTime ASC"


```

**Comment by LiorKogan** [comment]
@zhangliang-zl Which Redis and RedisGraph versions are you using?

**Comment by zhangliang-zl** [comment]
Yes, will the new version solve these problems? Your version is updating a bit quickly, I don't know how to choose the most recent stable version. Do you have any recommendations?

**Comment by LiorKogan** [comment]
If you don't need any new functionality, switch to the latest 2.8 (2.8.26).

I understand your frustration with the data corruption issue (RDB and in-memory) but it was solved a long time ago.

**Comment by zhangliang-zl** [comment]
If we upgrade to the latest version (2.8.26), we still need to do some verification work.



Can upgrading to 2.8.20 solve most RDB crashes? We have conducted some validation on version 2.8.20.

**Comment by LiorKogan** [comment]
Yes, upgrading to 2.8.20 will solve the RDB issues. However, I believe you should upgrade to 2.8.26 even if you need to revalidate. Some additional high-priority issues including potential hangs and crashes were fixed.

**Comment by zhangliang-zl** [comment]
I have reproduced this issue in version 2.8.21. How should I try to avoid it from happening?

During this process, I added fields to the label and used statements like this to add data

``` UNWIND $rows as row CREATE (n:Device{name:row[i]}) ```

**Comment by LiorKogan** [comment]
Please add a query or set of queries the reproduce this issue, starting with an empty database.

If your initial RDB is already defective we won't be able to help.
