### ISSUE TITLE
Unexpected error about log(0) and log10(0)

### ISSUE THREAD

**Issue by ljhhuxiaoba** [RedisGraph/RedisGraph#3027]
I execute a query on my RedisGraph ,and an error occurs.

Redis version:6.2.10
RedisGraph version: v2.10.9
operating system: windows 10
API：Cypher version 9
query:return log(0),log10(0)
error message:"Integer overflow '0'"

But if I execute query such as:return log(0) or return log10(0),then they can run successfully and return -inf.

Steps to reproduce:
return log(0),log10(0)

Expected behavior:
The query should run successfully and no error should occur.

Actual behavior:
The query failed.

**Comment by LiorKogan** [comment]
The problem is not with `log(0)` and `log10(0)`. Both return `inf` as expected.

```
GRAPH.QUERY g "RETURN log(0)"
1) 1) "log(0)"
2) 1) 1) "-inf"

GRAPH.QUERY g "RETURN log10(0)"
1) 1) "log10(0)"
2) 1) 1) "-inf"
```

The root cause is probably #2931 (fixed in #3021 but not merged yet). This is a regression from RedisGraph 2.8

You can trigger this error by querying the following:

```
GRAPH.QUERY g "RETURN log10(0), 5"
(error) Integer overflow '5'
```
