### ISSUE TITLE
PageRank algorithm?

### ISSUE THREAD

**Issue by Raidus** [RedisGraph/RedisGraph#304]
Hi,

do you have any plans to implement pagerank algorithm in near future?

Reference: https://neo4j.com/docs/graph-algorithms/current/algorithms/page-rank/

Kind regards
Wilhelm

**Comment by swilly22** [comment]
Hi @Raidus,
Unfortunately currently not,
but we already have an implementation of PageRank using Matrices and linear-algebra.
All that's left is to decide on the API.

**Comment by swilly22** [comment]
Pagerank is supported.
see [doc](https://oss.redislabs.com/redisgraph/commands/#procedures)
`CALL algo.pageRank('person', 'friend') YIELD node, score RETURN node.name ORDER BY score DESC`
