### ISSUE TITLE
DELETE clause on relation have no immediate effect

### ISSUE THREAD

**Issue by olivbak** [RedisGraph/RedisGraph#3183]
Tested with latest commit of RedisGraph 2.10: b4b5ee89b45ea40b9b65b35ef038386c9de0c6f5
=========================================================================
I have this issue where a DELETE operation have no immediate effect. 
Instead of writing a long description, I have created a minimal reproducible example:

1. Start off by creating some initial state (this is not where the issue occurs)
```
    MERGE (:Actor {id: 1})-[:STARS_IN]->(:Movie)
```
2. This query counts the relations directly after the deletion occurs. In this scenario, the query returns 1, even though I would expect it to return 0 (since the relation is deleted).
```
    OPTIONAL MATCH (actor:Actor {id: 1})
    OPTIONAL MATCH (actor)-[relation:STARS_IN]->(:Movie)
    DELETE relation

    WITH actor.id as actor_id

    OPTIONAL MATCH (:Actor {id: actor_id})-[relations:STARS_IN]->(:Movie)

    WITH COUNT(relations) as rels
    // returns 1
    RETURN rels
```

3. Another interesting thing is, that performing another delete after `DELETE relation` will apply the deletion of the relation. Thus the following slighty modified query returns the expected result of 0: 
```
    OPTIONAL MATCH (actor:Actor {id: 1})
    OPTIONAL MATCH (actor)-[relation:STARS_IN]->(:Movie)
    DELETE relation

    WITH actor.id as actor_id

    MERGE (force:ForceEvaluate)
    DELETE force

    WITH actor_id
    OPTIONAL MATCH (:Actor {id: actor_id})-[relations:STARS_IN]->(:Movie)

    WITH COUNT(relations) as rels
    // returns 0
    RETURN rels
```

**Comment by swilly22** [comment]
Hi @olivbak,
I agree the query should return 0.

I've ran your queries on my local machine using the latest version of RedisGraph (2.12.8) and this is what I'm getting:

```sh
127.0.0.1:6379> GRAPH.QUERY g "MERGE (:Actor {id: 1})-[:STARS_IN]->(:Movie)"
1) 1) "Labels added: 2"
   2) "Nodes created: 2"
   3) "Properties set: 1"
   4) "Relationships created: 1"
   5) "Cached execution: 0"
   6) "Query internal execution time: 0.669126 milliseconds"

127.0.0.1:6379> graph.query g "OPTIONAL MATCH (actor:Actor {id: 1}) OPTIONAL MATCH (actor)-[relation:STARS_IN]->(:Movie) DELETE relation WITH act
or.id as actor_id OPTIONAL MATCH (:Actor {id: actor_id})-[relations:STARS_IN]->(:Movie) WITH COUNT(relations) as rels RETURN rels"
1) 1) "rels"
2) 1) 1) (integer) 0
3) 1) "Relationships deleted: 1"
   2) "Cached execution: 0"
   3) "Query internal execution time: 1.327667 milliseconds"
```

**Comment by olivbak** [comment]
@swilly22 I am glad to hear that this is fixed in RedisGraph 2.12. I will mark the issue as closed, since this is probably not worth spending effort fixing in RedisGraph 2.10? Thanks for your time!

**Comment by olivbak** [comment]
@swilly22 on a side note, do you have any idea when a new release of RedisGraph 2.12 will be released? We are experiencing tons of issues/crashes with the current released version of RedisGraph 2.12 GA (v2.12.3), to the point we have to stick with 2.10 for now. I can see you did a lot of bugfixes after v2.12.3 tho.

**Comment by swilly22** [comment]
Yeah sorry about that,
Let me check with the team and I'll get back to you shortly

**Comment by swilly22** [comment]
@olivbak, 2.12.9 had been released
https://github.com/RedisGraph/RedisGraph/releases/tag/v2.12.9
