### ISSUE TITLE
UNION clause propagates restrictions on MATCH clause

### ISSUE THREAD

**Issue by olivbak** [RedisGraph/RedisGraph#3186]
RedisGraph 2.12.8
===============================
Running this query yields on v2.12.8:
```
127.0.0.1:16379> GRAPH.QUERY g "OPTIONAL MATCH (a:Actor {id: 1}) RETURN a.id UNION MATCH (a:Actor {id: 2}) RETURN a.id"
(error) A WITH clause is required to introduce a MATCH clause after an OPTIONAL MATCH.
```
which to me seems like a parser error. I would expect this restriction of the MATCH clause (that it cannot follow a subset of clauses, with introducing WITH) to not propagate to the second query of the UNION.

The error is not present on latest commit of RedisGraph 2.10 master, and thus returns the correct result on that specific version.

**Comment by AviAvni** [comment]
thanks this is a regression will fix this soon
