### ISSUE TITLE
Unexpected result about number of nodes in graph

### ISSUE THREAD

**Issue by ljhhuxiaoba** [RedisGraph/RedisGraph#3192]
I execute a query on my empty RedisGraph and get an unexpected result.

Redis version:6.2.10
RedisGraph version: v2.10.9
operating system: windows 10
API：Cypher version 9
query:create (n) delete n with 1 as a match (n0) return count(n0)

The query creates a node and then deletes it, at which point the number of nodes in the graph is 0, but the return result is 1.

**Comment by AviAvni** [comment]
it is not crashing in 2.12.9

**Comment by ljhhuxiaoba** [comment]
I've upgraded the version and the problem is solved, thanks!
