### ISSUE TITLE
Crash When replace MATCH or CREATE with MERGE

### ISSUE THREAD

**Issue by ljhhuxiaoba** [RedisGraph/RedisGraph#3203]
I execute a query on my empty RedisGraph and get a crash.

Redis version:7.2.0
RedisGraph version: v2.12.10
operating system: windows 11
API：Cypher version 9

Steps to reproduce:
MERGE ()-[r0:T]->({k:[properties(r0{.k})]}) WITH * MERGE () RETURN 1

It is worth noting that the following two queries do not cause a crash：
_MERGE ()-[r0:T]->({k:[properties(r0{.k})]}) WITH * MATCH () RETURN 1
MERGE ()-[r0:T]->({k:[properties(r0{.k})]}) WITH * CREATE () RETURN 1_

The error message is as follows：
"Reached the max retries per request limit (which is 1). Refer to \"maxRetriesPerRequest\" option for details."

Actual behavior:
The query failed and the redisgraph container exited abnormally with the error message.

**Comment by swilly22** [comment]
Hi @ljhhuxiaoba,
Thank you for reporting!

Here's a simplified version of the crash:

```cypher
GRAPH.QUERY g "create (:A {v:1, x:'s'})"
GRAPH.QUERY g "Match (n) return properties(n{.*})"
```

**Comment by ljhhuxiaoba** [comment]
I encountered another crash in the query "CREATE (n0{id:61}) MERGE (n2:L1{k11:isEmpty(properties(n0{.id}))}) RETURN 1", is this the same bug as in the issue?
