### ISSUE TITLE
Crash about using List Comprehension in UNWIND clause 

### ISSUE THREAD

**Issue by ljhhuxiaoba** [RedisGraph/RedisGraph#3210]
I execute a query on my RedisGraph and get a crash.

Redis version:7.2.0
RedisGraph version: v2.12.10
operating system: windows 11
API：Cypher version 9
error message:"Reached the max retries per request limit (which is 1). Refer to "maxRetriesPerRequest" option for details."

To reproduce:
CREATE (),(),(),()
MATCH () UNWIND [[x IN [1,NULL]]] AS a0 MERGE (n0) RETURN 1

Actual behavior:
The query failed and the redisgraph container exited abnormally with the error message.

**Comment by ljhhuxiaoba** [comment]
Has this bug fixed?

**Comment by gkorland** [comment]
It was fixed on FalkorDB see: https://github.com/FalkorDB/FalkorDB/pull/496
