### ISSUE TITLE
Crash when MATCH path of length 0

### ISSUE THREAD

**Issue by ljhhuxiaoba** [RedisGraph/RedisGraph#3213]
I execute a query on my empty RedisGraph and get a crash.

Redis version:7.2.0
RedisGraph version: v2.12.10
operating system: windows 11
API：Cypher version 9
error message:"Reached the max retries per request limit (which is 1). Refer to "maxRetriesPerRequest" option for details."

To reproduce:
MATCH (a:L)<-[*0..0]-(b) WHERE a is not null and id(b)>=0  RETURN count(a)

Actual behavior:
The query failed and the redisgraph container exited abnormally with the error message.

**Comment by ljhhuxiaoba** [comment]
May I ask if this bug has been fixed?

**Comment by gkorland** [comment]
It was fixed on FalkorDB see: https://github.com/FalkorDB/FalkorDB/pull/483
