### ISSUE TITLE
Are there any visualization tools can be used with redis-graph?

### ISSUE THREAD

**Issue by Huarong** [RedisGraph/RedisGraph#35]

**Comment by swilly22** [comment]
Hi @Huarong,
At the moment there isn't,
I think the first step in that direction would be to translate RedisGraph response structure (table) into a graph representation, once we'll have that, drawing the result should be easy.

It's likely that we'll address that soon after July 31.

**Comment by lundq** [comment]
Any news on this one? I would like to visualize redis graph on the front-end. What workaround would be best, query with cypher and recreate edges or use a redis client to query nodes and edges in redis?

**Comment by stockholmux** [comment]
@lundq This is not an official product or anything but we've built a few demos with visualization. [Check out this one](https://github.com/K-Jo/redisgraph-iam-demo/tree/master/front-end) - perhaps you can customize the JS to fit your needs.

**Comment by lundq** [comment]
@stockholmux Thanks for your reply, so would the returned vertices/data contain an in/out index to map edges? I need to query and retrieve a tree in a forest structure and use that data, not necessarily for visualization. Could not find any examples of returned data yet. Best regards

**Comment by swilly22** [comment]
To get incoming/outgoing edges of a node `n` run the following:
`GRAPH.QUERY <GRAPH_ID> "MATCH ()-[in]->(n)-[out]->(B) RETURN in, n, out`
You would probably want to specify a filter to pick `n`

**Comment by lundq** [comment]
@swilly22 Thanks, nice to read that you can retrieve edges as well. Understand your original answer better now. 
Can you elaborate on this: give me nodes with all in and out edges (like you suggested) where the node has a out edge to a specific node (the filter you suggested). Looking forward to play around myself with this.

**Comment by rahst12** [comment]
@stockholmux are there any screenshots of the demo?

**Comment by swilly22** [comment]
@lundq, if I understand your question correctly: 

> vertices/data contain an in/out index to map edges?

You're interested in retrieving vertices along with their incoming / outgoing edges,
to do that you can run the query i've specified above.

**Comment by lundq** [comment]
@swilly22 yes you answered my Initial question, I was just trying to figure how the filter would look like.
All the nodes need to be connected to one specific node but I still want to retrieve the interconnected edges between them. Thanks

**Comment by swilly22** [comment]
@lundq Say you're interested in the incoming and outgoing edges of node X which you can find by applying some criteria,
```
GRAPH.QUERY <GRAPH_ID> "MATCH ()-[in]->(n)-[out]->(B) 
WHERE n.attribute=value
RETURN in, n, out
```

**Comment by lundq** [comment]
@swilly22 ok, so you can write something like this aswell:
GRAPH.QUERY <GRAPH_ID> "MATCH ()-[in]->(n)-[out]->(B) 
WHERE (n) - [] - > (v.attribute=value)
RETURN in, n, out

and still recieve all interconnected edges as well, not just the edges specified in the WHERE clause?
This way I could hopefully retrieve a tree structure but filtered on a specific edge. 
Sorry for any unclarities.

**Comment by lundq** [comment]
@swilly22 I'll try it out myself, I am pretty sure I will find out how. Thanks for your answers so far.

**Comment by gnaneshr** [comment]
RedisGraph visualization is provided by redisinsight: https://redislabs.com/redisinsight/

**Comment by mayuresh-kumbhar** [comment]
To download RedisInsights for windows below link is broken
https://downloads.redisinsight.redislabs.com/latest/redisinsight-win.msi

**Comment by gnaneshr** [comment]
> To download RedisInsights for windows below link is broken
> https://downloads.redisinsight.redislabs.com/latest/redisinsight-win.msi

@mayuresh-kumbhar It's working. Check it again.

**Comment by mayuresh-kumbhar** [comment]
Please find below screenshot. I did filled form with my details like name ,email , org but still its failing.

Note: I am not connected to any VPN/Restricted network

![image](https://user-images.githubusercontent.com/51693642/77247502-e0effc00-6c57-11ea-9731-7759f97274dc.png)

**Comment by swilly22** [comment]
@mayuresh-kumbhar 
I've just downloaded RedisInsight from https://redislabs.com/redisinsight/

**Comment by slemeur** [comment]
Works for me as well.
have you been able to retry today @mayuresh-kumbhar ?
