### ISSUE TITLE
support for WHERE ... IN clause?

### ISSUE THREAD

**Issue by dipeti** [RedisGraph/RedisGraph#358]
Considering that OpenCypher's [documentation](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf) does mention the `WHERE ... IN` clause I would like to know whether you plan to extend your parser with it in the near future. 
```
MATCH (a)
WHERE a.name IN ['Peter', 'Tobias']
RETURN a.name, a.age
```
Thanks

**Comment by swilly22** [comment]
Hi @dipeti 
Sure, `WHERE a.name IN ['peter', 'Tobias']` will be supported, no doubt.
I can't commit on a date right now as our roadmap is packed, I'll try to see if this is a quick win and if so I'll try to seek it in.

**Comment by Jonahss** [comment]
Ooh, I was looking for this. Right now I'm just programmatically constructing long `WHERE a.name = 'Peter' OR a.name = 'Tobias' OR a.name =  ...` queries.

**Comment by K-Jo** [comment]
@dipeti @Jonahss We understand the request, but at this moment we're trying to support a bigger refactoring of our AST parsing by using libcypher #318 #355 for supporting #254 (the WITH clause).  After this, additions such as the IN clause, should be more trivial to achieve with less technical debt.  Bear with us!

**Comment by Jonahss** [comment]
For sure! Was just voicing my vote. I know ya'll have a nice jam-packed roadmap of great enhancements to add in the coming year :D Looking at the other github issues, a lot of focus is on this change for #254. I can understand how it unlocks a lot.

**Comment by swilly22** [comment]
WHERE a.v IN [] is supported.
```
GRAPH.EXPLAIN g "MATCH (a) WHERE a.name IN ['Peter', 'Tobias'] RETURN a.name, a.age"
1) "Results"
2) "    Project"
3) "        Filter"
4) "            All Node Scan | (a)"
```
