### ISSUE TITLE
When setting a property to `NULL` the property is not deleted from node / relationship

### ISSUE THREAD

**Issue by K-Jo** [RedisGraph/RedisGraph#363]
```
redis:6379> graph.query test "CREATE (n { prop: 'test'})"
1) (empty list or set)
2) 1) "Nodes created: 1"
   2) "Properties set: 1"
   3) "Query internal execution time: 0.644500 milliseconds"
redis:6379> graph.query test "MATCH (n) SET n.prop=null"
1) (empty list or set)
2) 1) "Properties set: 1"
   2) "Query internal execution time: 0.391800 milliseconds"
redis:6379> graph.query test "MATCH (n) return n"
1) 1) 1) "n.prop"
   2) 1) "NULL"
2) 1) "Query internal execution time: 0.354900 milliseconds"
redis:6379>
```

**Comment by swilly22** [comment]
127.0.0.1:6379> graph.query test "CREATE (n { prop: 'test'})"
1) 1) "Nodes created: 1"
   2) "Properties set: 1"
   3) "Query internal execution time: 0.327000 milliseconds"

127.0.0.1:6379> graph.query test "MATCH (n) SET n.prop=null"
1) 1) "Properties set: 1"
   2) "Query internal execution time: 0.162000 milliseconds"

127.0.0.1:6379> graph.query test "MATCH (n) return n"
1) 1) "n"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) (empty list or set)
         3) 1) "properties"
            2) (empty list or set)
