### ISSUE TITLE
Handling a huge social graph

### ISSUE THREAD

**Issue by wa11a** [RedisGraph/RedisGraph#387]
Hi,
Lets say i'm building a social graph with 400M Vertices, and each vertex will have at least 200 edges.
each edge will have around 2-5 properties, and each vertex will have around 20 properties.
can redisGraph can handle this size of graph ?
i'll probably need to have hundreds of r/w per second some of them heavy (like calculate cliques) and some of them are light (like adding new vertices or edges).

and also, are you planning to implement sharding ?

Thanks.

**Comment by swilly22** [comment]
Hi @wa11a,
doing an early [calculation ](https://redislabs.com/redis-enterprise/redis-modules/redis-enterprise-modules/redisgraph/redisgraph-calculator/)

**Comment by yongdi** [comment]
I hope also but suppose cannot. Graph key is inaccessible to Redis. therefore, cluster hash can't work on them.

**Comment by swilly22** [comment]
My initial thought is no, but it depends on the underline hardware you'll be using.
[See redisgraph sizing calculator](https://redislabs.com/modules/redis-graph/redisgraph-sizing-calculator/)
Graph distribution is something we're still trying to figure out.
