### ISSUE TITLE
Crash on Merge - "This master is sending an error to its replica"

### ISSUE THREAD

**Issue by 2ZZ** [RedisGraph/RedisGraph#405]
Hi, following the command:

```
redis-graph:10000> GRAPH.QUERY redis-graph "MERGE (:TYPE { id: 'XX_XX00000' });"

1) (empty list or set)

2) 1) "Query internal execution time: 0.130081 milliseconds"
 
```

We see the Redis process crash with the error:

`28360:M 19 Mar 2019 14:21:12.408 # == CRITICAL == This master is sending an error to its replica: 'unknown command `Properties set: 1`, with args beginning with: `Query internal execution time: 0.212877 milliseconds`, ' after processing the command '<unknown>'`

I have more logs if required

**Comment by K-Jo** [comment]
Hi @2ZZ 
We have found the issue, and it is internal to redis: https://github.com/antirez/redis/pull/5962
A fix will be released soon

**Comment by swilly22** [comment]
Merged into Redis.
