### ISSUE TITLE
Support readonly operation on slave nodes

### ISSUE THREAD

**Issue by Liuguofu** [RedisGraph/RedisGraph#420]
Could you please share me the priority of this function? If so, we can use RedisGraph in real time system and we're not afraid the pressure of master node is too much.
Thx!

**Comment by swilly22** [comment]
Yes, in-fact the new redis 5.0.4 allows us to do so,
I'll expect this ability to be enabled within a week or two.

**Comment by K-Jo** [comment]
@Liuguofu We definitely will tackle this after we have finalised some more urgent features.  I'll rename this issue and we'll track and update here accordingly

**Comment by Liuguofu** [comment]
Thanks for your clarification. 
Looking forward to seeing this function release ASAP.

**Comment by vvippark** [comment]
I am also looking for this feature on my production environment. Please release it in next week if possible. Thanks.

**Comment by swilly22** [comment]
Please use `GRAPH.RO_QUERY` #1364
