### ISSUE TITLE
Updating all the properties of a Node with a map (add/update/delete)

### ISSUE THREAD

**Issue by epswartz** [RedisGraph/RedisGraph#428]
Hey,

I'm trying to update an entire node in the graph with the potential to both update and remove some properties, something like:

```
GRAPH.QUERY test "CREATE (:person {name: 'Ethan', age:23, food:'cheese'})"
GRAPH.QUERY test "MATCH (n:person {name: 'Ethan'} SET n = {name: 'Ethan', age:24})"
```

I know that currently there's no support for maps, so this won't work - is there another mechanism for doing something like this that doesn't require first doing a query to figure out what all the properties are so that I can set them to `NULL`, or should I just get the node first and then piece together my own `SET` using individual properties based on what I get out from the first query?

**Comment by jeffreylovitz** [comment]
Hi @epswartz,

We don't currently have a way of updating all properties on a node like you describe. Setting properties to NULL deletes them from the node, so if you know the property keys that are _potentially_ on the node, you can NULL-set them whether or not they're actually present:
`GRAPH.QUERY test "MATCH (n:person {name: 'Ethan'}) SET n.age = 24, n.food = NULL, n.probably_not_here = NULL"`

But if you don't have that advance knowledge of potential keys, doing a MATCH query first would be your best choice for the moment!

**Comment by epswartz** [comment]
@jeffreylovitz Thanks for the timely answer :) I'll do the MATCH first approach for now - are there any plans for map support in the future?

**Comment by K-Jo** [comment]
@epswartz Thanks for opening this issue!  Since we have a workaround currently, this will be for the second half of the year.   I added it to our backlog, hope this works for you?

**Comment by epswartz** [comment]
Yeah, that should be fine. Thanks for the help!

**Comment by bgeesaman** [comment]
Any update on the status of this functionality?  Would really help with large MERGEs.  Thanks!

**Comment by jeffreylovitz** [comment]
Updating properties with a map is planned for the next RedisGraph version, 2.4.

To simplify tracking, I'm closing this issue in favor of #943 .
