### ISSUE TITLE
want path of my redis graph

### ISSUE THREAD

**Issue by shukla200** [RedisGraph/RedisGraph#429]
Lets say i've 3 nodes A,B and C. A is connected to B via 'x' edge and B is connected to C via 'y' edge
so now i want path like A-x->B-y->C .

**Comment by K-Jo** [comment]
Are A,B and C `labels` and x and z `relationship types`? in that case your path would look like
```
MATCH (:A)-[:x]->(:B)-[:y]->(:C) ...
```
