### ISSUE TITLE
Statistics report is wrong when MERGE and setting a non-existent node property

### ISSUE THREAD

**Issue by madmac2501** [RedisGraph/RedisGraph#443]
Continuation from #435 

The query GRAPH.QUERY test "MERGE (s {key: 'value'}) SET s.num = s.num + 32"
will create the node s if it doesn't exists, in which case num will not be set, neo4j's output: Created 1 node, set 1 property

Running the same query in redis graph shows this statistic
"Nodes created: 1"
"Properties set: 2"

The number of properties set is different

**Comment by gkorland** [comment]
```
> GRAPH.QUERY test "MERGE (s {key: 'value'}) SET s.num = s.num + 32"
1) 1) "Nodes created: 1"
   2) "Properties set: 1"
   3) "Cached execution: 0"
   4) "Query internal execution time: 0.361666 milliseconds"
```

**Comment by madmac2501** [comment]
Thanks!
