### ISSUE TITLE
order by with aggregation

### ISSUE THREAD

**Issue by shkediy** [RedisGraph/RedisGraph#45]
Is it possible to do order by on an aggregation field? In the imdb demo, I am trying to list the top 10 movies with maximum number of actors.
I am running the following query:
GRAPH.QUERY imdb "match (a:actor)-[:act]->(m:movie) return m.title, count(a) order by count(a) desc  limit 10"

I get a syntax error.

**Comment by swilly22** [comment]
Yeah, you can, but at the moment please use the AS key work to rename your aggregated field:
For example:
GRAPH.QUERY imdb "MATCH (a:actor)-[:act]->(m:movie) RETURN m.title, count(a) AS actor_count ORDER BY actor_count DESC LIMIT 10"

**Comment by shkediy** [comment]
On the same note, is it possible to do a where with aggragation? For example, find the movies with max actor of age 30. In openCypher it seems to be possible using "WITH".

**Comment by swilly22** [comment]
Within the context of a single query (no subqueries) we can't include aggregation functions within the WHERE clause, similar to SQL.

An alternative would be using the WITH clause (as you've mentioned), unfortunately we've yet to support it, I'll update once we do.

**Comment by swilly22** [comment]
Order by aggregation is supported.
