### ISSUE TITLE
"OR" in where clause utilising index

### ISSUE THREAD

**Issue by vvippark** [RedisGraph/RedisGraph#464]

**Comment by K-Jo** [comment]
Hi @vvippark This will be part of our 2.0 release which we believe will be ready Q3 of this year.  Let me know if we can close this issue

**Comment by vvippark** [comment]
thanks for information ok you can  close it.

**Comment by WitchsCat** [comment]
Just for my understanding, before this if i want to find 3 nodes by 3 ids that are indexed. It would be far faster to run a 'for loop' over them than to write "MATCH (c:Claim) WHERE c.id = '1' OR c.id = '2' OR c.id = '3'"?

**Comment by swilly22** [comment]
Hi @WitchsCat, I'm not sure I fully understand what do you mean by "for loop", can you please elaborate?

**Comment by swilly22** [comment]
I see your point @WitchsCat,
The current implementation of indices within RedisGraph can't be utilise an index in a scenario where the indexed attribute takes part in an OR condition.
RedisGraph 2.0 will replace its index implementation with one that handles such cases.

**Comment by swilly22** [comment]
Utilised 
```
127.0.0.1:6379> GRAPH.EXPLAIN social "match (a:person) where a.age = 1 OR a.age = 2 return a"
1) "Results"
2) "    Project"
3) "        Index Scan | (a:person)"
```
