### ISSUE TITLE
Support for branching queries

### ISSUE THREAD

**Issue by elvis197686** [RedisGraph/RedisGraph#465]
Hello,

We are trying to expand our Redis Graph data model to allow for grouping of data at an intermediate level of the graph, and we cannot figure out how to write a query to get the groups of data with all connected parts of the graph returned.

Please let us know if/how this can be done in the current version of Redis Graph, and if it can't whether you are planning to support such a query on your roadmap.

The proposed model of our graph is:

BOOKSTORE [HAS] BOOKS [HAS] PAGES
GENRE [HAS] SUBGENRE [HAS] BOOKS

and we want a query to return the books, bookstore and selected pages for a given genre.

We thought it might be possible to use the WITH...AS clause to achieve this but we cannot get that to work.

An example query we tried is below:

```MATCH (g:GENRE)-[:HAS]->(sg:SUBGENRE)-[:HAS]->(b:BOOK) WITH b AS book MATCH (bs:BOOKSTORE)-[:HAS]->(book:BOOK)-[:HAS]->(p:PAGES) return bs, book, p```

..the result of which was an error:

`Identifier 'book' defined more than once`

**Comment by swilly22** [comment]
Hi @elvis197686,
The ability to specify a graph entity (`book` in your example) within multiple search patterns is important, we've yet to address this feature but it's on our short term roadmap.

For now the only option would be to rename the second occurrence of `book` to `x` and filter on ID
`MATCH (g:GENRE)-[:HAS]->(sg:SUBGENRE)-[:HAS]->(b:BOOK) MATCH (bs:BOOKSTORE)-[:HAS]->(x:BOOK)-[:HAS]->(p:PAGES) WHERE ID(b) = ID(x) RETURN bs, b, p`

A rough estimation for supporting this ability would be ~2 months.

**Comment by jeffreylovitz** [comment]
Hi @elvis197686,

Your sample query touches on two areas that we hope to work on in the timeline described by @swilly22. To simplify progress tracking, I've opened issues #466 and #467.

**Comment by elvis197686** [comment]
Thanks @swilly22 - that alternative option works well enough for us to use!

@jeffreylovitz - thanks for raising those separate tasks, it will help with tracking.

Keep up the good work.

**Comment by swilly22** [comment]
#474 
Can be done without the WITH clause:

graph.explain "MATCH (g:GENRE)-[:HAS]->(sg:SUBGENRE)-[:HAS]->(b:BOOK), (bs:BOOKSTORE)-[:HAS]->(b)-[:HAS]->(p:PAGES) RETURN bs, b, p"
1) "Results"
2) "    Project"
3) "        Conditional Traverse | (b:BOOK)->(bs:BOOKSTORE)"
4) "            Conditional Traverse | (b:BOOK)->(p:PAGES)"
5) "                Conditional Traverse | (g:GENRE)->(b:BOOK)"
6) "                    Node By Label Scan | (g:GENRE)"
