### ISSUE TITLE
Graph entities in WITH clause should be usable in subsequent MATCH clauses 

### ISSUE THREAD

**Issue by jeffreylovitz** [RedisGraph/RedisGraph#466]
Resolve the limitation described at
[https://oss.redislabs.com/redisgraph/known_limitations/#using-nodes-and-relationships-specified-in-with-clause-in-multiple-patterns](https://oss.redislabs.com/redisgraph/known_limitations/#using-nodes-and-relationships-specified-in-with-clause-in-multiple-patterns)

**Comment by K-Jo** [comment]
Should include LIMIT and SKIP support as described here #418

**Comment by jeffreylovitz** [comment]
Most of the WITH limitations have been lifted now, with the exception of reusing WITH-projected entities in subsequent patterns:
`MATCH (a {id: 1}) WITH a MATCH (a)-[]->(b) RETURN b`
