### ISSUE TITLE
Support traversals for patterns with node degrees greater than 2

### ISSUE THREAD

**Issue by jeffreylovitz** [RedisGraph/RedisGraph#467]
A single MATCH clause in Cypher limits the maximum degree of any node in a pattern to 2. More complex patterns are described using multiple MATCH clauses:   
`MATCH (a)-[]->(reused)<-[]-(b) MATCH (reused)-[]->(c)`

Currently, constructions like this will return a query validation error (reused identifier).

**Comment by swilly22** [comment]
#539
