### ISSUE TITLE
Support for Undirected Edges

### ISSUE THREAD

**Issue by esokullu** [RedisGraph/RedisGraph#475]
I know it's currently unsupported, but this is a feature request: (**not** urgent)

An undirected query like:
```MATCH (:user {udid: {u1}})-[r:message]-(:user {udid: {u2}}) SET r.IsRead = true RETURN startNode(r).udid as t, r ORDER BY r.SentTime DESC```

does NOT work. We have to split it into two directed queries and merge programmatically.

Similarly functions like `startNode `do NOT work, as documented in your Cypher coverage doc.

I just didn't see an issue on Github re: these, and wanted to add one. There's been a lot of progress lately, and you may want to add these two to your pipeline at some point.

Thanks, cheers,

**Comment by swilly22** [comment]
Support for undirected edges been added.
