### ISSUE TITLE
Index not created if node type doesn't exist

### ISSUE THREAD

**Issue by colinfike** [RedisGraph/RedisGraph#477]
This is not really a bug but something I ran into that required a little bit of debugging for me to understand what was going on.

If you create an index for a node type that has not had at least one instance created of it already, the index will not be made. You need to create a node first, then create the index. It's not the biggest deal breaker but it is a strange pattern to have to create a dummy node of type X to make an index on that node type then delete that dummy node.

This may be the norm when it comes to graph databases so I'll defer to you but I wanted to at least bring it up.

**Comment by swilly22** [comment]
Hi @colinfike,
Demanding a label to exists prior to creating an index over it, is a current limitation within RedisGraph, other graph databases will allow you to perform this action as you would expect.

We will accommodate that change, hopefully in the near future.
Thanks for pointing this out.
