### ISSUE TITLE
GRAPH.EXPLAIN for use in redis-cli

### ISSUE THREAD

**Issue by stockholmux** [RedisGraph/RedisGraph#481]
When you run `GRAPH.EXPLAIN` in redis-cli, you get escaped `\n` instead of new lines. It's not readable, so not very useful.

In RediSearch there is the command `FT.EXPLAINCLI` which takes `FT.EXPLAIN` (which spits out `\n`s as well) and converts it to a more readable format:

```
127.0.0.1:6379> FT.EXPLAIN foo "this is a test"
"UNION {\n  test\n  +test(expanded)\n}\n"
127.0.0.1:6379> FT.EXPLAINCLI foo "this is a test"
1) UNION {
2)   test
3)   +test(expanded)
4) }
```

I'd like to propose a similar command for RedisGraph - `GRAPH.EXPLAINCLI` that renders new lines as individual results. This would make the developer experience for `GRAPH.EXPLAIN` much better.

**Comment by stockholmux** [comment]
Example:
```
127.0.0.1:6379> GRAPH.EXPLAIN MotoGP "MATCH (r:Rider)-[:rides]->(t:Team) WHERE t.name = 'Yamaha' RETURN r,t"
1) Results
2)    Project
3)        Conditional Traverse
4)            Filter
5)                Node By Label Scan
```

**Comment by jeffreylovitz** [comment]
:+1: This is a very good idea.

**Comment by stockholmux** [comment]
In RediSearch, the implementation is pretty simple - `explainRoot` is the explanation with `\n` intact:
```
    RedisModule_ReplyWithArray(ctx, REDISMODULE_POSTPONED_ARRAY_LEN);
    char *explain = explainRoot;
    char *curLine = NULL;
    while ((curLine = strsep(&explain, "\n")) != NULL) {
      RedisModule_ReplyWithSimpleString(ctx, curLine);
      numElems++;
    }
    RedisModule_ReplySetArrayLength(ctx, numElems);
```

**Comment by swilly22** [comment]
@stockholmux We try to keep our set of APIs to a bare minimum, my suggestion is to simply modify GRAPH.EXPLAIN to return an array.

**Comment by swilly22** [comment]
GRAPH.EXPLAIN "MATCH (m:movie {title:'Black Mass'})<-[:act*1..2]-(a) RETURN a"
1) "Results"
2) "    Project"
3) "        Conditional Variable Length Traverse | (m:movie)-[anon_0:act*1..2]->(a)"
4) "            Filter"
5) "                Node By Label Scan | (m:movie)"
