### ISSUE TITLE
DELETE on an indexed property takes for ever.

### ISSUE THREAD

**Issue by WitchsCat** [RedisGraph/RedisGraph#486]
Is this a known problem that delete is very slow?

127.0.0.1:6379> graph.query tenant3 "MATCH (p:Permission{permissionId:'0ee7b1d281fd'}) delete p"
1) (empty list or set)
2) 1) "Nodes deleted: 8"
   2) "Query internal execution time: 2689.641612 milliseconds"
(2.69s)

Permission.permissionId is an indexed property. For cases when 1000 nodes have this property, delete simply hangs for ever.

**Comment by swilly22** [comment]
Hi @WitchsCat, thanks for reporting,
Let me look into it and I'll update here.

**Comment by swilly22** [comment]
@WitchsCat, we've found the issue, expecting a fix within a day or two.

**Comment by swilly22** [comment]
@WitchsCat, #492 should fix the issue, can you please confirm?
Thanks!
