### ISSUE TITLE
RedisGraph on Redis Cluster and in Replication modes

### ISSUE THREAD

**Issue by esokullu** [RedisGraph/RedisGraph#510]
Would it be expected to work the same way as a single node, or do you foresee some complexities this setup could create?

I will test it soon anyway, but I wanted to get your thoughts. I will update this with my observations.

**Comment by swilly22** [comment]
Well, as each graph resides entirely under a single key, I would expect different graph to be assigned to different nodes within the cluster.
With regard to replication, either full sync or partial sync, I believe both should work.
