### ISSUE TITLE
Support for count distinct

### ISSUE THREAD

**Issue by shkediy** [RedisGraph/RedisGraph#52]
It seems that count(distinct x) is not supported. Can only do distinct on a where clause.
Here's an example of a query I could use that:

Number of clubs required to set up each national team:
 GRAPH.QUERY euro2016 'MATCH (c:Club)<-[:PLAYS_FOR]-(p:Player)-[:REPRESENTS]->(n:NationalTeam) return n.name, count(**distinct** c.name)'

**Comment by swilly22** [comment]
Count distinct is supported.
