### ISSUE TITLE
Confusing behaviour when running multiple MERGE queries via python

### ISSUE THREAD

**Issue by leonh** [RedisGraph/RedisGraph#521]
I have been recently testing using RedisGraph and experimenting with creating a  python client for it. 

I have been experiencing a inconsistent/unexpected behaviour when Merging paths onto my graph.

I have a graph with 200 Person nodes in it.
One node has a 'name'  property of 'Abbie'

```
MATCH (p:Person {name:"Abbie"}) RETURN  p.name, p.age

p.name  p.age
0  Abbie     76
['Query internal execution time: 0.447000 milliseconds']
```

I then issue in a python loop many Merge commands 

```
MERGE (:Person {name: "Abbie",age: 76})-[:FRIEND]->(:Person {name: "Abigale",age: 59})
MERGE (:Person {name: "Adrianne",age: 63})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Adelind",age: 45})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Adore",age: 48})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Adaline",age: 53})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Abbie",age: 76})-[:FRIEND]->(:Person {name: "Adda",age: 70})
MERGE (:Person {name: "Abbie",age: 76})-[:FRIEND]->(:Person {name: "Aaren",age: 66})
MERGE (:Person {name: "Addi",age: 87})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Agretha",age: 32})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Ailsun",age: 66})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Alameda",age: 98})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Abbie",age: 76})-[:FRIEND]->(:Person {name: "Aindrea",age: 43})
MERGE (:Person {name: "Ailis",age: 24})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Adria",age: 67})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Abra",age: 88})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Adele",age: 44})-[:FRIEND]->(:Person {name: "Abbie",age: 76})
MERGE (:Person {name: "Abbie",age: 76})-[:FRIEND]->(:Person {name: "Adelina",age: 47})
```

After this the MATCH command returns 4 results 
 I was expecting to see just one result ?

```
MATCH (p:Person {name:"Abbie"}) RETURN  p.name, p.age
p.name  p.age
0  Abbie     76
1  Abbie     76
2  Abbie     76
3  Abbie     76
4  Abbie     76
['Query internal execution time: 0.793100 milliseconds']
```

**Comment by jeffreylovitz** [comment]
Hi @leonh ,

The MERGE clause will introduce new entities unless the _entire_ specified pattern already exists. Taking the example:
`MERGE (:Person {name: "Abbie",age: 76})-[:FRIEND]->(:Person {name: "Abigale",age: 59})`

Unless the `Abbie` and `Abigale` nodes and the directed `FRIEND` relation between them are all already in the graph, all of them will be constructed as entirely new entities. As [our documentation](https://oss.redislabs.com/redisgraph/commands/#merge) puts it, "MERGE will not partially use existing patterns — it’s all or nothing."

It seems that in your example, the `Person` nodes have all already been created, and you want to introduce the appropriate `FRIEND` relations. The proper syntax to do this would be:
`MATCH (a:Person {name: "Abbie",age: 76}), (b:Person {name: "Abigale",age: 59}) CREATE (a)-[:FRIEND]->(b)`

**Comment by leonh** [comment]
@jeffreylovitz Ah MERGE is all or nothing that explains it! Thanks for the quick reply. I'll try out using the MATCH CREATE route from now on.
