### ISSUE TITLE
Understanding memory usage related to number of relationship types

### ISSUE THREAD

**Issue by jonrscott** [RedisGraph/RedisGraph#522]
Hi. I have a graph with around 14M nodes, 56M edges and 3000 edge types. The nodes have only a single "id" string property, and the edges have no properties. When adding the edges, the machine quickly runs out of RAM, even on very high memory instances. The only way I can make it fit is by reducing the number of edge types that I store. For reference I'm using the bulk loading API, and the server crashes during a call to `GxB_Vector_resize()`.

Is there a rule-of-thumb for working out the amount of memory required based on the above figures?

Could I get around the issue by only having a single edge type, and using a property on the edge to distinguish between the different relationship types? Or would this create performance issues?

Thanks in advance for any advice :)

**Comment by swilly22** [comment]
Hi @jonrscott,
To get an estimation on the amount of memory required to accommodate a graph please see [RedisGraph Sizing Calculator](https://redislabs.com/redis-enterprise/redis-modules/redis-enterprise-modules/redisgraph/redisgraph-calculator/)

Now, internally RedisGraph will allocate two matrices for every edge type, this is probably the reason you run out of memory, as you've suggested using edge properties to hold a distinguishable values will probably solve your memory issues but there will be performance consequences as a result.

If possible try to modal your data in such a way where you would have a small number of edge types, these should help reduce your search space dramatically, from there use edge attribute to further focus your search.

For example:
Edge types: ['A', 'B', 'C']
Edge property: 'sub_type' with values: ['a', 'b', 'c'...]

`MATCH (n)-[e:B]->(z) WHERE e.sub_type = 'c' RETURN z`

**Comment by jonrscott** [comment]
Thanks for the speedy reply. I had already tried the sizing calculator, but because it doesn't take number of edge types into account it gave me quite an optimistic answer. Anyway your info is very helpful - I can probably model the data so that the important edge types are preserved and the less common ones are bundled together and distinguished by an attribute.
