### ISSUE TITLE
Query parameter insertion ambiguity

### ISSUE THREAD

**Issue by LWprogramming** [RedisGraph/RedisGraph#544]
I'd like to insert parameters into my Cypher queries. Is there a way to do this in RedisGraph?

For instance, this query has parameters
```cypher
MATCH (Foo:Bar)
WHERE Foo.name = $name
RETURN Foo
```
where `name` is a parameter, say `{'name': 'hello'}`.

Does RedisGraph support this? I didn't find any documentation of this, including how to set a parameter.

Using redis-cli to run a command like `GRAPH.QUERY animals 'MATCH(n) RETURN $x'` gives an error saying "`x` is not defined."

I'm looking for the equivalent of `:params name: 'hello'` in the [Neo4j browser](https://stackoverflow.com/a/42398794).

**Comment by swilly22** [comment]
Hi @LWprogramming,
Sorry but currently RedisGraph doesn't supports templated queries,
the plan is to start implementing this right after RedisGraph 2.0 is released (early August)

**Comment by LWprogramming** [comment]
Hi @swilly22,
Thanks for the info-- does that mean templated queries will be supported in early August, or is that when you expect work to _begin_ on templated queries?

**Comment by swilly22** [comment]
Expecting to start working on this feature.

**Comment by LWprogramming** [comment]
Got it, thanks!
