### ISSUE TITLE
Compilation Error in CentOS 7

### ISSUE THREAD

**Issue by jobs-git** [RedisGraph/RedisGraph#547]
This is from master

    error: expected expression before ‘int’
             int              : GxB_Global_Option_set ,  \

    error: expected expression before ‘_Bool’

Tested on gcc 4.8.5, gcc 4.9.2, gcc 5.3.1, gcc 6.3.1, gcc 7 & 8

**Comment by rafie** [comment]
This is due to gcc version < 7 (gcc 6 might do but probably no need to bother with that).
system-setup.py can be enabled to provide for gcc 7 on CentOS.

**Comment by jobs-git** [comment]
The requirement seems to have arisen due to GraphBlas, but why was this not designed as a universal code? Are there benefits in using those features at the cost of compatibility?

**Comment by swilly22** [comment]
Please see [CenOS dockerfile](https://github.com/RedisGraph/RedisGraph/blob/master/Dockerfile.centos) as a reference
