### ISSUE TITLE
Query fails on empty graph before nodes created

### ISSUE THREAD

**Issue by LWprogramming** [RedisGraph/RedisGraph#551]
Redisgraph has some bug related to empty graphs, where MATCH queries fail before any nodes are created. However, if we create a node then delete it (so that the graph is empty again), the query works correctly.

``` python
>>> import redis
>>> r = redis.Redis(host=u'localhost', port=6379) # default
>>> from redisgraph import Graph
>>> rg = Graph('animals', r)
>>> rg.query('MATCH (n) RETURN n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
redis.exceptions.ResponseError: key doesn't contains a graph object.
>>> r.execute_command('GRAPH.QUERY animals', 'MATCH (n) RETURN n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
redis.exceptions.ResponseError: key doesn't contains a graph object.
>>> r.execute_command('GRAPH.QUERY animals', 'CREATE (a:Animal {name: "hello"})')
[[], [b'Labels added: 1', b'Nodes created: 1', b'Properties set: 1', b'Query internal execution time: 0.938488 milliseconds']]
>>> r.execute_command('GRAPH.QUERY animals', 'MATCH (n) RETURN n')
[[[b'n.name'], [b'hello']], [b'Query internal execution time: 0.295545 milliseconds']]
>>> r.execute_command('GRAPH.QUERY animals', 'MATCH (n) DELETE n')
[[], [b'Nodes deleted: 1', b'Query internal execution time: 0.285277 milliseconds']]
>>> r.execute_command('GRAPH.QUERY animals', 'MATCH (n) RETURN n')
[[[b'n.name']], [b'Query internal execution time: 0.237867 milliseconds']]
>>> rg.query('MATCH (n) RETURN n')
<redisgraph.query_result.QueryResult object at 0x7efe6b644240>
>>> rg.query('MATCH (n) RETURN n').pretty_print()
+-------------------+
|     b'n.name'     |
+-------------------+
| No data returned. |
+-------------------+

b'Query internal execution time: 0.220629 milliseconds'
```

Other information

* Python version 3.6.7

* `redis.__version__` is 3.2.1

**Comment by swilly22** [comment]
Hi @LWprogramming,
There's a difference between a none-existing graph and an empty graph.
In your example the `animals` graph doesn't exists up until the point in which you introduce some graph entities, in which case the graph is created, your `DELETE` query will remove the only node in the graph which will make it empty yet the graph still remains, as such querying an empty graph returns a result-set.

**Comment by LWprogramming** [comment]
Hmm-- is there a way to create an empty graph without introducing graph entities?

**Comment by swilly22** [comment]
Currently no,
The only command which will execute without specifying graph ID is GRAPH.EXPLAIN
all other expect graph ID,
GRAPH.QUERY will either create the graph if it does not exists and the query is a write query
otherwise (a read query on a none-existing graph) will issue an error.

Would you mind sharing your use-case here?

**Comment by LWprogramming** [comment]
I'm writing some integration tests that involve putting some data in a RedisGraph database. 

Before running any tests, I wanted to delete all leftover data from the previous tests (`MATCH (n) DELETE n`) and then create the nodes and edges for the integration test data.

I suppose I could work around it by running `rg.query('CREATE (n)')` before deleting everything-- just wanted to check if there's a cleaner way to do it.

**Comment by swilly22** [comment]
you can simply run the `DEL` command specifying the previous GraphID.
