### ISSUE TITLE
Specifying Cypher version in query

### ISSUE THREAD

**Issue by LWprogramming** [RedisGraph/RedisGraph#552]
According to the Open Cypher [language specification](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf) page 196, we can specify which Cypher version to use at the start of a query:

```cypher
CYPHER 9
MATCH (n)
RETURN n
```

However, this doesn't seem to be the case for RedisGraph: 

```python
>>> import redis
>>> r = redis.Redis()
>>> r.execute_command('GRAPH.QUERY animals', 'CYPHER 9 MATCH (n) RETURN n')
Traceback (most recent call last):
...
redis.exceptions.ResponseError: Syntax error at offset 7 near 'CYPHER'
```
Is specifying the version like this unsupported for Redisgraph, or is there some way to do this that I've overlooked?

Other information

* Python version 3.6.7

* `redis.__version__` is 3.2.1

**Comment by jeffreylovitz** [comment]
Hi @LWprogramming,

We haven't added that syntax to RedisGraph yet, as its only current purpose is futureproofing. As indicated on the page you reference, openCypher version 9 is the only standard version so far.

If a future standard version does break compatibility with 9's syntax or behaviors, it's likely that we'll add this syntax, but it does not serve a purpose for the foreseeable future! Cypher 10 is a long way off, and all of the prospective changes that I'm aware of are very careful to not break compatibility in any way. If you're curious, language proposals can be found here: https://github.com/opencypher/openCypher/issues?q=label%3ACIP .

**Comment by LWprogramming** [comment]
Hi,

I ask since Neo4j seems to have a [different approach](https://github.com/neo4j/neo4j/issues/12239) which suggests that other Cypher versions exist. But since RedisGraph doesn't support it yet, I'll close this since that resolves the question. Thanks for the info!
