### ISSUE TITLE
Result set format vs. documentation

### ISSUE THREAD

**Issue by LWprogramming** [RedisGraph/RedisGraph#557]
According to the [RedisGraph docs](https://oss.redislabs.com/redisgraph/result_structure/), queries that return data give back a 3-element list. The docs also describe the nested list format for data. However, that didn't seem to be what's going on when I tried it out.

```python
>>> import redis
>>> r = redis.Redis()
>>> r.execute_command('GRAPH.QUERY', 'animals', 'MATCH (n) RETURN n')
[[[b'n.uuid', b'n.net_worth', b'n.name'], [b'cfc6e625-8594-0927-468f-f53d864a7a52', 200, b'Animal 2'], [b'cfc6e625-8594-0927-468f-f53d864a7a51', 100, b'Animal 1'], [b'Query internal execution time: 0.255296 milliseconds']]
```

which is a list of 2 elements, the first one containing a list of field names followed by lists of records, and the second one being a list of metadata.

Is this the intended behavior? I wanted to confirm since it doesn't match the docs and I don't see it mentioned elsewhere.

Other info

* python 3.6.7

* redis version 3.2.1

**Comment by jeffreylovitz** [comment]
Hi @LWprogramming ,

It looks like you're using an older version of RedisGraph. You can check this like so:
```
$ redis-cli module list
1) 1) "name"
   2) "graph"
   3) "ver"
   4) (integer) 19900
```
The latest version, seen here, is 1.99.00. Prior to this version, RedisGraph emitted the tabular format you provided a snippet of.

The default Docker tag and the master branch (if you're building from source) refer to the latest version, so upgrading should be straightforward!

**Comment by LWprogramming** [comment]
Hi,

Thanks for the info! Looking at the [release history](https://github.com/RedisGraph/RedisGraph/releases/), 1.99.00 appears to be a pre-release version so updating at this time might not be the best idea. Is there somewhere I could find version 1.2.2 documentation?

**Comment by jeffreylovitz** [comment]
Ah, I see! The format documentation is more fleshed out for 1.99.00 than 1.2.2, but some can be seen here:
https://github.com/RedisGraph/RedisGraph/blob/v1.2.2/docs/design.md#querying-the-graph

I'd recommend 1.9.9 over 1.2.2 if possible; it introduces a number of improvements and has proven stable so far (we hope to bump to 2.0 soon). I understand that may not be viable, though!

**Comment by LWprogramming** [comment]
Hmm, do we have an estimate on when the next release comes out (whether that's 1.9.9 or 2.0)?

**Comment by K-Jo** [comment]
@LWprogramming it will be in the course of Q3 of this year
