### ISSUE TITLE
I don't find the compiled binary at src/redisgraph.so

### ISSUE THREAD

**Issue by zhuguocheng29** [RedisGraph/RedisGraph#559]
I don't want to build redisgraph by myself, however I don't find the compiled binary at **src/redisgraph.so**

**Comment by swilly22** [comment]
The compiled binary is not part of the repository,
you'll have to compile the source code in order to get it,
an alternative would be using the docker image.

**Comment by rafie** [comment]
You can run the following to get redisgraph.so:
```
docker create --cidfile /tmp/rg.cid redislabs/redisgraph; docker cp $(cat /tmp/rg.cid):/usr/lib/redis/modules/redisgraph.so .
```
