### ISSUE TITLE
MacOS: Compilation issue

### ISSUE THREAD

**Issue by mohitkhanna** [RedisGraph/RedisGraph#561]
Hi,

I'm unable to compile RedisGraph module in MacOS. Any help will be appreciated. Build works fine on Amazon Linux (EC2) - but needed on MacOS for dev purposes. Attaching the build logs with this ticket.

High Siera: 10.13.6 (17G7024)

[RedisGraph-Build-issue.txt](https://github.com/RedisGraph/RedisGraph/files/3400220/RedisGraph-Build-issue.txt)

**Comment by swilly22** [comment]
Hi @mohitkhanna, thank you for reporting,
it seems like you're missing some build dependencies,
please make sure the following are available `cmake` `m4` `automake` `peg` `libtool` `autoconf`
I believe you should be able to get them using `brew`

**Comment by mohitkhanna** [comment]
Hi @swilly22 - thanks a lot! This worked perfectly.
