### ISSUE TITLE
Exclude relationship pattern using NOT

### ISSUE THREAD

**Issue by dipeti** [RedisGraph/RedisGraph#564]
Hi, 

I was wondering if there is any way in RedisGraph to filter on nodes that  **do not** have a specified relationship, just as it is described in the openCypher [docs](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf). 
```
MATCH (persons), (peter {name: 'Peter'})
WHERE NOT (persons)-[]->(peter)
RETURN persons.name, persons.age
```
The above query should return people who do not know Peter.

**Comment by swilly22** [comment]
Hi @dipeti,
At the moment there's no support for path objects.

**Comment by dipeti** [comment]
Can you think of any alternative way of doing it? Also an rough estimate for adding the feature would be greatly appreciated.

**Comment by swilly22** [comment]
No real alternatives,
Rough estimation, due to committed timeline this might take a few months ~4

**Comment by swilly22** [comment]
Support been added.
