### ISSUE TITLE
Question: New feature in 1.20 Graph Entity ID

### ISSUE THREAD

**Issue by m0rtal1990** [RedisGraph/RedisGraph#568]
Hello and first of all great Job with the module it's a great use of the Redis System 🙏🏼

Currently I have made smaller Tests with the Database and it is surprisingly straight-forward and quick to learn, I have seen the new 1.2 release notes and had a question sitting on my mind (since I'm currently in the planning phase of a graph). 

Jumping right to the matter, I had a question regarding the Graph Entity ID's, since they are immutable throughout their lifespan, is there a possibility to set those ID's  when creating Entities or would it chew too much on performance? I am asking and wondering if this would perhaps help in creating multi-dimensional graphs and traversals along them via calculations?  **Thanks in advance :)**

**Comment by jeffreylovitz** [comment]
Thanks, @m0rtal1990! Glad that you're enjoying the module.

Entity IDs are actually _not_ immutable. Currently, the only situation in which they might change is after entities have been deleted. Nodes and relations created following a deletion will re-use the deleted IDs, and during serialization there is a compaction stage in which nodes and edges with the highest IDs can be migrated to lower IDs that belonged to deleted entities.

If you require immutable IDs, it would be best to explicitly create a property on your nodes and relations to serve that purpose!
