### ISSUE TITLE
At this stage, can redis' clustering scheme be applied to redisgraph data storage?

### ISSUE THREAD

**Issue by fantasticKe** [RedisGraph/RedisGraph#57]
At this stage, can Redis's clustering scheme be applied to the data storage of redisgraph? Due to the large amount of data, the single-machine memory can no longer satisfy the storage of the relation graph. Can the clustering scheme be used to expand the data storage capacity of redisgraph?

**Comment by swilly22** [comment]
At the moment, RedisGraph can't distribute its data, be it the graph topology or the nodes attributes,
We've got a number of distribution models we would like to pursue somewhere along upcoming Aug/Sep.
I'll update here on our progress.

**Comment by rahst12** [comment]
@swilly22 I'm really interested if you've got an update on a distributed graph topic.  It seems to be the holy grail of graph databases.  👍

**Comment by swilly22** [comment]
@rahst12 I totally agree with you, unfortunately we haven't made much progress on that aspect, as we're currently pushing for a GA which will be able to accommodate quite large graphs within a decent hardware constraints (memory/cpu), once the GA milestone is complete, we'll be free to really give graph distribution a thought.

**Comment by rahst12** [comment]
@swilly22 What do you consider decent hardware (memory, disk, cpu)?  I'm actually doing a little research for what neo4j and dgraph considers 'decent' hardware right now.  I just came across RedisGraph last night.  I've known there was a plugin and some work out there, but nothing as advanced and put-together as this.

Also, do you have a 1 node = x bytes; 1 attribute = x bytes type calculator the size of a graph as it might grow?  

Thanks!

**Comment by swilly22** [comment]
@rahst12 I'm not exactly sure what do you mean by "there was a plugin and some work out there..."
anyhow, it's funny you've mentioned a graph size calculator as we've recently started working on one.

To give a general idea, an empty (no attributes) node / edge have a constant memory overhead of ~20 bytes, we might be able to squeeze that further.

Currently we don't do any attribute compaction and so for every attribute (key/value) pair you introduce RedisGraph would consume additional memory.

The intention is for users to use that calculator to get an estimation on the type of hardware required to accommodate their graph(s).
