### ISSUE TITLE
Multiple properties with same name can be created

### ISSUE THREAD

**Issue by GnaneshKunal** [RedisGraph/RedisGraph#573]
Started via: `docker run -p 6379:6379 -it --rm redislabs/redisgraph:1.99.0`

The following query creates two properties with the same name.
```
127.0.0.1:6379> GRAPH.QUERY my_graph "CREATE ({ name: 'one', name: 'two' })"
1) 1) "Nodes created: 1"
   2) "Properties set: 2"
   3) "Query internal execution time: 1.025026 milliseconds"
127.0.0.1:6379> GRAPH.QUERY my_graph "MATCH (n) RETURN n"
1) 1) "n"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) (empty array)
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "two"
               2) 1) "name"
                  2) "one"
3) 1) "Query internal execution time: 0.777872 milliseconds"
127.0.0.1:6379> GRAPH.QUERY my_graph "MATCH (n) RETURN n.name"
1) 1) "n.name"
2) 1) 1) "two"
3) 1) "Query internal execution time: 0.643699 milliseconds"
```

If we return the node, all the properties (even if multiple) are getting returned. But if we specifically try to return `node[prop_name]` we get the last one that has been assigned during the creation.

Also, searching doesn't work for the first one, but the second one.
```
127.0.0.1:6379> GRAPH.QUERY my_graph "MATCH (n { name: 'one'}) RETURN n"
1) 1) "n"
2) (empty array)
3) 1) "Query internal execution time: 0.287815 milliseconds"
127.0.0.1:6379> GRAPH.QUERY my_graph "MATCH (n { name: 'two'}) RETURN n"
1) 1) "n"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) (empty array)
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "two"
               2) 1) "name"
                  2) "one"
3) 1) "Query internal execution time: 0.386098 milliseconds"
``` 

We should either show an error or take the first value that is being assigned to it.

**Comment by swilly22** [comment]
Hi @GnaneshKunal,
Thank you for reporting this, checking with Neo4J
Running the query `CREATE (x:X{ name: 'one', name: 'two' })`
will create the node and the second (last) `name` attribute 'two' is applied.

We'll fix such that RedisGraph will operate in a deterministic way.

**Comment by gkorland** [comment]
ref https://github.com/RedisGraph/RedisGraph/issues/223
