### ISSUE TITLE
How to persist data with docker

### ISSUE THREAD

**Issue by liiri** [RedisGraph/RedisGraph#575]
I'm using the `redislabs/redisgraph` docker image, and I'd like to persist changes on disk.

Run command:
```
docker run -d \
    --name redis \
    -p 6379:6379 \
    -v /tmp/redis:/data \
    --restart=unless-stopped \
    redislabs/redisgraph
```

With the general redis image, I'd add `redis-server --appendonly yes` and would get data persisted in `/data`.

How can I achieve it with this image? I tried to add `--appendonly yes` to the `docker run`, but then I get the following errors from `redis-cli`:

> 127.0.0.1:6379> GRAPH.QUERY MotoGP "..."
> (error) ERR unknown command `GRAPH.QUERY`, with args beginning with: `MotoGP`...

**Comment by jeffreylovitz** [comment]
Hi @liiri ,

RedisGraph doesn't support the `appendonly` method of persistence right now (although we actually expect to introduce that quite soon). RDB persistence is supported, which has the default settings of persisting to disk:
```
#   after 900 sec (15 min) if at least 1 key changed
#   after 300 sec (5 min) if at least 10 keys changed
#   after 60 sec if at least 10000 keys changed
```
You can modify these settings by passing other `save` directives, such as `--save 60 1` to save every 60 seconds if at least 1 key has changed.

**Comment by liiri** [comment]
@jeffreylovitz I tried to add this config, but it seems to mess up the module installation. When running
```
docker run -d \
    --name redis \
    -p 6379:6379 \
    -v /tmp/redis:/data \
    --restart=unless-stopped \
    redislabs/redisgraph \
    --save 60 1
```

I'm getting errors in `docker-cli`, same as mentioned above `ERR unknown command GRAPH.QUERY`

**Comment by jeffreylovitz** [comment]
@liiri This turned out to be a Docker CMD/ENTRYPOINT issue. Adding any additional directive such as `--save 60 1` or `--appendonly yes` replaces the CMD we have set in our Dockerfile, which is:
`CMD ["redis-server", "--loadmodule", "/usr/lib/redis/modules/redisgraph.so"]`

As such, the module and the commands it introduces, like `GRAPH.QUERY`, don't get loaded!

One simple fix for this is to load explicitly in the `docker run` command:
```
docker run -d \
    --name redis \
    -p 6379:6379 \
    -v /tmp/redis:/data \
    --restart=unless-stopped \
    redislabs/redisgraph \
    --loadmodule /usr/lib/redis/modules/redisgraph.so \
    --save 60 1
```

**Comment by liiri** [comment]
I see, that works. Thanks!
