### ISSUE TITLE
Support Contains Query

### ISSUE THREAD

**Issue by vvippark** [RedisGraph/RedisGraph#579]
Unable to use contains query like Neo4j Cypher language.
where n.Name =~ '.*SUBSTRING.*' return n.Name, n;
I know String operators (STARTS WITH, ENDS WITH, CONTAINS) are not supported, though equivalent results can be obtained using string functions.
but unable to achieve Contains query feature using string function. just wanted to know is there any way to achieve contains query in redisgraph. Trying to find out substring between string without knowing start and end index of substring.

**Comment by swilly22** [comment]
`STARTS WITH` `ENDS WITH` and `CONTAINS ` just been added to the master branch,
you can get the latest version from DockerHub as-well.
