### ISSUE TITLE
Is there anyway to update, delete relationship of existing label.

### ISSUE THREAD

**Issue by vvippark** [RedisGraph/RedisGraph#580]
I am taking redis-graph reference to explain my problem better.

https://oss.redislabs.com/redisgraph/

GRAPH.QUERY MotoGP "CREATE (:Rider {name:'Valentino Rossi'})-[:rides]->(:Team {name:'Yamaha'}), (:Rider {name:'Dani Pedrosa'})-[:rides]->(:Team {name:'Honda'}), (:Rider {name:'Andrea Dovizioso'})-[:rides]->(:Team {name:'Ducati'})"

Here how can I update relationship of Rider(Valentino Rossi) with Team(Ducati) or delete this relationship.

I am looking for this feature as my product catalogue is too huge and I want to import product and its relationships in chunks. both from separate worker.

**Comment by swilly22** [comment]
It is a bit unclear, can you please elaborate,
as "Valentino Rossi" is not connected to "Ducati"

**Comment by sandyk12** [comment]
Yes "Valentino Rossi" is not connected to "Ducati" .
It is connected as below
Rider {name:'Valentino Rossi'})-[:rides]->(:Team {name:'Yamaha'})

Now is there any way I can change this relationship.

**Comment by vvippark** [comment]
Yes "Valentino Rossi" is not connected to "Ducati" .
It is connected as below
Rider {name:'Valentino Rossi'})-[:rides]->(:Team {name:'Yamaha'})

Now is there any way I can change this relationship.

**Comment by swilly22** [comment]
Sorry but what do you mean by change this relationship?
do you want to disconnect Valentino Rossi from Yamaha and connect him to some other node?

**Comment by vvippark** [comment]
yes i want to disconnect Valentino Rossi from Yamaha and connect him to some other node without delete Valentino Rossi.

**Comment by swilly22** [comment]
`MATCH (:Rider {name:'Valentino Rossi'})-[e:rides]->(:Team {name:'Yamaha'}) DELETE e`
will disconnect Rossi from Yamaha

`MATCH (a:Rider {name:'Valentino Rossi'}), (b:Team {name:'Honda'}) CREATE (a)-[:rides]->(b)`
will connect Rossi to Honda.

`MATCH (r:Rider {name:'Valentino Rossi'}) RETURN ID(r)`
Will return Rossi's unique (internal) ID.

**Comment by vvippark** [comment]
```GRAPH.QUERY MotoGP "MATCH (r:Rider {name:'Valentino Rossi'}) RETURN ID(r)"
1) 1) "ID(r)"
2) 1) 1) (integer) 4```
Result Show Like above.however my question is that can we use "Rossi's unique (internal) ID" to update Rossi's Properties and Relationship.

**Comment by swilly22** [comment]
yes you can, suppose Rossi's ID is 1
then you can update Rossi's properties by issuing the following query:
`MATCH (r) WHERE ID(r) = 1 SET r.name = 'Rossi Valentino'`

To connect Rossi to some other node issuing the following:
`MATCH (r), (h:Team {name:'Honda'}) WHERE ID(r) = 1 CREATE (r)-[:rides]->(h)`
