### ISSUE TITLE
Infinite Loop in indexing

### ISSUE THREAD

**Issue by esokullu** [RedisGraph/RedisGraph#592]
Hi guys,

Here's the Cypher query:

```
GRAPH.QUERY index "MATCH (sn:user {udid: '43161e90c186af93da307f04a24f09aa'})-[r:message]->(:user {udid: '42c934cbef9e1342009f156ee624f35a'}) SET r.IsRead = true RETURN sn.udid as t, r"
```

and here is the response I get:

```
...
...
...
   238513) 1) "43161e90c186af93da307f04a24f09aa"
           2) "aa8ba572b1dc95ab1b2e42243d1ad5fe"
           3) "hi Karen?\n"
           4) (integer) 1565594424
           5) "true"
   238514) 1) "43161e90c186af93da307f04a24f09aa"
           2) "aa8ba572b1dc95ab1b2e42243d1ad5fe"
           3) "hi Karen?\n"
           4) (integer) 1565594424
           5) "true"
   238515) 1) "43161e90c186af93da307f04a24f09aa"
           2) "aa8ba572b1dc95ab1b2e42243d1ad5fe"
           3) "hi Karen?\n"
           4) (integer) 1565594424
           5) "true"
2) 1) "Properties set: 238514"
   2) "Query internal execution time: 15872.198413 milliseconds"
(27.37s)
```

It retrieves the same result 238516 times.

Any idea why this is happening? I am on Redis 1.2.2 but the first time the "edge" in question was created was with the master branch of Redis pulled and compiled on April 30, 2019.

Thanks!

**Comment by swilly22** [comment]
HI @esokullu,

Can you please verify the number of connections between 
user with udid 43161e90c186af93da307f04a24f09aa and  user with udid 42c934cbef9e1342009f156ee624f35a over the message relation?

`GRAPH.QUERY index "MATCH (:user {udid: '43161e90c186af93da307f04a24f09aa'})-[r:message]->(:user {udid: '42c934cbef9e1342009f156ee624f35a'}) RETURN COUNT(r)"`

Thank you.

**Comment by esokullu** [comment]
Sure; here it is:

```
127.0.0.1:6379[19]> GRAPH.QUERY index "MATCH (:user {udid: '43161e90c186af93da307f04a24f09aa'})-[r:message]->(:user {udid: '42c934cbef9e1342009f156ee624f35a'}) RETURN COUNT(r)"
1) 1) 1) "COUNT(r)"
   2) 1) (integer) 238514
2) 1) "Query internal execution time: 68.756255 milliseconds"
```

**Comment by swilly22** [comment]
It seems, for what ever reason that, user `43161e90c186af93da307f04a24f09aa` is connected 238514 times to user `42c934cbef9e1342009f156ee624f35a` with an edge of type `message`

Any idea what were the steps leading to this situation?

**Comment by esokullu** [comment]
Thanks for bearing with me on this.
It was an issue on our side; https://github.com/pho-adapters/index-redis/commit/d35235b0d86d84bb8108a4445f6c2cd92d31a6d7
🙏
