### ISSUE TITLE
How to get all the nodes which are NOT having any relationship in redisgraph 

### ISSUE THREAD

**Issue by mayankbharadwaj** [RedisGraph/RedisGraph#593]
Hi,

I was wondering if there is any way in RedisGraph to get all nodes which are not linked (connected) with any node. I was not able to find it in the redisgraph documentation.

In Neo4j we have cypher query like below to get all the nodes . Can we make similar query in redisgraph or any work around which can be done to achieve this. 

MATCH (x) 
WHERE NOT (x)-[]-()
RETURN collect(x)

**Comment by swilly22** [comment]
Hi @mayankbharadwaj,
Currently we don't support pattern matching within the WHERE clause,
I believe we can quite easily introduce an incoming and outgoing degree functions which when given a node will return the incoming, outgoing degree of the node.

`MATCH (x)
WHERE incomingDegree(x) = 0 AND outgoingDegree(x) = 0
RETURN collect(x)`

**Comment by mayankbharadwaj** [comment]
Hi @swilly22 ,

So you are saying currently redisgraph doesn't provide any way through which we can get the list of unconnected nodes present in the graph.

**Comment by swilly22** [comment]
@mayankbharadwaj If you're willing to bare with us for a day or two you'll be able to use the query I've suggested above to achieve what you're after.

**Comment by mayankbharadwaj** [comment]
Thanks for your response. I will wait for 2-3 days and will check again after that.

**Comment by swilly22** [comment]
```
MATCH (x)
WHERE NOT (x)-[]-()
RETURN collect(x)
```
Is supported on RedisGraph 2.0
