### ISSUE TITLE
Response errors running GRAPH.PROFILE

### ISSUE THREAD

**Issue by jeffreylovitz** [RedisGraph/RedisGraph#620]
PROFILE calls currently result in the error:
```
API misuse detected in module graph:
RedisModule_ReplyWithArray(REDISMODULE_POSTPONED_ARRAY_LEN) not matched by the same number of RedisModule_SetReplyArrayLen()
```
This is probably a simple fix (check for how resultset calls differ from EXPLAIN and QUERY endpoints), but in general we should have the PROFILE endpoint covered in our flow tests as well.

**Comment by swilly22** [comment]
#1004
