### ISSUE TITLE
documentation: support for adding/updating relationship between two existing nodes

### ISSUE THREAD

**Issue by duffpw** [RedisGraph/RedisGraph#633]
I've reviewed the existing issue list, both open and closed, as well as the documentation. I'm trying to find the best practice for the current implementation to perform a cypher query that adds, and separately updates, a relationship between two existing nodes without creating "duplicate nodes". It's fine if this has to happen in separate sequential query steps.

All of the normal cypher queries I would use to do this, in say neo4j, seem to be unsupported in the implementation or cause a "duplicate" second node to be created. I don't think I'm hitting bugs but here is an example. In neo4j I might have a sequence like this:

query1: MERGE (a:Person {email:"test@example.com"})

query2: MERGE (a:Person {email:"rob@example.net"})

query3: MATCH (a:Person) WHERE a.email = "test@example.com" WITH a MATCH (b:Person) WHERE b.email= "rob@example.net" MERGE (a)-[:EMAILED]->(b)

and end up with a network that consists of two nodes and an EMAILED relationship between them. Later I might go back and add additional relationships between those node while leaving EMAILED intact. I understand this is not a supported query but I've tried many other permutations as well and always hit something unsupported or a situation where a new third node is created.

**Comment by swilly22** [comment]
Hi @duffpw,

Consider the following:
query1: `MERGE (a:Person {email:"test@example.com"})`
query2: `MERGE (a:Person {email:"rob@example.net"})`
query3: `MATCH (a:Person), (b:Person) WHERE a.email = "test@example.com" AND b.email = "rob@example.net" CREATE (a)-[:EMAILED]->(b)`

Please note that if node `a` is already connected to node `b` via an `EMAILED` relation the third query will introduce another edge of relationship type `EMAILED` between them.

**Comment by duffpw** [comment]
Thanks for that, I will test it. Is there any alternate syntax that won't duplicate the edge available at this point in time?

**Comment by swilly22** [comment]
At the moment I don't think so unless you're willing to introduce a fourth query.

**Comment by duffpw** [comment]
If you just mean an additional MATCH and then application logic to make the CREATE conditional I get that. Something idempotent would be much better for my use case. Again, thanks for the prompt response.

**Comment by swilly22** [comment]
Sure, we'll get there, there's an effort to extend our support of the `merge` clause.

**Comment by hiteshbal91** [comment]
@swilly22 I also wanted to check for the same to merge the relationship based on some attribute values of relations ship.

GRAPH.QUERY Cars 'MERGE (honda:Cars {id: "c12345"}) MERGE [r1:rider {id: "r12345", via: "uber"}] MERGE (driver1:Person {id: "d12345"}) CREATE (honda)-[r1]->(driver1)'

I have a relationship with the attribute based on which I will identify if that exists or not.

I don't want to create another edge between the 2 nodes if that already exists. Is there is any to achieve this?

**Comment by jeffreylovitz** [comment]
@hiteshbal91 If I understand your request correctly, the appropriate query would be:
`MERGE (honda:Cars {id: "c12345"}) MERGE (driver1:Person {id: "d12345"}) MERGE (honda)-[r1:rider {id: "r12345", via: "uber"}] ->(driver1)`

If one of the properties on `r1` is allowed to not match, you can `MERGE` just on the mandatory property and `ON MATCH/ON CREATE SET` the other one!

**Comment by hiteshbal91** [comment]
Hi @jeffreylovitz ,

I did not understand the above one, I will reiterate the request.

"MERGE" command allowed to merge the nodes if that already exists, in the same way If we can merge the relationship as well if it already exists instead of lookup with match and later to create or skip.

 Example, If there is already relationship [r1:rider {id: "r12345", via: "uber"}] between the node (honda:Cars {id: "c12345"}) and (driver1:Person {id: "d12345"}). Then the new relationship should not be created but currently lookup is the only option that I see.
 
Thanks,

**Comment by jeffreylovitz** [comment]
`MERGE` works for relationships precisely the same way that it does for nodes - https://oss.redislabs.com/redisgraph/commands/#merge .

You must still introduce relationships with the `(src)-[edge]->(dest)` syntax, but if the `src` and `dest` aliases have already been introduced in the query, they will be treated as read-only members and only the relationship might or might not be created.

**Comment by hiteshbal91** [comment]
@jeffreylovitz It seems like I am missing something. Following is what I have tried

- `GRAPH.QUERY Cars 'MERGE (honda:Cars {id: "c12345"}) MERGE (driver1:Person {id: "d12345"}) CREATE (honda)-[r1:rider {id: "r12345", via: "uber"}]->(driver1)'`

- `GRAPH.QUERY Cars 'MERGE (honda:Cars {id: "c12345"}) MERGE (driver1:Person {id: "d12345"}) CREATE (honda)-[r1:rider {id: "r12345", via: "uber"}]->(driver1)'`

- `GRAPH.QUERY Cars 'MATCH (car:Cars)-[r1:rider]-(driver:Person) RETURN car.id, r1.via, driver.id'`

In the output, we get the duplicated relationship.

Thanks,

**Comment by jeffreylovitz** [comment]
Replace your `CREATE` with a `MERGE` like so:
```
GRAPH.QUERY Cars 'MERGE (honda:Cars {id: "c12345"}) MERGE (driver1:Person {id: "d12345"}) MERGE (honda)-[r1:rider {id: "r12345", via: "uber"}]->(driver1)'
```

**Comment by hiteshbal91** [comment]
Got it @jeffreylovitz worked like a charm 👍
