### ISSUE TITLE
Unable to compile code - error GB_init.c variable ok is not defined

### ISSUE THREAD

**Issue by nareshgnT** [RedisGraph/RedisGraph#653]
when compile the source code as per instruction mentioned, getting error  ```GB_init.c variable ok is not defined``` looks like merge issue

**Comment by DvirDukhan** [comment]
Hi @nareshgnT 
Can you please give us some additional info?
1. which branch did you tried to compile?
2. which OS?

Thanks

**Comment by nareshgnT** [comment]
The RedisGraph repository: git clone --recurse-submodules -j8 https://github.com/RedisGraph/RedisGraph.git

Using OS X, verify that homebrew is installed and run: ```brew install cmake m4 automake peg libtool autoconf```

To build, run make in the project's directory.

**Comment by nareshgnT** [comment]
@DvirDukhan ^^^

**Comment by nareshgnT** [comment]
i fixed the issue introducing bool ok above the if block. that issue not happening in my local. But getting below error

```
1 warning generated.
    CC redisgraph.so
clang: error: unsupported option '-fopenmp'
make[1]: *** [redisgraph.so] Error 1
make: *** [all] Error 2
```

**Comment by DvirDukhan** [comment]
@nareshgnT 
Recently we added the latest version of GraphBLAS 3 which uses OpenMP for parallel execution. For that reason, we compile our code base with GCC compiler, on macOS. 

If you want to just work around this issue, I recommend you to use our latest docker version
`docker run -p 6379:6379 -it --rm redislabs/redisgraph:1.99.2` 
or
`docker run -p 6379:6379 -it --rm redislabs/redisgraph:edge` which is aligned with `master` branch.

If changing your default compiler is a valid option for you, please follow those simple instructions:
1. `brew install gcc`
2. verify that `/usr/local/bin` is part of your `PATH` environment variable, by calling `echo $PATH`. If it doesn't, call `export PATH=/usr/local/bin:$PATH`
3. add symbolc links to gcc (gcc 9 is the current version)
```
cd /usr/local/bin
ln -s /usr/local/bin/gcc-9 cc
ln -s /usr/local/bin/gcc-9 gcc
ln -s /usr/local/bin/g++-9 g++
ln -s /usr/local/bin/c++-9 c++
ln -s /usr/local/bin/cpp-9 cpp
```

**Comment by nareshgnT** [comment]
after updating compiler to GCC i am able to compile the code without any issue. Please update the readme if possible so other will benefit. Closed the issue. Thanks
