### ISSUE TITLE
Crash when using `IN` keyword in Redis 5.0.5

### ISSUE THREAD

**Issue by tanzhouwen** [RedisGraph/RedisGraph#656]
127.0.0.1:6379> GRAPH.QUERY social "MATCH (n) WHERE id(n) IN [1] RETURN n"
"Syntax error at offset 25 near 'IN'"

**Comment by DvirDukhan** [comment]
Hi @tanzhouwen 
please provide us some additional information:
1. RedisGraph version
2. Crash log

Thanks

**Comment by suparek** [comment]
also appeared in 5.0.3

**Comment by jeffreylovitz** [comment]
@tanzhouwen it seems likely that you're using an older version of the module. If using a Docker image, I'd recommend switching to `edge` or `1.99.3`; if compiling from source the master branch or 1.99.3 release will include this feature.
