### ISSUE TITLE
Cannot store an array as the property of nodes or edges

### ISSUE THREAD

**Issue by mingen-pan** [RedisGraph/RedisGraph#687]
I query the RedisGraph with the following cypher:
`graph.query Test "Create (:Person {name:['A', 'B']})"`

I got the return `RedisGraph does not currently support collection`

When could we expect this feature to be implemented?

**Comment by jeffreylovitz** [comment]
Hi @mingen-pan,

It sounds like you're running an older version of RedisGraph, this was introduced with version 1.99.2 (the latest is 1.99.3). I'd recommend upgrading!

If you're using a Docker image you can pull the tag `edge`, which corresponds to the `master` branch, or the tag `1.99.3`.

**Comment by mingen-pan** [comment]
It solved my issue. Thank you.
