### ISSUE TITLE
Container crashed while querying for a node with relationship when there is no relationship present

### ISSUE THREAD

**Issue by BhanuPrakash531** [RedisGraph/RedisGraph#699]
Below are the sequence of steps to replicate the issue

- `GRAPH.QUERY Testme "CREATE(e:Test{name:'one',parentId:'string',testUid:'c2afef4b-1ef9-4713-858b-c283891a2372'})"`
-- `1) 1) "Labels added: 1"
   2) "Nodes created: 1"
   3) "Properties set: 3"
   4) "Query internal execution time: 0.675100 milliseconds"`
- `GRAPH.QUERY Testme "MATCH(e:Test{testUid:'c2afef4b-1ef9-4713-858b-c283891a2372'}) RETURN e"`
- `GRAPH.QUERY Testme "MATCH (e:Test{testUid:'c2afef4b-1ef9-4713-858b-c283891a2372'})-[:parentId*1..]->(e2)RETURN e2"`
Container crashes on the above query

**Comment by jeffreylovitz** [comment]
Thanks for the report, @BhanuPrakash531!

This bug was a silly oversight on our part, #700 will resolve it.
