### ISSUE TITLE
Container crash on malformed Match query

### ISSUE THREAD

**Issue by leonh** [RedisGraph/RedisGraph#702]
1st query : works

` GRAPH.QUERY USERS "MATCH (a)-[r]->(b) WHERE id(a) = 1 AND id(b) = 2 AND type(r) = 'OWNS' RETURN count(r)"`

2nd malformed query : causes my redis docker container to crash

` GRAPH.QUERY USERS "MATCH (a)-[r]->(b) WHERE id(a) = string AND id(b) = string AND type(r) = 'OWNS' RETURN count(r)"`

redis_1              | === REDIS BUG REPORT START: Cut & paste starting from here ===
redis_1              | 1:M 21 Oct 2019 12:41:49.519 # Redis 5.0.5 crashed by signal: 11
redis_1              | 1:M 21 Oct 2019 12:41:49.519 # Crashed running the instruction at: 0x7fb0f21f9611
redis_1              | 1:M 21 Oct 2019 12:41:49.519 # Accessing address: (nil)
redis_1              | 1:M 21 Oct 2019 12:41:49.519 # Failed assertion: <no assertion failed> (<no file>:0)
redis_1              | 
redis_1              | ------ STACK TRACE ------
redis_1              | redis-server: /redisgraph/src/execution_plan/execution_plan.c:778: _NewExecutionPlanSegment: Assertion `op' failed.
redis_1              | EIP:
redis_1              | /lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7fb0f21f9611]
redis_1              | 
redis_1              | Backtrace:
redis_1              | redis-server *:6379(logStackTrace+0x32)[0x558fa3c80112]
redis_1              | redis-server *:6379(sigsegvHandler+0x9e)[0x558fa3c807ee]
redis_1              | /lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7fb0f23aa730]
redis_1              | /lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7fb0f21f9611]
redis_1              | /lib/x86_64-linux-gnu/libc.so.6(+0x2240f)[0x7fb0f21f940f]
redis_1              | /lib/x86_64-linux-gnu/libc.so.6(+0x30102)[0x7fb0f2207102]
redis_1              | /usr/lib/redis/modules/redisgraph.so(+0xb7a2f)[0x7fb0e48b2a2f]
redis_1              | /usr/lib/redis/modules/redisgraph.so(NewExecutionPlan+0x83)[0x7fb0e48b2af3]
redis_1              | /usr/lib/redis/modules/redisgraph.so(_MGraph_Query+0x2ea)[0x7fb0e48ae8fa]
redis_1              | /usr/lib/redis/modules/redisgraph.so(+0xd7a8d)[0x7fb0e48d2a8d]
redis_1              | /lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7fb0f239ffa3]
redis_1              | /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fb0f22d04cf]
redis_1              |

**Comment by jeffreylovitz** [comment]
@leonh Thanks for the report! This issue has been resolved in recent versions of RedisGraph.

The Docker tag edge, which corresponds to the master branch, or the tag 1.99.3, which is the last released version, should both cause the error:
```
GRAPH.QUERY USERS "MATCH (a)-[r]->(b) WHERE id(a) = string AND id(b) = string AND type(r) = 'OWNS' RETURN count(r)"
(error) string not defined

```

**Comment by leonh** [comment]
Thanks for your speedy reply! 

I was using redislabs/redisgraph:**latest** image 
Switching to using redislabs/redisgraph:**edge** I see the error has been handled
btw. Is there a way to see which release tag I'm using via the redis-cli ?
