### ISSUE TITLE
Need for GRAPH.BULK documentation

### ISSUE THREAD

**Issue by kkonevets** [RedisGraph/RedisGraph#709]
Currently I am struggling with csv format of bulk loader utility. I have my own data format witch is binary and I don't wont to convert it to csv because the size of csv would be huge.
So I need to read documentation to write my own bulk loader

**Comment by jeffreylovitz** [comment]
@kkonevets You are right, we don't currently have open documentation about the input format expected by the `GRAPH.BULK` endpoint that the bulk loader utility employs. It is not a secret, just ill-documented - the comments in the [endpoint source code](https://github.com/RedisGraph/RedisGraph/blob/master/src/bulk_insert/bulk_insert.c) and [utility code](https://github.com/RedisGraph/redisgraph-bulk-loader/blob/master/bulk_insert.py) should be comprehensive in their description.

I'll augment our [documentation](https://redisgraph.io) with a full specification when possible, though it may be a week or so before time allows!

**Comment by kevin-holbrook-epicor** [comment]
Any update on this? I see this is still undocumented which is disappointing. 
Loading data in bulk is hugely important,

**Comment by semiotomr** [comment]
Also, it seems to be changing!

For example, https://github.com/RedisGraph/redisgraph-iam-demo is out of sync with it:

```
$ ./import-py3.sh
...
  File "redisgraph-bulk-loader/bulk_insert.py", line 270, in bulk_insert
    allocate_graph(label_descriptors.total_entities, relation_count)
  File "redisgraph-bulk-loader/bulk_insert.py", line 195, in allocate_graph
    result = redis_client.execute_command(*cmd)
...
redis.exceptions.ResponseError: Bulk insert format error, failed to parse bulk insert sections.
```
