### ISSUE TITLE
String types stored from BULK api when they should be numeric

### ISSUE THREAD

**Issue by renewooller** [RedisGraph/RedisGraph#715]
To replicate:
Run the GRAPH_DEMO from the provided example in https://github.com/RedisGraph/redisgraph-bulk-loader:

```python3 bulk_insert.py GRAPH_DEMO -n example/Person.csv -n example/Country.csv -r example/KNOWS.csv -r example/VISITED.csv```

Query the data to observe the numerics stored as strings:

```graph.query "GRAPH_DEMO" "match(p:Person) return p"```

``` 14) 1) 1) 1) "id"
             2) (integer) 13
          2) 1) "labels"
             2) 1) "Person"
          3) 1) "properties"
             2) 1) 1) "name"
                   2) "Noam Nativ"
                2) 1) "age"
                   2) "34"
                3) 1) "gender"
                   2) "male"
                4) 1) "status"
                   2) "single"
``` 
Observe 'age' above.

Create a person, not using the bulk loader:

```graph.query "GRAPH_DEMO" "CREATE (p:Person) SET p.name='Rene', p.age=38, p.gender='male', p.status='separated'"```

Query the data to observe the numerics stored as numerics:

```15) 1) 1) 1) "id"
             2) (integer) 27
          2) 1) "labels"
             2) 1) "Person"
          3) 1) "properties"
             2) 1) 1) "name"
                   2) "Rene"
                2) 1) "age"
                   2) (integer) 38
                3) 1) "gender"
                   2) "male"
                4) 1) "status"
                   2) "separated"
```

Observer age is "(integer) 38" as it should be.

Forcing the types has no affect, which is why I suspect the problem is in the BULK api rather than the loader:

```python3 bulk_insert.py GRAPH_DEMO -q3 -f '{"Person":[3,2,3,3]}' -n example/Person.csv -n example/Country.csv -r example/KNOWS.csv -r example/VISITED.csv```

**Comment by jeffreylovitz** [comment]
@renewooller,

Thanks for drawing attention to this! Currently, the bulk importer tool and endpoint don't differentiate between integer and floating-point user values. Using `redis-cli`, floating-point values print as strings [as per RESP2 limitations](https://oss.redislabs.com/redisgraph/result_structure/#scalars), though internally and in language-specific clients, examples like the one you provide should be processed as numeric floats/doubles.

That said, the bulk import tool should differentiate between integers and floats. A few enhancements for this tool are in the works, so we'll add this one in the near future as well!

**Comment by jeffreylovitz** [comment]
This is no longer an issue in the bulk loader.
