### ISSUE TITLE
Typo in Error Message

### ISSUE THREAD

**Issue by dandago** [RedisGraph/RedisGraph#718]
Hi,

I am learning RedisGraph and Cypher. I was fooling around (no idea what I'm doing) and got the error below:

```
127.0.0.1:6379> GRAPH.QUERY MotoGP "MATCH (r)-[]->(x) WHERE actor.name = 'Valentino Rossi' RETURN x"
(error) key doesn't contains a graph object.
```

I just wanted to point out the obvious typo in there: it should say "doesn't contain" (without the 's').

**Comment by jeffreylovitz** [comment]
@dandago Thanks for pointing this out! This typo, and in fact this error, are not present on the latest version of RedisGraph (which is 1.99.4).

I'd recommend switching this version if you can; it has a number of improvements including much friendlier error handling!

If you're using Docker, the tag `edge` always corresponds to the master branch.
