### ISSUE TITLE
looking up by identifier

### ISSUE THREAD

**Issue by renewooller** [RedisGraph/RedisGraph#737]
Hi, 
As far as I understand we can access the identifier via look up thus: 

```graph.query "test" "MATCH (a) WHERE id(a) = 9 RETURN a"```

However, it seems expensive to run the scalar function id over every record. 

Is there a way to access the internal id?
I tried
```graph.query "test" "MATCH (a) WHERE a.id = 9 RETURN a"```
```graph.query "test" "MATCH (a {id: 9}) RETURN a"```
with idx and _id variants. 

Side note:  the documentation says re the 'id()' function : "Returns the internal ID of a relationship or node (which is not immutable.)" does this mean that it is mutable?

Cheers,
Rene

**Comment by swilly22** [comment]
Hi @renewooller,
Running `ID(n)` compared to `n.v` should be negligible, both are what we refer to as arithmetic expression, AE, which will be evaluated in runtime against a given `n` entity.

Have you seen a dramatic difference in execution time between the two?

Currently the only way to access an entity internal ID is via the `ID` function.

Regarding the documentation, we should update it to make it clearer, the internal ID is immutable, that is an entity ID will not change as long as RedisGraph is running, in the process of loading from either AOF or RDB a given entity N which might had an ID value of X (ID(N) = X) prior to booting from AOF/RDB might have a different internal ID once the loading process is finished.

**Comment by renewooller** [comment]
Thanks - I haven't run any benchmarks on it or observed any difference, so it's good to know I can use it.

Thanks for the extra information
