### ISSUE TITLE
RedisGraph crashes in case of union with path variable

### ISSUE THREAD

**Issue by siphonelee** [RedisGraph/RedisGraph#741]
When running:

MATCH p=(v:V)-[:B]->(:K)-[:P * 0..]->(:K{sid:301}) 
return v.sid as sid, length(p) as len 
UNION ALL
MATCH p1=(v1:V)-[:B]->(:K)-[:P * 0..]->(:K{sid:302}) 
return v1.sid as sid, length(p1) as len

Redis crashes as listed in the following matrix:

1st MATCH result NOT NULL / 2nd MATCH result NOT NULL
yes
1st MATCH result NOT NULL / 2nd Match result NULL
yes
1st Match result NULL / 2nd MATCH result NOT NULL
no
1st Match result NULL / 2nd Match result NULL
no

While this one works fine even if the 1st MATCH result is NOT NULL:

MATCH p=(v:V)-[:B]->(:K)-[:P * 0..]->(:K{sid:301}) 
return v.sid as sid,1 as tag  
UNION ALL 
MATCH p1=(v1:V)-[:B]->(:K)-[:P * 0..]->(:K{sid:302}) 
return v1.sid as sid,2 as tag

Code branch: master
commit efa45de8980bc78e40bdb7160bcdf4a4c3709660
Date:   Wed Nov 13 19:55:50 2019 +0200

**Comment by swilly22** [comment]
@siphonelee thank you for reporting,
I'm looking into it.

**Comment by swilly22** [comment]
@siphonelee Fix just been merged to the master branch, should be available on docker-hub shortly.
please confirm.
