### ISSUE TITLE
How to query like this without coalesce?

### ISSUE THREAD

**Issue by siphonelee** [RedisGraph/RedisGraph#742]
To calculate the sum while some involving attributes (W1 or W2 below) are missing or null:

match (n:V) return n.sid as id, (n.W1+10*n.W2) as score order by score DESC

**Comment by jeffreylovitz** [comment]
Hi @siphonelee,

Until support for COALESCE is introduced, you can get the same functionality with CASE WHEN statements. This can be a little verbose, so for composability I'm going to also use the WITH clause:
```
MATCH (n:V)
WITH n.sid AS id,
CASE WHEN n.W1 THEN n.W1 ELSE 0 END AS W1,
CASE WHEN n.W2 THEN n.W2 ELSE 0 END AS W2
RETURN id, W1+10*W2 AS score
ORDER BY score DESC
```

**Comment by siphonelee** [comment]
Thanks @jeffreylovitz, it works.
