### ISSUE TITLE
RedisGraph does not support AOF

### ISSUE THREAD

**Issue by botzill** [RedisGraph/RedisGraph#744]
I get this in logs when I try to load the module. Using redis 5.0.6.

Any ideas how to properly load it?

```
1:M 15 Nov 2019 18:37:56.869 # <graph> RedisGraph does not support AOF
1:M 15 Nov 2019 18:37:56.873 # Module /usr/lib/redis/modules/redisgraph.so initialization failed. Module not loaded
```

**Comment by jeffreylovitz** [comment]
Hi @botzill,

What version of the module you're using?

You can check this with the command `redis-cli MODULE LIST`. The version will print as an integer, but corresponds to a semantic version, so `19904` would indicate version 1.99.4.

AOF should be supported starting from version 1.99.3.

**Comment by botzill** [comment]
Hi, thx.

Module is not loaded so I can't see the version, but I do load it from 

```Dockerfile
FROM redislabs/redisgraph as redisgraph
COPY --from=redisgraph /usr/lib/redis/modules/redisgraph.so $LIBDIR
```

**Comment by botzill** [comment]
The other modules were loaded OK:

```bash
module list
1) 1) "name"
   2) "timeseries"
   3) "ver"
   4) (integer) 10003
2) 1) "name"
   2) "ft"
   3) "ver"
   4) (integer) 10417
```

**Comment by botzill** [comment]
I see the issue, I use `latest` but I should be using `1.99.4`.

Thx a lot @jeffreylovitz
