### ISSUE TITLE
Looks like an issue with OPTIONAL MATCH

### ISSUE THREAD

**Issue by siphonelee** [RedisGraph/RedisGraph#746]
With this query:

MATCH (u:U{sid:501}),(v:V{sid:801}) 
return u,v

I can see both u and v exists. But with this query:

OPTIONAL MATCH (u:U{sid:501})-[r:R]->(v:V{sid:801}) 
return u,v

the return result is empty (there's no such R relationship exists). My understanding is it should return the same result as above query.

**Comment by swilly22** [comment]
Hi @siphonelee,
`OPTIONAL MATCH` is not supported at the moment, we should add a validation and report back.

**Comment by siphonelee** [comment]
Thanks @swilly22 .
