### ISSUE TITLE
Advice for loading redisgraph cache

### ISSUE THREAD

**Issue by renewooller** [RedisGraph/RedisGraph#749]
Hi,
We currently have various tables and relationships in mysql and I'm working on caching them in redisgraph. The general approach is to export from MySql into csv and loading using the redisgraph bulk loader into a new key, then rename the keys within a single transaction so that any reads are unaffected.  

I've managed to get six nodes and 3 relationships loading within a suitable amount of time.   However there are still 2 relationships stored in quite large tables  1GB and 3GB that take far longer than the period (eg 5 minutes) that is acceptable in keeping the cache up to date.

Is there any techniques the RedisGraph devs know of that could help?

For example if there was a way to query from one redisgraph key and pipe it immediately back into a different key, ie without causing I/O, I could keep track of the large relationships in a separate graph using particular events, and then efficiently write them in over the top of the newly loaded cache before they keys are renamed. 

Note : ultimately I wouldn't like to have to rely on MySql but instead use the same set of messages that is being used to write to MySql, however there are complications with that route and time is short, so this poll/cache update approach is the interim strategy. 

Cheers,
Rene

**Comment by gkorland** [comment]
The only way to "batch" operations between graphs on the server side is by using LUA script see https://redis.io/commands/eval
