### ISSUE TITLE
Filtering with path pattern not supported yet, any workaround?

### ISSUE THREAD

**Issue by siphonelee** [RedisGraph/RedisGraph#750]
When running:

MATCH (v:V)-[:B]->(:C)<-[:F]-(u:U{sid:501}) 
WHERE NOT (u)-[:R]->(v) 
return v.sid as vid

I got an error saying "RedisGraph currently does not support filtering with path pattern". So is there any workaround to make this negation filter work?

**Comment by swilly22** [comment]
Unfortunately no, this capability should be supported by the end of November.

**Comment by siphonelee** [comment]
Ok, thanks @swilly22 .
