### ISSUE TITLE
UNION not supported

### ISSUE THREAD

**Issue by dandago** [RedisGraph/RedisGraph#753]
[UNION](https://oss.redislabs.com/redisgraph/commands/#union) is in the documentation and I figured I'd try it out. Sure enough I got this result:

> (error) RedisGraph does not currently support UNION

In fact, UNION is listed as [unsupported](https://oss.redislabs.com/redisgraph/cypher_support/#set-operations).

If that's the case, then why is it listed in the docs as an available command?

**Comment by jeffreylovitz** [comment]
Hi @dandago,

UNION is a fairly recent addition to RedisGraph (and it looks like some of the documentation hasn't caught up, as you pointed out - we'll fix that shortly).

It's likely that you're using an older version of RedisGraph! If you're using a Docker image, the `edge` tag will have UNION support; if compiling from source, the master branch will.

**Comment by dandago** [comment]
Hi @jeffreylovitz,

I am using the `edge` tag as far as I can tell. I hope I'm doing it right. Here is the command:

```
sudo docker run -p 6379:6379 -it --rm redislabs/redisgraph:edge
```

**Comment by jeffreylovitz** [comment]
That's the right command! UNION support was added 8 days ago (https://github.com/RedisGraph/RedisGraph/pull/730). Is it possible that you pulled the `edge` tag less recently than that?

If so, the update command would be:
`docker pull redislabs/redisgraph:edge`

**Comment by dandago** [comment]
You are absolutely right! I am in fact quite new to Docker and still learning. I can confirm that `UNION` works. Thank you.

**Comment by dandago** [comment]
Actually, might be worth keeping this open just to remember to update the docs.
