### ISSUE TITLE
issue with Aggregations collect command

### ISSUE THREAD

**Issue by BhanuPrakash531** [RedisGraph/RedisGraph#761]
`localhost:6379> graph.query Test "CREATE (p1:Person{name:'Person1', age:30}), (p2:Person{name:'Person2', age:31}), (p3:Person{name:'Person3', age:32})"
1) 1) "Labels added: 1"
   2) "Nodes created: 3"
   3) "Properties set: 6"
   4) "Query internal execution time: 0.497300 milliseconds"

localhost:6379> graph.query Test "MATCH (p:Person) RETURN p"
1) 1) "p"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person1"
               2) 1) "age"
                  2) (integer) 30
   2) 1) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person2"
               2) 1) "age"
                  2) (integer) 31
   3) 1) 1) 1) "id"
            2) (integer) 2
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person3"
               2) 1) "age"
                  2) (integer) 32
3) 1) "Query internal execution time: 0.322400 milliseconds"

localhost:6379> graph.query Test "MATCH (p:Person) RETURN count(p)"
1) 1) "count(p)"
2) 1) 1) (integer) 3
3) 1) "Query internal execution time: 0.343100 milliseconds"

localhost:6379> graph.query Test "MATCH (p:Person) RETURN collect(p)"
(error) Unknown function 'collect'
localhost:6379> graph.query Test "MATCH (p:Person) RETURN collect(p.name)"
(error) Unknown function 'collect'`
localhost:6379> graph.query Test "MATCH (p:Person) RETURN collect(p.age) as collectage"
(error) Unknown function 'collect'

**Comment by DvirDukhan** [comment]
hi @BhanuPrakash531 
which version of RedisGraph are you using?
I tried your query on `master`
```
127.0.0.1:6379> graph.query Test "MATCH (p:Person) RETURN collect(p.name)"
1) 1) "collect(p.name)"
2) 1) 1) "[Person1, Person2, Person3]"
3) 1) "Query internal execution time: 0.256000 milliseconds"
```

**Comment by BhanuPrakash531** [comment]
**19901**
localhost:6379> module list
1) 1) "name"
   2) "graph"
   3) "ver"
   4) (integer) 19901

**Comment by DvirDukhan** [comment]
@BhanuPrakash531 `collect` is supported by v1.99.2 and up. The current version is v1.99.4. we will release v1.99.5 shortly. You can always clone `master` branch or use docker tagged with `latest` for the latest release, or `edge` for the build composed from `master` branch.
