### ISSUE TITLE
Create empty graph

### ISSUE THREAD

**Issue by mingen-pan** [RedisGraph/RedisGraph#763]
Is there anyway to create an empty graph without inserting any nodes or edges?

**Comment by swilly22** [comment]
@mingen-pan, yes, simply issue a "read" query against a graph ID which doesn't exists.
for example: `GRAPH.QUERY g "RETURN 1"` if `g` doesn't exists it will be created as an empty graph.

**Comment by mingen-pan** [comment]
Cool! Thank you.
