### ISSUE TITLE
Container Crash on UNION ALL and ORDER BY Clause

### ISSUE THREAD

**Issue by BhanuPrakash531** [RedisGraph/RedisGraph#764]
> `localhost:6379> graph.query Test "CREATE (p1:Person{name:'Person1', age:30}), (p2:Person{name:'Person2', age:31}), (p3:Person{name:'Person3', age:32})"`

> `localhost:6379> graph.query Test "MATCH (p:Person{age:30}) RETURN p UNION ALL MATCH(p:Person{age:31}) RETURN p"`

> `localhost:6379> graph.query Test "MATCH (p:Person{age:30}) RETURN p UNION ALL MATCH(p:Person{age:31}) RETURN p ORDER BY p.age ASC"`

**Comment by swilly22** [comment]
Hi @BhanuPrakash531,
Thank you for reporting, a fix should be merged shortly.

**Comment by swilly22** [comment]
@BhanuPrakash531 Fix just been merged to the master branch, should be available on dockerhub shortly, if you can verify, thank you.

**Comment by BhanuPrakash531** [comment]
**ORDER BY** seems to be not working. Or anything wrong I'm doing here? 
> 127.0.0.1:6379> graph.query Test "MATCH (p:Person{age:30}) RETURN p UNION ALL MATCH(p:Person{age:31}) RETURN p ORDER BY p.age ASC"
1) 1) "p"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person1"
               2) 1) "age"
                  2) (integer) 30
  2) 1) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person2"
               2) 1) "age"
                  2) (integer) 31
3) 1) "Query internal execution time: 0.467900 milliseconds"

> 127.0.0.1:6379> graph.query Test "MATCH (p:Person{age:30}) RETURN p UNION ALL MATCH(p:Person{age:31}) RETURN p ORDER BY TOLOWER (p.name)  ASC SKIP 0 LIMIT 19"
1) 1) "p"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person1"
               2) 1) "age"
                  2) (integer) 30
   2) 1) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person2"
               2) 1) "age"
                  2) (integer) 31
3) 1) "Query internal execution time: 0.331200 milliseconds"

> 127.0.0.1:6379> graph.query Test "MATCH (p:Person{age:30}) RETURN p UNION ALL MATCH(p:Person{age:31}) RETURN p ORDER BY p.age  ASC SKIP 0 LIMIT 19"
1) 1) "p"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person1"
               2) 1) "age"
                  2) (integer) 30
   2) 1) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person2"
               2) 1) "age"
                  2) (integer) 31
3) 1) "Query internal execution time: 0.366800 milliseconds"

> 127.0.0.1:6379> graph.query Test "MATCH (p:Person{age:30}) RETURN p UNION ALL MATCH(p:Person{age:31}) RETURN p ORDER BY p.age DESC SKIP 0 LIMIT 19"
1) 1) "p"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person1"
               2) 1) "age"
                  2) (integer) 30
   2) 1) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person2"
               2) 1) "age"
                  2) (integer) 31
3) 1) "Query internal execution time: 0.254600 milliseconds"

> 127.0.0.1:6379> graph.query Test "MATCH (p:Person{age:30}) RETURN p UNION ALL MATCH(p:Person{age:31}) RETURN p ORDER BY TOLOWER (p.name) DESC SKIP 0 LIMIT 19"
1) 1) "p"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person1"
               2) 1) "age"
                  2) (integer) 30
   2) 1) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "Person"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Person2"
               2) 1) "age"
                  2) (integer) 31
3) 1) "Query internal execution time: 0.485500 milliseconds"

**Comment by jeffreylovitz** [comment]
Hi @BhanuPrakash531,

If I understand you correctly, you want to sort the results of the UNION ALL output. This kind of functionality, known as "post-union processing", is actually not a part of the current Cypher version!

This is a [rather long-standing complaint](https://github.com/neo4j/neo4j/issues/2725), and [an updated grammar](https://github.com/petraselmer/openCypher/blob/CIP-nested-subqueries/cip/1.accepted/CIP2016-06-22-nested-updating-and-chained-subqueries.adoc#41-read-only-nested-table-subqueries) has been proposed that will resolve it. Hopefully this will make its way into the Cypher version 10.

The reason that your queries aren't functioning as you expect is that `SKIP`, `LIMIT`, and `ORDER BY` are not stand-alone clauses; they are modifiers that change the behavior of `WITH` and `RETURN` clauses. As such, they only affect the output of the query before or after the `UNION`, rather than affecting the overall output.

A workaround for some cases is to mimic the behavior of `UNION` using the `COLLECT` and `UNWIND` functions [as described here](https://neo4j.com/developer/kb/post-union-processing/).
