### ISSUE TITLE
Deleting many relationships causes redisgraph to hang

### ISSUE THREAD

**Issue by renewooller** [RedisGraph/RedisGraph#771]
I created 50k relationships within 20seconds by using indices on the source and target nodes. 

However when I try to delete all the relationships, RedisGraph consumes all available CPU and becomes unresponsive to other requests for 10+ minutes. 

"GRAPH.QUERY" "nl-tune-yards:devauto:graph" "MATCH (:a)-[ab:ab]->(:b) DELETE ab"

Is there a better way to delete relationships in RedisGraph?

Thanks,
Rene

**Comment by swilly22** [comment]
Hi @renewooller, thank you for reporting!
I believe I found the issue, I'll push a fix shortly, apologise.

**Comment by swilly22** [comment]
Hi @renewooller, a fix just been merged to the master branch, our testing shows a drop down from
72797 milliseconds to just 151 milliseconds when deleting 50000 edges. ~500X improvement this is all thanks to @DvirDukhan, If you can please confirm.

**Comment by renewooller** [comment]
This works now, however getting a problem counting all relationships, I'll report that separately
