### ISSUE TITLE
Any support for UNWIND "nodes from a parameter list" type queries?

### ISSUE THREAD

**Issue by schwab** [RedisGraph/RedisGraph#784]
Consider the following batch delete statement which is able to quickly delete a set of records using an UNWIND list...
```
UNWIND [1,2,3,4,5] as del_id
MATCH (x) WHERE id(x) = del_id
DELETE x
```
This is very nice solution since it cleanly separates the list of items to work on from the MATCH DELETE statement making the creation of the entire batch command very code friendly and it seems to run very fast with large sets of delete lists as well.

However we run into a problem when we attempt to do batch inserts for edges (or nodes ) since we require more than just a single value in the unwind list to generate a proper statement.  In the neo4j version of UNWIND they have support for something called "nodes from a parameter list" in which the UNWIND statement is capable of operating on a list of dictionary values like so... 

```

UNWIND [{'from_id':10, 'to_id':12}, {'from_id':8, 'to_id':23}, ...] AS map
MATCH (x), (y)
WHERE id(x) = map.from_id and id(y) = map.to_id
CREATE (x)-[:link]->[y]

```

The result would be a batch create of all the to/from edges specified in the map.   Is it possible to do this or something like it using redis graph currently?  What work-arounds would be possible and highly-performant?

In my testing, attempts to use any dictionary like syntax in the UNWIND statement failed with 
```
GRAPH.QUERY graph:ortho "WITH [{'id':1},{'id':2},{'id':3},{'id':4}] as d UNWIND d as x RETURN x.id"
"errMsg: Invalid input '\\'': expected a parameter, a property name or '}' line: 1, column: 8, offset: 7 errCtx: WITH [{'id':1},{'id':2},{'id':3},{'id':4}] as d UNWIND d as x RETURN x.id errCtxOffset: 7"
```

Similarly with tuple-like syntax... 

```
GRAPH.QUERY graph:ortho "WITH [(5,1),(9,2)] as d UNWIND d RETURN d"
"errMsg: Invalid input ',': expected '.', AND, OR, XOR, NOT, '=~', '=', '<>', '+', '-', '*', '/', '%', '^', IN, CONTAINS, STARTS WITH, ENDS WITH, '<=', '>=', '<', '>', IS NULL, IS NOT NULL, '[', '{', a label or ')' line: 1, column: 9, offset: 8 errCtx: WITH [(5,1),(9,2)] as d UNWIND d RETURN d errCtxOffset: 8"

**Comment by DvirDukhan** [comment]
hi @schwab 
you can try this (A toy example)
```
127.0.0.1:6379> graph.query g "UNWIND range(0, 23) as x create ()"
1) 1) "Nodes created: 24"
   2) "Query internal execution time: 0.275000 milliseconds"
127.0.0.1:6379> graph.query g "UNWIND [[10,12],[8,23]] as mapping MATCH (x), (y) WHERE id(x) = mapping[0] and id(y) = mapping [0] create (x)-[:link]->(y)"
1) 1) "Relationships created: 2"
   2) "Query internal execution time: 1.519000 milliseconds"
```

**Comment by schwab** [comment]
Ah, list-of-lists.. with indexing.. that will work.  Thank you!

**Comment by DvirDukhan** [comment]
@schwab I'm glad it helped. We are currently not supporting map (dictionary) as a datatype, sorry for that.
