### ISSUE TITLE
Crash when omitting single quotes around string property values

### ISSUE THREAD

**Issue by riney** [RedisGraph/RedisGraph#787]
Hello! The following query works:

```
127.0.0.1:6379> graph.query mygraph "create (:cat {eyes: 2, color: 'blue'})"
1) 1) "Labels added: 1"
   2) "Nodes created: 1"
   3) "Properties set: 2"
   4) "Query internal execution time: 14.939800 milliseconds"
```

But this one results in Redis falling over:

```
127.0.0.1:6379> graph.query mygraph "create (:cat {eyes: 1, color: brown})"
Error: Server closed the connection
```

Seems like this should return an error instead of killing the server.

Redis version: 5.0.7
RedisGraph module version: 19905 (from Docker image redislabs/redisgraph:edge, image id 236d8e796fe8, created: "2 days ago")

**Comment by jeffreylovitz** [comment]
Hi @riney,

You're right, this should emit an error - sorry about that! We're drafting an overhaul to our error-checking logic to make the user experience a lot friendlier; I expect that (which will contain this fix) to be merged within a week.

**Comment by riney** [comment]
@jeffreylovitz Thank you! The performance improvements in RedisGraph 2 are amazing, so it's been well worth the occasional pre-release hiccup.

**Comment by swilly22** [comment]
```
127.0.0.1:6379> graph.query mygraph "create (:cat {eyes: 1, color: brown})"
(error) brown not defined
127.0.0.1:6379>
```
