### ISSUE TITLE
The query caused a crash

### ISSUE THREAD

**Issue by YoJn** [RedisGraph/RedisGraph#799]
## RedisGraph Version

- docker pull redislabs/redisgraph:latest

## data structure

```
Person{
            pid : string
            name : string
            age : int
            job : string
            # A person has 4 friends
            friend : [Person]
        }
```
- I have 200 thousand nodes, 800 thousand edges

- [data.zip](https://github.com/RedisGraph/RedisGraph/files/3943651/data.zip)

- I use redisgraph-bulk-loader import data

## How to reproduce

```cql
match (p:people) where  (p)<-[:relationship]-(:people{pid:1}) or p.job="fxj2oKrUnduT0lk" return p
```

- This will cause  redis to crash

- I noticed that the update date of redisgraph on dockerhub was 3 months ago, is it related to this?

**Comment by DvirDukhan** [comment]
hi @YoJn 
please use `edge` docker tag, as it is aligned with the `master` branch latest additions.
I managed to reproduce your issue with the `latest` tag. On `edge` the flow was:

1. docker run edge
`docker run -p 6379:6379 -it --rm redislabs/redisgraph:edge`

2. loading data:
`python3 bulk_insert.py issue799 -n ~/Downloads/data/people.csv -r ~/Downloads/data/relationship.csv`

3. query and response.
`
127.0.0.1:6379> graph.query issue799 "match (p:people) where  (p)<-[:relationship]-(:people{pid:1}) or p.job='fxj2oKrUnduT0lk' return p"`
`(error) RedisGraph currently does not support filtering with path pattern`


regarding the error response, we are now working support for path patterns filters at #798. Hopefully, it will not take too long to finish it.

**Comment by YoJn** [comment]
hi @DvirDukhan
