### ISSUE TITLE
Malformed query crashes redis

### ISSUE THREAD

**Issue by jinxmcg** [RedisGraph/RedisGraph#802]
Hi, 
The following query works:

_GRAPH.QUERY social "MATCH (u:user)-[w:works]->(e:employer) where **w.since IS NOT NULL** return count(u)_

however by mistake i did not put IS in the IS NOT NULL condition and the container crashed

_GRAPH.QUERY social "MATCH (u:user)-[w:works]->(e:employer) where **w.since NOT NULL** return count(u)_

I have the graph 19907 version

I know is a query typo but i think it should not crash  throw error

Thank you

 === REDIS BUG REPORT START: Cut & paste starting from here ===
nredis | 1:M 11 Dec 2019 14:15:10.128 # Redis 5.0.4 crashed by signal: 11
nredis | 1:M 11 Dec 2019 14:15:10.128 # Crashed running the instruction at: 0x7f29f8d4c529
nredis | 1:M 11 Dec 2019 14:15:10.128 # Accessing address: (nil)
nredis | 1:M 11 Dec 2019 14:15:10.128 # Failed assertion: <no assertion failed> (<no file>:0)
nredis | 
nredis | ------ STACK TRACE ------
nredis | EIP:
nredis | /lib/x86_64-linux-gnu/libc.so.6(abort+0x269)[0x7f29f8d4c529]
nredis | 
nredis | Backtrace:
nredis | redis-server 127.0.0.1:6379(logStackTrace+0x37)[0x55787bf70f87]
nredis | redis-server 127.0.0.1:6379(sigsegvHandler+0xb0)[0x55787bf716b0]
nredis | /lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0)[0x7f29f90c80e0]
nredis | /lib/x86_64-linux-gnu/libc.so.6(abort+0x269)[0x7f29f8d4c529]
nredis | /lib/x86_64-linux-gnu/libc.so.6(+0x2be67)[0x7f29f8d43e67]
nredis | /lib/x86_64-linux-gnu/libc.so.6(+0x2bf12)[0x7f29f8d43f12]
nredis | /usr/lib/redis/modules/redisgraph.so(+0x18f25c)[0x7f29f556525c]
nredis | /usr/lib/redis/modules/redisgraph.so(_CreateFilterSubtree+0x4d)[0x7f29f55652ad]
nredis | /usr/lib/redis/modules/redisgraph.so(_AST_ConvertFilters+0x36b)[0x7f29f55656ab]
nredis | /usr/lib/redis/modules/redisgraph.so(_AST_ConvertFilters+0xe3)[0x7f29f5565423]
nredis | /usr/lib/redis/modules/redisgraph.so(AST_BuildFilterTree+0x62)[0x7f29f5565722]
nredis | /usr/lib/redis/modules/redisgraph.so(+0x170dcb)[0x7f29f5546dcb]
nredis | /usr/lib/redis/modules/redisgraph.so(NewExecutionPlan+0x1a6)[0x7f29f5548046]
nredis | /usr/lib/redis/modules/redisgraph.so(Graph_Query+0x2b0)[0x7f29f5541290]
nredis | /usr/lib/redis/modules/redisgraph.so(+0x199794)[0x7f29f556f794]
nredis | /lib/x86_64-linux-gnu/libpthread.so.0(+0x74a4)[0x7f29f90be4a4]
nredis | /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f29f8e00d0f]
nredis | 
nredis | ------ INFO OUTPUT ------
nredis | # Server
nredis | redis_version:5.0.4
nredis | redis_git_sha1:00000000
nredis | redis_git_dirty:0
nredis | redis_build_id:fb75b7389a142ac3
nredis | redis_mode:standalone
nredis | os:Linux 5.3.0-23-generic x86_64
nredis | arch_bits:64
nredis | multiplexing_api:epoll
nredis | atomicvar_api:atomic-builtin
nredis | gcc_version:6.3.0
nredis | process_id:1
nredis | run_id:c12d6774c00ed93ac5f759ccc07438233ef9cf25
nredis | tcp_port:6379
nredis | uptime_in_seconds:17
nredis | uptime_in_days:0
nredis | hz:10
nredis | configured_hz:10
nredis | lru_clock:15792622
nredis | executable:/data/redis-server
nredis | config_file:/etc/redis.conf
nredis | 
nredis | # Clients
nredis | connected_clients:1
nredis | client_recent_max_input_buffer:2
nredis | client_recent_max_output_buffer:0
nredis | blocked_clients:1
nredis | 
nredis | # Memory
nredis | used_memory:58343728
nredis | used_memory_human:55.64M
nredis | used_memory_rss:66142208
nredis | used_memory_rss_human:63.08M
nredis | used_memory_peak:58355640
nredis | used_memory_peak_human:55.65M
nredis | used_memory_peak_perc:99.98%
nredis | used_memory_overhead:841182
nredis | used_memory_startup:791384
nredis | used_memory_dataset:57502546
nredis | used_memory_dataset_perc:99.91%
nredis | allocator_allocated:58523208
nredis | allocator_active:59478016
nredis | allocator_resident:67674112
nredis | total_system_memory:67107770368
nredis | total_system_memory_human:62.50G
nredis | used_memory_lua:37888
nredis | used_memory_lua_human:37.00K
nredis | used_memory_scripts:0
nredis | used_memory_scripts_human:0B
nredis | number_of_cached_scripts:0
nredis | maxmemory:0
nredis | maxmemory_human:0B
nredis | maxmemory_policy:noeviction
nredis | allocator_frag_ratio:1.02
nredis | allocator_frag_bytes:954808
nredis | allocator_rss_ratio:1.14
nredis | allocator_rss_bytes:8196096
nredis | rss_overhead_ratio:0.98
nredis | rss_overhead_bytes:-1531904
nredis | mem_fragmentation_ratio:1.14
nredis | mem_fragmentation_bytes:7883704
nredis | mem_not_counted_for_evict:0
nredis | mem_replication_backlog:0
nredis | mem_clients_slaves:0
nredis | mem_clients_normal:49694
nredis | mem_aof_buffer:0
nredis | mem_allocator:jemalloc-5.1.0
nredis | active_defrag_running:0
nredis | lazyfree_pending_objects:0
nredis | 
nredis | # Persistence
nredis | loading:0
nredis | rdb_changes_since_last_save:0
nredis | rdb_bgsave_in_progress:0
nredis | rdb_last_save_time:1576073693
nredis | rdb_last_bgsave_status:ok
nredis | rdb_last_bgsave_time_sec:-1
nredis | rdb_current_bgsave_time_sec:-1
nredis | rdb_last_cow_size:0
nredis | aof_enabled:0
nredis | aof_rewrite_in_progress:0
nredis | aof_rewrite_scheduled:0
nredis | aof_last_rewrite_time_sec:-1
nredis | aof_current_rewrite_time_sec:-1
nredis | aof_last_bgrewrite_status:ok
nredis | aof_last_write_status:ok
nredis | aof_last_cow_size:0
nredis | 
nredis | # Stats
nredis | total_connections_received:1
nredis | total_commands_processed:3
nredis | instantaneous_ops_per_sec:0
nredis | total_net_input_bytes:360
nredis | total_net_output_bytes:198
nredis | instantaneous_input_kbps:0.00
nredis | instantaneous_output_kbps:0.00
nredis | rejected_connections:0
nredis | sync_full:0
nredis | sync_partial_ok:0
nredis | sync_partial_err:0
nredis | expired_keys:0
nredis | expired_stale_perc:0.00
nredis | expired_time_cap_reached_count:0
nredis | evicted_keys:0
nredis | keyspace_hits:3
nredis | keyspace_misses:0
nredis | pubsub_channels:0
nredis | pubsub_patterns:0
nredis | latest_fork_usec:0
nredis | migrate_cached_sockets:0
nredis | slave_expires_tracked_keys:0
nredis | active_defrag_hits:0
nredis | active_defrag_misses:0
nredis | active_defrag_key_hits:0
nredis | active_defrag_key_misses:0
nredis | 
nredis | # Replication
nredis | role:master
nredis | connected_slaves:0
nredis | master_replid:3f1ad8e856adf28d2d2a9424af84b247ca3b6a0b
nredis | master_replid2:0000000000000000000000000000000000000000
nredis | master_repl_offset:0
nredis | second_repl_offset:-1
nredis | repl_backlog_active:0
nredis | repl_backlog_size:1048576
nredis | repl_backlog_first_byte_offset:0
nredis | repl_backlog_histlen:0
nredis | 
nredis | # CPU
nredis | used_cpu_sys:1.261833
nredis | used_cpu_user:4.285955
nredis | used_cpu_sys_children:0.000000
nredis | used_cpu_user_children:0.000000
nredis | 
nredis | # Commandstats
nredis | cmdstat_graph.QUERY:calls=3,usec=126,usec_per_call=42.00
nredis | 
nredis | # Cluster
nredis | cluster_enabled:0
nredis | 
nredis | # Keyspace
nredis | db0:keys=1,expires=0,avg_ttl=0
nredis | 
nredis | ------ CLIENT LIST OUTPUT ------
nredis | id=6 addr=127.0.0.1:51592 fd=7 name= age=11 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY
nredis | 
nredis | ------ REGISTERS ------
nredis | 1:M 11 Dec 2019 14:15:10.131 # 
nredis | RAX:0000000000000006 RBX:00007f29f9df7000
nredis | RCX:00007f29f8d4afff RDX:0000000000000000
nredis | RDI:0000000000000002 RSI:00007f29f39a2fa0
nredis | RBP:00007f29f5b91244 RSP:00007f29f39a30b0
nredis | R8 :0000000000000000 R9 :00007f29f39a2fa0
nredis | R10:0000000000000008 R11:0000000000000246
nredis | R12:00000000000000dc R13:00007f29f5b98a40
nredis | R14:0000000000000002 R15:00007f29dce1f000
nredis | RIP:00007f29f8d4c529 EFL:0000000000010246
nredis | CSGSFS:002b000000000033
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30bf) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30be) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30bd) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30bc) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30bb) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30ba) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30b9) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30b8) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30b7) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30b6) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30b5) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30b4) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30b3) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30b2) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30b1) -> 0000000000000000
nredis | 1:M 11 Dec 2019 14:15:10.131 # (00007f29f39a30b0) -> 0000000000000020
nredis | 
nredis | ------ FAST MEMORY TEST ------
nredis | 1:M 11 Dec 2019 14:15:10.132 # Bio thread for job type #0 terminated
nredis | 1:M 11 Dec 2019 14:15:10.132 # Bio thread for job type #1 terminated
nredis | 1:M 11 Dec 2019 14:15:10.132 # Bio thread for job type #2 terminated
nredis | *** Preparing to test memory region 55787c2a6000 (2248704 bytes)
nredis | *** Preparing to test memory region 55787d1b6000 (135168 bytes)
nredis | *** Preparing to test memory region 7f29c8000000 (135168 bytes)
nredis | *** Preparing to test memory region 7f29d0000000 (2113536 bytes)
nredis | *** Preparing to test memory region 7f29d4000000 (2113536 bytes)
nredis | *** Preparing to test memory region 7f29d8000000 (135168 bytes)
nredis | *** Preparing to test memory region 7f29dce00000 (12582912 bytes)
nredis | *** Preparing to test memory region 7f29dda6d000 (58195968 bytes)
nredis | *** Preparing to test memory region 7f29e11ee000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e19ef000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e21f0000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e29f1000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e31f2000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e39f3000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e41f4000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e49f5000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e51f6000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e59f7000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e61f8000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e69f9000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e71fa000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e79fb000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e81fc000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e89fd000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e91fe000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29e99ff000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29ea200000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29eaa00000 (5767168 bytes)
nredis | *** Preparing to test memory region 7f29eb196000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29eb997000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29ec198000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29ec999000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29ed19a000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29ed99b000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29ee19c000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29ee99d000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29ef19e000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29ef99f000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f01a0000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f09a1000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f11a2000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f19a3000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f21a4000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f29a5000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f31a6000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f39a7000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f41a8000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f49a9000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f5fbe000 (12288 bytes)
nredis | *** Preparing to test memory region 7f29f63f9000 (12288 bytes)
nredis | *** Preparing to test memory region 7f29f63fd000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f6bfe000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f73ff000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f7c00000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f8400000 (8388608 bytes)
nredis | *** Preparing to test memory region 7f29f90b3000 (16384 bytes)
nredis | *** Preparing to test memory region 7f29f92d0000 (16384 bytes)
nredis | *** Preparing to test memory region 7f29f9df7000 (4096 bytes)
nredis | *** Preparing to test memory region 7f29f9e3b000 (24576 bytes)
nredis | *** Preparing to test memory region 7f29f9e44000 (8192 bytes)
nredis | *** Preparing to test memory region 7f29f9e48000 (4096 bytes)

**Comment by swilly22** [comment]
@jinxmcg thank you for reporting, we'll have a fix shortly.
