### ISSUE TITLE
Redis crashing with RedisGraph when using MATCH ** CREATE ** Commands

### ISSUE THREAD

**Issue by orenlandau** [RedisGraph/RedisGraph#817]
The following command caused the Redis/shard to crash.
It was observed on both Docker instance and Redis Enterprise cluster.

127.0.0.1:6379> GRAPH.QUERY some "MATCH ( a:Policy {externalId:'POL0000001'}), (b:Party { externalId:'PTY0000001_OWR'}), (b)-[r]->(a) WHERE r.relationshipKey <> '2B80955F-7C1C-4422-B34E-2BEA8D82A4DF' CREATE (b) -[r:PartyPolicyRelation {relationshipKey:'2B80955F-7C1C-4422-B34E-2BEA8D82A4DF', roleCode:'OWR',primaryOwner:'Y', startDate:123123123, expiryDate:123123123}] -> (a)"
Could not connect to Redis at 127.0.0.1:6379: Connection refused

The following command worked well:

GRAPH.QUERY some "MATCH (a:Party { externalId:'PTY0000001_OWR'})-[r]->(b:Policy {externalId:'POL0000001'}) WHERE r.relationshipKey <> '2B80955F-7C1C-4422-B34E-2BEA8D82A4DF' CREATE (a)-[:PartyPolicyRelation {relationshipKey:'2B80955F-7C1C-4422-B34E-2BEA8D82A4DF', roleCode:'OWR',primaryOwner:'Y', startDate:123123123, expiryDate:123123123}]->(b)"

Local Docker Stack Trace
------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7fddcbc32611]

Backtrace:
redis-server *:6379(logStackTrace+0x32)[0x557456967112]
redis-server *:6379(sigsegvHandler+0x9e)[0x5574569677ee]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7fddcbde3730]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7fddcbc32611]
/lib/x86_64-linux-gnu/libc.so.6(+0x2240f)[0x7fddcbc3240f]
/lib/x86_64-linux-gnu/libc.so.6(+0x30102)[0x7fddcbc40102]
/usr/lib/redis/modules/redisgraph.so(QueryGraph_AddPath+0x44a)[0x7fddc99100ca]
/usr/lib/redis/modules/redisgraph.so(AST_PrepareCreateOp+0x1e5)[0x7fddc991a265]
/usr/lib/redis/modules/redisgraph.so(+0xba0d6)[0x7fddc98ff0d6]
/usr/lib/redis/modules/redisgraph.so(NewExecutionPlan+0xb6)[0x7fddc98ffe06]
/usr/lib/redis/modules/redisgraph.so(_MGraph_Query+0x3ee)[0x7fddc98fb20e]
/usr/lib/redis/modules/redisgraph.so(+0xdac2d)[0x7fddc991fc2d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7fddcbdd8fa3]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fddcbd094cf]

------ INFO OUTPUT ------
# Server
redis_version:5.0.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:442b43d467cd2b03
redis_mode:standalone
os:Linux 4.9.184-linuxkit x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0
process_id:1
run_id:d1cb09816c063f98ae43a7db2da8e3955b2caeab
tcp_port:6379
uptime_in_seconds:3
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:15748034
executable:/data/redis-server
config_file:

# Clients
connected_clients:1
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:1

# Memory
used_memory:1853960
used_memory_human:1.77M
used_memory_rss:6328320
used_memory_rss_human:6.04M
used_memory_peak:1853960
used_memory_peak_human:1.77M
used_memory_peak_perc:225.83%
used_memory_overhead:841126
used_memory_startup:791360
used_memory_dataset:1012834
used_memory_dataset_perc:95.32%
allocator_allocated:1041456
allocator_active:1220608
allocator_resident:3735552
total_system_memory:2095968256
total_system_memory_human:1.95G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.17
allocator_frag_bytes:179152
allocator_rss_ratio:3.06
allocator_rss_bytes:2514944
rss_overhead_ratio:1.69
rss_overhead_bytes:2592768
mem_fragmentation_ratio:7.71
mem_fragmentation_bytes:5507384
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:49694
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:1
rdb_bgsave_in_progress:0
rdb_last_save_time:1576029119
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:1
total_commands_processed:1
instantaneous_ops_per_sec:0
total_net_input_bytes:370
total_net_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:82d7057807299a695421891826b7321919d5dddc
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.010000
used_cpu_user:0.060000
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Commandstats
cmdstat_graph.QUERY:calls=1,usec=57,usec_per_call=57.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=4 addr=172.17.0.1:46212 fd=8 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY

------ REGISTERS ------
1:M 11 Dec 2019 01:52:02.465 #
RAX:0000000000000000 RBX:0000000000000000
RCX:0000000000000000 RDX:0000000000000000
RDI:0000000000000002 RSI:00007fddc9841cf0
RBP:00007fddcbd94ee0 RSP:00007fddc9841e10
R8 :0000000000000000 R9 :00007fddc9841cf0
R10:0000000000000008 R11:0000000000000246
R12:00007fddc9a68df8 R13:00007fddc9a68e20
R14:0000000000000044 R15:00007fddc741e0a0
RIP:00007fddcbc32611 EFL:0000000000010246
CSGSFS:002b000000000033
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e1f) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e1e) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e1d) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e1c) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e1b) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e1a) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e19) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e18) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e17) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e16) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e15) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e14) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.465 # (00007fddc9841e13) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.466 # (00007fddc9841e12) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.466 # (00007fddc9841e11) -> 0000000000000000
1:M 11 Dec 2019 01:52:02.466 # (00007fddc9841e10) -> 0000000000000020

------ FAST MEMORY TEST ------
1:M 11 Dec 2019 01:52:02.466 # Bio thread for job type #0 terminated
1:M 11 Dec 2019 01:52:02.466 # Bio thread for job type #1 terminated
1:M 11 Dec 2019 01:52:02.467 # Bio thread for job type #2 terminated
*** Preparing to test memory region 557456a94000 (2248704 bytes)
*** Preparing to test memory region 5574576da000 (135168 bytes)
*** Preparing to test memory region 7fddc0000000 (417792 bytes)
*** Preparing to test memory region 7fddc7400000 (4194304 bytes)
*** Preparing to test memory region 7fddc7842000 (8388608 bytes)
*** Preparing to test memory region 7fddc8043000 (8388608 bytes)
*** Preparing to test memory region 7fddc8844000 (8388608 bytes)
*** Preparing to test memory region 7fddc9045000 (8388608 bytes)
*** Preparing to test memory region 7fddc9bfa000 (12288 bytes)
*** Preparing to test memory region 7fddc9bfe000 (8388608 bytes)
*** Preparing to test memory region 7fddca3ff000 (8388608 bytes)
*** Preparing to test memory region 7fddcac00000 (8388608 bytes)
*** Preparing to test memory region 7fddcb400000 (8388608 bytes)
*** Preparing to test memory region 7fddcbc0a000 (24576 bytes)
*** Preparing to test memory region 7fddcbdcd000 (16384 bytes)
*** Preparing to test memory region 7fddcbdee000 (16384 bytes)
*** Preparing to test memory region 7fddcbf84000 (8192 bytes)
*** Preparing to test memory region 7fddcbf87000 (4096 bytes)
*** Preparing to test memory region 7fddcbfb1000 (4096 bytes)
.O.O.O.O.O.O.O.

**Comment by swilly22** [comment]
Hi @orenlandau, thank you for reporting.
We'll introduce a validation in the next couple of days, the query which crashes is invalid as `r` is already declared by the MATCH clause.

**Comment by jeffreylovitz** [comment]
Hi @orenlandau,

This query should raise a syntax error now - can you confirm?
