### ISSUE TITLE
MATCH (u:node_label) WHERE ID(u)>0 disregards node_label

### ISSUE THREAD

**Issue by jinxmcg** [RedisGraph/RedisGraph#818]
Hi, 

I do not know if this is expected behaviour or not, consider the following queries:

````
127.0.0.1:6379> GRAPH.QUERY graphdb "MATCH (u:user) where id(u)>0 and labels(u)='user' return count(u)"
1) 1) "count(u)"
2) 1) 1) (integer) 1531
3) 1) "Query internal execution time: 7.028319 milliseconds"

127.0.0.1:6379> GRAPH.QUERY graphdb "MATCH (u:user) where id(u)>0 return count(u)"
1) 1) "count(u)"
2) 1) 1) (integer) 7308
3) 1) "Query internal execution time: 3.491876 milliseconds"
````

The first query returns the correct number of results as we double specified in the WHERE clause that we want label user, however in the second the u:user is disregarded and return all nodes with id>0.

I believe it should return the same like the first.
Any ideas?

(Also quick question is it safe to use the ID of the node generated by REDIS GRAPH in my app, are they mutable? or reused if I delete a node it will be reassigned?)

Thanks

**Comment by DvirDukhan** [comment]
@jinxmcg work in progress. I'll update once it is fixed

**Comment by DvirDukhan** [comment]
@jinxmcg please confirm #819 solves the issue

**Comment by jinxmcg** [comment]
Yes it works and is faster:
```
127.0.0.1:6379> GRAPH.QUERY graphdb "MATCH (u:user) where id(u)>0 and labels(u)='user' return count(u)"
1) 1) "count(u)"
2) 1) 1) (integer) 1531
3) 1) "Query internal execution time: 4.580645 milliseconds"
127.0.0.1:6379> GRAPH.QUERY graphdb "MATCH (u:user) where id(u)>0 return count(u)"
1) 1) "count(u)"
2) 1) 1) (integer) 1531
3) 1) "Query internal execution time: 1.428785 milliseconds"
```
