### ISSUE TITLE
Crash while creating many relationships

### ISSUE THREAD

**Issue by renewooller** [RedisGraph/RedisGraph#831]
I'm not sure why this crash occured - I'd been running many of these commands pipelining them 50 at a time. After an hour or so of this, redisgraph crashed.

Query example:

`MATCH (song_5a92fe241f:song {filename : <redacted>}),(song_c0883ebf12:song {filename : <redacted>}),(song_bdd4e2f188:song {filename : <redacted>}),(song_5d969f81e4:song {filename : <redacted>}),(song_93d793b39c:song {filename : <redacted>}),(song_2f36d204c8:song {filename : <redacted>}),(song_f2d303c09e:song {filename : <redacted>}),(song_f0bcd97b53:song {filename : <redacted>}),(song_82b2b342e1:song {filename : <redacted>}),(song_bc7c570ce1:song {filename : <redacted>}),(song_b2ef4ed848:song {filename : <redacted>}),(song_1f0bc59b81:song {filename : <redacted>}),(song_92f7a8832e:song {filename : <redacted>}),(song_708738f543:song {filename : <redacted>}),(song_2c61ed8705:song {filename : <redacted>}),(song_db10e80365:song {filename : <redacted>}),(song_53682570cc:song {filename : <redacted>}),(song_cfd1dc0d79:song {filename : <redacted>}),(song_e73e71d300:song {filename : <redacted>}),(song_dfdf1496e9:song {filename : <redacted>}),(song_bd0e7ce346:song {filename : <redacted>}),(song_88b351e770:song {filename : <redacted>}),(song_5372999cef:song {filename : <redacted>}),(song_3faabfa504:song {filename : <redacted>}),(song_0f5b31fd37:song {filename : <redacted>}),(song_aa8762c034:song {filename : <redacted>}),(song_10352c8393:song {filename : <redacted>}),(song_ee1e59ac5d:song {filename : <redacted>}),(song_1601760be4:song {filename : <redacted>}),(song_9def4f0e80:song {filename : <redacted>}),(song_4443c73f2b:song {filename : <redacted>}),(song_52cc027cf7:song {filename : <redacted>}),(song_ca24c02187:song {filename : <redacted>}),(song_9cc3fe7172:song {filename : <redacted>}),(song_37bc09e6ab:song {filename : <redacted>}),(song_acaf1a550e:song {filename : <redacted>}),(song_95c00f08b4:song {filename : <redacted>}),(song_dc4fcdf350:song {filename : <redacted>}),(song_bc222e18f7:song {filename : <redacted>}),(song_0b4f3f23ca:song {filename : <redacted>}),(song_9419daecb2:song {filename : <redacted>}),(song_a1e8a745ae:song {filename : <redacted>}),(song_60aa77a3b4:song {filename : <redacted>}),(song_2e57596fc3:song {filename : <redacted>}),(song_8066049899:song {filename : <redacted>}),(song_50d5cee886:song {filename : <redacted>}),(song_fead4f4b54:song {filename : <redacted>}),(song_67fbb2e8e0:song {filename : <redacted>}),(song_5898d26c62:song {filename : <redacted>}),(song_15147d38b1:song {filename : <redacted>}),(system_zone_d8ac5e8cb9:system_zone {syszone : '<redacted>'}) CREATE (song_5a92fe241f)-[created0:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_c0883ebf12)-[created1:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_bdd4e2f188)-[created2:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_5d969f81e4)-[created3:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_93d793b39c)-[created4:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_2f36d204c8)-[created5:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_f2d303c09e)-[created6:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_f0bcd97b53)-[created7:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_82b2b342e1)-[created8:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_bc7c570ce1)-[created9:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_b2ef4ed848)-[created10:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_1f0bc59b81)-[created11:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_92f7a8832e)-[created12:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_708738f543)-[created13:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_2c61ed8705)-[created14:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_db10e80365)-[created15:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_53682570cc)-[created16:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_cfd1dc0d79)-[created17:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_e73e71d300)-[created18:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_dfdf1496e9)-[created19:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_bd0e7ce346)-[created20:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_88b351e770)-[created21:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_5372999cef)-[created22:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_3faabfa504)-[created23:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_0f5b31fd37)-[created24:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_aa8762c034)-[created25:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_10352c8393)-[created26:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_ee1e59ac5d)-[created27:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_1601760be4)-[created28:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_9def4f0e80)-[created29:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_4443c73f2b)-[created30:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_52cc027cf7)-[created31:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_ca24c02187)-[created32:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_9cc3fe7172)-[created33:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_37bc09e6ab)-[created34:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_acaf1a550e)-[created35:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_95c00f08b4)-[created36:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_dc4fcdf350)-[created37:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_bc222e18f7)-[created38:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_0b4f3f23ca)-[created39:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_9419daecb2)-[created40:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_a1e8a745ae)-[created41:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_60aa77a3b4)-[created42:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_2e57596fc3)-[created43:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_8066049899)-[created44:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_50d5cee886)-[created45:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_fead4f4b54)-[created46:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_67fbb2e8e0)-[created47:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_5898d26c62)-[created48:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9),(song_15147d38b1)-[created49:SONG_ON_ZONE {removed : 1,hidden : 0}]->(system_zone_d8ac5e8cb9)`

Crash:

```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 18 Dec 2019 04:11:51.855 # Redis 5.0.7 crashed by signal: 11
1:M 18 Dec 2019 04:11:51.855 # Crashed running the instruction at: 0x7f21538f1e6e
1:M 18 Dec 2019 04:11:51.855 # Accessing address: 0x10
1:M 18 Dec 2019 04:11:51.855 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/usr/lib/redis/modules/redisgraph.so(IndexSpec_GetField+0xe)[0x7f21538f1e6e]

Backtrace:
redis-server *:6379(logStackTrace+0x32)[0x555d554b7572]
redis-server *:6379(sigsegvHandler+0x9e)[0x555d554b7c4e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7f21546d3730]
/usr/lib/redis/modules/redisgraph.so(IndexSpec_GetField+0xe)[0x7f21538f1e6e]
/usr/lib/redis/modules/redisgraph.so(IndexSpec_GetFieldBit+0x9)[0x7f21538f1f69]
/usr/lib/redis/modules/redisgraph.so(RediSearch_CreateTagNode+0x48)[0x7f21538f0788]
/usr/lib/redis/modules/redisgraph.so(_StringRangeToQueryNode+0x23)[0x7f21533b37d3]
/usr/lib/redis/modules/redisgraph.so(reduce_scan_op+0x20a)[0x7f21533b429a]
/usr/lib/redis/modules/redisgraph.so(utilizeIndices+0x6f)[0x7f21533b466f]
/usr/lib/redis/modules/redisgraph.so(optimizePlan+0x11)[0x7f21533b34e1]
/usr/lib/redis/modules/redisgraph.so(NewExecutionPlan+0x28c)[0x7f21533a6d3c]
/usr/lib/redis/modules/redisgraph.so(Graph_Query+0x2f6)[0x7f21533a1776]
/usr/lib/redis/modules/redisgraph.so(+0x193fed)[0x7f21533cbfed]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7f21546c8fa3]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f21545f94cf]

------ INFO OUTPUT ------
# Server
redis_version:5.0.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:7359662505fc6f11
redis_mode:standalone
os:Linux 4.14.154-128.181.amzn2.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0
process_id:1
run_id:1cf9e1c40765ed867b698e675922c67271d0d74c
tcp_port:6379
uptime_in_seconds:192436
uptime_in_days:2
hz:10
configured_hz:10
lru_clock:16361223
executable:/data/redis-server
config_file:

# Clients
connected_clients:4
client_recent_max_input_buffer:835980
client_recent_max_output_buffer:0
blocked_clients:2

# Memory
used_memory:1429713808
used_memory_human:1.33G
used_memory_rss:1320075264
used_memory_rss_human:1.23G
used_memory_peak:1462675880
used_memory_peak_human:1.36G
used_memory_peak_perc:97.75%
used_memory_overhead:1078571
used_memory_startup:824144
used_memory_dataset:1428635237
used_memory_dataset_perc:99.98%
allocator_allocated:1456872008
allocator_active:1472086016
allocator_resident:1490518016
total_system_memory:3884974080
total_system_memory_human:3.62G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.01
allocator_frag_bytes:15214008
allocator_rss_ratio:1.01
allocator_rss_bytes:18432000
rss_overhead_ratio:0.89
rss_overhead_bytes:-170442752
mem_fragmentation_ratio:0.91
mem_fragmentation_bytes:-136667576
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:254219
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:83751
rdb_bgsave_in_progress:0
rdb_last_save_time:1576449875
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:35
total_commands_processed:94560
instantaneous_ops_per_sec:134
total_net_input_bytes:789099608
total_net_output_bytes:19500173
instantaneous_input_kbps:1051.58
instantaneous_output_kbps:16.24
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:167490
keyspace_misses:15
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:3263143e11f54f8de790be2d0ab3414c4451864b
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:109.011010
used_cpu_user:126809.475468
used_cpu_sys_children:0.000000
used_cpu_user_children:0.002344

# Commandstats
cmdstat_client:calls=8829,usec=68699,usec_per_call=7.78
cmdstat_keys:calls=4,usec=46,usec_per_call=11.50
cmdstat_latency:calls=1,usec=33,usec_per_call=33.00
cmdstat_ping:calls=4,usec=3,usec_per_call=0.75
cmdstat_slowlog:calls=2,usec=95,usec_per_call=47.50
cmdstat_graph.BULK:calls=18,usec=32818882,usec_per_call=1823271.25
cmdstat_graph.QUERY:calls=83744,usec=1224712,usec_per_call=14.62
cmdstat_scan:calls=12,usec=104,usec_per_call=8.67
cmdstat_exists:calls=9,usec=19,usec_per_call=2.11
cmdstat_set:calls=3,usec=18,usec_per_call=6.00
cmdstat_del:calls=2,usec=4,usec_per_call=2.00
cmdstat_select:calls=1,usec=2,usec_per_call=2.00
cmdstat_config:calls=3,usec=154,usec_per_call=51.33
cmdstat_get:calls=4,usec=5,usec_per_call=1.25
cmdstat_command:calls=4,usec=3109,usec_per_call=777.25
cmdstat_type:calls=15,usec=26,usec_per_call=1.73
cmdstat_flushall:calls=2,usec=44,usec_per_call=22.00
cmdstat_module:calls=29,usec=122,usec_per_call=4.21
cmdstat_info:calls=1868,usec=109350,usec_per_call=58.54
cmdstat_graph.EXPLAIN:calls=6,usec=1187,usec_per_call=197.83

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=3,expires=1,avg_ttl=28692102850

------ CLIENT LIST OUTPUT ------
id=74281 addr=10.10.35.194:51114 fd=11 name= age=107902 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=186523 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY
id=148295 addr=10.10.35.194:49180 fd=9 name= age=10614 idle=10614 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=info
id=148310 addr=10.10.35.194:49202 fd=10 name= age=10604 idle=10604 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=info
id=161374 addr=192.168.2.54:61591 fd=8 name=RedisInsight age=26 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY

------ REGISTERS ------
1:M 18 Dec 2019 04:11:51.863 # 
RAX:0000000000000008 RBX:00007f20fb986680
RCX:0000000000000000 RDX:0000000000000008
RDI:0000000000000000 RSI:00007f2152a34000
RBP:00007f2152a34000 RSP:00007f2152a33d10
R8 :00007f2152a33e50 R9 :000000000000002a
R10:0000000000000000 R11:00007f2152a34fb8
R12:0000000000000000 R13:00007f2152a34000
R14:00007f20fb702cb0 R15:00007f20fb702cd0
RIP:00007f21538f1e6e EFL:0000000000010202
CSGSFS:002b000000000033
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d1f) -> 00007f21533b37d3
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d1e) -> 0000000000000000
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d1d) -> 00007f20fb74dfb8
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d1c) -> 00007f20fb74dfb8
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d1b) -> 00007f21538f0788
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d1a) -> 00007f2152a34000
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d19) -> 00007f21538f1f69
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d18) -> 00007f20fb702cd0
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d17) -> 00007f20fb702cb0
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d16) -> 00007f2152a34000
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d15) -> 0000000000000000
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d14) -> 00007f2152a34000
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d13) -> 00007f20fb986680
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d12) -> 0000000000000009
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d11) -> 00007f211a21a0c0
1:M 18 Dec 2019 04:11:51.863 # (00007f2152a33d10) -> 00007f2152a34000

------ FAST MEMORY TEST ------
1:M 18 Dec 2019 04:11:51.863 # Bio thread for job type #0 terminated
1:M 18 Dec 2019 04:11:51.863 # Bio thread for job type #1 terminated
1:M 18 Dec 2019 04:11:51.863 # Bio thread for job type #2 terminated
*** Preparing to test memory region 555d555e5000 (2248704 bytes)
*** Preparing to test memory region 555d57228000 (135168 bytes)
*** Preparing to test memory region 7f20d4e00000 (121634816 bytes)
*** Preparing to test memory region 7f20dc3ff000 (360710144 bytes)
*** Preparing to test memory region 7f20f1c00000 (8388608 bytes)
*** Preparing to test memory region 7f20f2400000 (435032064 bytes)
*** Preparing to test memory region 7f2110300000 (66981888 bytes)
*** Preparing to test memory region 7f21180ff000 (13631488 bytes)
*** Preparing to test memory region 7f2118e00000 (8388608 bytes)
*** Preparing to test memory region 7f2119600000 (631242752 bytes)
*** Preparing to test memory region 7f213f0b2000 (218103808 bytes)
*** Preparing to test memory region 7f214c0b3000 (8388608 bytes)
*** Preparing to test memory region 7f214c8b3000 (68681728 bytes)
*** Preparing to test memory region 7f2150a34000 (8388608 bytes)
*** Preparing to test memory region 7f2151235000 (8388608 bytes)
*** Preparing to test memory region 7f2151a36000 (8388608 bytes)
*** Preparing to test memory region 7f2152237000 (8388608 bytes)
*** Preparing to test memory region 7f2152a38000 (8388608 bytes)
*** Preparing to test memory region 7f2153bfd000 (12288 bytes)
*** Preparing to test memory region 7f2153c00000 (8388608 bytes)
*** Preparing to test memory region 7f21544fa000 (24576 bytes)
*** Preparing to test memory region 7f21546bd000 (16384 bytes)
*** Preparing to test memory region 7f21546de000 (16384 bytes)
*** Preparing to test memory region 7f2154874000 (8192 bytes)
*** Preparing to test memory region 7f21548a1000 (4096 bytes)
```

**Comment by jrozentur** [comment]
Same here, in official docker image created a million and half simple nodes, updated every node, created ~ 30k simple relationships -> crash. Happened fast, maybe 10 min into the run

**Comment by renewooller** [comment]
probably OOM as well
