### ISSUE TITLE
How do I match a node where it or its child contains a keyword?

### ISSUE THREAD

**Issue by mingen-pan** [RedisGraph/RedisGraph#833]
I have a node `(a:Parent {name: 'ABC'})`. It may or may not have a child `(b:Child {name: 'CDE'})`. If a child exists, their relationship is `--[:Has]-->`.

How can I write a cypher to return a node if it or its child contains keyword in their `name` field? Thank you.

**Comment by jeffreylovitz** [comment]
Hi @mingen-pan ,

One option is to use a variable-length traversal with a lower bound of 0:
`MATCH (a:Parent)-[:HAS*0..1]->(b:Child) WHERE a.name = 'keyword' OR b.name = 'keyword' RETURN a`

We'll soon introduce path filtering, which would be another way to achieve this!

**Comment by mingen-pan** [comment]
Thank you @jeffreylovitz . I realize this query will return two identical nodes of `Parent` if the condition `a.name` is matched. Is this designed in this way?

For example, query `MATCH (a:Parent)-[:HAS*0..1]->(b:Child) WHERE a.name contains 'A' OR b.name contains 'A' RETURN a` will return two `(a: Parent {name: 'ABC'})` with the same `id`, given the nodes I mentioned above.

**Comment by jeffreylovitz** [comment]
`RETURN` doesn't automatically unique the outputs, so the same entity `a` will be outputted once for every match, even if you're only returning one element of that match. To return it only once, you can specify `DISTINCT`:
`MATCH (a:Parent)-[:HAS*0..1]->(b:Child) WHERE a.name contains 'A' OR b.name contains 'A' RETURN DISTINCT a`

**Comment by DvirDukhan** [comment]
@mingen-pan in addition to @jeffreylovitz response, we are working now on enabling filtering according to patterns. The PR #798 is currently in "Work In Progress" status, and I hope it will be merged very soon. 
For your example (executed on my machine):
```
127.0.0.1:6379> graph.query g "CREATE (:Parent {name:'ABC'}), (:Parent)-[:HAS]->(:Child {name:'ABC'})"
1) 1) "Labels added: 2"
   2) "Nodes created: 3"
   3) "Properties set: 2"
   4) "Relationships created: 1"
   5) "Query internal execution time: 1.375000 milliseconds"
```
and the query is
```
127.0.0.1:6379> graph.query g "MATCH (a:Parent) WHERE a.name='ABC' or (a)-[:HAS]->(:Child {name:'ABC'}) RETURN DISTINCT a"
1) 1) "a"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "Parent"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "ABC"
   2) 1) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "Parent"
         3) 1) "properties"
            2) (empty list or set)
3) 1) "Query internal execution time: 0.588000 milliseconds"
```

**Comment by mingen-pan** [comment]
Thanks a lot @jeffreylovitz @DvirDukhan !
