### ISSUE TITLE
Qs with fuzzy query

### ISSUE THREAD

**Issue by s506795003** [RedisGraph/RedisGraph#853]
Dear Sir
Im trying to use redisgraph with my data and the version is download from docker directly.
However, when I try to do some fuzzy search query like 'match (m) where m.id =~ "aaa" return m', he told me RedisGraph does not currently support =~. Also, it can not work with query using 'like ', the way we use in mysql.
How could I do some fuzzy query in redisgraph, could u help me with that.
Or it can not de fuzzy query now?
Thanks

**Comment by DvirDukhan** [comment]
hi @s506795003 
we do not support regex right now
you can try to use built in strings functions such as START WITH, left, right etc...

**Comment by swilly22** [comment]
Hi @s506795003, sorry for my late response
In case you've created a full-text index over the in-query attributes you'll be able to use our index to perform fuzzy matching

See:
1. [full-text index creation](https://oss.redislabs.com/redisgraph/commands/#full-text-indexes)
2. [fuzzy matching query](https://oss.redislabs.com/redisearch/Query_Syntax.html#fuzzy_matching)

**Comment by s506795003** [comment]
Thanks 
But I still got some qs, could you help me with this.

1. About the full-text index creation I have tried it and it works well. But I did not find some way to change the index from the documentation. eg. I set an index with label(text) and properties in sampleContent. (GRAPH.QUERY test "CALL db.idx.fulltext.createNodeIndex('text', 'sampleContent')"), After that, if I wanna change the nodes' index to another properties like title, I do (GRAPH.QUERY test "CALL db.idx.fulltext.createNodeIndex('text', 'title')"). But it not work

2. About how to using %content% in your link is not very clear. Count you give me an example of that which will helps me a lot. 
Thankes
@swilly22

**Comment by swilly22** [comment]
You can remove a full-text index with: `call db.idx.fulltext.drop('text')`
And so if you start out with a full-text index over text: sampleContent and would like to update the index to include only text:sampleContent then remove your current index and re-create it.

2.  Given a full-text index over the label `movie` and its `title` attribute `db.idx.fulltext.queryNodes('movie', '%Book%')` will find all movies with a title 1 [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) away from `Book`

**Comment by s506795003** [comment]
Here is my search result, is it correct?
I search by word sina.com and got 30k nodes. However, only 42 nodes got by search %si%. 
So how does the %% works?

GRAPH.QUERY kg_test "CALL db.idx.fulltext.queryNodes('ping2lun4', 'sina.com') YIELD node RETURN count(node)"
1) 1) "count(node)"
2) 1) 1) (integer) 30821

"Query internal execution time: 13.614765 milliseconds"
127.0.0.1:6379> GRAPH.QUERY kg_test "CALL db.idx.fulltext.queryNodes('ping2lun4', '%si%') YIELD node RETURN count(node)"
1) 1) "count(node)"
2) 1) 1) (integer) 42

**Comment by MeirShpilraien** [comment]
@s506795003 if you use `%` you ask for LD of 1 (https://en.wikipedia.org/wiki/Levenshtein_distance) which means that it will return terms which are in LD of 1 from `si` (like `ki` or `sj` for example). If you want prefix search you need to do `si*`

**Comment by s506795003** [comment]
thanks I got it
