### ISSUE TITLE
DISTINCT in WITH clause not being honored unless another modifier is present

### ISSUE THREAD

**Issue by mdecuir** [RedisGraph/RedisGraph#863]
It appears that the DISTINCT modifier is not honored in a WITH clause unless another modifier is present.

```
MATCH (n:node)
WITH DISTINCT n as n2
RETURN COUNT(n2), COUNT(DISTINCT n2)
`MATCH (n:node)
WITH DISTINCT n as n2 ORDER BY n
RETURN COUNT(n2), COUNT(DISTINCT n2)
```
The above 2 queries should produce execution plans that only differ to the extent that one contains a SORT operator and the other doesn't.  Instead, the following execution plans are produced:
```
Results
    Aggregate
        Project
            Node By Label Scan | (n:node)
Results
    Aggregate
        Sort
            Distinct
                Project
                    Node By Label Scan | (n:node)
```
Applying `LIMIT 2147483647` as a modifier also produces an execution plan where the DISTINCT is honored and is logically equivalent.  Adding SKIP as a modifier also allows the DISTINCT to be honored, but only if it is set to a value greater than 0, which is not logically equivalent.

I would expect the execution plan for the first query where DISTINCT is applied without any other modifiers to look something like the following:
```
Results
    Aggregate
        Distinct
            Project
                Node By Label Scan | (n:node)
```
Fortunately, I can work around this problem by applying another modifier that logically does nothing, but this seems like it is not intentional behavior.

**Comment by jeffreylovitz** [comment]
Thanks for the report, @mdecuir !

This bug is the result of an overzealous optimization, and should be resolved by #865. On that branch, the execution plan for the first query looks exactly like you expect.
