### ISSUE TITLE
After deleting unrelated nodes/relationships, [*] types of queries fail

### ISSUE THREAD

**Issue by ritchieleeann** [RedisGraph/RedisGraph#867]
Before doing any deletions, a query such as 
`MATCH (:One {name: "node1"})<-[*]-(two:Two) RETURN two` 
works just fine. If I then run something like 
`MATCH (three:Three) DELETE three`
it deletes the nodes and relationships I expect. If I then rerun the first query, redisGraph crashes:
`Error while reading from socket: ('Connection closed by server.',)`

Upon further digging for an actual error we found this error: 
`redis-server: /redisgraph/src/graph/graph.c:492: Graph_GetEdgesConnectingNodes: Assertion `Graph_GetNode(g, srcID, &srcNode)' failed.
Aborted`

**Comment by jeffreylovitz** [comment]
Hi @ritchieleeann,

Thanks for the report! This is indeed a bug - it looks like one of the adjacency matrices is not being updated properly at deletion time. We'll have a fix out shortly!

**Comment by jeffreylovitz** [comment]
@ritchieleeann, we just merged a fix to this issue - it should be fixed now on the master branch or the `edge` Docker tag. Can you please confirm?

**Comment by ritchieleeann** [comment]
Thank you! We'll try it and get back to you in the morning once there's a new docker build.

**Comment by ritchieleeann** [comment]
Confirmed that this is working now. Thanks for your quick help!
