### ISSUE TITLE
How to use dynamic properties ?

### ISSUE THREAD

**Issue by Sceat** [RedisGraph/RedisGraph#916]
Working on a javascript app i'd like to upsert an User with dynamic properties but can't make it work on Redisgraph (the exact same code work in neo4j).

### Query
```cypher
MATCH (u:User {uuid: 0}) SET u += $user RETURN u
```
as in 
```js
const foo = { a: 1, b: 2 }
graph.query('MATCH (u:User {uuid: 0}) SET u += $user RETURN u', { user: foo })
```
I'm getting the error
```
ReplyError: errMsg: Invalid input 'b': expected OR line: 1, column: 22, offset: 21 errCtx: CYPHER user=[object Object]  MATCH (u:User {uuid: 0}) SET u += $user RETURN u errCtxOffset: 21```

**Comment by jeffreylovitz** [comment]
Hi @Sceat,

We haven't yet added the functionality for using `+=` syntax in `SET` clauses. Currently, each property should be specified independently:
`graph.query('MATCH (u:User {uuid: 0}) SET u.a = $a, u.b = $b RETURN u', foo)`

**Comment by Sceat** [comment]
Hi @jeffreylovitz thanks for the quick reply, i just saw by trying stuff in the cli that the error was due to 
```
(error) Maps are not currently supported outside of node and relation patterns.
```
error is correctly handled here but if i try something like
```
GRAPH.QUERY test "MERGE (u:User {uuid: 0, a: {foo:'bar'}}) RETURN u"
```
it make the whole redis crash with `Encountered unhandled type 'map'`
As i'm new to Graph databases i guess nested object are not something that should work but instead i should create another node, anyway i'll wait for `+=` support, is that something planned or even open to contribution ?

**Comment by jeffreylovitz** [comment]
Cypher doesn't support key-value maps as property values, so the construction `(u:User {a: {foo:'bar'}})` isn't valid. That said, your example query should emit a syntax error rather than causing a crash; we'll fix that shortly!

We haven't heard much demand for `+=` support, as the same effect can pretty much always be achieved with more verbose syntax, so it's not very high on the project roadmap currently. I don't expect it would be too complex to implement, however - if you'd like to give it a shot, I'd be happy to point you in the right direction!

**Comment by Sceat** [comment]
As i don't know anything about C i opted to contribute by writting a reactive-style js driver, i'll create a pr to reference it once the doc is done! it is extendable with observables and support procedure caching

https://github.com/HydreIO/hydre.rgraph

**Comment by jeffreylovitz** [comment]
Oh, that sounds great - thanks!

**Comment by Sceat** [comment]
All done #928 , closing the issue

**Comment by Sceat** [comment]
For anyone in need of the `+=` operator, it is supported in the [rgraph](https://github.com/HydreIO/rgraph) driver
![image](https://user-images.githubusercontent.com/11330271/74923192-a3861d80-53d0-11ea-87d0-26cfeae4382b.png)
