### ISSUE TITLE
Unexpected characters cause crash

### ISSUE THREAD

**Issue by FallingSnow** [RedisGraph/RedisGraph#920]
I'm trying to do a prefix text match (for auto complete).

The following queries cause the server to crash with the error below:
- `CALL db.idx.fulltext.queryNodes('FERAS', 'ALL%')`
- `CALL db.idx.fulltext.queryNodes('FERAS', '.*ALL')`
- `CALL db.idx.fulltext.queryNodes('FERAS', '.*ALL.*')`

Error:
```
redis-server: /home/ayrton/.cache/yay/redis-graph-git/src/redis-graph/src/procedures/proc_fulltext_query.c:58: Proc_FulltextQueryNodeInvoke: Assertion `pdata->iter' failed.
redis.service: Main process exited, code=killed, status=6/ABRT
redis.service: Failed with result 'signal'.
```

Output of `module list`:
![image](https://user-images.githubusercontent.com/2512197/74470557-a1adde80-4e53-11ea-9756-ec88df0c4889.png)

**Comment by jeffreylovitz** [comment]
Hi @FallingSnow , 

Thanks for the report! This crash is a bug; a syntax error should be emitted here. We'll resolve this soon!

Our full-text indexes are backed by RediSearch, and should use [its syntax](https://oss.redislabs.com/redisearch/Query_Syntax.html#prefix_matching). For prefix matching on the literal prefix "ALL", the query would be:
`CALL db.idx.fulltext.queryNodes('FERAS', 'ALL*')`

**Comment by FallingSnow** [comment]
Thank you, that syntax works.

**Comment by FallingSnow** [comment]
`CALL db.idx.fulltext.queryNodes('FERAS', 'adoc *') YIELD node AS feras RETURN COUNT(feras) AS count` also causes the same crash. I'm sure this is invalid syntax, but this shouldn't cause a crash.

**Comment by jeffreylovitz** [comment]
You're definitely right! We'll close this issue once the crash has been replaced with a sensible user-facing error, which I'd expect to be early next week.
