### ISSUE TITLE
MATCH WHERE ID out of range returns all nodes

### ISSUE THREAD

**Issue by JakkoJokiranta** [RedisGraph/RedisGraph#999]
Using redisgraph (latest docker image, ID f673c0d80f34), I've just encountered that if I query for a node with some ID higher than highest node ID already present, redisgraph returns all nodes

![first_query](https://user-images.githubusercontent.com/61584416/75544361-b4abdb80-5a1b-11ea-90e7-be1add84f770.png)

Currently, highest node ID its 37, then, if I try to get a node with a id higher than 37, it returns all  Nodes with specified label:
![2_query](https://user-images.githubusercontent.com/61584416/75544588-37349b00-5a1c-11ea-930b-06a0248c1736.png)

![Screenshot_20200228_112046](https://user-images.githubusercontent.com/61584416/75544668-63501c00-5a1c-11ea-9059-06d322557a9a.png)

**Comment by jeffreylovitz** [comment]
@JakkoJokiranta Thanks for the report! This should be a quick fix; I'll have something out shortly.

**Comment by swilly22** [comment]
Fix been merged.
